import type { Language } from './storage';

export interface CityData {
  name: { pl: string; native: string; };
  description: { pl: string; native: string; };
  facts: {
    population: string;
    area: { pl: string; native: string; };
    landmark: { pl: string; native: string; };
    founded: { pl: string; native: string; };
    nickname: { pl: string; native: string; };
  };
}

export interface CitiesPageData {
  lang: Language;
  countryName: { pl: string; native: string; };
  cities: CityData[];
  ui: {
    title: { pl: string; native: string; };
    backButton: { pl: string; native: string; };
    language: { pl: string; native: string; };
    population: { pl: string; native: string; };
    area: { pl: string; native: string; };
    landmark: { pl: string; native: string; };
    founded: { pl: string; native: string; };
    nickname: { pl: string; native: string; };
  }
}

export const allCitiesData: Record<Language, CitiesPageData> = {
  en: {
    lang: 'en',
    countryName: { pl: 'Anglia', native: 'England' },
    cities: [
      { name: { pl: 'Londyn', native: 'London' }, description: { pl: 'Stolica Anglii, globalne centrum finansów, kultury i mody. Miasto oferuje nieskończoną liczbę atrakcji, od ikonicznych zabytków jak Tower of London, przez światowej klasy muzea (British Museum, Tate Modern), po tętniące życiem teatry West Endu i różnorodne dzielnice, takie jak Notting Hill czy Camden.', native: 'The capital of England, a global hub for finance, culture, and fashion. The city offers an endless number of attractions, from iconic landmarks like the Tower of London, through world-class museums (British Museum, Tate Modern), to the vibrant theatres of the West End and diverse districts like Notting Hill or Camden.' }, facts: { population: '~9.0 million', area: { pl: '1,572 km²', native: '607 sq mi' }, landmark: { pl: 'Pałac Buckingham', native: 'Buckingham Palace' }, founded: {pl: '47 n.e.', native: '47 AD'}, nickname: { pl: 'The Big Smoke', native: 'The Big Smoke' } } },
      { name: { pl: 'Manchester', native: 'Manchester' }, description: { pl: 'Serce rewolucji przemysłowej, znane z bogatej sceny muzycznej, która wydała takie zespoły jak The Smiths i Oasis. Miasto łączy dziedzictwo industrialne z nowoczesną energią, będąc domem dla dwóch potężnych klubów piłkarskich i dynamicznie rozwijającego się centrum medialnego w Salford Quays.', native: 'The heart of the Industrial Revolution, known for its rich music scene that produced bands like The Smiths and Oasis. The city blends industrial heritage with modern energy, being home to two powerful football clubs and a rapidly growing media hub at Salford Quays.' }, facts: { population: '~550,000', area: { pl: '115 km²', native: '44.6 sq mi' }, landmark: { pl: 'Stadion Old Trafford', native: 'Old Trafford Stadium' }, founded: {pl: '79 n.e.', native: '79 AD'}, nickname: { pl: 'Cottonopolis', native: 'Cottonopolis' } } },
      { name: { pl: 'Birmingham', native: 'Birmingham' }, description: { pl: 'Kluczowe miasto przemysłowe z rozległą siecią kanałów, większą niż w Wenecji. Dziś to tętniące życiem centrum handlu, z nowoczesnym centrum handlowym Bullring, oraz bogatej sceny kulinarnej, w tym słynnego "Balti Triangle". Miasto jest również gospodarzem wielu międzynarodowych wydarzeń.', native: 'A key industrial city with an extensive canal network, larger than Venice\'s. Today, it is a bustling hub for commerce, with the modern Bullring shopping centre, and a rich culinary scene, including the famous "Balti Triangle". The city also hosts many international events.' }, facts: { population: '~1.1 million', area: { pl: '267 km²', native: '103.4 sq mi' }, landmark: { pl: 'Biblioteka w Birmingham', native: 'Library of Birmingham' }, founded: {pl: 'VII wiek', native: '7th century'}, nickname: { pl: 'Miasto Tysiąca Fachów', native: 'City of a Thousand Trades' } } },
      { name: { pl: 'Liverpool', native: 'Liverpool' }, description: { pl: 'Miasto Beatlesów i morskiej historii, które szczyci się większą liczbą muzeów i galerii niż jakiekolwiek inne miasto w Wielkiej Brytanii poza Londynem. Jego nabrzeże, z historycznym Albert Dock, jest wpisane na listę UNESCO i tętni życiem, kulturą i muzyką.', native: 'The city of The Beatles and maritime history, boasting more museums and galleries than any other UK city outside of London. Its waterfront, with the historic Albert Dock, is a UNESCO World Heritage site and buzzes with life, culture, and music.' }, facts: { population: '~500,000', area: { pl: '111 km²', native: '43.2 sq mi' }, landmark: { pl: 'Albert Dock', native: 'Albert Dock' }, founded: {pl: '1207', native: '1207'}, nickname: { pl: 'Basen Życia', native: 'The Pool of Life' } } },
      { name: { pl: 'Bristol', native: 'Bristol' }, description: { pl: 'Znany z prężnej sceny kulturalnej, sztuki ulicznej (w tym Banksy\'ego) i ikonicznego mostu wiszącego Clifton. To miasto kreatywności i innowacji, z silnym duchem niezależności, co widać w licznych niezależnych sklepach, kawiarniach i festiwalach.', native: 'Known for its vibrant cultural scene, street art (including Banksy), and the iconic Clifton Suspension Bridge. It is a city of creativity and innovation, with a strong independent spirit reflected in its many independent shops, cafes, and festivals.' }, facts: { population: '~470,000', area: { pl: '110 km²', native: '42 sq mi' }, landmark: { pl: 'Most Wiszący Clifton', native: 'Clifton Suspension Bridge' }, founded: {pl: 'ok. 1000', native: 'c. 1000'}, nickname: { pl: 'Brizzle', native: 'Brizzle' } } },
      { name: { pl: 'Leeds', native: 'Leeds' }, description: { pl: 'Główne centrum finansowe i handlowe w West Yorkshire, znane z zakupów, wiktoriańskiej architektury i tętniącego życia nocnego. Odegrało kluczową rolę w przemyśle wełnianym, a dziś jest dynamicznym ośrodkiem z wieloma galeriami, muzeami i sceną muzyczną.', native: 'A major financial and commercial hub in West Yorkshire, known for its shopping, Victorian architecture, and vibrant nightlife. It played a key role in the wool industry and is now a dynamic center with many galleries, museums, and a thriving music scene.' }, facts: { population: '~812,000', area: { pl: '551 km²', native: '213 sq mi' }, landmark: { pl: 'Targ Kirkgate', native: 'Kirkgate Market' }, founded: { pl: 'V wiek', native: '5th century' }, nickname: { pl: 'Nieoficjalna stolica Yorkshire', native: 'The Unofficial Capital of Yorkshire' } } },
      { name: { pl: 'Newcastle', native: 'Newcastle upon Tyne' }, description: { pl: 'Tętniące życiem miasto w północno-wschodniej Anglii, słynące z dziedzictwa przemysłowego, ikonicznych mostów na rzece Tyne i przyjaznej kultury "Geordie". Jest centrum nauki, finansów i sztuki, oferując bogate życie nocne i historyczne centrum miasta.', native: 'A vibrant city in North East England, famous for its industrial heritage, iconic bridges over the River Tyne, and friendly Geordie culture. It is a center for science, finance, and the arts, offering a rich nightlife and a historic city center.' }, facts: { population: '~300,000', area: { pl: '114 km²', native: '44 sq mi' }, landmark: { pl: 'Most Tyne', native: 'Tyne Bridge' }, founded: { pl: 'II wiek', native: '2nd century' }, nickname: { pl: 'The Toon', native: 'The Toon' } } },
    ],
    ui: { title: { pl: 'Miasta Anglii', native: 'Cities of England' }, backButton: { pl: 'Powrót do Kultury', native: 'Back to Culture' }, language: { pl: 'Język', native: 'Language' }, population: { pl: 'Populacja', native: 'Population' }, area: { pl: 'Powierzchnia', native: 'Area' }, landmark: { pl: 'Główny zabytek', native: 'Key Landmark' }, founded: { pl: 'Założenie', native: 'Founded' }, nickname: { pl: 'Przydomek', native: 'Nickname' } }
  },
  de: {
    lang: 'de',
    countryName: { pl: 'Niemcy', native: 'Deutschland' },
    cities: [
      { name: { pl: 'Berlin', native: 'Berlin' }, description: { pl: 'Stolica Niemiec, miasto historii, sztuki i nieskończonych możliwości. Symbolami są Brama Brandenburska i pozostałości Muru Berlińskiego. Berlin jest znany ze swojej otwartej atmosfery, życia nocnego i dynamicznej sceny artystycznej, przyciągając twórców z całego świata.', native: 'Die Hauptstadt Deutschlands, eine Stadt der Geschichte, Kunst und unendlichen Möglichkeiten. Ihre Symbole sind das Brandenburger Tor und die Überreste der Berliner Mauer. Berlin ist bekannt für seine offene Atmosphäre, sein Nachtleben und seine dynamische Kunstszene, die Künstler aus aller Welt anzieht.' }, facts: { population: '~3.7 million', area: { pl: '891 km²', native: '344 sq mi' }, landmark: { pl: 'Brama Brandenburska', native: 'Brandenburger Tor' }, founded: {pl: '1237', native: '1237'}, nickname: { pl: 'Szare Miasto', native: 'Die Graue Stadt' } } },
      { name: { pl: 'Hamburg', native: 'Hamburg' }, description: { pl: 'Główne miasto portowe Niemiec z siecią kanałów i historycznym Speicherstadt, wpisanym na listę UNESCO. Słynie z Elbphilharmonie i tętniącego życiem portu, a także dzielnicy rozrywki St. Pauli z ulicą Reeperbahn, oferując unikalne połączenie kultury i zabawy.', native: 'Deutschlands wichtigste Hafenstadt mit einem Netz von Kanälen und der historischen Speicherstadt, einem UNESCO-Weltkulturerbe. Berühmt für die Elbphilharmonie und ihren belebten Hafen sowie das Vergnügungsviertel St. Pauli mit der Reeperbahn, bietet sie eine einzigartige Mischung aus Kultur und Spaß.' }, facts: { population: '~1.8 million', area: { pl: '755 km²', native: '292 sq mi' }, landmark: { pl: 'Speicherstadt', native: 'Speicherstadt' }, founded: {pl: 'IX wiek', native: '9th century'}, nickname: { pl: 'Brama do Świata', native: 'Das Tor zur Welt' } } },
      { name: { pl: 'Monachium', native: 'München' }, description: { pl: 'Stolica Bawarii, znana z Oktoberfest, kultury piwnej i bliskości Alp. Serce miasta to tętniący życiem Marienplatz. Monachium to także ważne centrum technologiczne i siedziba wielu międzynarodowych korporacji, łącząc tradycję z nowoczesnością.', native: 'Die Hauptstadt Bayerns, bekannt für das Oktoberfest, ihre Bierkultur und die Nähe zu den Alpen. Das Herz der Stadt ist der belebte Marienplatz. München ist auch ein wichtiges Technologiezentrum und Sitz vieler internationaler Konzerne, das Tradition mit Moderne verbindet.' }, facts: { population: '~1.5 million', area: { pl: '310 km²', native: '120 sq mi' }, landmark: { pl: 'Marienplatz', native: 'Marienplatz' }, founded: {pl: '1158', native: '1158'}, nickname: { pl: 'Miasto z sercem', native: 'Die Weltstadt mit Herz' } } },
      { name: { pl: 'Frankfurt nad Menem', native: 'Frankfurt am Main' }, description: { pl: 'Finansowe centrum Niemiec i Europy, siedziba Europejskiego Banku Centralnego. Charakterystyczna panorama wieżowców nadaje mu przydomek "Mainhattan". Miasto oferuje również bogatą scenę kulturalną, z licznymi muzeami wzdłuż brzegu Menu.', native: 'Das Finanzzentrum Deutschlands und Europas, Sitz der Europäischen Zentralbank. Seine charakteristische Skyline aus Wolkenkratzern verleiht ihm den Spitznamen "Mainhattan". Die Stadt bietet auch eine reiche Kulturszene mit zahlreichen Museen am Mainufer.' }, facts: { population: '~770,000', area: { pl: '248 km²', native: '95.8 sq mi' }, landmark: { pl: 'Dzielnica bankowa', native: 'Bankenviertel' }, founded: {pl: '794', native: '794'}, nickname: { pl: 'Mainhattan', native: 'Mainhattan' } } },
      { name: { pl: 'Kolonia', native: 'Köln' }, description: { pl: 'Miasto o ponad 2000-letniej historii z majestatyczną katedrą (Kölner Dom), wpisaną na listę UNESCO, która przetrwała bombardowania II wojny światowej. Znane z radosnej atmosfery, słynnego na cały świat karnawału oraz lokalnego piwa Kölsch.', native: 'Eine Stadt mit über 2000-jähriger Geschichte und dem majestätischen Kölner Dom, einem UNESCO-Weltkulturerbe, das die Bombenangriffe des Zweiten Weltkriegs überstand. Bekannt für ihre fröhliche Atmosphäre, den weltberühmten Karneval und das lokale Kölsch-Bier.' }, facts: { population: '~1.1 million', area: { pl: '405 km²', native: '156 sq mi' }, landmark: { pl: 'Katedra w Kolonii', native: 'Kölner Dom' }, founded: {pl: '50 n.e.', native: '50 AD'}, nickname: { pl: 'Miasto Katedralne', native: 'Die Domstadt' } } },
      { name: { pl: 'Stuttgart', native: 'Stuttgart' }, description: { pl: 'Stolica Badenii-Wirtembergii, znana jako "kolebka motoryzacji" i siedziba Mercedes-Benz i Porsche. Miasto położone jest w dolinie, otoczone winnicami i lasami, oferując mieszankę życia miejskiego i natury. Oferuje także bogate życie kulturalne z teatrami i operą.', native: 'Hauptstadt von Baden-Württemberg, bekannt als die "Wiege des Automobils" und Heimat von Mercedes-Benz und Porsche. Die Stadt liegt in einem Tal, umgeben von Weinbergen und Wäldern, und bietet eine Mischung aus städtischem Leben und Natur. Sie bietet auch ein reiches Kulturleben mit Theatern und einer Oper.' }, facts: { population: '~630,000', area: { pl: '207 km²', native: '80 sq mi' }, landmark: { pl: 'Muzeum Mercedes-Benz', native: 'Mercedes-Benz Museum' }, founded: { pl: 'X wiek', native: '10th century' }, nickname: { pl: 'Metropolia Szwabska', native: 'Schwabenmetropole' } } },
      { name: { pl: 'Düsseldorf', native: 'Düsseldorf' }, description: { pl: 'Międzynarodowe centrum biznesowe i finansowe, znane z mody i targów. Miasto szczyci się nowoczesnym krajobrazem architektonicznym, zwłaszcza wzdłuż Renu, oraz żywą sceną artystyczną. Stare Miasto (Altstadt) jest słynne jako "najdłuższy bar na świecie".', native: 'Ein internationales Geschäfts- und Finanzzentrum, bekannt für Mode und Messen. Die Stadt rühmt sich einer modernen architektonischen Landschaft, besonders am Rhein, und einer lebendigen Kunstszene. Die Altstadt ist als "längste Theke der Welt" bekannt.' }, facts: { population: '~620,000', area: { pl: '217 km²', native: '84 sq mi' }, landmark: { pl: 'Rheinturm (Wieża Reńska)', native: 'Rheinturm (Rhine Tower)' }, founded: { pl: '1288', native: '1288' }, nickname: { pl: 'Biurko Zagłębia Ruhry', native: 'Schreibtisch des Ruhrgebiets' } } },
    ],
    ui: { title: { pl: 'Miasta Niemiec', native: 'Städte Deutschlands' }, backButton: { pl: 'Powrót do Kultury', native: 'Zurück zur Kultur' }, language: { pl: 'Język', native: 'Sprache' }, population: { pl: 'Populacja', native: 'Bevölkerung' }, area: { pl: 'Powierzchnia', native: 'Fläche' }, landmark: { pl: 'Główny zabytek', native: 'Wahrzeichen' }, founded: { pl: 'Założenie', native: 'Gegründet' }, nickname: { pl: 'Przydomek', native: 'Spitzname' } }
  },
  fr: {
    lang: 'fr',
    countryName: { pl: 'Francja', native: 'France' },
    cities: [
      { name: { pl: 'Paryż', native: 'Paris' }, description: { pl: 'Stolica Francji, miasto miłości, sztuki i świateł. Dom ikonicznej Wieży Eiffla, Luwru i katedry Notre-Dame. Paryż oferuje niezapomniane spacery wzdłuż Sekwany, urokliwe kawiarnie na Montmartre i luksusowe zakupy na Polach Elizejskich.', native: 'La capitale de la France, la ville de l\'amour, de l\'art et des lumières. Elle abrite l\'emblématique Tour Eiffel, le Louvre et la cathédrale Notre-Dame. Paris offre des promenades inoubliables le long de la Seine, des cafés charmants à Montmartre et du shopping de luxe sur les Champs-Élysées.' }, facts: { population: '~2.1 million', area: { pl: '105 km²', native: '40.7 sq mi' }, landmark: { pl: 'Wieża Eiffla', native: 'Tour Eiffel' }, founded: {pl: 'III w. p.n.e.', native: '3rd cent. BC'}, nickname: { pl: 'Miasto Świateł', native: 'La Ville Lumière' } } },
      { name: { pl: 'Marsylia', native: 'Marseille' }, description: { pl: 'Najstarsze miasto Francji i największy port, łączący wpływy europejskie i afrykańskie. Tętniący życiem Vieux-Port (Stary Port) jest sercem miasta, pełnym restauracji i łodzi. Warto również odwiedzić Park Narodowy Calanques z jego spektakularnymi klifami.', native: 'La plus ancienne ville de France et son plus grand port, mêlant les influences européennes et africaines. Le Vieux-Port animé est le cœur de la ville, rempli de restaurants et de bateaux. Le Parc National des Calanques, avec ses falaises spectaculaires, vaut également le détour.' }, facts: { population: '~870,000', area: { pl: '240 km²', native: '93 sq mi' }, landmark: { pl: 'Vieux-Port', native: 'Vieux-Port' }, founded: {pl: 'ok. 600 p.n.e.', native: 'c. 600 BC'}, nickname: { pl: 'Miasto Fokajskie', native: 'La Cité Phocéenne' } } },
      { name: { pl: 'Lyon', native: 'Lyon' }, description: { pl: 'Uważany za gastronomiczną stolicę Francji, słynący z tradycyjnych restauracji "bouchons". Miasto posiada piękną starówkę (Vieux Lyon), wpisaną na listę UNESCO, i słynie z corocznego Festiwalu Świateł, który przyciąga miliony turystów.', native: 'Considérée comme la capitale gastronomique de la France, célèbre pour ses restaurants traditionnels, les "bouchons". La ville possède une magnifique vieille ville (Vieux Lyon), classée au patrimoine mondial de l\'UNESCO, et est réputée pour sa Fête des Lumières annuelle, qui attire des millions de touristes.' }, facts: { population: '~520,000', area: { pl: '48 km²', native: '18.5 sq mi' }, landmark: { pl: 'Vieux Lyon', native: 'Vieux Lyon' }, founded: {pl: '43 p.n.e.', native: '43 BC'}, nickname: { pl: 'Stolica Galów', native: 'Capitale des Gaules' } } },
      { name: { pl: 'Nicea', native: 'Nice' }, description: { pl: 'Perła Lazurowego Wybrzeża, słynąca ze słonecznych plaż, błękitnego morza i słynnej Promenade des Anglais. Miasto inspirowało wielu artystów, w tym Matisse\'a i Chagalla, których muzea można tu zwiedzać. Jego stare miasto (Vieux Nice) zachwyca wąskimi uliczkami i barokową architekturą.', native: 'La perle de la Côte d\'Azur, célèbre pour ses plages ensoleillées, sa mer d\'un bleu azur et la fameuse Promenade des Anglais. La ville a inspiré de nombreux artistes, dont Matisse et Chagall, dont on peut visiter les musées. Sa vieille ville (Vieux Nice) séduit par ses ruelles étroites et son architecture baroque.' }, facts: { population: '~340,000', area: { pl: '72 km²', native: '27.8 sq mi' }, landmark: { pl: 'Promenada Anglików', native: 'Promenade des Anglais' }, founded: {pl: 'ok. 350 p.n.e.', native: 'c. 350 BC'}, nickname: { pl: 'Nissa la Bella', native: 'Nissa la Bella' } } },
      { name: { pl: 'Strasburg', native: 'Strasbourg' }, description: { pl: 'Stolica Alzacji i siedziba Parlamentu Europejskiego. Urzeka malowniczą dzielnicą La Petite France z domami z muru pruskiego i kanałami. W okresie świątecznym miasto słynie z jednego z najstarszych i najpiękniejszych jarmarków bożonarodzeniowych w Europie.', native: 'La capitale de l\'Alsace et siège du Parlement européen. Elle charme par son quartier pittoresque de La Petite France, avec ses maisons à colombages et ses canaux. Pendant la période des fêtes, la ville est célèbre pour l\'un des plus anciens et des plus beaux marchés de Noël d\'Europe.' }, facts: { population: '~290,000', area: { pl: '78 km²', native: '30 sq mi' }, landmark: { pl: 'La Petite France', native: 'La Petite France' }, founded: {pl: '12 p.n.e.', native: '12 BC'}, nickname: { pl: 'Stolica Europy', native: 'Capitale de l\'Europe' } } },
      { name: { pl: 'Bordeaux', native: 'Bordeaux' }, description: { pl: 'Światowa stolica wina, to eleganckie miasto nad rzeką Garonną szczyci się oszałamiającą XVIII-wieczną architekturą. Jego historyczne centrum jest wpisane na listę światowego dziedzictwa UNESCO i obejmuje Place de la Bourse z lustrem wodnym "miroir d\'eau".', native: 'Capitale mondiale du vin, cette ville élégante sur la Garonne possède une architecture éblouissante du XVIIIe siècle. Son centre historique est classé au patrimoine mondial de l\'UNESCO et comprend la Place de la Bourse avec son miroir d\'eau.' }, facts: { population: '~260,000', area: { pl: '49 km²', native: '19 sq mi' }, landmark: { pl: 'Plac Giełdy', native: 'Place de la Bourse' }, founded: { pl: 'III w. p.n.e.', native: '3rd century BC' }, nickname: { pl: 'Perła Akwitanii', native: 'La Perle d\'Aquitaine' } } },
      { name: { pl: 'Tuluza', native: 'Toulouse' }, description: { pl: 'Znana jako "La Ville Rose" (Różowe Miasto) ze względu na charakterystyczną architekturę z terakotowej cegły. Jest głównym ośrodkiem europejskiego przemysłu lotniczego i kosmicznego, siedzibą Airbusa. Miasto ma młodzieńczą atmosferę dzięki dużej populacji uniwersyteckiej.', native: 'Connue sous le nom de "La Ville Rose" en raison de son architecture distinctive en brique de terre cuite. C\'est un centre majeur de l\'industrie aérospatiale européenne et le siège d\'Airbus. La ville a une ambiance jeune grâce à sa grande population universitaire.' }, facts: { population: '~490,000', area: { pl: '118 km²', native: '45.6 sq mi' }, landmark: { pl: 'Kapitol w Tuluzie', native: 'Capitole de Toulouse' }, founded: { pl: 'II w. p.n.e.', native: '2nd century BC' }, nickname: { pl: 'Różowe Miasto', native: 'La Ville Rose' } } },
    ],
    ui: { title: { pl: 'Miasta Francji', native: 'Villes de France' }, backButton: { pl: 'Powrót do Kultury', native: 'Retour à la Culture' }, language: { pl: 'Język', native: 'Langue' }, population: { pl: 'Populacja', native: 'Population' }, area: { pl: 'Powierzchnia', native: 'Superficie' }, landmark: { pl: 'Główny zabytek', native: 'Monument Principal' }, founded: { pl: 'Założenie', native: 'Fondé' }, nickname: { pl: 'Przydomek', native: 'Surnom' } }
  },
  it: {
    lang: 'it',
    countryName: { pl: 'Włochy', native: 'Italia' },
    cities: [
      { name: { pl: 'Rzym', native: 'Roma' }, description: { pl: 'Wieczne Miasto, stolica Włoch i kolebka cywilizacji zachodniej. Pełne antycznych ruin, jak Koloseum i Forum Romanum, oraz siedziba Watykanu. Rzym to także miasto fontann, placów i niezrównanej kuchni, gdzie historia spotyka się z pulsującym życiem współczesnej metropolii.', native: 'La Città Eterna, capitale d\'Italia e culla della civiltà occidentale. Piena di rovine antiche come il Colosseo e il Foro Romano, e sede del Vaticano. Roma è anche una città di fontane, piazze e cucina ineguagliabile, dove la storia incontra la vita pulsante di una metropoli moderna.' }, facts: { population: '~2.8 million', area: { pl: '1,285 km²', native: '496 sq mi' }, landmark: { pl: 'Koloseum', native: 'Colosseo' }, founded: {pl: '753 p.n.e.', native: '753 BC'}, nickname: { pl: 'Wieczne Miasto', native: 'La Città Eterna' } } },
      { name: { pl: 'Mediolan', native: 'Milano' }, description: { pl: 'Światowa stolica mody i finansowe serce Włoch. Słynie z imponującej, gotyckiej katedry Duomo, opery La Scala oraz "Ostatniej Wieczerzy" Leonarda da Vinci. Mediolan to dynamiczne miasto biznesu, designu i nowoczesnego stylu życia.', native: 'La capitale mondiale della moda e il cuore finanziario d\'Italia. Famosa per l\'imponente Duomo gotico, il teatro alla Scala e "L\'Ultima Cena" di Leonardo da Vinci. Milano è una città dinamica di affari, design e stile di vita moderno.' }, facts: { population: '~1.4 million', area: { pl: '181 km²', native: '70 sq mi' }, landmark: { pl: 'Katedra w Mediolanie', native: 'Duomo di Milano' }, founded: {pl: 'ok. 600 p.n.e.', native: 'c. 600 BC'}, nickname: { pl: 'Moralna Stolica Włoch', native: 'Capitale morale d\'Italia' } } },
      { name: { pl: 'Wenecja', native: 'Venezia' }, description: { pl: 'Unikalne miasto zbudowane na wodzie, słynące z kanałów, gondoli i romantycznej atmosfery. Plac Świętego Marka z jego bazyliką jest sercem miasta. Wenecja to labirynt wąskich uliczek i mostów, gdzie każdy zakątek kryje historyczne skarby i niezapomniane widoki.', native: 'Una città unica costruita sull\'acqua, famosa per i suoi canali, le gondole e l\'atmosfera romantica. Piazza San Marco con la sua basilica è il cuore della città. Venezia è un labirinto di calli e ponti, dove ogni angolo nasconde tesori storici e viste indimenticabili.' }, facts: { population: '~260,000', area: { pl: '414 km²', native: '160 sq mi' }, landmark: { pl: 'Canal Grande', native: 'Canal Grande' }, founded: {pl: '421 n.e.', native: '421 AD'}, nickname: { pl: 'La Serenissima', native: 'La Serenissima' } } },
      { name: { pl: 'Florencja', native: 'Firenze' }, description: { pl: 'Kolebka renesansu, dom dzieł Michała Anioła i Leonarda da Vinci. Galeria Uffizi i katedra z kopułą Brunelleschiego to miejsca obowiązkowe. Miasto, położone w sercu Toskanii, zachwyca sztuką na każdym kroku, od rzeźb po architekturę.', native: 'La culla del Rinascimento, patria delle opere di Michelangelo e Leonardo da Vinci. La Galleria degli Uffizi e il Duomo con la cupola del Brunelleschi sono tappe obbligate. La città, situata nel cuore della Toscana, delizia con l\'arte ad ogni passo, dalle sculture all\'architettura.' }, facts: { population: '~380,000', area: { pl: '102 km²', native: '39 sq mi' }, landmark: { pl: 'Katedra we Florencji', native: 'Cattedrale di Firenze' }, founded: {pl: '59 p.n.e.', native: '59 BC'}, nickname: { pl: 'Kolebka Renesansu', native: 'Culla del Rinascimento' } } },
      { name: { pl: 'Neapol', native: 'Napoli' }, description: { pl: 'Tętniące życiem miasto w cieniu Wezuwiusza, uważane za kolebkę pizzy. Jego historyczne centrum jest wpisane na listę UNESCO. Neapol to brama do historycznych ruin Pompei i Herkulanum oraz malowniczego Wybrzeża Amalfitańskiego.', native: 'Una città vivace all\'ombra del Vesuvio, considerata la culla della pizza. Il suo centro storico è patrimonio dell\'UNESCO. Napoli è la porta d\'accesso alle rovine storiche di Pompei ed Ercolano e alla pittoresca Costiera Amalfitana.' }, facts: { population: '~960,000', area: { pl: '117 km²', native: '45 sq mi' }, landmark: { pl: 'Wezuwiusz', native: 'Vesuvio' }, founded: {pl: '470 p.n.e.', native: '470 BC'}, nickname: { pl: 'Miasto Słońca', native: 'Città del Sole' } } },
      { name: { pl: 'Turyn', native: 'Torino' }, description: { pl: 'Pierwsza stolica Włoch, główne centrum przemysłowe i kulturalne na północy. Siedziba Fiata, znana z barokowej architektury, wielkich placów i tajemniczego Całunu Turyńskiego. Miasto było także gospodarzem Zimowych Igrzysk Olimpijskich w 2006 roku.', native: 'La prima capitale d\'Italia, un importante centro industriale e culturale del nord. Sede della Fiat, è nota per la sua architettura barocca, le grandi piazze e la misteriosa Sacra Sindone. La città ha anche ospitato le Olimpiadi Invernali del 2006.' }, facts: { population: '~850,000', area: { pl: '130 km²', native: '50 sq mi' }, landmark: { pl: 'Mole Antonelliana', native: 'Mole Antonelliana' }, founded: { pl: '28 p.n.e.', native: '28 BC' }, nickname: { pl: 'Magiczne Miasto', native: 'La Città Magica' } } },
      { name: { pl: 'Bolonia', native: 'Bologna' }, description: { pl: 'Siedziba najstarszego uniwersytetu w świecie zachodnim, Bolonia to historyczne miasto słynące z rozległych portyków i bogatej tradycji kulinarnej (stąd przydomek "La Grassa" - Tłusta). Jej dachy z czerwonej dachówki nadają jej inny przydomek, "La Rossa".', native: 'Sede della più antica università del mondo occidentale, Bologna è una città storica famosa per i suoi ampi portici e la ricca tradizione culinaria (da cui il soprannome "La Grassa"). I suoi tetti di tegole rosse le conferiscono un altro soprannome, "La Rossa".' }, facts: { population: '~390,000', area: { pl: '140 km²', native: '54 sq mi' }, landmark: { pl: 'Dwie Wieże', native: 'Le due Torri' }, founded: { pl: 'ok. 1000 p.n.e.', native: 'c. 1000 BC' }, nickname: { pl: 'Uczona, Tłusta, Czerwona', native: 'La Dotta, la Grassa, la Rossa' } } },
    ],
    ui: { title: { pl: 'Miasta Włoch', native: 'Città d\'Italia' }, backButton: { pl: 'Powrót do Kultury', native: 'Torna a Cultura' }, language: { pl: 'Język', native: 'Lingua' }, population: { pl: 'Populacja', native: 'Popolazione' }, area: { pl: 'Powierzchnia', native: 'Superficie' }, landmark: { pl: 'Główny zabytek', native: 'Monumento principale' }, founded: { pl: 'Założenie', native: 'Fondato' }, nickname: { pl: 'Przydomek', native: 'Soprannome' } }
  },
  es: {
    lang: 'es',
    countryName: { pl: 'Hiszpania', native: 'España' },
    cities: [
      { name: { pl: 'Madryt', native: 'Madrid' }, description: { pl: 'Tętniąca życiem stolica Hiszpanii, znana z bogatego życia nocnego, światowej klasy muzeów w "Trójkącie Sztuki" (Prado, Reina Sofía, Thyssen) i pięknych parków jak Retiro. Madryt to miasto, które nigdy nie śpi, oferując niezliczone bary tapas i energetyczną atmosferę.', native: 'La vibrante capital de España, conocida por su animada vida nocturna, sus museos de talla mundial en el "Triángulo del Arte" (Prado, Reina Sofía, Thyssen) y hermosos parques como El Retiro. Madrid es una ciudad que nunca duerme, que ofrece innumerables bares de tapas y un ambiente enérgico.' }, facts: { population: '~3.3 million', area: { pl: '604 km²', native: '233 sq mi' }, landmark: { pl: 'Pałac Królewski', native: 'Palacio Real' }, founded: {pl: 'IX wiek', native: '9th century'}, nickname: { pl: 'Forum', native: 'El Foro' } } },
      { name: { pl: 'Barcelona', native: 'Barcelona' }, description: { pl: 'Miasto Gaudíego, słynące z unikalnej architektury modernistycznej, w tym nieukończonej Sagrada Família i Parku Güell. Łączy kulturę, plaże i energię metropolii, a jej gotycka dzielnica (Barri Gòtic) kryje labirynt urokliwych uliczek.', native: 'La ciudad de Gaudí, famosa por su singular arquitectura modernista, incluida la inacabada Sagrada Familia y el Parque Güell. Combina cultura, playas y energía metropolitana, y su Barrio Gótico esconde un laberinto de encantadoras callejuelas.' }, facts: { population: '~1.6 million', area: { pl: '101 km²', native: '39 sq mi' }, landmark: { pl: 'Sagrada Família', native: 'Sagrada Família' }, founded: {pl: 'I w. p.n.e.', native: '1st cent. BC'}, nickname: { pl: 'Wielka Czarodziejka', native: 'La Gran Encantadora' } } },
      { name: { pl: 'Sewilla', native: 'Sevilla' }, description: { pl: 'Stolica Andaluzji i serce flamenco. Urzeka mauretańskim pałacem Alcázar, ogromną gotycką katedrą, w której znajduje się grób Kolumba, i klimatycznymi uliczkami dzielnicy Santa Cruz. To miasto pasji, słońca i tradycji.', native: 'La capital de Andalucía y el corazón del flamenco. Cautiva con el palacio del Alcázar de estilo morisco, la enorme catedral gótica que alberga la tumba de Colón y las atmosféricas calles del barrio de Santa Cruz. Es una ciudad de pasión, sol y tradición.' }, facts: { population: '~680,000', area: { pl: '140 km²', native: '54 sq mi' }, landmark: { pl: 'Plac Hiszpański', native: 'Plaza de España' }, founded: {pl: 'VIII w. p.n.e.', native: '8th cent. BC'}, nickname: { pl: 'Perła Andaluzji', native: 'La Perla de Andalucía' } } },
      { name: { pl: 'Walencja', native: 'Valencia' }, description: { pl: 'Miasto kontrastów, gdzie historyczne centrum spotyka się z futurystycznym Miastem Sztuki i Nauki. Słynie z autentycznej paelli, jedwabnej giełdy La Lonja (UNESCO) i spektakularnego festiwalu ognia Las Fallas, odbywającego się w marcu.', native: 'Una ciudad de contrastes, donde el centro histórico se encuentra con la futurista Ciudad de las Artes y las Ciencias. Famosa por su auténtica paella, la Lonja de la Seda (UNESCO) y la espectacular fiesta del fuego de Las Fallas que se celebra en marzo.' }, facts: { population: '~800,000', area: { pl: '134 km²', native: '52 sq mi' }, landmark: { pl: 'Miasto Sztuki i Nauki', native: 'Ciudad de las Artes y las Ciencias' }, founded: {pl: '138 p.n.e.', native: '138 BC'}, nickname: { pl: 'Miasto Kwiatów', native: 'La Ciudad de las Flores' } } },
      { name: { pl: 'Granada', native: 'Granada' }, description: { pl: 'Dom jednego z najwspanialszych zabytków świata, pałacu Alhambra, arcydzieła architektury mauretańskiej. Położone u podnóża gór Sierra Nevada, miasto oferuje unikalną mieszankę kultury andaluzyjskiej i arabskiej, widoczną w dzielnicy Albaicín.', native: 'Sede de uno de los monumentos más magníficos del mundo, el Palacio de la Alhambra, una obra maestra de la arquitectura morisca. Situada a los pies de las montañas de Sierra Nevada, la ciudad ofrece una mezcla única de cultura andaluza y árabe, visible en el barrio del Albaicín.' }, facts: { population: '~230,000', area: { pl: '88 km²', native: '34 sq mi' }, landmark: { pl: 'Alhambra', native: 'Alhambra' }, founded: {pl: 'VII w. p.n.e.', native: '7th cent. BC'}, nickname: { pl: 'Kraina Tysiąca Zamków', native: 'La Tierra de los Mil Castillos' } } },
      { name: { pl: 'Bilbao', native: 'Bilbao' }, description: { pl: 'Serce Kraju Basków, miasto to przekształciło się z portu przemysłowego w światowej sławy centrum sztuki i architektury, dzięki ikonicznemu Muzeum Guggenheima. To miasto kontrastów, gdzie awangardowy design spotyka się z historycznym starym miastem (Casco Viejo).', native: 'El corazón del País Vasco, esta ciudad se transformó de un puerto industrial a un centro de arte y arquitectura de renombre mundial, gracias al icónico Museo Guggenheim. Es una ciudad de contrastes, donde el diseño de vanguardia se encuentra con un casco viejo histórico.' }, facts: { population: '~345,000', area: { pl: '41 km²', native: '16 sq mi' }, landmark: { pl: 'Muzeum Guggenheima', native: 'Guggenheim Museum' }, founded: { pl: '1300', native: '1300' }, nickname: { pl: 'Dziura', native: 'El Botxo' } } },
      { name: { pl: 'Malaga', native: 'Málaga' }, description: { pl: 'Tętniąca życiem stolica Costa del Sol, miejsce narodzin Pabla Picassa. Miasto łączy słoneczne plaże z bogatą historią, odnowionym portem i kwitnącą sceną artystyczną, w tym Muzeum Picassa i Centrum Pompidou Málaga.', native: 'La vibrante capital de la Costa del Sol, lugar de nacimiento de Pablo Picasso. La ciudad combina playas soleadas con una rica historia, un puerto remodelado y una próspera escena artística, que incluye el Museo Picasso y el Centre Pompidou Málaga.' }, facts: { population: '~580,000', area: { pl: '398 km²', native: '154 sq mi' }, landmark: { pl: 'Alcazaba', native: 'Alcazaba' }, founded: { pl: '770 p.n.e.', native: '770 BC' }, nickname: { pl: 'Piękna', native: 'La Bella' } } },
    ],
    ui: { title: { pl: 'Miasta Hiszpanii', native: 'Ciudades de España' }, backButton: { pl: 'Powrót do Kultury', native: 'Volver a Cultura' }, language: { pl: 'Język', native: 'Idioma' }, population: { pl: 'Populacja', native: 'Población' }, area: { pl: 'Powierzchnia', native: 'Superficie' }, landmark: { pl: 'Główny zabytek', native: 'Monumento principal' }, founded: { pl: 'Założenie', native: 'Fundado' }, nickname: { pl: 'Przydomek', native: 'Apodo' } }
  },
};
