import type { Language } from './storage';

export interface Phrase {
  phrase: string;
  translation: string;
}

export interface PhraseCategory {
  [category: string]: {
    title: string;
    phrases: Phrase[];
  };
}

export interface PhrasesContent {
  [lang: string]: PhraseCategory;
}

export const allPhrases: PhrasesContent = {
  en: {
    restaurant: {
      title: 'Restaurant',
      phrases: [
        { phrase: 'A table for two, please.', translation: 'Stolik dla dwojga, proszę.' },
        { phrase: 'I\'d like to book a table.', translation: 'Chciałbym/Chciałabym zarezerwować stolik.' },
        { phrase: 'Can I see the menu, please?', translation: 'Czy mogę zobaczyć menu?' },
        { phrase: 'What do you recommend?', translation: 'Co pan/pani poleca?' },
        { phrase: 'I would like to order...', translation: 'Chciałbym/Chciałabym zamówić...' },
        { phrase: 'What\'s the soup of the day?', translation: 'Jaka jest zupa dnia?' },
        { phrase: 'I\'m a vegetarian.', translation: 'Jestem wegetarianinem/wegetarianką.' },
        { phrase: 'I have an allergy to nuts.', translation: 'Mam alergię na orzechy.' },
        { phrase: 'Is this dish spicy?', translation: 'Czy to danie jest ostre?' },
        { phrase: 'Can I have some water, please?', translation: 'Czy mogę prosić o wodę?' },
        { phrase: 'Another glass of wine, please.', translation: 'Jeszcze jeden kieliszek wina, proszę.' },
        { phrase: 'How long will we have to wait?', translation: 'Jak długo będziemy musieli czekać?' },
        { phrase: 'Enjoy your meal!', translation: 'Smacznego!' },
        { phrase: 'Everything was delicious!', translation: 'Wszystko było pyszne!' },
        { phrase: 'My food is cold.', translation: 'Moje jedzenie jest zimne.' },
        { phrase: 'This isn\'t what I ordered.', translation: 'To nie jest to, co zamawiałem/am.' },
        { phrase: 'Could we have the bill, please?', translation: 'Czy możemy prosić o rachunek?' },
        { phrase: 'Can we pay separately?', translation: 'Czy możemy zapłacić osobno?' },
        { phrase: 'Is service included?', translation: 'Czy obsługa jest wliczona w cenę?' },
        { phrase: 'Keep the change.', translation: 'Reszty nie trzeba.' },
        { phrase: 'Where is the restroom?', translation: 'Gdzie jest toaleta?' },
        { phrase: 'I\'ll have the same.', translation: 'Wezmę to samo.' },
        { phrase: 'Can you recommend a local dish?', translation: 'Czy może pan/pani polecić lokalne danie?' },
        { phrase: 'What are your opening hours?', translation: 'W jakich godzinach jest otwarte?' },
        { phrase: 'Do you have a high chair for a child?', translation: 'Czy macie krzesełko dla dziecka?' },
        { phrase: 'Can I get this to go?', translation: 'Czy mogę to wziąć na wynos?' }
      ]
    },
    airport: {
        title: 'Airport',
        phrases: [
            { phrase: 'Where is the check-in desk for this flight?', translation: 'Gdzie jest stanowisko odprawy dla tego lotu?' },
            { phrase: 'Is my flight on time?', translation: 'Czy mój lot jest o czasie?' },
            { phrase: 'I have one bag to check in.', translation: 'Mam jedną torbę do nadania.' },
            { phrase: 'Where is the boarding gate?', translation: 'Gdzie jest bramka do wejścia na pokład?' },
            { phrase: 'Where is gate B25?', translation: 'Gdzie jest bramka B25?' },
            { phrase: 'What time does the boarding begin?', translation: 'O której godzinie zaczyna się wejście na pokład?' },
            { phrase: 'This is my boarding pass.', translation: 'To jest moja karta pokładowa.' },
            { phrase: 'I\'d like a window/aisle seat, please.', translation: 'Poproszę o miejsce przy oknie/od przejścia.' },
            { phrase: 'Do I need to take my laptop out of the bag?', translation: 'Czy muszę wyjąć laptopa z torby?' },
            { phrase: 'Can I have a blanket and a pillow?', translation: 'Czy mogę prosić o koc i poduszkę?' },
            { phrase: 'Please fasten your seatbelt.', translation: 'Proszę zapiąć pasy.' },
            { phrase: 'Where can I claim my baggage?', translation: 'Gdzie mogę odebrać bagaż?' },
            { phrase: 'Where can I find the arrivals hall?', translation: 'Gdzie znajdę halę przylotów?' },
            { phrase: 'I have nothing to declare.', translation: 'Nie mam nic do oclenia.' },
            { phrase: 'My flight is delayed.', translation: 'Mój lot jest opóźniony.' },
            { phrase: 'My flight has been cancelled.', translation: 'Mój lot został odwołany.' },
            { phrase: 'My luggage hasn\'t arrived.', translation: 'Mój bagaż nie dotarł.' },
            { phrase: 'I lost my passport.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'I have a connecting flight.', translation: 'Mam lot z przesiadką.' },
            { phrase: 'Where is the currency exchange?', translation: 'Gdzie jest kantor wymiany walut?' },
            { phrase: 'How do I get to the city center?', translation: 'Jak dostanę się do centrum miasta?' },
            { phrase: 'Can you tell me where the taxi stand is?', translation: 'Czy może mi pan/pani powiedzieć, gdzie jest postój taksówek?' },
            { phrase: 'Where is the information desk?', translation: 'Gdzie jest punkt informacyjny?' },
            { phrase: 'Is there Wi-Fi here?', translation: 'Czy jest tu Wi-Fi?' },
            { phrase: 'I\'m looking for the departure lounge.', translation: 'Szukam hali odlotów.' },
            { phrase: 'Could you help me with my bags?', translation: 'Czy mógłbyś/mogłabyś mi pomóc z torbami?' }
        ]
    },
    shop: {
        title: 'Shop',
        phrases: [
            { phrase: 'I\'m just looking, thanks.', translation: 'Tylko się rozglądam, dziękuję.' },
            { phrase: 'How much is this?', translation: 'Ile to kosztuje?' },
            { phrase: 'Can you help me?', translation: 'Czy może mi pan/pani pomóc?' },
            { phrase: 'Do you have this in a smaller/larger size?', translation: 'Czy macie to w mniejszym/większym rozmiarze?' },
            { phrase: 'Do you have this in a different color?', translation: 'Czy macie to w innym kolorze?' },
            { phrase: 'Can I try this on?', translation: 'Czy mogę to przymierzyć?' },
            { phrase: 'Where are the fitting rooms?', translation: 'Gdzie są przymierzalnie?' },
            { phrase: 'I\'ll take it.', translation: 'Wezmę to.' },
            { phrase: 'Can I pay by card?', translation: 'Czy mogę zapłacić kartą?' },
            { phrase: 'Do you accept credit cards?', translation: 'Czy akceptujecie karty kredytowe?' },
            { phrase: 'I\'ll pay in cash.', translation: 'Zapłacę gotówką.' },
            { phrase: 'Can I get a receipt, please?', translation: 'Czy mogę prosić o paragon?' },
            { phrase: 'Where is the checkout?', translation: 'Gdzie jest kasa?' },
            { phrase: 'Is this on sale?', translation: 'Czy to jest na wyprzedaży?' },
            { phrase: 'This is too expensive.', translation: 'To jest za drogie.' },
            { phrase: 'Do you have anything cheaper?', translation: 'Czy macie coś tańszego?' },
            { phrase: 'I would like to return this.', translation: 'Chciałbym/Chciałabym to zwrócić.' },
            { phrase: 'What is your return policy?', translation: 'Jaka jest wasza polityka zwrotów?' },
            { phrase: 'Can you gift wrap it for me?', translation: 'Czy może pan/pani zapakować to na prezent?' },
            { phrase: 'I am looking for a souvenir.', translation: 'Szukam pamiątki.' },
            { phrase: 'I\'m looking for a gift for my friend.', translation: 'Szukam prezentu dla przyjaciela/przyjaciółki.' },
            { phrase: 'Where can I find bread?', translation: 'Gdzie znajdę chleb?' },
            { phrase: 'I need a shopping cart.', translation: 'Potrzebuję wózka na zakupy.' },
            { phrase: 'A plastic bag, please.', translation: 'Poproszę torbę foliową.' },
            { phrase: 'What time do you close?', translation: 'O której zamykacie?' },
            { phrase: 'Can I have a tax-free form?', translation: 'Czy mogę prosić o formularz zwrotu podatku?' }
        ]
    },
    station: {
        title: 'Station',
        phrases: [
            { phrase: 'A one-way ticket to London, please.', translation: 'Poproszę bilet w jedną stronę do Londynu.' },
            { phrase: 'A round-trip ticket, please.', translation: 'Poproszę bilet w obie strony.' },
            { phrase: 'Which platform does the train to Berlin leave from?', translation: 'Z którego peronu odjeżdża pociąg do Berlina?' },
            { phrase: 'What time is the next train to Paris?', translation: 'O której jest następny pociąg do Paryża?' },
            { phrase: 'Is this train direct?', translation: 'Czy ten pociąg jest bezpośredni?' },
            { phrase: 'Where is the ticket office?', translation: 'Gdzie jest kasa biletowa?' },
            { phrase: 'Where can I find the timetable?', translation: 'Gdzie znajdę rozkład jazdy?' },
            { phrase: 'I need to validate my ticket.', translation: 'Muszę skasować bilet.' },
            { phrase: 'Is this seat taken?', translation: 'Czy to miejsce jest zajęte?' },
            { phrase: 'This is my stop.', translation: 'To mój przystanek.' },
            { phrase: 'I missed my train.', translation: 'Spóźniłem/am się na pociąg.' },
            { phrase: 'The train is cancelled.', translation: 'Pociąg jest odwołany.' },
            { phrase: 'First or second class?', translation: 'Pierwsza czy druga klasa?' },
            { phrase: 'How many stops to the central station?', translation: 'Ile przystanków do dworca centralnego?' },
            { phrase: 'Does this bus go to the city center?', translation: 'Czy ten autobus jedzie do centrum miasta?' },
            { phrase: 'How long is the journey?', translation: 'Jak długa jest podróż?' },
            { phrase: 'Is there a toilet on the train?', translation: 'Czy w pociągu jest toaleta?' },
            { phrase: 'Where are the lockers?', translation: 'Gdzie są szafki na bagaż?' },
            { phrase: 'I\'d like to reserve a seat.', translation: 'Chciałbym/Chciałabym zarezerwować miejsce.' },
            { phrase: 'I have a rail pass.', translation: 'Mam bilet okresowy na pociąg.' },
            { phrase: 'I lost my ticket.', translation: 'Zgubiłem/am bilet.' },
            { phrase: 'The train is arriving at platform 5.', translation: 'Pociąg wjeżdża na peron 5.' },
            { phrase: 'Is there a dining car on this train?', translation: 'Czy w tym pociągu jest wagon restauracyjny?' },
            { phrase: 'Please mind the gap.', translation: 'Proszę uważać na odstęp (między pociągiem a peronem).' },
            { phrase: 'I\'d like to buy a ticket from the machine.', translation: 'Chciałbym/Chciałabym kupić bilet w automacie.' },
            { phrase: 'How much is a ticket for a child?', translation: 'Ile kosztuje bilet dla dziecka?' }
        ]
    },
    party: {
        title: 'Party',
        phrases: [
            { phrase: 'Thanks for inviting me.', translation: 'Dziękuję za zaproszenie.' },
            { phrase: 'Pleased to meet you.', translation: 'Miło mi cię poznać.' },
            { phrase: 'Cheers!', translation: 'Na zdrowie!' },
            { phrase: 'It\'s a great party!', translation: 'To świetna impreza!' },
            { phrase: 'Do you want to dance?', translation: 'Chcesz zatańczyć?' },
            { phrase: 'I love this song!', translation: 'Uwielbiam tę piosenkę!' },
            { phrase: 'This is delicious!', translation: 'To jest pyszne!' },
            { phrase: 'I\'m having a great time.', translation: 'Świetnie się bawię.' },
            { phrase: 'Can I get you a drink?', translation: 'Mogę ci przynieść coś do picia?' },
            { phrase: 'What do you do for a living?', translation: 'Czym się zajmujesz zawodowo?' },
            { phrase: 'Congratulations!', translation: 'Gratulacje!' },
            { phrase: 'Happy birthday!', translation: 'Wszystkiego najlepszego z okazji urodzin!' },
            { phrase: 'I really like your outfit.', translation: 'Bardzo podoba mi się twój strój.' },
            { phrase: 'The atmosphere is amazing.', translation: 'Atmosfera jest niesamowita.' },
            { phrase: 'Let\'s take a picture.', translation: 'Zróbmy sobie zdjęcie.' },
            { phrase: 'Could you pass me the snacks?', translation: 'Czy możesz podać mi przekąski?' },
            { phrase: 'What are you drinking?', translation: 'Co pijesz?' },
            { phrase: 'I have to go now, thanks for everything.', translation: 'Muszę już iść, dziękuję za wszystko.' },
            { phrase: 'Let\'s keep in touch.', translation: 'Bądźmy w kontakcie.' },
            { phrase: 'See you next time!', translation: 'Do zobaczenia następnym razem!' },
            { phrase: 'Shall we go outside for some fresh air?', translation: 'Wyjdziemy na zewnątrz zaczerpnąć świeżego powietrza?' },
            { phrase: 'The music is a bit too loud.', translation: 'Muzyka jest trochę za głośna.' },
            { phrase: 'This place is beautiful.', translation: 'To miejsce jest piękne.' },
            { phrase: 'Who is the DJ?', translation: 'Kto jest DJ-em?' },
            { phrase: 'Is it okay if I smoke here?', translation: 'Czy mogę tu zapalić?' },
            { phrase: 'I\'ll be right back.', translation: 'Zaraz wracam.' }
        ]
    },
    emergency: {
        title: 'Emergency',
        phrases: [
            { phrase: 'Help!', translation: 'Pomocy!' },
            { phrase: 'Call an ambulance!', translation: 'Wezwij karetkę!' },
            { phrase: 'Call the police!', translation: 'Wezwij policję!' },
            { phrase: 'Call the fire department!', translation: 'Wezwij straż pożarną!' },
            { phrase: 'What is the emergency number?', translation: 'Jaki jest numer alarmowy?' },
            { phrase: 'There is a fire!', translation: 'Pali się!' },
            { phrase: 'There\'s been an accident.', translation: 'Wydarzył się wypadek.' },
            { phrase: 'I need a doctor.', translation: 'Potrzebuję lekarza.' },
            { phrase: 'Is there a hospital nearby?', translation: 'Czy w pobliżu jest szpital?' },
            { phrase: 'I don\'t feel well.', translation: 'Nie czuję się dobrze.' },
            { phrase: 'I have a pain here.', translation: 'Boli mnie tutaj.' },
            { phrase: 'I can\'t breathe.', translation: 'Nie mogę oddychać.' },
            { phrase: 'Someone stole my bag.', translation: 'Ktoś ukradł moją torbę.' },
            { phrase: 'I\'ve lost my wallet.', translation: 'Zgubiłem/am portfel.' },
            { phrase: 'I\'ve lost my passport.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'I am lost.', translation: 'Zgubiłem/am się.' },
            { phrase: 'My child is missing.', translation: 'Moje dziecko zaginęło.' },
            { phrase: 'Leave me alone!', translation: 'Zostaw mnie w spokoju!' },
            { phrase: 'Watch out!', translation: 'Uważaj!' },
            { phrase: 'Please, hurry!', translation: 'Proszę, pospiesz się!' },
            { phrase: 'I need help.', translation: 'Potrzebuję pomocy.' },
            { phrase: 'Is anyone here a doctor?', translation: 'Czy jest tu jakiś lekarz?' },
            { phrase: 'I think I broke my leg.', translation: 'Chyba złamałem/am nogę.' },
            { phrase: 'I am allergic to penicillin.', translation: 'Jestem uczulony/a na penicylinę.' },
            { phrase: 'Where is the nearest pharmacy?', translation: 'Gdzie jest najbliższa apteka?' },
            { phrase: 'I need to go to the embassy.', translation: 'Muszę iść do ambasady.' }
        ]
    },
    hotel: {
        title: 'Hotel',
        phrases: [
            { phrase: 'I have a reservation.', translation: 'Mam rezerwację.' },
            { phrase: 'Can I check in, please?', translation: 'Czy mogę się zameldować?' },
            { phrase: 'What time is check-out?', translation: 'O której godzinie jest wymeldowanie?' },
            { phrase: 'I\'d like to check out.', translation: 'Chciałbym/Chciałabym się wymeldować.' },
            { phrase: 'Does the room have Wi-Fi?', translation: 'Czy w pokoju jest Wi-Fi?' },
            { phrase: 'What\'s the Wi-Fi password?', translation: 'Jakie jest hasło do Wi-Fi?' },
            { phrase: 'My key card doesn\'t work.', translation: 'Moja karta-klucz nie działa.' },
            { phrase: 'The air conditioning is not working.', translation: 'Klimatyzacja nie działa.' },
            { phrase: 'There is no hot water.', translation: 'Nie ma ciepłej wody.' },
            { phrase: 'The room is too noisy.', translation: 'Pokój jest zbyt głośny.' },
            { phrase: 'Can I have a room with a view?', translation: 'Czy mogę prosić o pokój z widokiem?' },
            { phrase: 'Can I have an extra towel?', translation: 'Czy mogę prosić o dodatkowy ręcznik?' },
            { phrase: 'A wake-up call at 7 AM, please.', translation: 'Poproszę o budzenie o 7 rano.' },
            { phrase: 'Can I have breakfast in my room?', translation: 'Czy mogę prosić o śniadanie do pokoju?' },
            { phrase: 'What time is breakfast served?', translation: 'O której godzinie podawane jest śniadanie?' },
            { phrase: 'Can you call a taxi for me?', translation: 'Czy może pan/pani wezwać dla mnie taksówkę?' },
            { phrase: 'Can I pay by credit card?', translation: 'Czy mogę zapłacić kartą kredytową?' },
            { phrase: 'Can I leave my luggage here?', translation: 'Czy mogę zostawić tutaj bagaż?' },
            { phrase: 'Where is the restaurant/gym?', translation: 'Gdzie jest restauracja/siłownia?' },
            { phrase: 'Is there a safe in the room?', translation: 'Czy w pokoju jest sejf?' },
            { phrase: 'I lost my room key.', translation: 'Zgubiłem/am klucz do pokoju.' },
            { phrase: 'Does the hotel have a swimming pool?', translation: 'Czy hotel ma basen?' }
        ]
    },
    weather: {
        title: 'Weather',
        phrases: [
            { phrase: 'What\'s the weather like today?', translation: 'Jaka jest dzisiaj pogoda?' },
            { phrase: 'What\'s the weather forecast?', translation: 'Jaka jest prognoza pogody?' },
            { phrase: 'It\'s sunny.', translation: 'Jest słonecznie.' },
            { phrase: 'It\'s raining.', translation: 'Pada deszcz.' },
            { phrase: 'It\'s cloudy.', translation: 'Jest pochmurno.' },
            { phrase: 'It\'s windy.', translation: 'Jest wietrznie.' },
            { phrase: 'It\'s cold.', translation: 'Jest zimno.' },
            { phrase: 'It\'s hot.', translation: 'Jest gorąco.' },
            { phrase: 'What\'s the temperature?', translation: 'Jaka jest temperatura?' },
            { phrase: 'It\'s 20 degrees Celsius.', translation: 'Jest 20 stopni Celsjusza.' },
            { phrase: 'It\'s snowing.', translation: 'Pada śnieg.' },
            { phrase: 'It\'s foggy.', translation: 'Jest mgliście.' },
            { phrase: 'There\'s a thunderstorm.', translation: 'Jest burza.' },
            { phrase: 'Is it going to rain tomorrow?', translation: 'Czy jutro będzie padać?' },
            { phrase: 'It\'s a beautiful day.', translation: 'To piękny dzień.' },
            { phrase: 'The sun is shining.', translation: 'Słońce świeci.' },
            { phrase: 'It\'s freezing.', translation: 'Jest mroźno.' },
            { phrase: 'I need an umbrella.', translation: 'Potrzebuję parasola.' },
            { phrase: 'It\'s humid.', translation: 'Jest wilgotno.' },
            { phrase: 'The weather is changing.', translation: 'Pogoda się zmienia.' },
            { phrase: 'It\'s getting dark.', translation: 'Robi się ciemno.' }
        ]
    }
  },
  de: {
    restaurant: {
      title: 'Im Restaurant',
      phrases: [
        { phrase: 'Einen Tisch für zwei, bitte.', translation: 'Stolik dla dwojga, proszę.' },
        { phrase: 'Ich möchte einen Tisch reservieren.', translation: 'Chciałbym/Chciałabym zarezerwować stolik.' },
        { phrase: 'Könnte ich bitte die Speisekarte haben?', translation: 'Czy mogę prosić o kartę dań?' },
        { phrase: 'Was empfehlen Sie?', translation: 'Co Pan/Pani poleca?' },
        { phrase: 'Ich möchte bestellen...', translation: 'Chciałbym/Chciałabym zamówić...' },
        { phrase: 'Was ist die Tagessuppe?', translation: 'Jaka jest zupa dnia?' },
        { phrase: 'Ich bin Vegetarier/in.', translation: 'Jestem wegetarianinem/wegetarianką.' },
        { phrase: 'Ich habe eine Nussallergie.', translation: 'Mam alergię na orzechy.' },
        { phrase: 'Ist dieses Gericht scharf?', translation: 'Czy to danie jest ostre?' },
        { phrase: 'Ein Wasser, bitte.', translation: 'Poproszę wodę.' },
        { phrase: 'Noch ein Glas Wein, bitte.', translation: 'Jeszcze jeden kieliszek wina, proszę.' },
        { phrase: 'Wie lange müssen wir warten?', translation: 'Jak długo musimy czekać?' },
        { phrase: 'Guten Appetit!', translation: 'Smacznego!' },
        { phrase: 'Es hat alles sehr gut geschmeckt!', translation: 'Wszystko bardzo dobrze smakowało!' },
        { phrase: 'Mein Essen ist kalt.', translation: 'Moje jedzenie jest zimne.' },
        { phrase: 'Das habe ich nicht bestellt.', translation: 'Tego nie zamawiałem/am.' },
        { phrase: 'Die Rechnung, bitte.', translation: 'Rachunek, proszę.' },
        { phrase: 'Können wir getrennt zahlen?', translation: 'Czy możemy zapłacić osobno?' },
        { phrase: 'Ist das Trinkgeld inbegriffen?', translation: 'Czy napiwek jest wliczony w cenę?' },
        { phrase: 'Stimmt so.', translation: 'Reszty nie trzeba.' },
        { phrase: 'Wo ist die Toilette?', translation: 'Gdzie jest toaleta?' },
        { phrase: 'Ich nehme das Gleiche.', translation: 'Wezmę to samo.' },
        { phrase: 'Können Sie ein lokales Gericht empfehlen?', translation: 'Czy może Pan/Pani polecić lokalne danie?' },
        { phrase: 'Was sind Ihre Öffnungszeiten?', translation: 'Jakie są godziny otwarcia?' },
        { phrase: 'Haben Sie einen Kinderstuhl?', translation: 'Czy macie krzesełko dla dziecka?' },
        { phrase: 'Kann ich das zum Mitnehmen haben?', translation: 'Czy mogę to wziąć na wynos?' }
      ]
    },
    airport: {
        title: 'Am Flughafen',
        phrases: [
            { phrase: 'Wo ist der Check-in-Schalter für diesen Flug?', translation: 'Gdzie jest stanowisko odprawy dla tego lotu?' },
            { phrase: 'Ist mein Flug pünktlich?', translation: 'Czy mój lot jest o czasie?' },
            { phrase: 'Ich habe einen Koffer zum Aufgeben.', translation: 'Mam jedną torbę do nadania.' },
            { phrase: 'Wo ist der Flugsteig?', translation: 'Gdzie jest bramka do wejścia na pokład?' },
            { phrase: 'Wo ist das Gate B25?', translation: 'Gdzie jest bramka B25?' },
            { phrase: 'Wann beginnt das Boarding?', translation: 'O której godzinie zaczyna się wejście na pokład?' },
            { phrase: 'Das ist meine Bordkarte.', translation: 'To jest moja karta pokładowa.' },
            { phrase: 'Ich hätte gern einen Fensterplatz/Gangplatz.', translation: 'Poproszę o miejsce przy oknie/od przejścia.' },
            { phrase: 'Muss ich meinen Laptop aus der Tasche nehmen?', translation: 'Czy muszę wyjąć laptopa z torby?' },
            { phrase: 'Kann ich eine Decke und ein Kissen haben?', translation: 'Czy mogę prosić o koc i poduszkę?' },
            { phrase: 'Bitte schnallen Sie sich an.', translation: 'Proszę zapiąć pasy.' },
            { phrase: 'Wo ist die Gepäckausgabe?', translation: 'Gdzie mogę odebrać bagaż?' },
            { phrase: 'Wo finde ich die Ankunftshalle?', translation: 'Gdzie znajdę halę przylotów?' },
            { phrase: 'Ich habe nichts zu verzollen.', translation: 'Nie mam nic do oclenia.' },
            { phrase: 'Mein Flug hat Verspätung.', translation: 'Mój lot jest opóźniony.' },
            { phrase: 'Mein Flug wurde gestrichen.', translation: 'Mój lot został odwołany.' },
            { phrase: 'Mein Gepäck ist nicht angekommen.', translation: 'Mój bagaż nie dotarł.' },
            { phrase: 'Ich habe meinen Pass verloren.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Ich habe einen Anschlussflug.', translation: 'Mam lot z przesiadką.' },
            { phrase: 'Wo ist die Wechselstube?', translation: 'Gdzie jest kantor wymiany walut?' },
            { phrase: 'Wie komme ich ins Stadtzentrum?', translation: 'Jak dostanę się do centrum miasta?' },
            { phrase: 'Können Sie mir sagen, wo der Taxistand ist?', translation: 'Czy może mi pan/pani powiedzieć, gdzie jest postój taksówek?' },
            { phrase: 'Wo ist die Information?', translation: 'Gdzie jest punkt informacyjny?' },
            { phrase: 'Gibt es hier WLAN?', translation: 'Czy jest tu Wi-Fi?' },
            { phrase: 'Ich suche die Abflughalle.', translation: 'Szukam hali odlotów.' },
            { phrase: 'Könnten Sie mir mit meinem Gepäck helfen?', translation: 'Czy mógłbyś/mogłabyś mi pomóc z bagażem?' }
        ]
    },
    shop: {
        title: 'Im Geschäft',
        phrases: [
            { phrase: 'Ich schaue nur, danke.', translation: 'Tylko się rozglądam, dziękuję.' },
            { phrase: 'Wie viel kostet das?', translation: 'Ile to kosztuje?' },
            { phrase: 'Können Sie mir helfen?', translation: 'Czy może mi pan/pani pomóc?' },
            { phrase: 'Haben Sie das in einer kleineren/größeren Größe?', translation: 'Czy macie to w mniejszym/większym rozmiarze?' },
            { phrase: 'Haben Sie das in einer anderen Farbe?', translation: 'Czy macie to w innym kolorze?' },
            { phrase: 'Kann ich das anprobieren?', translation: 'Czy mogę to przymierzyć?' },
            { phrase: 'Wo sind die Umkleidekabinen?', translation: 'Gdzie są przymierzalnie?' },
            { phrase: 'Ich nehme es.', translation: 'Wezmę to.' },
            { phrase: 'Kann ich mit Karte bezahlen?', translation: 'Czy mogę zapłacić kartą?' },
            { phrase: 'Akzeptieren Sie Kreditkarten?', translation: 'Czy akceptujecie karty kredytowe?' },
            { phrase: 'Ich zahle bar.', translation: 'Zapłacę gotówką.' },
            { phrase: 'Kann ich bitte eine Quittung haben?', translation: 'Czy mogę prosić o paragon?' },
            { phrase: 'Wo ist die Kasse?', translation: 'Gdzie jest kasa?' },
            { phrase: 'Ist das im Angebot?', translation: 'Czy to jest na wyprzedaży?' },
            { phrase: 'Das ist zu teuer.', translation: 'To jest za drogie.' },
            { phrase: 'Haben Sie etwas Günstigeres?', translation: 'Czy macie coś tańszego?' },
            { phrase: 'Ich möchte das zurückgeben.', translation: 'Chciałbym/Chciałabym to zwrócić.' },
            { phrase: 'Wie sind Ihre Rückgabebedingungen?', translation: 'Jaka jest wasza polityka zwrotów?' },
            { phrase: 'Können Sie es als Geschenk verpacken?', translation: 'Czy może pan/pani zapakować to na prezent?' },
            { phrase: 'Ich suche ein Souvenir.', translation: 'Szukam pamiątki.' },
            { phrase: 'Ich suche ein Geschenk für meinen Freund/meine Freundin.', translation: 'Szukam prezentu dla przyjaciela/przyjaciółki.' },
            { phrase: 'Wo finde ich Brot?', translation: 'Gdzie znajdę chleb?' },
            { phrase: 'Ich brauche einen Einkaufswagen.', translation: 'Potrzebuję wózka na zakupy.' },
            { phrase: 'Eine Plastiktüte, bitte.', translation: 'Poproszę torbę foliową.' },
            { phrase: 'Wann schließen Sie?', translation: 'O której zamykacie?' },
            { phrase: 'Kann ich ein Tax-Free-Formular haben?', translation: 'Czy mogę prosić o formularz zwrotu podatku?' }
        ]
    },
    station: {
        title: 'Am Bahnhof',
        phrases: [
            { phrase: 'Eine einfache Fahrt nach Berlin, bitte.', translation: 'Poproszę bilet w jedną stronę do Berlina.' },
            { phrase: 'Eine Rückfahrkarte, bitte.', translation: 'Poproszę bilet w obie strony.' },
            { phrase: 'Von welchem Gleis fährt der Zug nach Berlin ab?', translation: 'Z którego peronu odjeżdża pociąg do Berlina?' },
            { phrase: 'Wann fährt der nächste Zug nach Paris?', translation: 'O której jest następny pociąg do Paryża?' },
            { phrase: 'Ist das ein direkter Zug?', translation: 'Czy ten pociąg jest bezpośredni?' },
            { phrase: 'Wo ist der Fahrkartenschalter?', translation: 'Gdzie jest kasa biletowa?' },
            { phrase: 'Wo finde ich den Fahrplan?', translation: 'Gdzie znajdę rozkład jazdy?' },
            { phrase: 'Ich muss meine Fahrkarte entwerten.', translation: 'Muszę skasować bilet.' },
            { phrase: 'Ist dieser Platz besetzt?', translation: 'Czy to miejsce jest zajęte?' },
            { phrase: 'Das ist meine Haltestelle.', translation: 'To mój przystanek.' },
            { phrase: 'Ich habe meinen Zug verpasst.', translation: 'Spóźniłem/am się na pociąg.' },
            { phrase: 'Der Zug fällt aus.', translation: 'Pociąg jest odwołany.' },
            { phrase: 'Erste oder zweite Klasse?', translation: 'Pierwsza czy druga klasa?' },
            { phrase: 'Wie viele Haltestellen bis zum Hauptbahnhof?', translation: 'Ile przystanków do dworca centralnego?' },
            { phrase: 'Fährt dieser Bus ins Stadtzentrum?', translation: 'Czy ten autobus jedzie do centrum miasta?' },
            { phrase: 'Wie lange dauert die Fahrt?', translation: 'Jak długa jest podróż?' },
            { phrase: 'Gibt es eine Toilette im Zug?', translation: 'Czy w pociągu jest toaleta?' },
            { phrase: 'Wo sind die Schließfächer?', translation: 'Gdzie są szafki na bagaż?' },
            { phrase: 'Ich möchte einen Sitzplatz reservieren.', translation: 'Chciałbym/Chciałabym zarezerwować miejsce.' },
            { phrase: 'Ich habe eine Monatskarte.', translation: 'Mam bilet miesięczny.' },
            { phrase: 'Ich habe meine Fahrkarte verloren.', translation: 'Zgubiłem/am bilet.' },
            { phrase: 'Der Zug kommt auf Gleis 5 an.', translation: 'Pociąg wjeżdża na peron 5.' },
            { phrase: 'Gibt es einen Speisewagen in diesem Zug?', translation: 'Czy w tym pociągu jest wagon restauracyjny?' },
            { phrase: 'Vorsicht an der Bahnsteigkante.', translation: 'Proszę uważać na odstęp (między pociągiem a peronem).' },
            { phrase: 'Ich möchte eine Fahrkarte am Automaten kaufen.', translation: 'Chciałbym/Chciałabym kupić bilet w automacie.' },
            { phrase: 'Wie viel kostet eine Kinderfahrkarte?', translation: 'Ile kosztuje bilet dla dziecka?' }
        ]
    },
    party: {
        title: 'Auf einer Party',
        phrases: [
            { phrase: 'Danke für die Einladung.', translation: 'Dziękuję za zaproszenie.' },
            { phrase: 'Freut mich, dich kennenzulernen.', translation: 'Miło mi cię poznać.' },
            { phrase: 'Prost!', translation: 'Na zdrowie!' },
            { phrase: 'Das ist eine tolle Party!', translation: 'To świetna impreza!' },
            { phrase: 'Möchtest du tanzen?', translation: 'Chcesz zatańczyć?' },
            { phrase: 'Ich liebe dieses Lied!', translation: 'Uwielbiam tę piosenkę!' },
            { phrase: 'Das ist köstlich!', translation: 'To jest pyszne!' },
            { phrase: 'Ich amüsiere mich prächtig.', translation: 'Świetnie się bawię.' },
            { phrase: 'Soll ich dir etwas zu trinken holen?', translation: 'Przynieść ci coś do picia?' },
            { phrase: 'Was machst du beruflich?', translation: 'Czym się zajmujesz zawodowo?' },
            { phrase: 'Herzlichen Glückwunsch!', translation: 'Gratulacje!' },
            { phrase: 'Alles Gute zum Geburtstag!', translation: 'Wszystkiego najlepszego z okazji urodzin!' },
            { phrase: 'Dein Outfit gefällt mir sehr.', translation: 'Bardzo podoba mi się twój strój.' },
            { phrase: 'Die Atmosphäre ist super.', translation: 'Atmosfera jest niesamowita.' },
            { phrase: 'Machen wir ein Foto.', translation: 'Zróbmy sobie zdjęcie.' },
            { phrase: 'Könntest du mir die Snacks reichen?', translation: 'Czy możesz podać mi przekąski?' },
            { phrase: 'Was trinkst du?', translation: 'Co pijesz?' },
            { phrase: 'Ich muss jetzt gehen, danke für alles.', translation: 'Muszę już iść, dziękuję za wszystko.' },
            { phrase: 'Lass uns in Kontakt bleiben.', translation: 'Bądźmy w kontakcie.' },
            { phrase: 'Bis zum nächsten Mal!', translation: 'Do zobaczenia następnym razem!' },
            { phrase: 'Wollen wir kurz an die frische Luft gehen?', translation: 'Wyjdziemy na zewnątrz zaczerpnąć świeżego powietrza?' },
            { phrase: 'Die Musik ist ein bisschen zu laut.', translation: 'Muzyka jest trochę za głośna.' },
            { phrase: 'Dieser Ort ist wunderschön.', translation: 'To miejsce jest piękne.' },
            { phrase: 'Wer ist der DJ?', translation: 'Kto jest DJ-em?' },
            { phrase: 'Ist es in Ordnung, wenn ich hier rauche?', translation: 'Czy mogę tu zapalić?' },
            { phrase: 'Ich bin gleich wieder da.', translation: 'Zaraz wracam.' }
        ]
    },
    emergency: {
        title: 'Notfall',
        phrases: [
            { phrase: 'Hilfe!', translation: 'Pomocy!' },
            { phrase: 'Rufen Sie einen Krankenwagen!', translation: 'Wezwij karetkę!' },
            { phrase: 'Rufen Sie die Polizei!', translation: 'Wezwij policję!' },
            { phrase: 'Rufen Sie die Feuerwehr!', translation: 'Wezwij straż pożarną!' },
            { phrase: 'Wie lautet die Notrufnummer?', translation: 'Jaki jest numer alarmowy?' },
            { phrase: 'Es brennt!', translation: 'Pali się!' },
            { phrase: 'Es gab einen Unfall.', translation: 'Wydarzył się wypadek.' },
            { phrase: 'Ich brauche einen Arzt.', translation: 'Potrzebuję lekarza.' },
            { phrase: 'Gibt es ein Krankenhaus in der Nähe?', translation: 'Czy w pobliżu jest szpital?' },
            { phrase: 'Ich fühle mich nicht wohl.', translation: 'Nie czuję się dobrze.' },
            { phrase: 'Ich habe hier Schmerzen.', translation: 'Boli mnie tutaj.' },
            { phrase: 'Ich kann nicht atmen.', translation: 'Nie mogę oddychać.' },
            { phrase: 'Jemand hat meine Tasche gestohlen.', translation: 'Ktoś ukradł moją torbę.' },
            { phrase: 'Ich habe meine Brieftasche verloren.', translation: 'Zgubiłem/am portfel.' },
            { phrase: 'Ich habe meinen Reisepass verloren.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Ich habe mich verlaufen.', translation: 'Zgubiłem/am się.' },
            { phrase: 'Mein Kind wird vermisst.', translation: 'Moje dziecko zaginęło.' },
            { phrase: 'Lassen Sie mich in Ruhe!', translation: 'Zostaw mnie w spokoju!' },
            { phrase: 'Achtung!', translation: 'Uważaj!' },
            { phrase: 'Bitte, beeilen Sie sich!', translation: 'Proszę, pospiesz się!' },
            { phrase: 'Ich brauche Hilfe.', translation: 'Potrzebuję pomocy.' },
            { phrase: 'Ist hier ein Arzt anwesend?', translation: 'Czy jest tu jakiś lekarz?' },
            { phrase: 'Ich glaube, ich habe mir das Bein gebrochen.', translation: 'Chyba złamałem/am nogę.' },
            { phrase: 'Ich bin allergisch gegen Penizillin.', translation: 'Jestem uczulony/a na penicylinę.' },
            { phrase: 'Wo ist die nächste Apotheke?', translation: 'Gdzie jest najbliższa apteka?' },
            { phrase: 'Ich muss zur Botschaft.', translation: 'Muszę iść do ambasady.' }
        ]
    },
    hotel: {
        title: 'Hotel',
        phrases: [
            { phrase: 'Ich habe eine Reservierung.', translation: 'Mam rezerwację.' },
            { phrase: 'Kann ich bitte einchecken?', translation: 'Czy mogę się zameldować?' },
            { phrase: 'Wann ist der Check-out?', translation: 'O której godzinie jest wymeldowanie?' },
            { phrase: 'Ich möchte auschecken.', translation: 'Chciałbym/Chciałabym się wymeldować.' },
            { phrase: 'Gibt es WLAN im Zimmer?', translation: 'Czy w pokoju jest Wi-Fi?' },
            { phrase: 'Wie lautet das WLAN-Passwort?', translation: 'Jakie jest hasło do Wi-Fi?' },
            { phrase: 'Meine Schlüsselkarte funktioniert nicht.', translation: 'Moja karta-klucz nie działa.' },
            { phrase: 'Die Klimaanlage funktioniert nicht.', translation: 'Klimatyzacja nie działa.' },
            { phrase: 'Es gibt kein heißes Wasser.', translation: 'Nie ma ciepłej wody.' },
            { phrase: 'Das Zimmer ist zu laut.', translation: 'Pokój jest zbyt głośny.' },
            { phrase: 'Kann ich ein Zimmer mit Aussicht haben?', translation: 'Czy mogę prosić o pokój z widokiem?' },
            { phrase: 'Kann ich ein zusätzliches Handtuch haben?', translation: 'Czy mogę prosić o dodatkowy ręcznik?' },
            { phrase: 'Einen Weckruf um 7 Uhr, bitte.', translation: 'Poproszę o budzenie o 7 rano.' },
            { phrase: 'Kann ich das Frühstück auf dem Zimmer haben?', translation: 'Czy mogę prosić o śniadanie do pokoju?' },
            { phrase: 'Wann wird das Frühstück serviert?', translation: 'O której godzinie podawane jest śniadanie?' },
            { phrase: 'Können Sie mir ein Taxi rufen?', translation: 'Czy może pan/pani wezwać dla mnie taksówkę?' },
            { phrase: 'Kann ich mit Kreditkarte bezahlen?', translation: 'Czy mogę zapłacić kartą kredytową?' },
            { phrase: 'Kann ich mein Gepäck hier lassen?', translation: 'Czy mogę zostawić tutaj bagaż?' },
            { phrase: 'Wo ist das Restaurant/der Fitnessraum?', translation: 'Gdzie jest restauracja/siłownia?' },
            { phrase: 'Gibt es einen Safe im Zimmer?', translation: 'Czy w pokoju jest sejf?' },
            { phrase: 'Ich habe meinen Zimmerschlüssel verloren.', translation: 'Zgubiłem/am klucz do pokoju.' },
            { phrase: 'Hat das Hotel einen Pool?', translation: 'Czy hotel ma basen?' }
        ]
    },
    wetter: {
        title: 'Wetter',
        phrases: [
            { phrase: 'Wie ist das Wetter heute?', translation: 'Jaka jest dzisiaj pogoda?' },
            { phrase: 'Wie ist die Wettervorhersage?', translation: 'Jaka jest prognoza pogody?' },
            { phrase: 'Es ist sonnig.', translation: 'Jest słonecznie.' },
            { phrase: 'Es regnet.', translation: 'Pada deszcz.' },
            { phrase: 'Es ist bewölkt.', translation: 'Jest pochmurno.' },
            { phrase: 'Es ist windig.', translation: 'Jest wietrznie.' },
            { phrase: 'Es ist kalt.', translation: 'Jest zimno.' },
            { phrase: 'Es ist heiß.', translation: 'Jest gorąco.' },
            { phrase: 'Wie viel Grad haben wir?', translation: 'Jaka jest temperatura?' },
            { phrase: 'Es sind 20 Grad Celsius.', translation: 'Jest 20 stopni Celsjusza.' },
            { phrase: 'Es schneit.', translation: 'Pada śnieg.' },
            { phrase: 'Es ist neblig.', translation: 'Jest mgliście.' },
            { phrase: 'Es gibt ein Gewitter.', translation: 'Jest burza.' },
            { phrase: 'Wird es morgen regnen?', translation: 'Czy jutro będzie padać?' },
            { phrase: 'Es ist ein schöner Tag.', translation: 'To piękny dzień.' },
            { phrase: 'Die Sonne scheint.', translation: 'Słońce świeci.' },
            { phrase: 'Es ist eiskalt.', translation: 'Jest mroźno.' },
            { phrase: 'Ich brauche einen Regenschirm.', translation: 'Potrzebuję parasola.' },
            { phrase: 'Es ist feucht.', translation: 'Jest wilgotno.' },
            { phrase: 'Das Wetter ändert sich.', translation: 'Pogoda się zmienia.' },
            { phrase: 'Es wird dunkel.', translation: 'Robi się ciemno.' }
        ]
    }
  },
  fr: {
    restaurant: {
      title: 'Au Restaurant',
      phrases: [
        { phrase: 'Une table pour deux, s\'il vous plaît.', translation: 'Stolik dla dwojga, proszę.' },
        { phrase: 'Je voudrais réserver une table.', translation: 'Chciałbym/Chciałabym zarezerwować stolik.' },
        { phrase: 'Je peux voir la carte, s\'il vous plaît?', translation: 'Czy mogę zobaczyć menu?' },
        { phrase: 'Qu\'est-ce que vous recommandez?', translation: 'Co pan/pani poleca?' },
        { phrase: 'Je voudrais commander...', translation: 'Chciałbym/Chciałabym zamówić...' },
        { phrase: 'Quelle est la soupe du jour?', translation: 'Jaka jest zupa dnia?' },
        { phrase: 'Je suis végétarien(ne).', translation: 'Jestem wegetarianinem/wegetarianką.' },
        { phrase: 'Je suis allergique aux noix.', translation: 'Mam alergię na orzechy.' },
        { phrase: 'Est-ce que ce plat est épicé?', translation: 'Czy to danie jest ostre?' },
        { phrase: 'Je pourrais avoir de l\'eau, s\'il vous plaît?', translation: 'Czy mogę prosić o wodę?' },
        { phrase: 'Un autre verre de vin, s\'il vous plaît.', translation: 'Jeszcze jeden kieliszek wina, proszę.' },
        { phrase: 'Combien de temps devrons-nous attendre?', translation: 'Jak długo będziemy musieli czekać?' },
        { phrase: 'Bon appétit!', translation: 'Smacznego!' },
        { phrase: 'Tout était délicieux!', translation: 'Wszystko było pyszne!' },
        { phrase: 'Mon plat est froid.', translation: 'Moje jedzenie jest zimne.' },
        { phrase: 'Ce n\'est pas ce que j\'ai commandé.', translation: 'To nie jest to, co zamawiałem/am.' },
        { phrase: 'L\'addition, s\'il vous plaît.', translation: 'Rachunek, proszę.' },
        { phrase: 'Pouvons-nous payer séparément?', translation: 'Czy możemy zapłacić osobno?' },
        { phrase: 'Le service est-il inclus?', translation: 'Czy obsługa jest wliczona w cenę?' },
        { phrase: 'Gardez la monnaie.', translation: 'Reszty nie trzeba.' },
        { phrase: 'Où sont les toilettes?', translation: 'Gdzie jest toaleta?' },
        { phrase: 'Je prendrai la même chose.', translation: 'Wezmę to samo.' },
        { phrase: 'Pouvez-vous recommander un plat local?', translation: 'Czy może pan/pani polecić lokalne danie?' },
        { phrase: 'Quelles sont vos heures d\'ouverture?', translation: 'W jakich godzinach jest otwarte?' },
        { phrase: 'Avez-vous une chaise haute pour enfant?', translation: 'Czy macie krzesełko dla dziecka?' },
        { phrase: 'Je peux l\'emporter?', translation: 'Czy mogę to wziąć na wynos?' }
      ]
    },
    airport: {
        title: 'À l\'Aéroport',
        phrases: [
            { phrase: 'Où est le comptoir d\'enregistrement pour ce vol?', translation: 'Gdzie jest stanowisko odprawy dla tego lotu?' },
            { phrase: 'Mon vol est-il à l\'heure?', translation: 'Czy mój lot jest o czasie?' },
            { phrase: 'J\'ai une valise à enregistrer.', translation: 'Mam jedną torbę do nadania.' },
            { phrase: 'Où est la porte d\'embarquement?', translation: 'Gdzie jest bramka do wejścia na pokład?' },
            { phrase: 'Où est la porte d\'embarquement B25?', translation: 'Gdzie jest bramka B25?' },
            { phrase: 'À quelle heure commence l\'embarquement?', translation: 'O której godzinie zaczyna się wejście na pokład?' },
            { phrase: 'Voici ma carte d\'embarquement.', translation: 'To jest moja karta pokładowa.' },
            { phrase: 'Je voudrais une place côté hublot/couloir, s\'il vous plaît.', translation: 'Poproszę o miejsce przy oknie/od przejścia.' },
            { phrase: 'Dois-je sortir mon ordinateur portable du sac?', translation: 'Czy muszę wyjąć laptopa z torby?' },
            { phrase: 'Puis-je avoir une couverture et un oreiller?', translation: 'Czy mogę prosić o koc i poduszkę?' },
            { phrase: 'Veuillez attacher votre ceinture de sécurité.', translation: 'Proszę zapiąć pasy.' },
            { phrase: 'Où puis-je récupérer mes bagages?', translation: 'Gdzie mogę odebrać bagaż?' },
            { phrase: 'Où se trouve le hall des arrivées?', translation: 'Gdzie znajdę halę przylotów?' },
            { phrase: 'Je n\'ai rien à déclarer.', translation: 'Nie mam nic do oclenia.' },
            { phrase: 'Mon vol est en retard.', translation: 'Mój lot jest opóźniony.' },
            { phrase: 'Mon vol a été annulé.', translation: 'Mój lot został odwołany.' },
            { phrase: 'Mes bagages ne sont pas arrivés.', translation: 'Mój bagaż nie dotarł.' },
            { phrase: 'J\'ai perdu mon passeport.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'J\'ai un vol en correspondance.', translation: 'Mam lot z przesiadką.' },
            { phrase: 'Où est le bureau de change?', translation: 'Gdzie jest kantor wymiany walut?' },
            { phrase: 'Comment puis-je me rendre au centre-ville?', translation: 'Jak dostanę się do centrum miasta?' },
            { phrase: 'Pouvez-vous me dire où est la station de taxis?', translation: 'Czy może mi pan/pani powiedzieć, gdzie jest postój taksówek?' },
            { phrase: 'Où est le bureau d\'information?', translation: 'Gdzie jest punkt informacyjny?' },
            { phrase: 'Y a-t-il du Wi-Fi ici?', translation: 'Czy jest tu Wi-Fi?' },
            { phrase: 'Je cherche la salle d\'embarquement.', translation: 'Szukam hali odlotów.' },
            { phrase: 'Pourriez-vous m\'aider avec mes bagages?', translation: 'Czy mógłbyś/mogłabyś mi pomóc z bagażem?' }
        ]
    },
    shop: {
        title: 'Au Magasin',
        phrases: [
            { phrase: 'Je regarde juste, merci.', translation: 'Tylko się rozglądam, dziękuję.' },
            { phrase: 'Combien ça coûte?', translation: 'Ile to kosztuje?' },
            { phrase: 'Pouvez-vous m\'aider?', translation: 'Czy może mi pan/pani pomóc?' },
            { phrase: 'Vous avez ça dans une taille plus petite/grande?', translation: 'Czy macie to w mniejszym/większym rozmiarze?' },
            { phrase: 'L\'avez-vous dans une autre couleur?', translation: 'Czy macie to w innym kolorze?' },
            { phrase: 'Puis-je l\'essayer?', translation: 'Czy mogę to przymierzyć?' },
            { phrase: 'Où sont les cabines d\'essayage?', translation: 'Gdzie są przymierzalnie?' },
            { phrase: 'Je le prends.', translation: 'Wezmę to.' },
            { phrase: 'Je peux payer par carte?', translation: 'Czy mogę zapłacić kartą?' },
            { phrase: 'Acceptez-vous les cartes de crédit?', translation: 'Czy akceptujecie karty kredytowe?' },
            { phrase: 'Je paie en espèces.', translation: 'Zapłacę gotówką.' },
            { phrase: 'Je peux avoir un reçu, s\'il vous plaît?', translation: 'Czy mogę prosić o paragon?' },
            { phrase: 'Où est la caisse?', translation: 'Gdzie jest kasa?' },
            { phrase: 'Est-ce que c\'est en solde?', translation: 'Czy to jest na wyprzedaży?' },
            { phrase: 'C\'est trop cher.', translation: 'To jest za drogie.' },
            { phrase: 'Avez-vous quelque chose de moins cher?', translation: 'Czy macie coś tańszego?' },
            { phrase: 'Je voudrais retourner cet article.', translation: 'Chciałbym/Chciałabym to zwrócić.' },
            { phrase: 'Quelle est votre politique de retour?', translation: 'Jaka jest wasza polityka zwrotów?' },
            { phrase: 'Pouvez-vous me faire un paquet-cadeau?', translation: 'Czy może pan/pani zapakować to na prezent?' },
            { phrase: 'Je cherche un souvenir.', translation: 'Szukam pamiątki.' },
            { phrase: 'Je cherche un cadeau pour mon ami(e).', translation: 'Szukam prezentu dla przyjaciela/przyjaciółki.' },
            { phrase: 'Où puis-je trouver le pain?', translation: 'Gdzie znajdę chleb?' },
            { phrase: 'J\'ai besoin d\'un chariot.', translation: 'Potrzebuję wózka na zakupy.' },
            { phrase: 'Un sac en plastique, s\'il vous plaît.', translation: 'Poproszę torbę foliową.' },
            { phrase: 'À quelle heure fermez-vous?', translation: 'O której zamykacie?' },
            { phrase: 'Puis-je avoir un formulaire de détaxe?', translation: 'Czy mogę prosić o formularz zwrotu podatku?' }
        ]
    },
    station: {
        title: 'À la Gare',
        phrases: [
            { phrase: 'Un aller simple pour Paris, s\'il vous plaît.', translation: 'Poproszę bilet w jedną stronę do Paryża.' },
            { phrase: 'Un aller-retour, s\'il vous plaît.', translation: 'Poproszę bilet w obie strony.' },
            { phrase: 'De quel quai part le train pour Berlin?', translation: 'Z którego peronu odjeżdża pociąg do Berlina?' },
            { phrase: 'À quelle heure est le prochain train pour Paris?', translation: 'O której jest następny pociąg do Paryża?' },
            { phrase: 'Est-ce un train direct?', translation: 'Czy ten pociąg jest bezpośredni?' },
            { phrase: 'Où est le guichet?', translation: 'Gdzie jest kasa biletowa?' },
            { phrase: 'Où puis-je trouver les horaires?', translation: 'Gdzie znajdę rozkład jazdy?' },
            { phrase: 'Je dois composter mon billet.', translation: 'Muszę skasować bilet.' },
            { phrase: 'Est-ce que cette place est libre?', translation: 'Czy to miejsce jest wolne?' },
            { phrase: 'C\'est mon arrêt.', translation: 'To mój przystanek.' },
            { phrase: 'J\'ai raté mon train.', translation: 'Spóźniłem/am się na pociąg.' },
            { phrase: 'Le train est annulé.', translation: 'Pociąg jest odwołany.' },
            { phrase: 'Première ou seconde classe?', translation: 'Pierwsza czy druga klasa?' },
            { phrase: 'Combien d\'arrêts jusqu\'à la gare centrale?', translation: 'Ile przystanków do dworca centralnego?' },
            { phrase: 'Ce bus va-t-il au centre-ville?', translation: 'Czy ten autobus jedzie do centrum miasta?' },
            { phrase: 'Combien de temps dure le trajet?', translation: 'Jak długa jest podróż?' },
            { phrase: 'Y a-t-il des toilettes dans le train?', translation: 'Czy w pociągu jest toaleta?' },
            { phrase: 'Où sont les consignes?', translation: 'Gdzie są szafki na bagaż?' },
            { phrase: 'Je voudrais réserver une place.', translation: 'Chciałbym/Chciałabym zarezerwować miejsce.' },
            { phrase: 'J\'ai un abonnement.', translation: 'Mam bilet okresowy.' },
            { phrase: 'J\'ai perdu mon billet.', translation: 'Zgubiłem/am bilet.' },
            { phrase: 'Le train arrive sur la voie 5.', translation: 'Pociąg wjeżdża na peron 5.' },
            { phrase: 'Y a-t-il un wagon-restaurant dans ce train?', translation: 'Czy w tym pociągu jest wagon restauracyjny?' },
            { phrase: 'Attention à la marche.', translation: 'Proszę uważać na odstęp (między pociągiem a peronem).' },
            { phrase: 'Je voudrais acheter un billet au distributeur.', translation: 'Chciałbym/Chciałabym kupić bilet w automacie.' },
            { phrase: 'Combien coûte un billet pour enfant?', translation: 'Ile kosztuje bilet dla dziecka?' }
        ]
    },
    party: {
        title: 'À une Fête',
        phrases: [
            { phrase: 'Merci pour l\'invitation.', translation: 'Dziękuję za zaproszenie.' },
            { phrase: 'Enchanté(e).', translation: 'Miło mi cię poznać.' },
            { phrase: 'Santé!', translation: 'Na zdrowie!' },
            { phrase: 'C\'est une super soirée!', translation: 'To świetna impreza!' },
            { phrase: 'Tu veux danser?', translation: 'Chcesz zatańczyć?' },
            { phrase: 'J\'adore cette chanson!', translation: 'Uwielbiam tę piosenkę!' },
            { phrase: 'C\'est délicieux!', translation: 'To jest pyszne!' },
            { phrase: 'Je m\'amuse beaucoup.', translation: 'Świetnie się bawię.' },
            { phrase: 'Je peux t\'offrir un verre?', translation: 'Mogę ci postawić drinka?' },
            { phrase: 'Qu\'est-ce que tu fais dans la vie?', translation: 'Czym się zajmujesz zawodowo?' },
            { phrase: 'Félicitations!', translation: 'Gratulacje!' },
            { phrase: 'Joyeux anniversaire!', translation: 'Wszystkiego najlepszego z okazji urodzin!' },
            { phrase: 'J\'aime beaucoup ta tenue.', translation: 'Bardzo podoba mi się twój strój.' },
            { phrase: 'L\'ambiance est géniale.', translation: 'Atmosfera jest niesamowita.' },
            { phrase: 'On fait une photo.', translation: 'Zróbmy sobie zdjęcie.' },
            { phrase: 'Tu peux me passer les chips?', translation: 'Czy możesz podać mi chipsy?' },
            { phrase: 'Qu\'est-ce que tu bois?', translation: 'Co pijesz?' },
            { phrase: 'Je dois y aller, merci pour tout.', translation: 'Muszę już iść, dziękuję za wszystko.' },
            { phrase: 'On reste en contact.', translation: 'Bądźmy w kontakcie.' },
            { phrase: 'À la prochaine!', translation: 'Do zobaczenia następnym razem!' },
            { phrase: 'On va prendre l\'air?', translation: 'Wyjdziemy na zewnątrz zaczerpnąć świeżego powietrza?' },
            { phrase: 'La musique est un peu trop forte.', translation: 'Muzyka jest trochę za głośna.' },
            { phrase: 'Cet endroit est magnifique.', translation: 'To miejsce jest piękne.' },
            { phrase: 'Qui est le DJ?', translation: 'Kto jest DJ-em?' },
            { phrase: 'Ça ne dérange pas si je fume ici?', translation: 'Czy mogę tu zapalić?' },
            { phrase: 'Je reviens tout de suite.', translation: 'Zaraz wracam.' }
        ]
    },
    emergency: {
        title: 'Urgence',
        phrases: [
            { phrase: 'Au secours!', translation: 'Pomocy!' },
            { phrase: 'Appelez une ambulance!', translation: 'Wezwij karetkę!' },
            { phrase: 'Appelez la police!', translation: 'Wezwij policję!' },
            { phrase: 'Appelez les pompiers!', translation: 'Wezwij straż pożarną!' },
            { phrase: 'Quel est le numéro d\'urgence?', translation: 'Jaki jest numer alarmowy?' },
            { phrase: 'Au feu!', translation: 'Pali się!' },
            { phrase: 'Il y a eu un accident.', translation: 'Wydarzył się wypadek.' },
            { phrase: 'J\'ai besoin d\'un médecin.', translation: 'Potrzebuję lekarza.' },
            { phrase: 'Y a-t-il un hôpital près d\'ici?', translation: 'Czy w pobliżu jest szpital?' },
            { phrase: 'Je ne me sens pas bien.', translation: 'Nie czuję się dobrze.' },
            { phrase: 'J\'ai mal ici.', translation: 'Boli mnie tutaj.' },
            { phrase: 'Je n\'arrive pas à respirer.', translation: 'Nie mogę oddychać.' },
            { phrase: 'On m\'a volé mon sac.', translation: 'Ktoś ukradł moją torbę.' },
            { phrase: 'J\'ai perdu mon portefeuille.', translation: 'Zgubiłem/am portfel.' },
            { phrase: 'J\'ai perdu mon passeport.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Je suis perdu(e).', translation: 'Zgubiłem/am się.' },
            { phrase: 'Mon enfant a disparu.', translation: 'Moje dziecko zaginęło.' },
            { phrase: 'Laissez-moi tranquille!', translation: 'Zostaw mnie w spokoju!' },
            { phrase: 'Attention!', translation: 'Uważaj!' },
            { phrase: 'Vite, s\'il vous plaît!', translation: 'Proszę, pospiesz się!' },
            { phrase: 'J\'ai besoin d\'aide.', translation: 'Potrzebuję pomocy.' },
            { phrase: 'Y a-t-il un médecin ici?', translation: 'Czy jest tu jakiś lekarz?' },
            { phrase: 'Je crois que je me suis cassé la jambe.', translation: 'Chyba złamałem/am nogę.' },
            { phrase: 'Je suis allergique à la pénicilline.', translation: 'Jestem uczulony/a na penicylinę.' },
            { phrase: 'Où est la pharmacie la plus proche?', translation: 'Gdzie jest najbliższa apteka?' },
            { phrase: 'Je dois aller à l\'ambassade.', translation: 'Muszę iść do ambasady.' }
        ]
    },
    hotel: {
        title: 'Hôtel',
        phrases: [
            { phrase: 'J\'ai une réservation.', translation: 'Mam rezerwację.' },
            { phrase: 'Je peux m\'enregistrer, s\'il vous plaît?', translation: 'Czy mogę się zameldować?' },
            { phrase: 'À quelle heure est le départ?', translation: 'O której godzinie jest wymeldowanie?' },
            { phrase: 'Je voudrais régler ma note.', translation: 'Chciałbym/Chciałabym się wymeldować.' },
            { phrase: 'La chambre a-t-elle le Wi-Fi?', translation: 'Czy w pokoju jest Wi-Fi?' },
            { phrase: 'Quel est le mot de passe du Wi-Fi?', translation: 'Jakie jest hasło do Wi-Fi?' },
            { phrase: 'Ma carte-clé ne fonctionne pas.', translation: 'Moja karta-klucz nie działa.' },
            { phrase: 'La climatisation ne fonctionne pas.', translation: 'Klimatyzacja nie działa.' },
            { phrase: 'Il n\'y a pas d\'eau chaude.', translation: 'Nie ma ciepłej wody.' },
            { phrase: 'La chambre est trop bruyante.', translation: 'Pokój jest zbyt głośny.' },
            { phrase: 'Puis-je avoir une chambre avec vue?', translation: 'Czy mogę prosić o pokój z widokiem?' },
            { phrase: 'Puis-je avoir une serviette supplémentaire?', translation: 'Czy mogę prosić o dodatkowy ręcznik?' },
            { phrase: 'Un réveil à 7h, s\'il vous plaît.', translation: 'Poproszę o budzenie o 7 rano.' },
            { phrase: 'Puis-je avoir le petit-déjeuner dans ma chambre?', translation: 'Czy mogę prosić o śniadanie do pokoju?' },
            { phrase: 'À quelle heure le petit-déjeuner est-il servi?', translation: 'O której godzinie podawane jest śniadanie?' },
            { phrase: 'Pouvez-vous m\'appeler un taxi?', translation: 'Czy może pan/pani wezwać dla mnie taksówkę?' },
            { phrase: 'Puis-je payer par carte de crédit?', translation: 'Czy mogę zapłacić kartą kredytową?' },
            { phrase: 'Puis-je laisser mes bagages ici?', translation: 'Czy mogę zostawić tutaj bagaż?' },
            { phrase: 'Où se trouve le restaurant/la salle de sport?', translation: 'Gdzie jest restauracja/siłownia?' },
            { phrase: 'Y a-t-il un coffre-fort dans la chambre?', translation: 'Czy w pokoju jest sejf?' },
            { phrase: 'J\'ai perdu ma clé de chambre.', translation: 'Zgubiłem/am klucz do pokoju.' },
            { phrase: 'L\'hôtel dispose-t-il d\'une piscine?', translation: 'Czy hotel ma basen?' }
        ]
    },
    meteo: {
        title: 'Météo',
        phrases: [
            { phrase: 'Quel temps fait-il aujourd\'hui?', translation: 'Jaka jest dzisiaj pogoda?' },
            { phrase: 'Quelles sont les prévisions météo?', translation: 'Jaka jest prognoza pogody?' },
            { phrase: 'Il fait beau.', translation: 'Jest słonecznie.' },
            { phrase: 'Il pleut.', translation: 'Pada deszcz.' },
            { phrase: 'Le ciel est nuageux.', translation: 'Jest pochmurno.' },
            { phrase: 'Il y a du vent.', translation: 'Jest wietrznie.' },
            { phrase: 'Il fait froid.', translation: 'Jest zimno.' },
            { phrase: 'Il fait chaud.', translation: 'Jest gorąco.' },
            { phrase: 'Quelle est la température?', translation: 'Jaka jest temperatura?' },
            { phrase: 'Il fait 20 degrés Celsius.', translation: 'Jest 20 stopni Celsjusza.' },
            { phrase: 'Il neige.', translation: 'Pada śnieg.' },
            { phrase: 'Il y a du brouillard.', translation: 'Jest mgliście.' },
            { phrase: 'Il y a un orage.', translation: 'Jest burza.' },
            { phrase: 'Va-t-il pleuvoir demain?', translation: 'Czy jutro będzie padać?' },
            { phrase: 'C\'est une belle journée.', translation: 'To piękny dzień.' },
            { phrase: 'Le soleil brille.', translation: 'Słońce świeci.' },
            { phrase: 'Il gèle.', translation: 'Jest mroźno.' },
            { phrase: 'J\'ai besoin d\'un parapluie.', translation: 'Potrzebuję parasola.' },
            { phrase: 'C\'est humide.', translation: 'Jest wilgotno.' },
            { phrase: 'Le temps change.', translation: 'Pogoda się zmienia.' },
            { phrase: 'Il commence à faire nuit.', translation: 'Robi się ciemno.' }
        ]
    }
  },
  es: {
    restaurant: {
      title: 'En el Restaurante',
      phrases: [
        { phrase: 'Una mesa para dos, por favor.', translation: 'Stolik dla dwojga, proszę.' },
        { phrase: 'Quisiera reservar una mesa.', translation: 'Chciałbym/Chciałabym zarezerwować stolik.' },
        { phrase: '¿Puedo ver el menú, por favor?', translation: 'Czy mogę zobaczyć menu?' },
        { phrase: '¿Qué me recomienda?', translation: 'Co mi pan/pani poleca?' },
        { phrase: 'Quisiera pedir...', translation: 'Chciałbym/Chciałabym zamówić...' },
        { phrase: '¿Cuál es la sopa del día?', translation: 'Jaka jest zupa dnia?' },
        { phrase: 'Soy vegetariano/a.', translation: 'Jestem wegetarianinem/wegetarianką.' },
        { phrase: 'Soy alérgico/a a las nueces.', translation: 'Mam alergię na orzechy.' },
        { phrase: '¿Este plato es picante?', translation: 'Czy to danie jest ostre?' },
        { phrase: 'Un vaso de agua, por favor.', translation: 'Poproszę szklankę wody.' },
        { phrase: 'Otra copa de vino, por favor.', translation: 'Jeszcze jeden kieliszek wina, proszę.' },
        { phrase: '¿Cuánto tiempo tendremos que esperar?', translation: 'Jak długo będziemy musieli czekać?' },
        { phrase: '¡Buen provecho!', translation: 'Smacznego!' },
        { phrase: '¡Todo estaba delicioso!', translation: 'Wszystko było pyszne!' },
        { phrase: 'Mi comida está fría.', translation: 'Moje jedzenie jest zimne.' },
        { phrase: 'Esto no es lo que pedí.', translation: 'To nie jest to, co zamawiałem/am.' },
        { phrase: 'La cuenta, por favor.', translation: 'Rachunek, proszę.' },
        { phrase: '¿Podemos pagar por separado?', translation: 'Czy możemy zapłacić osobno?' },
        { phrase: '¿El servicio está incluido?', translation: 'Czy obsługa jest wliczona w cenę?' },
        { phrase: 'Quédese con el cambio.', translation: 'Reszty nie trzeba.' },
        { phrase: '¿Dónde está el baño?', translation: 'Gdzie jest toaleta?' },
        { phrase: 'Tomaré lo mismo.', translation: 'Wezmę to samo.' },
        { phrase: '¿Puede recomendar un plato local?', translation: 'Czy może pan/pani polecić lokalne danie?' },
        { phrase: '¿Cuál es su horario?', translation: 'W jakich godzinach jest otwarte?' },
        { phrase: '¿Tiene una silla alta para niños?', translation: 'Czy macie krzesełko dla dziecka?' },
        { phrase: '¿Me lo puede poner para llevar?', translation: 'Czy mogę to wziąć na wynos?' }
      ]
    },
    airport: {
        title: 'En el Aeropuerto',
        phrases: [
            { phrase: '¿Dónde está el mostrador de facturación para este vuelo?', translation: 'Gdzie jest stanowisko odprawy dla tego lotu?' },
            { phrase: '¿Mi vuelo sale a tiempo?', translation: 'Czy mój lot jest o czasie?' },
            { phrase: 'Tengo una maleta para facturar.', translation: 'Mam jedną torbę do nadania.' },
            { phrase: '¿Dónde está la puerta de embarque?', translation: 'Gdzie jest bramka do wejścia na pokład?' },
            { phrase: '¿Dónde está la puerta de embarque B25?', translation: 'Gdzie jest bramka B25?' },
            { phrase: '¿A qué hora empieza el embarque?', translation: 'O której godzinie zaczyna się wejście na pokład?' },
            { phrase: 'Esta es mi tarjeta de embarque.', translation: 'To jest moja karta pokładowa.' },
            { phrase: 'Quisiera un asiento de ventanilla/pasillo, por favor.', translation: 'Poproszę o miejsce przy oknie/od przejścia.' },
            { phrase: '¿Tengo que sacar mi portátil de la bolsa?', translation: 'Czy muszę wyjąć laptopa z torby?' },
            { phrase: '¿Me puede dar una manta y una almohada?', translation: 'Czy mogę prosić o koc i poduszkę?' },
            { phrase: 'Por favor, abróchense los cinturones.', translation: 'Proszę zapiąć pasy.' },
            { phrase: '¿Dónde puedo recoger mi equipaje?', translation: 'Gdzie mogę odebrać bagaż?' },
            { phrase: '¿Dónde puedo encontrar la sala de llegadas?', translation: 'Gdzie znajdę halę przylotów?' },
            { phrase: 'No tengo nada que declarar.', translation: 'Nie mam nic do oclenia.' },
            { phrase: 'Mi vuelo está retrasado.', translation: 'Mój lot jest opóźniony.' },
            { phrase: 'Mi vuelo ha sido cancelado.', translation: 'Mój lot został odwołany.' },
            { phrase: 'Mi equipaje no ha llegado.', translation: 'Mój bagaż nie dotarł.' },
            { phrase: 'He perdido mi pasaporte.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Tengo un vuelo de conexión.', translation: 'Mam lot z przesiadką.' },
            { phrase: '¿Dónde hay una oficina de cambio?', translation: 'Gdzie jest kantor wymiany walut?' },
            { phrase: '¿Cómo llego al centro de la ciudad?', translation: 'Jak dostanę się do centrum miasta?' },
            { phrase: '¿Puede decirme dónde está la parada de taxis?', translation: 'Czy może mi pan/pani powiedzieć, gdzie jest postój taksówek?' },
            { phrase: '¿Dónde está el punto de información?', translation: 'Gdzie jest punkt informacyjny?' },
            { phrase: '¿Hay Wi-Fi aquí?', translation: 'Czy jest tu Wi-Fi?' },
            { phrase: 'Estoy buscando la sala de embarque.', translation: 'Szukam hali odlotów.' },
            { phrase: '¿Podría ayudarme con mis maletas?', translation: 'Czy mógłbyś/mogłabyś mi pomóc z torbami?' }
        ]
    },
    shop: {
        title: 'En la Tienda',
        phrases: [
            { phrase: 'Solo estoy mirando, gracias.', translation: 'Tylko się rozglądam, dziękuję.' },
            { phrase: '¿Cuánto cuesta esto?', translation: 'Ile to kosztuje?' },
            { phrase: '¿Me puede ayudar?', translation: 'Czy może mi pan/pani pomóc?' },
            { phrase: '¿Tiene esto en una talla más pequeña/grande?', translation: 'Czy macie to w mniejszym/większym rozmiarze?' },
            { phrase: '¿Lo tiene en otro color?', translation: 'Czy macie to w innym kolorze?' },
            { phrase: '¿Puedo probármelo?', translation: 'Czy mogę to przymierzyć?' },
            { phrase: '¿Dónde están los probadores?', translation: 'Gdzie są przymierzalnie?' },
            { phrase: 'Me lo llevo.', translation: 'Wezmę to.' },
            { phrase: '¿Puedo pagar con tarjeta?', translation: 'Czy mogę zapłacić kartą?' },
            { phrase: '¿Aceptan tarjetas de crédito?', translation: 'Czy akceptujecie karty kredytowe?' },
            { phrase: 'Pago en efectivo.', translation: 'Zapłacę gotówką.' },
            { phrase: '¿Me da un recibo, por favor?', translation: 'Czy mogę prosić o paragon?' },
            { phrase: '¿Dónde está la caja?', translation: 'Gdzie jest kasa?' },
            { phrase: '¿Está en oferta?', translation: 'Czy to jest na wyprzedaży?' },
            { phrase: 'Es demasiado caro.', translation: 'To jest za drogie.' },
            { phrase: '¿Tiene algo más barato?', translation: 'Czy macie coś tańszego?' },
            { phrase: 'Quisiera devolver esto.', translation: 'Chciałbym/Chciałabym to zwrócić.' },
            { phrase: '¿Cuál es su política de devoluciones?', translation: 'Jaka jest wasza polityka zwrotów?' },
            { phrase: '¿Puede envolverlo para regalo?', translation: 'Czy może pan/pani zapakować to na prezent?' },
            { phrase: 'Estoy buscando un recuerdo.', translation: 'Szukam pamiątki.' },
            { phrase: 'Estoy buscando un regalo para mi amigo/a.', translation: 'Szukam prezentu dla przyjaciela/przyjaciółki.' },
            { phrase: '¿Dónde puedo encontrar el pan?', translation: 'Gdzie znajdę chleb?' },
            { phrase: 'Necesito un carrito de la compra.', translation: 'Potrzebuję wózka na zakupy.' },
            { phrase: 'Una bolsa de plástico, por favor.', translation: 'Poproszę torbę foliową.' },
            { phrase: '¿A qué hora cierran?', translation: 'O której zamykacie?' },
            { phrase: '¿Me puede dar el formulario de tax-free?', translation: 'Czy mogę prosić o formularz zwrotu podatku?' }
        ]
    },
    station: {
        title: 'En la Estación',
        phrases: [
            { phrase: 'Un billete de ida a Madrid, por favor.', translation: 'Poproszę bilet w jedną stronę do Madrytu.' },
            { phrase: 'Un billete de ida y vuelta, por favor.', translation: 'Poproszę bilet w obie strony.' },
            { phrase: '¿De qué andén sale el tren para Barcelona?', translation: 'Z którego peronu odjeżdża pociąg do Barcelony?' },
            { phrase: '¿A qué hora es el próximo tren a Sevilla?', translation: 'O której jest następny pociąg do Sewilli?' },
            { phrase: '¿Este tren es directo?', translation: 'Czy ten pociąg jest bezpośredni?' },
            { phrase: '¿Dónde está la taquilla?', translation: 'Gdzie jest kasa biletowa?' },
            { phrase: '¿Dónde puedo encontrar el horario?', translation: 'Gdzie znajdę rozkład jazdy?' },
            { phrase: 'Tengo que validar mi billete.', translation: 'Muszę skasować bilet.' },
            { phrase: '¿Está ocupado este asiento?', translation: 'Czy to miejsce jest zajęte?' },
            { phrase: 'Esta es mi parada.', translation: 'To mój przystanek.' },
            { phrase: 'He perdido mi tren.', translation: 'Spóźniłem/am się na pociąg.' },
            { phrase: 'El tren está cancelado.', translation: 'Pociąg jest odwołany.' },
            { phrase: '¿Primera o segunda clase?', translation: 'Pierwsza czy druga klasa?' },
            { phrase: '¿Cuántas paradas hasta la estación central?', translation: 'Ile przystanków do dworca centralnego?' },
            { phrase: '¿Este autobús va al centro?', translation: 'Czy ten autobus jedzie do centrum?' },
            { phrase: '¿Cuánto dura el viaje?', translation: 'Jak długa jest podróż?' },
            { phrase: '¿Hay un baño en el tren?', translation: 'Czy w pociągu jest toaleta?' },
            { phrase: '¿Dónde están las consignas?', translation: 'Gdzie są szafki na bagaż?' },
            { phrase: 'Quisiera reservar un asiento.', translation: 'Chciałbym/Chciałabym zarezerwować miejsce.' },
            { phrase: 'Tengo un abono de transporte.', translation: 'Mam bilet okresowy.' },
            { phrase: 'He perdido mi billete.', translation: 'Zgubiłem/am bilet.' },
            { phrase: 'El tren llega al andén 5.', translation: 'Pociąg wjeżdża na peron 5.' },
            { phrase: '¿Hay vagón restaurante en este tren?', translation: 'Czy w tym pociągu jest wagon restauracyjny?' },
            { phrase: 'Cuidado con el hueco entre el tren y el andén.', translation: 'Proszę uważać na odstęp (między pociągiem a peronem).' },
            { phrase: 'Quisiera comprar un billete en la máquina.', translation: 'Chciałbym/Chciałabym kupić bilet w automacie.' },
            { phrase: '¿Cuánto cuesta un billete para niño?', translation: 'Ile kosztuje bilet dla dziecka?' }
        ]
    },
    party: {
        title: 'En una Fiesta',
        phrases: [
            { phrase: 'Gracias por invitarme.', translation: 'Dziękuję za zaproszenie.' },
            { phrase: 'Encantado/a de conocerte.', translation: 'Miło mi cię poznać.' },
            { phrase: '¡Salud!', translation: 'Na zdrowie!' },
            { phrase: '¡Es una fiesta genial!', translation: 'To świetna impreza!' },
            { phrase: '¿Quieres bailar?', translation: 'Chcesz zatańczyć?' },
            { phrase: '¡Me encanta esta canción!', translation: 'Uwielbiam tę piosenkę!' },
            { phrase: '¡Esto está delicioso!', translation: 'To jest pyszne!' },
            { phrase: 'Me lo estoy pasando genial.', translation: 'Świetnie się bawię.' },
            { phrase: '¿Te traigo algo de beber?', translation: 'Przynieść ci coś do picia?' },
            { phrase: '¿A qué te dedicas?', translation: 'Czym się zajmujesz zawodowo?' },
            { phrase: '¡Enhorabuena! / ¡Felicidades!', translation: 'Gratulacje!' },
            { phrase: '¡Feliz cumpleaños!', translation: 'Wszystkiego najlepszego z okazji urodzin!' },
            { phrase: 'Me gusta mucho tu ropa.', translation: 'Bardzo podoba mi się twój strój.' },
            { phrase: 'El ambiente es increíble.', translation: 'Atmosfera jest niesamowita.' },
            { phrase: 'Vamos a hacernos una foto.', translation: 'Zróbmy sobie zdjęcie.' },
            { phrase: '¿Me pasas los aperitivos?', translation: 'Czy możesz podać mi przekąski?' },
            { phrase: '¿Qué estás bebiendo?', translation: 'Co pijesz?' },
            { phrase: 'Tengo que irme ya, gracias por todo.', translation: 'Muszę już iść, dziękuję za wszystko.' },
            { phrase: 'Seguimos en contacto.', translation: 'Bądźmy w kontakcie.' },
            { phrase: '¡Hasta la próxima!', translation: 'Do zobaczenia następnym razem!' },
            { phrase: '¿Salimos a tomar el aire?', translation: 'Wyjdziemy na zewnątrz zaczerpnąć świeżego powietrza?' },
            { phrase: 'La música está un poco alta.', translation: 'Muzyka jest trochę za głośna.' },
            { phrase: 'Este lugar es precioso.', translation: 'To miejsce jest piękne.' },
            { phrase: '¿Quién es el DJ?', translation: 'Kto jest DJ-em?' },
            { phrase: '¿Te importa si fumo aquí?', translation: 'Czy mogę tu zapalić?' },
            { phrase: 'Ahora vuelvo.', translation: 'Zaraz wracam.' }
        ]
    },
    emergency: {
        title: 'Emergencia',
        phrases: [
            { phrase: '¡Socorro! / ¡Ayuda!', translation: 'Pomocy!' },
            { phrase: '¡Llame a una ambulancia!', translation: 'Wezwij karetkę!' },
            { phrase: '¡Llame a la policía!', translation: 'Wezwij policję!' },
            { phrase: '¡Llame a los bomberos!', translation: 'Wezwij straż pożarną!' },
            { phrase: '¿Cuál es el número de emergencias?', translation: 'Jaki jest numer alarmowy?' },
            { phrase: '¡Fuego!', translation: 'Pali się!' },
            { phrase: 'Ha habido un accidente.', translation: 'Wydarzył się wypadek.' },
            { phrase: 'Necesito un médico.', translation: 'Potrzebuję lekarza.' },
            { phrase: '¿Hay un hospital cerca?', translation: 'Czy w pobliżu jest szpital?' },
            { phrase: 'No me encuentro bien.', translation: 'Nie czuję się dobrze.' },
            { phrase: 'Me duele aquí.', translation: 'Boli mnie tutaj.' },
            { phrase: 'No puedo respirar.', translation: 'Nie mogę oddychać.' },
            { phrase: 'Alguien me ha robado el bolso.', translation: 'Ktoś ukradł moją torbę.' },
            { phrase: 'He perdido mi cartera.', translation: 'Zgubiłem/am portfel.' },
            { phrase: 'He perdido mi pasaporte.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Estoy perdido/a.', translation: 'Zgubiłem/am się.' },
            { phrase: 'Mi hijo/a ha desaparecido.', translation: 'Moje dziecko zaginęło.' },
            { phrase: '¡Déjeme en paz!', translation: 'Zostaw mnie w spokoju!' },
            { phrase: '¡Cuidado!', translation: 'Uważaj!' },
            { phrase: '¡Rápido, por favor!', translation: 'Proszę, pospiesz się!' },
            { phrase: 'Necesito ayuda.', translation: 'Potrzebuję pomocy.' },
            { phrase: '¿Hay algún médico aquí?', translation: 'Czy jest tu jakiś lekarz?' },
            { phrase: 'Creo que me he roto la pierna.', translation: 'Chyba złamałem/am nogę.' },
            { phrase: 'Soy alérgico/a a la penicilina.', translation: 'Jestem uczulony/a na penicylinę.' },
            { phrase: '¿Dónde está la farmacia más cercana?', translation: 'Gdzie jest najbliższa apteka?' },
            { phrase: 'Necesito ir a la embajada.', translation: 'Muszę iść do ambasady.' }
        ]
    },
    hotel: {
        title: 'Hotel',
        phrases: [
            { phrase: 'Tengo una reserva.', translation: 'Mam rezerwację.' },
            { phrase: '¿Puedo registrarme, por favor?', translation: 'Czy mogę się zameldować?' },
            { phrase: '¿A qué hora es el check-out?', translation: 'O której godzinie jest wymeldowanie?' },
            { phrase: 'Quisiera hacer el check-out.', translation: 'Chciałbym/Chciałabym się wymeldować.' },
            { phrase: '¿La habitación tiene Wi-Fi?', translation: 'Czy w pokoju jest Wi-Fi?' },
            { phrase: '¿Cuál es la contraseña del Wi-Fi?', translation: 'Jakie jest hasło do Wi-Fi?' },
            { phrase: 'Mi tarjeta de la habitación no funciona.', translation: 'Moja karta-klucz nie działa.' },
            { phrase: 'El aire acondicionado no funciona.', translation: 'Klimatyzacja nie działa.' },
            { phrase: 'No hay agua caliente.', translation: 'Nie ma ciepłej wody.' },
            { phrase: 'La habitación es demasiado ruidosa.', translation: 'Pokój jest zbyt głośny.' },
            { phrase: '¿Puedo tener una habitación con vistas?', translation: 'Czy mogę prosić o pokój z widokiem?' },
            { phrase: '¿Puedo tener una toalla extra?', translation: 'Czy mogę prosić o dodatkowy ręcznik?' },
            { phrase: 'Una llamada de despertador a las 7, por favor.', translation: 'Poproszę o budzenie o 7 rano.' },
            { phrase: '¿Puedo pedir el desayuno en la habitación?', translation: 'Czy mogę prosić o śniadanie do pokoju?' },
            { phrase: '¿A qué hora se sirve el desayuno?', translation: 'O której godzinie podawane jest śniadanie?' },
            { phrase: '¿Puede llamarme un taxi?', translation: 'Czy może pan/pani wezwać dla mnie taksówkę?' },
            { phrase: '¿Puedo pagar con tarjeta de crédito?', translation: 'Czy mogę zapłacić kartą kredytową?' },
            { phrase: '¿Puedo dejar mi equipaje aquí?', translation: 'Czy mogę zostawić tutaj bagaż?' },
            { phrase: '¿Dónde está el restaurante/gimnasio?', translation: 'Gdzie jest restauracja/siłownia?' },
            { phrase: '¿Hay caja fuerte en la habitación?', translation: 'Czy w pokoju jest sejf?' },
            { phrase: 'He perdido la llave de mi habitación.', translation: 'Zgubiłem/am klucz do pokoju.' },
            { phrase: '¿El hotel tiene piscina?', translation: 'Czy hotel ma basen?' }
        ]
    },
    tiempo: {
        title: 'Tiempo',
        phrases: [
            { phrase: '¿Qué tiempo hace hoy?', translation: 'Jaka jest dzisiaj pogoda?' },
            { phrase: '¿Cuál es el pronóstico del tiempo?', translation: 'Jaka jest prognoza pogody?' },
            { phrase: 'Hace sol.', translation: 'Jest słonecznie.' },
            { phrase: 'Está lloviendo.', translation: 'Pada deszcz.' },
            { phrase: 'Está nublado.', translation: 'Jest pochmurno.' },
            { phrase: 'Hace viento.', translation: 'Jest wietrznie.' },
            { phrase: 'Hace frío.', translation: 'Jest zimno.' },
            { phrase: 'Hace calor.', translation: 'Jest gorąco.' },
            { phrase: '¿Qué temperatura hace?', translation: 'Jaka jest temperatura?' },
            { phrase: 'Estamos a 20 grados centígrados.', translation: 'Jest 20 stopni Celsjusza.' },
            { phrase: 'Está nevando.', translation: 'Pada śnieg.' },
            { phrase: 'Hay niebla.', translation: 'Jest mgliście.' },
            { phrase: 'Hay una tormenta.', translation: 'Jest burza.' },
            { phrase: '¿Va a llover mañana?', translation: 'Czy jutro będzie padać?' },
            { phrase: 'Hace un día precioso.', translation: 'To piękny dzień.' },
            { phrase: 'El sol brilla.', translation: 'Słońce świeci.' },
            { phrase: 'Hace un frío que pela.', translation: 'Jest mroźno.' },
            { phrase: 'Necesito un paraguas.', translation: 'Potrzebuję parasola.' },
            { phrase: 'Hay humedad.', translation: 'Jest wilgotno.' },
            { phrase: 'El tiempo está cambiando.', translation: 'Pogoda się zmienia.' },
            { phrase: 'Está anocheciendo.', translation: 'Robi się ciemno.' }
        ]
    }
  },
  it: {
    restaurant: {
      title: 'Al Ristorante',
      phrases: [
        { phrase: 'Un tavolo per due, per favore.', translation: 'Stolik dla dwojga, proszę.' },
        { phrase: 'Vorrei prenotare un tavolo.', translation: 'Chciałbym/Chciałabym zarezerwować stolik.' },
        { phrase: 'Posso vedere il menu, per favore?', translation: 'Czy mogę zobaczyć menu?' },
        { phrase: 'Cosa ci consiglia?', translation: 'Co nam Pan/Pani poleca?' },
        { phrase: 'Vorrei ordinare...', translation: 'Chciałbym/Chciałabym zamówić...' },
        { phrase: 'Qual è la zuppa del giorno?', translation: 'Jaka jest zupa dnia?' },
        { phrase: 'Sono vegetariano/a.', translation: 'Jestem wegetarianinem/wegetarianką.' },
        { phrase: 'Sono allergico/a alle noci.', translation: 'Mam alergię na orzechy.' },
        { phrase: 'Questo piatto è piccante?', translation: 'Czy to danie jest ostre?' },
        { phrase: 'Un po\' d\'acqua, per favore.', translation: 'Poproszę trochę wody.' },
        { phrase: 'Un altro bicchiere di vino, per favore.', translation: 'Jeszcze jeden kieliszek wina, proszę.' },
        { phrase: 'Quanto dovremo aspettare?', translation: 'Jak długo będziemy musieli czekać?' },
        { phrase: 'Buon appetito!', translation: 'Smacznego!' },
        { phrase: 'Era tutto delizioso!', translation: 'Wszystko było pyszne!' },
        { phrase: 'Il mio piatto è freddo.', translation: 'Moje jedzenie jest zimne.' },
        { phrase: 'Non è quello che ho ordinato.', translation: 'To nie jest to, co zamawiałem/am.' },
        { phrase: 'Il conto, per favore.', translation: 'Rachunek, proszę.' },
        { phrase: 'Possiamo pagare separatamente?', translation: 'Czy możemy zapłacić osobno?' },
        { phrase: 'Il servizio è incluso?', translation: 'Czy obsługa jest wliczona w cenę?' },
        { phrase: 'Tenga il resto.', translation: 'Reszty nie trzeba.' },
        { phrase: 'Dov\'è il bagno?', translation: 'Gdzie jest toaleta?' },
        { phrase: 'Prendo lo stesso.', translation: 'Wezmę to samo.' },
        { phrase: 'Può consigliare un piatto locale?', translation: 'Czy może pan/pani polecić lokalne danie?' },
        { phrase: 'Qual è il vostro orario di apertura?', translation: 'W jakich godzinach jest otwarte?' },
        { phrase: 'Avete un seggiolone per bambini?', translation: 'Czy macie krzesełko dla dziecka?' },
        { phrase: 'Posso prenderlo da asporto?', translation: 'Czy mogę to wziąć na wynos?' }
      ]
    },
    airport: {
        title: 'All\'Aeroporto',
        phrases: [
            { phrase: 'Dov\'è il banco del check-in per questo volo?', translation: 'Gdzie jest stanowisko odprawy dla tego lotu?' },
            { phrase: 'Il mio volo è in orario?', translation: 'Czy mój lot jest o czasie?' },
            { phrase: 'Ho una valigia da imbarcare.', translation: 'Mam jedną torbę do nadania.' },
            { phrase: 'Dov\'è il gate d\'imbarco?', translation: 'Gdzie jest bramka do wejścia na pokład?' },
            { phrase: 'Dov\'è l\'uscita B25?', translation: 'Gdzie jest bramka B25?' },
            { phrase: 'A che ora inizia l\'imbarco?', translation: 'O której godzinie zaczyna się wejście na pokład?' },
            { phrase: 'Questa è la mia carta d\'imbarco.', translation: 'To jest moja karta pokładowa.' },
            { phrase: 'Vorrei un posto vicino al finestrino/corridoio.', translation: 'Poproszę o miejsce przy oknie/od przejścia.' },
            { phrase: 'Devo togliere il portatile dalla borsa?', translation: 'Czy muszę wyjąć laptopa z torby?' },
            { phrase: 'Posso avere una coperta e un cuscino?', translation: 'Czy mogę prosić o koc i poduszkę?' },
            { phrase: 'Allacciare le cinture di sicurezza, prego.', translation: 'Proszę zapiąć pasy.' },
            { phrase: 'Dove si ritirano i bagagli?', translation: 'Gdzie mogę odebrać bagaż?' },
            { phrase: 'Dove posso trovare la sala arrivi?', translation: 'Gdzie znajdę halę przylotów?' },
            { phrase: 'Non ho nulla da dichiarare.', translation: 'Nie mam nic do oclenia.' },
            { phrase: 'Il mio volo è in ritardo.', translation: 'Mój lot jest opóźniony.' },
            { phrase: 'Il mio volo è stato cancellato.', translation: 'Mój lot został odwołany.' },
            { phrase: 'Il mio bagaglio non è arrivato.', translation: 'Mój bagaż nie dotarł.' },
            { phrase: 'Ho perso il passaporto.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Ho un volo in coincidenza.', translation: 'Mam lot z przesiadką.' },
            { phrase: 'Dov\'è l\'ufficio cambio?', translation: 'Gdzie jest kantor wymiany walut?' },
            { phrase: 'Come arrivo in centro?', translation: 'Jak dostanę się do centrum miasta?' },
            { phrase: 'Mi può dire dov\'è la fermata dei taxi?', translation: 'Czy może mi pan/pani powiedzieć, gdzie jest postój taksówek?' },
            { phrase: 'Dov\'è il punto informazioni?', translation: 'Gdzie jest punkt informacyjny?' },
            { phrase: 'C\'è il Wi-Fi qui?', translation: 'Czy jest tu Wi-Fi?' },
            { phrase: 'Cerco la sala partenze.', translation: 'Szukam hali odlotów.' },
            { phrase: 'Potrebbe aiutarmi con i bagagli?', translation: 'Czy mógłbyś/mogłabyś mi pomóc z bagażem?' }
        ]
    },
    shop: {
        title: 'In Negozio',
        phrases: [
            { phrase: 'Sto solo guardando, grazie.', translation: 'Tylko się rozglądam, dziękuję.' },
            { phrase: 'Quanto costa questo?', translation: 'Ile to kosztuje?' },
            { phrase: 'Mi può aiutare?', translation: 'Czy może mi pan/pani pomóc?' },
            { phrase: 'Ce l\'ha in una taglia più piccola/grande?', translation: 'Czy macie to w mniejszym/większym rozmiarze?' },
            { phrase: 'Ce l\'ha di un altro colore?', translation: 'Czy macie to w innym kolorze?' },
            { phrase: 'Posso provarlo?', translation: 'Czy mogę to przymierzyć?' },
            { phrase: 'Dove sono i camerini?', translation: 'Gdzie są przymierzalnie?' },
            { phrase: 'Lo prendo.', translation: 'Wezmę to.' },
            { phrase: 'Posso pagare con la carta?', translation: 'Czy mogę zapłacić kartą?' },
            { phrase: 'Accettate carte di credito?', translation: 'Czy akceptujecie karty kredytowe?' },
            { phrase: 'Pago in contanti.', translation: 'Zapłacę gotówką.' },
            { phrase: 'Posso avere lo scontrino, per favore?', translation: 'Czy mogę prosić o paragon?' },
            { phrase: 'Dov\'è la cassa?', translation: 'Gdzie jest kasa?' },
            { phrase: 'È in saldo?', translation: 'Czy to jest na wyprzedaży?' },
            { phrase: 'È troppo caro.', translation: 'To jest za drogie.' },
            { phrase: 'Ha qualcosa di più economico?', translation: 'Czy macie coś tańszego?' },
            { phrase: 'Vorrei restituire questo articolo.', translation: 'Chciałbym/Chciałabym to zwrócić.' },
            { phrase: 'Qual è la vostra politica sui resi?', translation: 'Jaka jest wasza polityka zwrotów?' },
            { phrase: 'Può farmi un pacchetto regalo?', translation: 'Czy może pan/pani zapakować to na prezent?' },
            { phrase: 'Cerco un souvenir.', translation: 'Szukam pamiątki.' },
            { phrase: 'Cerco un regalo per un mio amico/una mia amica.', translation: 'Szukam prezentu dla przyjaciela/przyjaciółki.' },
            { phrase: 'Dove posso trovare il pane?', translation: 'Gdzie znajdę chleb?' },
            { phrase: 'Ho bisogno di un carrello.', translation: 'Potrzebuję wózka na zakupy.' },
            { phrase: 'Un sacchetto di plastica, per favore.', translation: 'Poproszę torbę foliową.' },
            { phrase: 'A che ora chiudete?', translation: 'O której zamykacie?' },
            { phrase: 'Posso avere il modulo per il tax-free?', translation: 'Czy mogę prosić o formularz zwrotu podatku?' }
        ]
    },
    station: {
        title: 'Alla Stazione',
        phrases: [
            { phrase: 'Un biglietto di sola andata per Roma, per favore.', translation: 'Poproszę bilet w jedną stronę do Rzymu.' },
            { phrase: 'Un biglietto di andata e ritorno, per favore.', translation: 'Poproszę bilet w obie strony.' },
            { phrase: 'Da quale binario parte il treno per Milano?', translation: 'Z którego peronu odjeżdża pociąg do Mediolanu?' },
            { phrase: 'A che ora è il prossimo treno per Napoli?', translation: 'O której jest następny pociąg do Neapolu?' },
            { phrase: 'Questo treno è diretto?', translation: 'Czy ten pociąg jest bezpośredni?' },
            { phrase: 'Dov\'è la biglietteria?', translation: 'Gdzie jest kasa biletowa?' },
            { phrase: 'Dove posso trovare l\'orario ferroviario?', translation: 'Gdzie znajdę rozkład jazdy?' },
            { phrase: 'Devo convalidare il biglietto.', translation: 'Muszę skasować bilet.' },
            { phrase: 'È occupato questo posto?', translation: 'Czy to miejsce jest zajęte?' },
            { phrase: 'Questa è la mia fermata.', translation: 'To mój przystanek.' },
            { phrase: 'Ho perso il treno.', translation: 'Spóźniłem/am się na pociąg.' },
            { phrase: 'Il treno è stato cancellato.', translation: 'Pociąg jest odwołany.' },
            { phrase: 'Prima o seconda classe?', translation: 'Pierwsza czy druga klasa?' },
            { phrase: 'Quante fermate fino alla stazione centrale?', translation: 'Ile przystanków do dworca centralnego?' },
            { phrase: 'Questo autobus va in centro?', translation: 'Czy ten autobus jedzie do centrum?' },
            { phrase: 'Quanto dura il viaggio?', translation: 'Jak długa jest podróż?' },
            { phrase: 'C\'è un bagno sul treno?', translation: 'Czy w pociągu jest toaleta?' },
            { phrase: 'Dove sono i depositi bagagli?', translation: 'Gdzie są szafki na bagaż?' },
            { phrase: 'Vorrei prenotare un posto.', translation: 'Chciałbym/Chciałabym zarezerwować miejsce.' },
            { phrase: 'Ho un abbonamento.', translation: 'Mam bilet okresowy.' },
            { phrase: 'Ho perso il biglietto.', translation: 'Zgubiłem/am bilet.' },
            { phrase: 'Il treno arriva al binario 5.', translation: 'Pociąg wjeżdża na peron 5.' },
            { phrase: 'C\'è una carrozza ristorante su questo treno?', translation: 'Czy w tym pociągu jest wagon restauracyjny?' },
            { phrase: 'Attenzione alla distanza tra il treno e la banchina.', translation: 'Proszę uważać na odstęp (między pociągiem a peronem).' },
            { phrase: 'Vorrei comprare un biglietto alla macchinetta.', translation: 'Chciałbym/Chciałabym kupić bilet w automacie.' },
            { phrase: 'Quanto costa un biglietto per bambini?', translation: 'Ile kosztuje bilet dla dziecka?' }
        ]
    },
    party: {
        title: 'A una Festa',
        phrases: [
            { phrase: 'Grazie per l\'invito.', translation: 'Dziękuję za zaproszenie.' },
            { phrase: 'Piacere di conoscerti.', translation: 'Miło mi cię poznać.' },
            { phrase: 'Salute! / Cin cin!', translation: 'Na zdrowie!' },
            { phrase: 'È una festa fantastica!', translation: 'To świetna impreza!' },
            { phrase: 'Vuoi ballare?', translation: 'Chcesz zatańczyć?' },
            { phrase: 'Adoro questa canzone!', translation: 'Uwielbiam tę piosenkę!' },
            { phrase: 'È delizioso!', translation: 'To jest pyszne!' },
            { phrase: 'Mi sto divertendo un mondo.', translation: 'Świetnie się bawię.' },
            { phrase: 'Posso offrirti da bere?', translation: 'Mogę ci postawić drinka?' },
            { phrase: 'Cosa fai nella vita?', translation: 'Czym się zajmujesz zawodowo?' },
            { phrase: 'Congratulazioni!', translation: 'Gratulacje!' },
            { phrase: 'Buon compleanno!', translation: 'Wszystkiego najlepszego z okazji urodzin!' },
            { phrase: 'Mi piace molto come sei vestito/a.', translation: 'Bardzo podoba mi się twój strój.' },
            { phrase: 'L\'atmosfera è fantastica.', translation: 'Atmosfera jest niesamowita.' },
            { phrase: 'Facciamoci una foto.', translation: 'Zróbmy sobie zdjęcie.' },
            { phrase: 'Mi passi le patatine?', translation: 'Czy możesz podać mi chipsy?' },
            { phrase: 'Cosa stai bevendo?', translation: 'Co pijesz?' },
            { phrase: 'Devo andare ora, grazie di tutto.', translation: 'Muszę już iść, dziękuję za wszystko.' },
            { phrase: 'Rimaniamo in contatto.', translation: 'Bądźmy w kontakcie.' },
            { phrase: 'Alla prossima!', translation: 'Do zobaczenia następnym razem!' },
            { phrase: 'Andiamo fuori a prendere una boccata d\'aria?', translation: 'Wyjdziemy na zewnątrz zaczerpnąć świeżego powietrza?' },
            { phrase: 'La musica è un po\' troppo alta.', translation: 'Muzyka jest trochę za głośna.' },
            { phrase: 'Questo posto è bellissimo.', translation: 'To miejsce jest piękne.' },
            { phrase: 'Chi è il DJ?', translation: 'Kto jest DJ-em?' },
            { phrase: 'Ti dispiace se fumo qui?', translation: 'Czy mogę tu zapalić?' },
            { phrase: 'Torno subito.', translation: 'Zaraz wracam.' }
        ]
    },
    emergency: {
        title: 'Emergenza',
        phrases: [
            { phrase: 'Aiuto!', translation: 'Pomocy!' },
            { phrase: 'Chiami un\'ambulanza!', translation: 'Wezwij karetkę!' },
            { phrase: 'Chiami la polizia!', translation: 'Wezwij policję!' },
            { phrase: 'Chiami i vigili del fuoco!', translation: 'Wezwij straż pożarną!' },
            { phrase: 'Qual è il numero di emergenza?', translation: 'Jaki jest numer alarmowy?' },
            { phrase: 'Al fuoco!', translation: 'Pali się!' },
            { phrase: 'C\'è stato un incidente.', translation: 'Wydarzył się wypadek.' },
            { phrase: 'Ho bisogno di un medico.', translation: 'Potrzebuję lekarza.' },
            { phrase: 'C\'è un ospedale qui vicino?', translation: 'Czy w pobliżu jest szpital?' },
            { phrase: 'Non mi sento bene.', translation: 'Nie czuję się dobrze.' },
            { phrase: 'Ho un dolore qui.', translation: 'Boli mnie tutaj.' },
            { phrase: 'Non riesco a respirare.', translation: 'Nie mogę oddychać.' },
            { phrase: 'Mi hanno rubato la borsa.', translation: 'Ktoś ukradł moją torbę.' },
            { phrase: 'Ho perso il portafoglio.', translation: 'Zgubiłem/am portfel.' },
            { phrase: 'Ho perso il passaporto.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Mi sono perso/a.', translation: 'Zgubiłem/am się.' },
            { phrase: 'Mio/a figlio/a è scomparso/a.', translation: 'Moje dziecko zaginęło.' },
            { phrase: 'Mi lasci in pace!', translation: 'Zostaw mnie w spokoju!' },
            { phrase: 'Attenzione!', translation: 'Uważaj!' },
            { phrase: 'Presto, per favore!', translation: 'Proszę, pospiesz się!' },
            { phrase: 'Ho bisogno di aiuto.', translation: 'Potrzebuję pomocy.' },
            { phrase: 'C\'è un medico qui?', translation: 'Czy jest tu jakiś lekarz?' },
            { phrase: 'Credo di essermi rotto/a una gamba.', translation: 'Chyba złamałem/am nogę.' },
            { phrase: 'Sono allergico/a alla penicillina.', translation: 'Jestem uczulony/a na penicylinę.' },
            { phrase: 'Dov\'è la farmacia più vicina?', translation: 'Gdzie jest najbliższa apteka?' },
            { phrase: 'Devo andare all\'ambasciata.', translation: 'Muszę iść do ambasady.' }
        ]
    },
    hotel: {
        title: 'Hotel',
        phrases: [
            { phrase: 'Ho una prenotazione.', translation: 'Mam rezerwację.' },
            { phrase: 'Posso fare il check-in, per favore?', translation: 'Czy mogę się zameldować?' },
            { phrase: 'A che ora è il check-out?', translation: 'O której godzinie jest wymeldowanie?' },
            { phrase: 'Vorrei fare il check-out.', translation: 'Chciałbym/Chciałabym się wymeldować.' },
            { phrase: 'La camera ha il Wi-Fi?', translation: 'Czy w pokoju jest Wi-Fi?' },
            { phrase: 'Qual è la password del Wi-Fi?', translation: 'Jakie jest hasło do Wi-Fi?' },
            { phrase: 'La mia chiave elettronica non funziona.', translation: 'Moja karta-klucz nie działa.' },
            { phrase: 'L\'aria condizionata non funziona.', translation: 'Klimatyzacja nie działa.' },
            { phrase: 'Non c\'è acqua calda.', translation: 'Nie ma ciepłej wody.' },
            { phrase: 'La camera è troppo rumorosa.', translation: 'Pokój jest zbyt głośny.' },
            { phrase: 'Posso avere una camera con vista?', translation: 'Czy mogę prosić o pokój z widokiem?' },
            { phrase: 'Posso avere un asciugamano in più?', translation: 'Czy mogę prosić o dodatkowy ręcznik?' },
            { phrase: 'Una sveglia alle 7, per favore.', translation: 'Poproszę o budzenie o 7 rano.' },
            { phrase: 'Posso avere la colazione in camera?', translation: 'Czy mogę prosić o śniadanie do pokoju?' },
            { phrase: 'A che ora viene servita la colazione?', translation: 'O której godzinie podawane jest śniadanie?' },
            { phrase: 'Può chiamarmi un taxi?', translation: 'Czy może pan/pani wezwać dla mnie taksówkę?' },
            { phrase: 'Posso pagare con la carta di credito?', translation: 'Czy mogę zapłacić kartą kredytową?' },
            { phrase: 'Posso lasciare qui i miei bagagli?', translation: 'Czy mogę zostawić tutaj bagaż?' },
            { phrase: 'Dov\'è il ristorante/la palestra?', translation: 'Gdzie jest restauracja/siłownia?' },
            { phrase: 'C\'è una cassaforte in camera?', translation: 'Czy w pokoju jest sejf?' },
            { phrase: 'Ho perso la chiave della camera.', translation: 'Zgubiłem/am klucz do pokoju.' },
            { phrase: 'L\'hotel ha una piscina?', translation: 'Czy hotel ma basen?' }
        ]
    },
    meteo: {
        title: 'Meteo',
        phrases: [
            { phrase: 'Che tempo fa oggi?', translation: 'Jaka jest dzisiaj pogoda?' },
            { phrase: 'Quali sono le previsioni del tempo?', translation: 'Jaka jest prognoza pogody?' },
            { phrase: 'C\'è il sole.', translation: 'Jest słonecznie.' },
            { phrase: 'Piove.', translation: 'Pada deszcz.' },
            { phrase: 'È nuvoloso.', translation: 'Jest pochmurno.' },
            { phrase: 'C\'è vento.', translation: 'Jest wietrznie.' },
            { phrase: 'Fa freddo.', translation: 'Jest zimno.' },
            { phrase: 'Fa caldo.', translation: 'Jest gorąco.' },
            { phrase: 'Che temperatura c\'è?', translation: 'Jaka jest temperatura?' },
            { phrase: 'Ci sono 20 gradi Celsius.', translation: 'Jest 20 stopni Celsjusza.' },
            { phrase: 'Nevica.', translation: 'Pada śnieg.' },
            { phrase: 'C\'è nebbia.', translation: 'Jest mgliście.' },
            { phrase: 'C\'è un temporale.', translation: 'Jest burza.' },
            { phrase: 'Pioverà domani?', translation: 'Czy jutro będzie padać?' },
            { phrase: 'È una bella giornata.', translation: 'To piękny dzień.' },
            { phrase: 'Il sole splende.', translation: 'Słońce świeci.' },
            { phrase: 'Si gela.', translation: 'Jest mroźno.' },
            { phrase: 'Ho bisogno di un ombrello.', translation: 'Potrzebuję parasola.' },
            { phrase: 'È umido.', translation: 'Jest wilgotno.' },
            { phrase: 'Il tempo sta cambiando.', translation: 'Pogoda się zmienia.' },
            { phrase: 'Sta facendo buio.', translation: 'Robi się ciemno.' }
        ]
    }
  },
};
