export interface IrregularVerbQuestion {
  id: number;
  verb: string; // Base form
  form2: string; // Passé composé (e.g., 'j'ai fait')
  form3: string; // Participe passé
  translationOptions: string[];
  correctTranslation: string;
}

// Note: 'form2' represents a common past tense example (Passé Composé with 'je'/'j'').
export const questions: IrregularVerbQuestion[] = [
  { id: 1, verb: 'être', form2: 'j\'ai été', form3: 'été', translationOptions: ['być', 'mieć', 'robić'], correctTranslation: 'być' },
  { id: 2, verb: 'avoir', form2: 'j\'ai eu', form3: 'eu', translationOptions: ['dawać', 'brać', 'mieć'], correctTranslation: 'mieć' },
  { id: 3, verb: 'aller', form2: 'je suis allé(e)', form3: 'allé', translationOptions: ['iść, jechać', 'przychodzić', 'biec'], correctTranslation: 'iść, jechać' },
  { id: 4, verb: 'faire', form2: 'j\'ai fait', form3: 'fait', translationOptions: ['robić', 'mówić', 'widzieć'], correctTranslation: 'robić' },
  { id: 5, verb: 'dire', form2: 'j\'ai dit', form3: 'dit', translationOptions: ['słuchać', 'pisać', 'mówić'], correctTranslation: 'mówić' },
  { id: 6, verb: 'pouvoir', form2: 'j\'ai pu', form3: 'pu', translationOptions: ['chcieć', 'móc', 'musieć'], correctTranslation: 'móc' },
  { id: 7, verb: 'prendre', form2: 'j\'ai pris', form3: 'pris', translationOptions: ['dawać', 'brać', 'przynosić'], correctTranslation: 'brać' },
  { id: 8, verb: 'venir', form2: 'je suis venu(e)', form3: 'venu', translationOptions: ['przychodzić', 'wychodzić', 'zostawać'], correctTranslation: 'przychodzić' },
  { id: 9, verb: 'voir', form2: 'j\'ai vu', form3: 'vu', translationOptions: ['słyszeć', 'patrzeć', 'widzieć'], correctTranslation: 'widzieć' },
  { id: 10, verb: 'savoir', form2: 'j\'ai su', form3: 'su', translationOptions: ['myśleć', 'wiedzieć', 'ignorować'], correctTranslation: 'wiedzieć' },
  { id: 11, verb: 'vouloir', form2: 'j\'ai voulu', form3: 'voulu', translationOptions: ['potrzebować', 'chcieć', 'lubić'], correctTranslation: 'chcieć' },
  { id: 12, verb: 'mettre', form2: 'j\'ai mis', form3: 'mis', translationOptions: ['kłaść, wkładać', 'wyjmować', 'przesuwać'], correctTranslation: 'kłaść, wkładać' },
  { id: 13, verb: 'donner', form2: 'j\'ai donné', form3: 'donné', translationOptions: ['brać', 'dawać', 'otrzymywać'], correctTranslation: 'dawać' },
  { id: 14, verb: 'tenir', form2: 'j\'ai tenu', form3: 'tenu', translationOptions: ['trzymać', 'puszczać', 'upuszczać'], correctTranslation: 'trzymać' },
  { id: 15, verb: 'parler', form2: 'j\'ai parlé', form3: 'parlé', translationOptions: ['mówić', 'milczeć', 'słuchać'], correctTranslation: 'mówić' },
  { id: 16, verb: 'trouver', form2: 'j\'ai trouvé', form3: 'trouvé', translationOptions: ['znaleźć', 'zgubić', 'szukać'], correctTranslation: 'znaleźć' },
  { id: 17, verb: 'rendre', form2: 'j\'ai rendu', form3: 'rendu', translationOptions: ['oddawać', 'pożyczać', 'brać'], correctTranslation: 'oddawać' },
  { id: 18, verb: 'partir', form2: 'je suis parti(e)', form3: 'parti', translationOptions: ['wyjeżdżać', 'przyjeżdżać', 'zostawać'], correctTranslation: 'wyjeżdżać' },
  { id: 19, verb: 'sortir', form2: 'je suis sorti(e)', form3: 'sorti', translationOptions: ['wychodzić', 'wchodzić', 'zostawać'], correctTranslation: 'wychodzić' },
  { id: 20, verb: 'arriver', form2: 'je suis arrivé(e)', form3: 'arrivé', translationOptions: ['wyjeżdżać', 'przybywać', 'odjeżdżać'], correctTranslation: 'przybywać' },
  { id: 21, verb: 'entrer', form2: 'je suis entré(e)', form3: 'entré', translationOptions: ['wchodzić', 'wychodzić', 'czekać'], correctTranslation: 'wchodzić' },
  { id: 22, verb: 'rester', form2: 'je suis resté(e)', form3: 'resté', translationOptions: ['odchodzić', 'zostawać', 'wracać'], correctTranslation: 'zostawać' },
  { id: 23, verb: 'tomber', form2: 'je suis tombé(e)', form3: 'tombé', translationOptions: ['upaść', 'wstać', 'skakać'], correctTranslation: 'upaść' },
  { id: 24, verb: 'devenir', form2: 'je suis devenu(e)', form3: 'devenu', translationOptions: ['być', 'stawać się', 'pozostawać'], correctTranslation: 'stawać się' },
  { id: 25, verb: 'revenir', form2: 'je suis revenu(e)', form3: 'revenu', translationOptions: ['wrócić', 'wyjechać', 'odejść'], correctTranslation: 'wrócić' },
  { id: 26, verb: 'croire', form2: 'j\'ai cru', form3: 'cru', translationOptions: ['wątpić', 'wierzyć', 'wiedzieć'], correctTranslation: 'wierzyć' },
  { id: 27, verb: 'penser', form2: 'j\'ai pensé', form3: 'pensé', translationOptions: ['czuć', 'wiedzieć', 'myśleć'], correctTranslation: 'myśleć' },
  { id: 28, verb: 'passer', form2: 'j\'ai passé', form3: 'passé', translationOptions: ['spędzać, przechodzić', 'zatrzymać się', 'zostawać'], correctTranslation: 'spędzać, przechodzić' },
  { id: 29, verb: 'laisser', form2: 'j\'ai laissé', form3: 'laissé', translationOptions: ['pozwalać, zostawiać', 'brać', 'zabraniać'], correctTranslation: 'pozwalać, zostawiać' },
  { id: 30, verb: 'sembler', form2: 'j\'ai semblé', form3: 'semblé', translationOptions: ['być pewnym', 'wydawać się', 'wiedzieć'], correctTranslation: 'wydawać się' },
  { id: 31, verb: 'porter', form2: 'j\'ai porté', form3: 'porté', translationOptions: ['nosić', 'zdejmować', 'przymierzać'], correctTranslation: 'nosić' },
  { id: 32, verb: 'suivre', form2: 'j\'ai suivi', form3: 'suivi', translationOptions: ['podążać', 'prowadzić', 'zatrzymywać się'], correctTranslation: 'podążać' },
  { id: 33, verb: 'connaître', form2: 'j\'ai connu', form3: 'connu', translationOptions: ['znać', 'uczyć się', 'zapominać'], correctTranslation: 'znać' },
  { id: 34, verb: 'vivre', form2: 'j\'ai vécu', form3: 'vécu', translationOptions: ['umierać', 'żyć', 'przeżyć'], correctTranslation: 'żyć' },
  { id: 35, verb: 'sentir', form2: 'j\'ai senti', form3: 'senti', translationOptions: ['dotykać', 'patrzeć', 'czuć'], correctTranslation: 'czuć' },
  { id: 36, verb: 'écouter', form2: 'j\'ai écouté', form3: 'écouté', translationOptions: ['mówić', 'słuchać', 'ignorować'], correctTranslation: 'słuchać' },
  { id: 37, verb: 'entendre', form2: 'j\'ai entendu', form3: 'entendu', translationOptions: ['słyszeć', 'widzieć', 'mówić'], correctTranslation: 'słyszeć' },
  { id: 38, verb: 'perdre', form2: 'j\'ai perdu', form3: 'perdu', translationOptions: ['znajdować', 'tracić', 'wygrywać'], correctTranslation: 'tracić' },
  { id: 39, verb: 'ouvrir', form2: 'j\'ai ouvert', form3: 'ouvert', translationOptions: ['zamykać', 'otwierać', 'pukać'], correctTranslation: 'otwierać' },
  { id: 40, verb: 'fermer', form2: 'j\'ai fermé', form3: 'fermé', translationOptions: ['otwierać', 'zamykać', 'łamać'], correctTranslation: 'zamykać' },
  { id: 41, verb: 'apprendre', form2: 'j\'ai appris', form3: 'appris', translationOptions: ['uczyć się', 'uczyć kogoś', 'zapominać'], correctTranslation: 'uczyć się' },
  { id: 42, verb: 'comprendre', form2: 'j\'ai compris', form3: 'compris', translationOptions: ['rozumieć', 'mylić', 'ignorować'], correctTranslation: 'rozumieć' },
  { id: 43, verb: 'écrire', form2: 'j\'ai écrit', form3: 'écrit', translationOptions: ['czytać', 'pisać', 'rysować'], correctTranslation: 'pisać' },
  { id: 44, verb: 'lire', form2: 'j\'ai lu', form3: 'lu', translationOptions: ['pisać', 'słuchać', 'czytać'], correctTranslation: 'czytać' },
  { id: 45, verb: 'boire', form2: 'j\'ai bu', form3: 'bu', translationOptions: ['jeść', 'pić', 'spać'], correctTranslation: 'pić' },
  { id: 46, verb: 'manger', form2: 'j\'ai mangé', form3: 'mangé', translationOptions: ['pić', 'głodować', 'jeść'], correctTranslation: 'jeść' },
  { id: 47, verb: 'recevoir', form2: 'j\'ai reçu', form3: 'reçu', translationOptions: ['dawać', 'wysyłać', 'otrzymywać'], correctTranslation: 'otrzymywać' },
  { id: 48, verb: 'répondre', form2: 'j\'ai répondu', form3: 'répondu', translationOptions: ['pytać', 'odpowiadać', 'milczeć'], correctTranslation: 'odpowiadać' },
  { id: 49, verb: 'attendre', form2: 'j\'ai attendu', form3: 'attendu', translationOptions: ['iść', 'odchodzić', 'czekać'], correctTranslation: 'czekać' },
  { id: 50, verb: 'chercher', form2: 'j\'ai cherché', form3: 'cherché', translationOptions: ['znaleźć', 'gubić', 'szukać'], correctTranslation: 'szukać' },
  { id: 51, verb: 'exister', form2: 'j\'ai existé', form3: 'existé', translationOptions: ['znikać', 'istnieć', 'tworzyć'], correctTranslation: 'istnieć' },
  { id: 52, verb: 'jouer', form2: 'j\'ai joué', form3: 'joué', translationOptions: ['pracować', 'uczyć się', 'grać'], correctTranslation: 'grać' },
  { id: 53, verb: 'marcher', form2: 'j\'ai marché', form3: 'marché', translationOptions: ['biegać', 'stać', 'chodzić'], correctTranslation: 'chodzić' },
  { id: 54, verb: 'travailler', form2: 'j\'ai travaillé', form3: 'travaillé', translationOptions: ['odpoczywać', 'pracować', 'bawić się'], correctTranslation: 'pracować' },
  { id: 55, verb: 'appeler', form2: 'j\'ai appelé', form3: 'appelé', translationOptions: ['odbierać', 'dzwonić', 'pisać'], correctTranslation: 'dzwonić' },
  { id: 56, verb: 'changer', form2: 'j\'ai changé', form3: 'changé', translationOptions: 'zmieniać', correctTranslation: 'zmieniać' },
  { id: 57, verb: 'utiliser', form2: 'j\'ai utilisé', form3: 'utilisé', translationOptions: ['używać', 'marnować', 'naprawiać'], correctTranslation: 'używać' },
  { id: 58, verb: 'montrer', form2: 'j\'ai montré', form3: 'montré', translationOptions: ['ukrywać', 'pokazywać', 'patrzeć'], correctTranslation: 'pokazywać' },
  { id: 59, verb: 'aimer', form2: 'j\'ai aimé', form3: 'aimé', translationOptions: ['nienawidzić', 'lubić, kochać', 'ignorować'], correctTranslation: 'lubić, kochać' },
  { id: 60, verb: 'détester', form2: 'j\'ai détesté', form3: 'détesté', translationOptions: ['uwielbiać', 'nienawidzić', 'tolerować'], correctTranslation: 'nienawidzić' },
  { id: 61, verb: 'naître', form2: 'je suis né(e)', form3: 'né', translationOptions: ['umierać', 'żyć', 'urodzić się'], correctTranslation: 'urodzić się' },
  { id: 62, verb: 'mourir', form2: 'je suis mort(e)', form3: 'mort', translationOptions: ['żyć', 'urodzić się', 'umrzeć'], correctTranslation: 'umrzeć' },
  { id: 63, verb: 'descendre', form2: 'je suis descendu(e)', form3: 'descendu', translationOptions: ['wchodzić', 'schodzić', 'wspinać się'], correctTranslation: 'schodzić' },
  { id: 64, verb: 'monter', form2: 'je suis monté(e)', form3: 'monté', translationOptions: ['schodzić', 'wchodzić', 'spadać'], correctTranslation: 'wchodzić' },
  { id: 65, verb: 'retourner', form2: 'je suis retourné(e)', form3: 'retourné', translationOptions: ['odchodzić', 'wracać', 'zostawać'], correctTranslation: 'wracać' },
  { id: 66, verb: 'rentrer', form2: 'je suis rentré(e)', form3: 'rentré', translationOptions: ['wyjść', 'wrócić (do domu)', 'podróżować'], correctTranslation: 'wrócić (do domu)' },
  { id: 67, verb: 'reconnaître', form2: 'j\'ai reconnu', form3: 'reconnu', translationOptions: ['zapominać', 'rozpoznać', 'ignorować'], correctTranslation: 'rozpoznać' },
  { id: 68, verb: 'choisir', form2: 'j\'ai choisi', form3: 'choisi', translationOptions: ['odrzucać', 'wybierać', 'wahać się'], correctTranslation: 'wybierać' },
  { id: 69, verb: 'dormir', form2: 'j\'ai dormi', form3: 'dormi', translationOptions: ['budzić się', 'spać', 'odpoczywać'], correctTranslation: 'spać' },
  { id: 70, verb: 'courir', form2: 'j\'ai couru', form3: 'couru', translationOptions: ['chodzić', 'stać', 'biec'], correctTranslation: 'biec' },
  { id: 71, verb: 'finir', form2: 'j\'ai fini', form3: 'fini', translationOptions: ['zaczynać', 'kończyć', 'kontynuować'], correctTranslation: 'kończyć' },
  { id: 72, verb: 'gagner', form2: 'j\'ai gagné', form3: 'gagné', translationOptions: ['przegrywać', 'wygrywać', 'remisować'], correctTranslation: 'wygrywać' },
  { id: 73, verb: 'permettre', form2: 'j\'ai permis', form3: 'permis', translationOptions: ['zabraniać', 'nakazywać', 'pozwalać'], correctTranslation: 'pozwalać' },
  { id: 74, verb: 'refuser', form2: 'j\'ai refusé', form3: 'refusé', translationOptions: ['zgadzać się', 'odmawiać', 'prosić'], correctTranslation: 'odmawiać' },
  { id: 75, verb: 'accepter', form2: 'j\'ai accepté', form3: 'accepté', translationOptions: ['odrzucać', 'akceptować', 'negocjować'], correctTranslation: 'akceptować' },
  { id: 76, verb: 'décider', form2: 'j\'ai décidé', form3: 'décidé', translationOptions: ['wahać się', 'zdecydować', 'myśleć'], correctTranslation: 'zdecydować' },
  { id: 77, verb: 'oublier', form2: 'j\'ai oublié', form3: 'oublié', translationOptions: ['pamiętać', 'zapomnieć', 'uczyć się'], correctTranslation: 'zapomnieć' },
  { id: 78, verb: 'préparer', form2: 'j\'ai préparé', form3: 'préparé', translationOptions: ['niszczyć', 'przygotować', 'kończyć'], correctTranslation: 'przygotować' },
  { id: 79, verb: 'payer', form2: 'j\'ai payé', form3: 'payé', translationOptions: ['otrzymywać', 'płacić', 'oszczędzać'], correctTranslation: 'płacić' },
  { id: 80, verb: 'acheter', form2: 'j\'ai acheté', form3: 'acheté', translationOptions: ['sprzedawać', 'kupować', 'wymieniać'], correctTranslation: 'kupować' },
  { id: 81, verb: 'vendre', form2: 'j\'ai vendu', form3: 'vendu', translationOptions: ['kupować', 'sprzedawać', 'pożyczać'], correctTranslation: 'sprzedawać' },
  { id: 82, verb: 'couper', form2: 'j\'ai coupé', form3: 'coupé', translationOptions: ['kleić', 'ciąć', 'łączyć'], correctTranslation: 'ciąć' },
  { id: 83, verb: 'tirer', form2: 'j\'ai tiré', form3: 'tiré', translationOptions: ['pchać', 'ciągnąć', 'nosić'], correctTranslation: 'ciągnąć' },
  { id: 84, verb: 'quitter', form2: 'j\'ai quitté', form3: 'quitté', translationOptions: ['zostawać', 'przybywać', 'opuszczać'], correctTranslation: 'opuszczać' },
  { id: 85, verb: 'rire', form2: 'j\'ai ri', form3: 'ri', translationOptions: ['płakać', 'śmiać się', 'krzyczeć'], correctTranslation: 'śmiać się' },
  { id: 86, verb: 'pleurer', form2: 'j\'ai pleuré', form3: 'pleuré', translationOptions: ['śmiać się', 'płakać', 'cieszyć się'], correctTranslation: 'płakać' },
  { id: 87, verb: 'servir', form2: 'j\'ai servi', form3: 'servi', translationOptions: ['brać', 'zamawiać', 'służyć/podawać'], correctTranslation: 'służyć/podawać' },
  { id: 88, verb: 'offrir', form2: 'j\'ai offert', form3: 'offert', translationOptions: ['odbierać', 'oferować/dawać', 'prosić'], correctTranslation: 'oferować/dawać' },
  { id: 89, verb: 'couvrir', form2: 'j\'ai couvert', form3: 'couvert', translationOptions: ['odkrywać', 'przykrywać', 'pokazywać'], correctTranslation: 'przykrywać' },
  { id: 90, verb: 'fuir', form2: 'j\'ai fui', form3: 'fui', translationOptions: ['ścigać', 'zostawać', 'uciekać'], correctTranslation: 'uciekać' },
  { id: 91, verb: 'joindre', form2: 'j\'ai joint', form3: 'joint', translationOptions: ['rozdzielać', 'dołączać', 'opuszczać'], correctTranslation: 'dołączać' },
  { id: 92, verb: 'craindre', form2: 'j\'ai craint', form3: 'craint', translationOptions: ['odważyć się', 'obawiać się', 'ignorować'], correctTranslation: 'obawiać się' },
  { id: 93, verb: 'peindre', form2: 'j\'ai peint', form3: 'peint', translationOptions: ['rysować', 'malować', 'wymazywać'], correctTranslation: 'malować' },
  { id: 94, verb: 'vaincre', form2: 'j\'ai vaincu', form3: 'vaincu', translationOptions: ['poddawać się', 'zwyciężać', 'walczyć'], correctTranslation: 'zwyciężać' },
  { id: 95, verb: 'résoudre', form2: 'j\'ai résolu', form3: 'résolu', translationOptions: ['tworzyć problem', 'rozwiązać', 'unikać'], correctTranslation: 'rozwiązać' },
  { id: 96, verb: 'conduire', form2: 'j\'ai conduit', form3: 'conduit', translationOptions: ['chodzić pieszo', 'prowadzić (pojazd)', 'być pasażerem'], correctTranslation: 'prowadzić (pojazd)' },
  { id: 97, verb: 'détester', form2: 'j\'ai détesté', form3: 'détesté', translationOptions: ['uwielbiać', 'tolerować', 'nienawidzić'], correctTranslation: 'nienawidzić' },
  { id: 98, verb: 'choisir', form2: 'j\'ai choisi', form3: 'choisi', translationOptions: ['wybierać', 'odrzucać', 'ignorować'], correctTranslation: 'wybierać' },
  { id: 99, verb: 'gagner', form2: 'j\'ai gagné', form3: 'gagné', translationOptions: ['przegrywać', 'wygrywać', 'remisować'], correctTranslation: 'wygrywać' },
  { id: 100, verb: 'refuser', form2: 'j\'ai refusé', form3: 'refusé', translationOptions: ['zgadzać się', 'odmawiać', 'prosić'], correctTranslation: 'odmawiać' }
];
