
export interface Question {
  id: number;
  language: 'Italian';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'Italian', word: 'Acqua in bocca', options: ['Woda w ustach', 'Trzymać sekret', 'Być spragnionym', 'Mówić niewyraźnie'], correctAnswer: 'Trzymać sekret' },
  { id: 2, language: 'Italian', word: 'Avere il pollice verde', options: ['Mieć zielony kciuk', 'Mieć rękę do roślin', 'Być brudnym od ziemi', 'Malować na zielono'], correctAnswer: 'Mieć rękę do roślin' },
  { id: 3, language: 'Italian', word: 'Avere le mani bucate', options: ['Mieć dziurawe ręce', 'Szybko wydawać pieniądze', 'Być niezdarnym', 'Pracować fizycznie'], correctAnswer: 'Szybko wydawać pieniądze' },
  { id: 4, language: 'Italian', word: 'Avere un diavolo per capello', options: ['Mieć diabła za włosy', 'Być bardzo złym lub zdenerwowanym', 'Mieć złą fryzurę', 'Wierzyć w przesądy'], correctAnswer: 'Być bardzo złym lub zdenerwowanym' },
  { id: 5, language: 'Italian', word: 'Battere il ferro finché è caldo', options: ['Kuć żelazo póki gorące', 'Działać w odpowiednim czasie', 'Pracować ciężko', 'Być kowalem'], correctAnswer: 'Działać w odpowiednim czasie' },
  { id: 6, language: 'Italian', word: 'Buttare l’acqua sporca', options: ['Wylać brudną wodę', 'Pozbyć się czegoś niepotrzebnego', 'Robić porządki', 'Marnować wodę'], correctAnswer: 'Pozbyć się czegoś niepotrzebnego' },
  { id: 7, language: 'Italian', word: 'Cadere dalle nuvole', options: ['Spadać z chmur', 'Być bardzo zaskoczonym', 'Śnić na jawie', 'Latać samolotem'], correctAnswer: 'Być bardzo zaskoczonym' },
  { id: 8, language: 'Italian', word: 'Cercare il pelo nell’uovo', options: ['Szukać włosa w jajku', 'Szukać dziury w całym', 'Być drobiazgowym', 'Gotować jajka'], correctAnswer: 'Szukać dziury w całym' },
  { id: 9, language: 'Italian', word: 'Chi dorme non piglia pesci', options: ['Kto śpi, nie łapie ryb', 'Bez pracy nie ma kołaczy', 'Być leniwym', 'Iść na ryby'], correctAnswer: 'Kto śpi, nie łapie ryb' },
  { id: 10, language: 'Italian', word: 'Chi fa da sé fa per tre', options: ['Kto robi sam, robi za trzech', 'Umiesz liczyć, licz na siebie', 'Pracować w zespole', 'Być egoistą'], correctAnswer: 'Umiesz liczyć, licz na siebie' },
  { id: 11, language: 'Italian', word: 'Chi la dura la vince', options: ['Kto wytrwa, ten wygrywa', 'Wytrwały osiąga cel', 'Być cierpliwym', 'Brać udział w zawodach'], correctAnswer: 'Wytrwały osiąga cel' },
  { id: 12, language: 'Italian', word: 'Chi va piano va sano e va lontano', options: ['Kto idzie powoli, idzie zdrowo i daleko', 'Śpiesz się powoli', 'Być ostrożnym', 'Chodzić na spacery'], correctAnswer: 'Śpiesz się powoli' },
  { id: 13, language: 'Italian', word: 'Cogliere l’attimo', options: ['Łapać chwilę', 'Chwytać dzień', 'Korzystać z okazji', 'Być impulsywnym'], correctAnswer: 'Chwytać chwilę' },
  { id: 14, language: 'Italian', word: 'Con il cuore in mano', options: ['Z sercem na dłoni', 'Szczerze, otwarcie', 'Być zakochanym', 'Mieć problemy z sercem'], correctAnswer: 'Szczerze, otwarcie' },
  { id: 15, language: 'Italian', word: 'Dare del filo da torcere', options: ['Dać nić do skręcania', 'Sprawiać trudności', 'Szyć', 'Pomagać'], correctAnswer: 'Sprawiać trudności' },
  { id: 16, language: 'Italian', word: 'Dare una mano', options: ['Podać rękę', 'Pomóc komuś', 'Uderzyć kogoś', 'Przywitać się'], correctAnswer: 'Pomóc komuś' },
  { id: 17, language: 'Italian', word: 'Essere al verde', options: ['Być na zielonym', 'Być spłukanym', 'Odpoczywać w parku', 'Być ekologiem'], correctAnswer: 'Być spłukanym' },
  { id: 18, language: 'Italian', word: 'Essere in gamba', options: ['Być w nodze', 'Być zdolnym, sprawnym', 'Być wysportowanym', 'Szybko biegać'], correctAnswer: 'Być zdolnym, sprawnym' },
  { id: 19, language: 'Italian', word: 'Essere in alto mare', options: ['Być na pełnym morzu', 'Być daleko od celu', 'Żeglować', 'Mieć problemy'], correctAnswer: 'Być daleko od celu' },
  { id: 20, language: 'Italian', word: 'Essere in cattive acque', options: ['Być w brudnej wodzie', 'Być w tarapatach', 'Pływać w rzece', 'Mieć długi'], correctAnswer: 'Być w tarapatach' },
  { id: 21, language: 'Italian', word: 'Essere in crisi', options: ['Być w kryzysie', 'Mieć problemy', 'Panikować', 'Być smutnym'], correctAnswer: 'Mieć problemy' },
  { id: 22, language: 'Italian', word: 'Fare buon viso a cattiva sorte', options: ['Robić dobrą minę do złej gry', 'Przyjąć coś ze spokojem', 'Uśmiechać się na siłę', 'Ukrywać smutek'], correctAnswer: 'Robić dobrą minę do złej gry' },
  { id: 23, language: 'Italian', word: 'Fare orecchie da mercante', options: ['Robić uszy kupca', 'Udawać, że się nie słyszy', 'Targować się', 'Być głuchym'], correctAnswer: 'Udawać, że się nie słyszy' },
  { id: 24, language: 'Italian', word: 'Fare la gatta morta', options: ['Robić martwego kota', 'Udawać niewinną', 'Być leniwym', 'Spać'], correctAnswer: 'Udawać niewinną' },
  { id: 25, language: 'Italian', word: 'Fare la figura del cioccolataio', options: ['Robić figurę czekoladnika', 'Wyjść na głupka', 'Sprzedawać czekoladę', 'Być eleganckim'], correctAnswer: 'Wyjść na głupka' },
  { id: 26, language: 'Italian', word: 'Fare il passo più lungo della gamba', options: ['Zrobić krok dłuższy niż noga', 'Przesadzić z ambicjami', 'Porywać się z motyką na słońce', 'Ćwiczyć gimnastykę'], correctAnswer: 'Porywać się z motyką na słońce' },
  { id: 27, language: 'Italian', word: 'Fare spallucce', options: ['Robić ramiona', 'Wzruszyć ramionami', 'Pokazać siłę', 'Ćwiczyć'], correctAnswer: 'Wzruszyć ramionami' },
  { id: 28, language: 'Italian', word: 'Finire in bellezza', options: ['Skończyć w piękności', 'Skończyć w dobrym stylu', 'Wygrać konkurs piękności', 'Udać się na emeryturę'], correctAnswer: 'Skończyć w dobrym stylu' },
  { id: 29, language: 'Italian', word: 'Gettare la spugna', options: ['Rzucić gąbkę', 'Poddawać się', 'Myć się', 'Sprzątać'], correctAnswer: 'Poddawać się' },
  { id: 30, language: 'Italian', word: 'Giocare con il fuoco', options: ['Bawić się ogniem', 'Bawić się niebezpiecznie', 'Być strażakiem', 'Rozpalać ognisko'], correctAnswer: 'Bawić się niebezpiecznie' },
  { id: 31, language: 'Italian', word: 'Guardare in faccia la realtà', options: ['Patrzeć w twarz rzeczywistości', 'Stawić czoła rzeczywistości', 'Być realistą', 'Oglądać wiadomości'], correctAnswer: 'Stawić czoła rzeczywistości' },
  { id: 32, language: 'Italian', word: 'Avere la testa fra le nuvole', options: ['Mieć głowę w chmurach', 'Marzyć, nie skupiać się', 'Być roztargnionym', 'Latać samolotem'], correctAnswer: 'Marzyć, nie skupiać się' },
  { id: 33, language: 'Italian', word: 'In bocca al lupo', options: ['W paszczy wilka', 'Powodzenia', 'Uważaj', 'Na zdrowie'], correctAnswer: 'Powodzenia' },
  { id: 34, language: 'Italian', word: 'L’abito non fa il monaco', options: ['Ubranie nie czyni mnicha', 'Nie oceniaj książki po okładce', 'Wygląd nie decyduje o wartości', 'Kupować ubrania'], correctAnswer: 'Wygląd nie decyduje o wartości' },
  { id: 35, language: 'Italian', word: 'La goccia che fa traboccare il vaso', options: ['Kropla, która przelewa wazę', 'Ostatnia kropla goryczy', 'Kropla, która przepełnia czarę', 'Pić wodę'], correctAnswer: 'Kropla, która przepełnia czarę' },
  { id: 36, language: 'Italian', word: 'Mettere i puntini sulle i', options: ['Stawiać kropki nad i', 'Wyjaśnić szczegóły', 'Być pedantycznym', 'Kończyć pisać'], correctAnswer: 'Wyjaśnić szczegóły' },
  { id: 37, language: 'Italian', word: 'Mettere il carro davanti ai buoi', options: ['Stawiać wóz przed wołami', 'Robić coś w złej kolejności', 'Pracować na farmie', 'Być niecierpliwym'], correctAnswer: 'Robić coś w złej kolejności' },
  { id: 38, language: 'Italian', word: 'Mettere la mano sul fuoco', options: ['Wkładać rękę w ogień', 'Być pewnym czegoś', 'Ręczyć za kogoś', 'Ryzykować'], correctAnswer: 'Być pewnym czegoś' },
  { id: 39, language: 'Italian', word: 'Mettere i bastoni tra le ruote', options: ['Wkładać kije między koła', 'Utrudniać komuś życie', 'Rzucać kłody pod nogi', 'Naprawiać rower'], correctAnswer: 'Rzucać kłody pod nogi' },
  { id: 40, language: 'Italian', word: 'Non avere peli sulla lingua', options: ['Nie mieć włosów na języku', 'Mówić bez ogródek', 'Być szczerym', 'Być niegrzecznym'], correctAnswer: 'Mówić bez ogródek' },
  { id: 41, language: 'Italian', word: 'Non tutte le ciambelle riescono col buco', options: ['Nie wszystkie pączki wychodzą z dziurką', 'Nie wszystko idzie idealnie', 'Piec pączki', 'Mieć pecha'], correctAnswer: 'Nie wszystko idzie idealnie' },
  { id: 42, language: 'Italian', word: 'Non vedere l’ora', options: ['Nie widzieć godziny', 'Nie móc się doczekać', 'Spóźniać się', 'Być podekscytowanym'], correctAnswer: 'Nie móc się doczekać' },
  { id: 43, language: 'Italian', word: 'Occhio per occhio', options: ['Oko za oko', 'Odwetu trzeba wymagać', 'Zemsta jest słodka', 'Prawo talionu'], correctAnswer: 'Oko za oko' },
  { id: 44, language: 'Italian', word: 'Pagare il fio', options: ['Zapłacić fio', 'Ponieść konsekwencje', 'Zapłacić karę', 'Być winnym'], correctAnswer: 'Ponieść konsekwencje' },
  { id: 45, language: 'Italian', word: 'Parlare a vanvera', options: ['Mówić na próżno', 'Mówić bez sensu', 'Gadać od rzeczy', 'Plotkować'], correctAnswer: 'Gadać od rzeczy' },
  { id: 46, language: 'Italian', word: 'Passare la notte in bianco', options: ['Spędzić białą noc', 'Nie spać całą noc', 'Imprezować do rana', 'Pracować w nocy'], correctAnswer: 'Nie spać całą noc' },
  { id: 47, language: 'Italian', word: 'Perdere la testa', options: ['Stracić głowę', 'Stracić kontrolę', 'Zakochać się', 'Zwariować'], correctAnswer: 'Stracić kontrolę' },
  { id: 48, language: 'Italian', word: 'Piantare in asso', options: ['Zasadzić asa', 'Porzucić kogoś w potrzebie', 'Zostawić kogoś na lodzie', 'Grać w karty'], correctAnswer: 'Zostawić kogoś na lodzie' },
  { id: 49, language: 'Italian', word: 'Piangere sul latte versato', options: ['Płakać nad rozlanym mlekiem', 'Rozpaczać nad czymś nieodwracalnym', 'Być niezdarnym', 'Sprzątać'], correctAnswer: 'Płakać nad rozlanym mlekiem' },
  { id: 50, language: 'Italian', word: 'Prendere due piccioni con una fava', options: ['Złapać dwa gołębie jedną fasolą', 'Upiec dwie pieczenie na jednym ogniu', 'Załatwić dwie sprawy naraz', 'Być sprytnym'], correctAnswer: 'Upiec dwie pieczenie na jednym ogniu' },
  { id: 51, language: 'Italian', word: 'Prendere in giro', options: ['Wziąć na przejażdżkę', 'Nabijać się z kogoś', 'Żartować', 'Oprowadzać kogoś'], correctAnswer: 'Nabijać się z kogoś' },
  { id: 52, language: 'Italian', word: 'Prendere il toro per le corna', options: ['Wziąć byka za rogi', 'Stawić czoła problemowi', 'Być odważnym', 'Iść na corridę'], correctAnswer: 'Wziąć byka za rogi' },
  { id: 53, language: 'Italian', word: 'Prendere per buono', options: ['Wziąć za dobre', 'Przyjąć za pewnik', 'Uwierzyć na słowo', 'Być naiwnym'], correctAnswer: 'Przyjąć za pewnik' },
  { id: 54, language: 'Italian', word: 'Restare a bocca aperta', options: ['Pozostać z otwartymi ustami', 'Być zdziwionym', 'Ziewać', 'Milczeć'], correctAnswer: 'Być zdziwionym' },
  { id: 55, language: 'Italian', word: 'Saltare di palo in frasca', options: ['Skakać z gałęzi na gałąź', 'Zmieniać temat nagle', 'Być niezdecydowanym', 'Chodzić po drzewach'], correctAnswer: 'Zmieniać temat nagle' },
  { id: 56, language: 'Italian', word: 'Sbattersene', options: ['Uderzać się', 'Ignorować coś', 'Mieć coś gdzieś', 'Być obojętnym'], correctAnswer: 'Ignorować coś' },
  { id: 57, language: 'Italian', word: 'Sparare a zero', options: ['Strzelać na zero', 'Krytykować ostro', 'Atakować bezlitośnie', 'Być agresywnym'], correctAnswer: 'Krytykować ostro' },
  { id: 58, language: 'Italian', word: 'Stare con le mani in mano', options: ['Stać z rękami w ręku', 'Nic nie robić', 'Być bezczynnym', 'Odpoczywać'], correctAnswer: 'Nic nie robić' },
  { id: 59, language: 'Italian', word: 'Stare sulle spine', options: ['Stać na kolcach', 'Być jak na szpilkach', 'Być zdenerwowanym', 'Czekać w napięciu'], correctAnswer: 'Być jak na szpilkach' },
  { id: 60, language: 'Italian', word: 'Svegliarsi col piede sbagliato', options: ['Obudzić się złą stopą', 'Wstać lewą nogą', 'Mieć zły dzień', 'Być w złym humorze'], correctAnswer: 'Wstać lewą nogą' },
  { id: 61, language: 'Italian', word: 'Tagliare la corda', options: ['Przeciąć linę', 'Uciec', 'Zmyć się', 'Zerwać znajomość'], correctAnswer: 'Uciec' },
  { id: 62, language: 'Italian', word: 'Tenere il broncio', options: ['Trzymać grymas', 'Dąsać się', 'Być obrażonym', 'Być smutnym'], correctAnswer: 'Być obrażonym' },
  { id: 63, language: 'Italian', word: 'Tenere il gioco', options: ['Trzymać grę', 'Kontrolować sytuację', 'Grać w grę', 'Oszukiwać'], correctAnswer: 'Kontrolować sytuację' },
  { id: 64, language: 'Italian', word: 'Tenere a mente', options: ['Trzymać w umyśle', 'Zapamiętać coś ważnego', 'Pamiętać', 'Notować'], correctAnswer: 'Zapamiętać coś ważnego' },
  { id: 65, language: 'Italian', word: 'Tirare acqua al proprio mulino', options: ['Ciągnąć wodę do swojego młyna', 'Działać na swoją korzyść', 'Być egoistą', 'Dbać o swoje interesy'], correctAnswer: 'Działać na swoją korzyść' },
  { id: 66, language: 'Italian', word: 'Tirare il pacco', options: ['Ciągnąć paczkę', 'Wystawić kogoś do wiatru', 'Zawieść kogoś', 'Nie dotrzymać obietnicy'], correctAnswer: 'Wystawić kogoś do wiatru' },
  { id: 67, language: 'Italian', word: 'Tirare su di morale', options: ['Podciągnąć morale', 'Pocieszać kogoś', 'Podnieść na duchu', 'Motywować'], correctAnswer: 'Podnieść na duchu' },
  { id: 68, language: 'Italian', word: 'Togliersi un peso', options: ['Zdjąć z siebie ciężar', 'Odetchnąć z ulgą', 'Poczuć ulgę', 'Rozwiązać problem'], correctAnswer: 'Odetchnąć z ulgą' },
  { id: 69, language: 'Italian', word: 'Trovarsi in mezzo al guado', options: ['Znaleźć się w środku brodu', 'Być w trudnej sytuacji', 'Być w połowie drogi', 'Nie wiedzieć co robić'], correctAnswer: 'Być w trudnej sytuacji' },
  { id: 70, language: 'Italian', word: 'Valere la pena', options: ['Być wartym kary', 'Być tego wartym', 'Opłacać się', 'Warto spróbować'], correctAnswer: 'Być tego wartym' },
  { id: 71, language: 'Italian', word: 'Volare alto', options: ['Latać wysoko', 'Mieć wysokie aspiracje', 'Być ambitnym', 'Marzyć'], correctAnswer: 'Mieć wysokie aspiracje' },
  { id: 72, language: 'Italian', word: 'Accontentarsi di poco', options: ['Zadowalać się małym', 'Być skromnym', 'Nie mieć dużych wymagań', 'Cieszyć się z małych rzeczy'], correctAnswer: 'Zadowalać się małym' },
  { id: 73, language: 'Italian', word: 'Dare il benservito', options: ['Dać dobre usługi', 'Zwolnić kogoś z pracy', 'Wyrzucić kogoś', 'Zakończyć współpracę'], correctAnswer: 'Zwolnić kogoś z pracy' },
  { id: 74, language: 'Italian', word: 'Essere un pezzo grosso', options: ['Być grubym kawałkiem', 'Być ważną osobą', 'Być kimś wpływowym', 'Szycha'], correctAnswer: 'Być ważną osobą' },
  { id: 75, language: 'Italian', word: 'Fare finta di niente', options: ['Udawać nic', 'Udawać, że nic się nie stało', 'Ignorować sytuację', 'Być obojętnym'], correctAnswer: 'Udawać, że nic się nie stało' },
  { id: 76, language: 'Italian', word: 'Fare il diavolo a quattro', options: ['Robić diabła na cztery', 'Robić dużo hałasu', 'Robić awanturę', 'Być wściekłym'], correctAnswer: 'Robić dużo hałasu' },
  { id: 77, language: 'Italian', word: 'Fare il filo a qualcuno', options: ['Robić komuś nić', 'Flirtować z kimś', 'Podrywać kogoś', 'Szyć dla kogoś'], correctAnswer: 'Flirtować z kimś' },
  { id: 78, language: 'Italian', word: 'Fare una brutta figura', options: ['Zrobić brzydką figurę', 'Wyjść źle w oczach innych', 'Skompromitować się', 'Zrobić złe wrażenie'], correctAnswer: 'Skompromitować się' },
  { id: 79, language: 'Italian', word: 'Essere sulla bocca di tutti', options: ['Być na ustach wszystkich', 'Być tematem rozmów', 'Być popularnym', 'Plotkować'], correctAnswer: 'Być na ustach wszystkich' },
  { id: 80, language: 'Italian', word: 'Essere tra l’incudine e il martello', options: ['Być między kowadłem a młotem', 'Być w trudnej sytuacji', 'Być pod presją', 'Nie mieć wyboru'], correctAnswer: 'Być między kowadłem a młotem' },
  { id: 81, language: 'Italian', word: 'Essere un libro aperto', options: ['Być otwartą księgą', 'Być przewidywalnym, szczerym', 'Nie mieć tajemnic', 'Dużo czytać'], correctAnswer: 'Być otwartą księgą' },
  { id: 82, language: 'Italian', word: 'Non avere la testa sulle spalle', options: ['Nie mieć głowy na ramionach', 'Nie myśleć rozsądnie', 'Być nieodpowiedzialnym', 'Być roztrzepanym'], correctAnswer: 'Nie myśleć rozsądnie' },
  { id: 83, language: 'Italian', word: 'Prendere una cantonata', options: ['Wziąć róg', 'Pomylić się całkowicie', 'Zaliczyć wpadkę', 'Skręcić w złą ulicę'], correctAnswer: 'Zaliczyć wpadkę' },
  { id: 84, language: 'Italian', word: 'Prendere la palla al balzo', options: ['Złapać piłkę w locie', 'Skorzystać z okazji', 'Być sprytnym', 'Szybko reagować'], correctAnswer: 'Skorzystać z okazji' },
  { id: 85, language: 'Italian', word: 'Restare di stucco', options: ['Zostać ze stiuku', 'Być zdumionym', 'Zaniemówić z wrażenia', 'Być w szoku'], correctAnswer: 'Być zdumionym' },
  { id: 86, language: 'Italian', word: 'Stare con il fiato sospeso', options: ['Stać z zawieszonym oddechem', 'Być w napięciu', 'Wstrzymać oddech', 'Czekać z niecierpliwością'], correctAnswer: 'Być w napięciu' },
  { id: 87, language: 'Italian', word: 'Stare sulle sue', options: ['Stać na swoich', 'Trzymać dystans', 'Być powściągliwym', 'Trzymać się swojego zdania'], correctAnswer: 'Trzymać dystans' },
  { id: 88, language: 'Italian', word: 'Tirare la corda', options: ['Ciągnąć linę', 'Przesadzić', 'Nadużywać cierpliwości', 'Ryzykować'], correctAnswer: 'Przesadzić' },
  { id: 89, language: 'Italian', word: 'Volerci pazienza', options: ['Chcieć cierpliwości', 'Wymagać cierpliwości', 'Trzeba być cierpliwym', 'Czekać'], correctAnswer: 'Wymagać cierpliwości' },
  { id: 90, language: 'Italian', word: 'Avere le spalle larghe', options: ['Mieć szerokie ramiona', 'Być odpornym na trudności', 'Być silnym', 'Mieć wsparcie'], correctAnswer: 'Być odpornym na trudności' },
  { id: 91, language: 'Italian', word: 'Dare buca', options: ['Dać dziurę', 'Nie przyjść na umówione spotkanie', 'Wystawić kogoś', 'Unikać kogoś'], correctAnswer: 'Wystawić kogoś' },
  { id: 92, language: 'Italian', word: 'Fare buona figura', options: ['Zrobić dobrą figurę', 'Wyjść dobrze w oczach innych', 'Zrobić dobre wrażenie', 'Być eleganckim'], correctAnswer: 'Zrobić dobre wrażenie' },
  { id: 93, language: 'Italian', word: 'Fare il punto della situazione', options: ['Zrobić punkt sytuacji', 'Podsumować sytuację', 'Zanalizować sytuację', 'Ocenić stan rzeczy'], correctAnswer: 'Podsumować sytuację' },
  { id: 94, language: 'Italian', word: 'Fare la morale', options: ['Robić morał', 'Pouczać', 'Moralizować', 'Krytykować'], correctAnswer: 'Pouczać' },
  { id: 95, language: 'Italian', word: 'Mettere il dito nella piaga', options: ['Włożyć palec w ranę', 'Uderzyć w czuły punkt', 'Rozdrapywać rany', 'Sprawiać ból'], correctAnswer: 'Uderzyć w czuły punkt' },
  { id: 96, language: 'Italian', word: 'Non c’è trippa per gatti', options: ['Nie ma flaków dla kotów', 'Nie ma na coś szans', 'Nic z tego nie będzie', 'Skończyło się dobre'], correctAnswer: 'Nic z tego nie będzie' },
  { id: 97, language: 'Italian', word: 'Prendere la via del ritorno', options: ['Wziąć drogę powrotną', 'Wracać do domu', 'Zacząć wracać', 'Być w drodze powrotnej'], correctAnswer: 'Wracać do domu' },
  { id: 98, language: 'Italian', word: 'Restare con un pugno di mosche', options: ['Zostać z garścią much', 'Pozostać z niczym', 'Nic nie osiągnąć', 'Ponieść porażkę'], correctAnswer: 'Pozostać z niczym' },
  { id: 99, language: 'Italian', word: 'Stare in guardia', options: ['Stać na straży', 'Być czujnym', 'Uważać', 'Mieć się na baczności'], correctAnswer: 'Być czujnym' },
  { id: 100, language: 'Italian', word: 'Tirare avanti', options: ['Ciągnąć do przodu', 'Radzić sobie', 'Jakoś sobie radzić', 'Przetrwać'], correctAnswer: 'Radzić sobie' },
  { id: 101, language: 'Italian', word: 'Volerci un occhio di riguardo', options: ['Chcieć oka szacunku', 'Wymagać specjalnego traktowania', 'Trzeba uważać', 'Być ostrożnym'], correctAnswer: 'Trzeba uważać' },
  { id: 102, language: 'Italian', word: 'Avere il coltello dalla parte del manico', options: ['Mieć nóż po stronie rękojeści', 'Mieć przewagę', 'Być w lepszej sytuacji', 'Kontrolować sytuację'], correctAnswer: 'Mieć przewagę' },
  { id: 103, language: 'Italian', word: 'Dare il massimo', options: ['Dać maksimum', 'Dać z siebie wszystko', 'Starać się jak najlepiej', 'Dać z siebie 100%'], correctAnswer: 'Dać z siebie wszystko' },
  { id: 104, language: 'Italian', word: 'Fare quattro chiacchiere', options: ['Zrobić cztery pogawędki', 'Pogadać sobie lekko', 'Uciąć sobie pogawędkę', 'Plotkować'], correctAnswer: 'Uciąć sobie pogawędkę' },
  { id: 105, language: 'Italian', word: 'Non sapere che pesci prendere', options: ['Nie wiedzieć, jakie ryby łowić', 'Nie wiedzieć, co robić', 'Być niezdecydowanym', 'Znaleźć się w kropce'], correctAnswer: 'Nie wiedzieć, co robić' },
  { id: 106, language: 'Italian', word: 'Restare a bocca asciutta', options: ['Zostać z suchymi ustami', 'Obejść się smakiem', 'Pozostać z niczym', 'Być rozczarowanym'], correctAnswer: 'Obejść się smakiem' },
  { id: 107, language: 'Italian', word: 'Stare a sentire', options: ['Stań i posłuchaj', 'Słuchać uważnie', 'Posłuchaj no', 'Zwracać uwagę'], correctAnswer: 'Słuchać uważnie' },
  { id: 108, language: 'Italian', word: 'Tirare le somme', options: ['Ciągnąć sumy', 'Podsumować wszystko', 'Wyciągnąć wnioski', 'Zrobić bilans'], correctAnswer: 'Podsumować wszystko' },
  { id: 109, language: 'Italian', word: 'Volerci molto', options: ['Chcieć dużo', 'Wymagać dużo wysiłku', 'To nie jest proste', 'Trzeba się postarać'], correctAnswer: 'Wymagać dużo wysiłku' }
];
