export interface Question {
  id: number;
  language: 'Polish';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  {
    id: 1,
    language: 'Polish',
    word: 'Cześć',
    options: ['Goodbye', 'Hello', 'Thank you', 'Sorry'],
    correctAnswer: 'Hello',
  },
  {
    id: 2,
    language: 'Polish',
    word: 'Do widzenia',
    options: ['Hello', 'Good morning', 'Goodnight', 'Goodbye'],
    correctAnswer: 'Goodbye',
  },
  {
    id: 3,
    language: 'Polish',
    word: 'Dziękuję',
    options: ['Please', 'You\'re welcome', 'Thank you', 'Excuse me'],
    correctAnswer: 'Thank you',
  },
  {
    id: 4,
    language: 'Polish',
    word: 'Tak',
    options: ['Yes', 'No', 'Maybe', 'Always'],
    correctAnswer: 'Yes',
  },
  {
    id: 5,
    language: 'Polish',
    word: 'Nie',
    options: ['Okay', 'Never', 'Why', 'No'],
    correctAnswer: 'No',
  },
  {
    id: 6,
    language: 'Polish',
    word: 'Mężczyzna',
    options: ['Woman', 'Man', 'Child', 'Person'],
    correctAnswer: 'Man',
  },
  {
    id: 7,
    language: 'Polish',
    word: 'Kobieta',
    options: ['Man', 'Girl', 'Woman', 'Boy'],
    correctAnswer: 'Woman',
  },
  {
    id: 8,
    language: 'Polish',
    word: 'Jeść',
    options: ['To drink', 'To sleep', 'To eat', 'To run'],
    correctAnswer: 'To eat',
  },
  {
    id: 9,
    language: 'Polish',
    word: 'Woda',
    options: ['Fire', 'Water', 'Earth', 'Air'],
    correctAnswer: 'Water',
  },
  {
    id: 10,
    language: 'Polish',
    word: 'Kot',
    options: ['Dog', 'Bird', 'Fish', 'Cat'],
    correctAnswer: 'Cat',
  },
  {
    id: 11,
    language: 'Polish',
    word: 'Pies',
    options: ['Cat', 'Dog', 'Lion', 'Tiger'],
    correctAnswer: 'Dog',
  },
  {
    id: 12,
    language: 'Polish',
    word: 'Dom',
    options: ['Car', 'School', 'House', 'Shop'],
    correctAnswer: 'House',
  },
  {
    id: 13,
    language: 'Polish',
    word: 'Samochód',
    options: ['Bicycle', 'Train', 'Bus', 'Car'],
    correctAnswer: 'Car',
  },
  {
    id: 14,
    language: 'Polish',
    word: 'Szkoła',
    options: ['Hospital', 'School', 'University', 'Library'],
    correctAnswer: 'School',
  },
  {
    id: 15,
    language: 'Polish',
    word: 'Książka',
    options: ['Movie', 'Song', 'Book', 'Painting'],
    correctAnswer: 'Book',
  },
  {
    id: 16,
    language: 'Polish',
    word: 'Słońce',
    options: ['Moon', 'Star', 'Sun', 'Cloud'],
    correctAnswer: 'Sun',
  },
  {
    id: 17,
    language: 'Polish',
    word: 'Księżyc',
    options: ['Sun', 'Planet', 'Moon', 'Comet'],
    correctAnswer: 'Moon',
  },
  {
    id: 18,
    language: 'Polish',
    word: 'Miłość',
    options: ['Hate', 'Joy', 'Sadness', 'Love'],
    correctAnswer: 'Love',
  },
  {
    id: 19,
    language: 'Polish',
    word: 'Przyjaciel',
    options: ['Enemy', 'Neighbor', 'Friend', 'Family'],
    correctAnswer: 'Friend',
  },
  {
    id: 20,
    language: 'Polish',
    word: 'Rodzina',
    options: ['Acquaintances', 'Family', 'Relatives', 'Neighbors'],
    correctAnswer: 'Family',
  },
  {
    id: 21,
    language: 'Polish',
    word: 'Rano',
    options: ['Evening', 'Night', 'Afternoon', 'Morning'],
    correctAnswer: 'Morning',
  },
  {
    id: 22,
    language: 'Polish',
    word: 'Noc',
    options: ['Day', 'Night', 'Dusk', 'Dawn'],
    correctAnswer: 'Night',
  },
  {
    id: 23,
    language: 'Polish',
    word: 'Dzień',
    options: ['Week', 'Month', 'Year', 'Day'],
    correctAnswer: 'Day',
  },
  {
    id: 24,
    language: 'Polish',
    word: 'Tydzień',
    options: ['Day', 'Week', 'Weekend', 'Month'],
    correctAnswer: 'Week',
  },
  {
    id: 25,
    language: 'Polish',
    word: 'Miesiąc',
    options: ['Year', 'Century', 'Decade', 'Month'],
    correctAnswer: 'Month',
  },
  {
    id: 26,
    language: 'Polish',
    word: 'Rok',
    options: ['Month', 'Year', 'Day', 'Hour'],
    correctAnswer: 'Year',
  },
  {
    id: 27,
    language: 'Polish',
    word: 'Dzisiaj',
    options: ['Yesterday', 'Tomorrow', 'Today', 'The day after tomorrow'],
    correctAnswer: 'Today',
  },
  {
    id: 28,
    language: 'Polish',
    word: 'Jutro',
    options: ['Today', 'Yesterday', 'The day before yesterday', 'Tomorrow'],
    correctAnswer: 'Tomorrow',
  },
  {
    id: 29,
    language: 'Polish',
    word: 'Proszę',
    options: ['Thank you', 'Please', 'Excuse me', 'You\'re welcome'],
    correctAnswer: 'Please',
  },
  {
    id: 30,
    language: 'Polish',
    word: 'Jabłko',
    options: ['Banana', 'Orange', 'Apple', 'Pear'],
    correctAnswer: 'Apple',
  },
];
