export interface Question {
  id: number;
  language: 'English';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'English', word: 'Hello', options: ['Do widzenia', 'Cześć', 'Dziękuję', 'Przepraszam'], correctAnswer: 'Cześć' },
  { id: 2, language: 'English', word: 'Goodbye', options: ['Cześć', 'Dzień dobry', 'Dobranoc', 'Do widzenia'], correctAnswer: 'Do widzenia' },
  { id: 3, language: 'English', word: 'Thank you', options: ['Proszę', 'Nie ma za co', 'Dziękuję', 'Przepraszam'], correctAnswer: 'Dziękuję' },
  { id: 4, language: 'English', word: 'Yes', options: ['Tak', 'Nie', 'Może', 'Zawsze'], correctAnswer: 'Tak' },
  { id: 5, language: 'English', word: 'No', options: ['Dobrze', 'Nigdy', 'Dlaczego', 'Nie'], correctAnswer: 'Nie' },
  { id: 6, language: 'English', word: 'Man', options: ['Kobieta', 'Mężczyzna', 'Dziecko', 'Osoba'], correctAnswer: 'Mężczyzna' },
  { id: 7, language: 'English', word: 'Woman', options: ['Mężczyzna', 'Dziewczyna', 'Kobieta', 'Chłopiec'], correctAnswer: 'Kobieta' },
  { id: 8, language: 'English', word: 'To eat', options: ['Pić', 'Spać', 'Jeść', 'Biegać'], correctAnswer: 'Jeść' },
  { id: 9, language: 'English', word: 'Water', options: ['Ogień', 'Woda', 'Ziemia', 'Powietrze'], correctAnswer: 'Woda' },
  { id: 10, language: 'English', word: 'Cat', options: ['Pies', 'Ptak', 'Ryba', 'Kot'], correctAnswer: 'Kot' },
  { id: 11, language: 'English', word: 'Dog', options: ['Kot', 'Pies', 'Lew', 'Tygrys'], correctAnswer: 'Pies' },
  { id: 12, language: 'English', word: 'House', options: ['Samochód', 'Szkoła', 'Dom', 'Sklep'], correctAnswer: 'Dom' },
  { id: 13, language: 'English', word: 'Car', options: ['Rower', 'Pociąg', 'Autobus', 'Samochód'], correctAnswer: 'Samochód' },
  { id: 14, language: 'English', word: 'School', options: ['Szpital', 'Szkoła', 'Uniwersytet', 'Biblioteka'], correctAnswer: 'Szkoła' },
  { id: 15, language: 'English', word: 'Book', options: ['Film', 'Piosenka', 'Książka', 'Obraz'], correctAnswer: 'Książka' },
  { id: 16, language: 'English', word: 'Sun', options: ['Księżyc', 'Gwiazda', 'Słońce', 'Chmura'], correctAnswer: 'Słońce' },
  { id: 17, language: 'English', word: 'Moon', options: ['Słońce', 'Planeta', 'Księżyc', 'Kometa'], correctAnswer: 'Księżyc' },
  { id: 18, language: 'English', word: 'Love', options: ['Nienawiść', 'Radość', 'Smutek', 'Miłość'], correctAnswer: 'Miłość' },
  { id: 19, language: 'English', word: 'Friend', options: ['Wróg', 'Sąsiad', 'Przyjaciel', 'Rodzina'], correctAnswer: 'Przyjaciel' },
  { id: 20, language: 'English', word: 'Family', options: ['Znajomi', 'Rodzina', 'Krewni', 'Sąsiedzi'], correctAnswer: 'Rodzina' },
  { id: 21, language: 'English', word: 'Morning', options: ['Wieczór', 'Noc', 'Popołudnie', 'Rano'], correctAnswer: 'Rano' },
  { id: 22, language: 'English', word: 'Night', options: ['Dzień', 'Noc', 'Zmierzch', 'Świt'], correctAnswer: 'Noc' },
  { id: 23, language: 'English', word: 'Day', options: ['Tydzień', 'Miesiąc', 'Rok', 'Dzień'], correctAnswer: 'Dzień' },
  { id: 24, language: 'English', word: 'Week', options: ['Dzień', 'Tydzień', 'Weekend', 'Miesiąc'], correctAnswer: 'Tydzień' },
  { id: 25, language: 'English', word: 'Month', options: ['Rok', 'Wiek', 'Dekada', 'Miesiąc'], correctAnswer: 'Miesiąc' },
  { id: 26, language: 'English', word: 'Year', options: ['Miesiąc', 'Rok', 'Dzień', 'Godzina'], correctAnswer: 'Rok' },
  { id: 27, language: 'English', word: 'Today', options: ['Wczoraj', 'Jutro', 'Dzisiaj', 'Pojutrze'], correctAnswer: 'Dzisiaj' },
  { id: 28, language: 'English', word: 'Tomorrow', options: ['Dzisiaj', 'Wczoraj', 'Przedwczoraj', 'Jutro'], correctAnswer: 'Jutro' },
  { id: 29, language: 'English', word: 'Please', options: ['Dziękuję', 'Proszę', 'Przepraszam', 'Nie ma za co'], correctAnswer: 'Proszę' },
  { id: 30, language: 'English', word: 'Apple', options: ['Banan', 'Pomarańcza', 'Jabłko', 'Gruszka'], correctAnswer: 'Jabłko' },
  { id: 31, language: 'English', word: 'Achieve', options: ['Tracić', 'Osiągać', 'Unikać', 'Poddawać się'], correctAnswer: 'Osiągać' },
  { id: 32, language: 'English', word: 'Environment', options: ['Miasto', 'Natura', 'Budynek', 'Środowisko'], correctAnswer: 'Środowisko' },
  { id: 33, language: 'English', word: 'Improve', options: ['Pogarszać', 'Poprawiać', 'Niszczyć', 'Zostawiać'], correctAnswer: 'Poprawiać' },
  { id: 34, language: 'English', word: 'Opportunity', options: ['Problem', 'Przeszkoda', 'Okazja', 'Ryzyko'], correctAnswer: 'Okazja' },
  { id: 35, language: 'English', word: 'Curious', options: ['Obojętny', 'Znudzony', 'Ciekawy', 'Smutny'], correctAnswer: 'Ciekawy' },
  { id: 36, language: 'English', word: 'Efficient', options: ['Powolny', 'Wydajny', 'Leniwy', 'Nieskuteczny'], correctAnswer: 'Wydajny' },
  { id: 37, language: 'English', word: 'Exhausted', options: [' wypoczęty', 'Pełen energii', 'Wyczerpany', 'Silny'], correctAnswer: 'Wyczerpany' },
  { id: 38, language: 'English', word: 'Negotiate', options: ['Kłócić się', 'Negocjować', 'Omawiać', 'Zgadzać się'], correctAnswer: 'Negocjować' },
  { id: 39, language: 'English', word: 'Reliable', options: ['Niezawodny', 'Niepewny', 'Ryzykowny', 'Zmienny'], correctAnswer: 'Niezawodny' },
  { id: 40, language: 'English', word: 'Sophisticated', options: ['Prosty', 'Prymitywny', 'Wyrafinowany', 'Zwykły'], correctAnswer: 'Wyrafinowany' },
  { id: 41, language: 'English', word: 'Ambiguous', options: ['Jasny', 'Doprecyzowany', 'Jednoznaczny', 'Dwuznaczny'], correctAnswer: 'Dwuznaczny' },
  { id: 42, language: 'English', word: 'Conscientious', options: ['Niedbały', 'Leniwy', 'Sumienny', 'Powierzchowny'], correctAnswer: 'Sumienny' },
  { id: 43, language: 'English', word: 'Entrepreneur', options: ['Pracownik', 'Przedsiębiorca', 'Artysta', 'Naukowiec'], correctAnswer: 'Przedsiębiorca' },
  { id: 44, language: 'English', word: 'Resilient', options: ['Podatny', 'Słaby', 'Odporny', 'Wrażliwy'], correctAnswer: 'Odporny' },
  { id: 45, language: 'English', word: 'Ubiquitous', options: ['Rzadki', 'Unikalny', 'Wszechobecny', 'Niewidoczny'], correctAnswer: 'Wszechobecny' },
  { id: 46, language: 'English', word: 'Accountability', options: ['Bezkarność', 'Odpowiedzialność', 'Chaos', 'Zabawa'], correctAnswer: 'Odpowiedzialność' },
  { id: 47, language: 'English', word: 'Meticulous', options: ['Niedokładny', 'Chaotyczny', 'Skrupulatny', 'Szybki'], correctAnswer: 'Skrupulatny' },
  { id: 48, language: 'English', word: 'Procrastinate', options: ['Działać natychmiast', 'Planować', 'Odkładać na później', 'Kończyć przed czasem'], correctAnswer: 'Odkładać na później' },
  { id: 49, language: 'English', word: 'Superfluous', options: ['Niezbędny', 'Konieczny', 'Ważny', 'Zbędny'], correctAnswer: 'Zbędny' },
  { id: 50, language: 'English', word: 'Versatile', options: ['Ograniczony', 'Jednostronny', 'Wszechstronny', 'Specjalistyczny'], correctAnswer: 'Wszechstronny' },
  { id: 51, language: 'English', word: 'Accomplish', options: ['Ponieść porażkę', 'Osiągnąć', 'Zrezygnować', 'Próbować'], correctAnswer: 'Osiągnąć' },
  { id: 52, language: 'English', word: 'Benefit', options: ['Szkoda', 'Wada', 'Korzyść', 'Strata'], correctAnswer: 'Korzyść' },
  { id: 53, language: 'English', word: 'Crucial', options: ['Nieistotny', 'Kluczowy', 'Dodatkowy', 'Opcjonalny'], correctAnswer: 'Kluczowy' },
  { id: 54, language: 'English', word: 'Diligent', options: ['Leniwy', 'Pilny', 'Niestaranny', 'Obojętny'], correctAnswer: 'Pilny' },
  { id: 55, language: 'English', word: 'Enhance', options: ['Pogorszyć', 'Ulepszyć', 'Zniszczyć', 'Osłabić'], correctAnswer: 'Ulepszyć' },
  { id: 56, language: 'English', word: 'Flexible', options: ['Sztywny', 'Elastyczny', 'Niezmienny', 'Stały'], correctAnswer: 'Elastyczny' },
  { id: 57, language: 'English', word: 'Generate', options: ['Niszczyć', 'Generować', 'Konsumować', 'Zatrzymywać'], correctAnswer: 'Generować' },
  { id: 58, language: 'English', word: 'Hesitate', options: ['Być pewnym', 'Wahać się', 'Decydować', 'Działać'], correctAnswer: 'Wahać się' },
  { id: 59, language: 'English', word: 'Implement', options: ['Ignorować', 'Wdrożyć', 'Planować', 'Odrzucać'], correctAnswer: 'Wdrożyć' },
  { id: 60, language: 'English', word: 'Justify', options: ['Oskarżać', 'Uzasadnić', 'Zaprzeczać', 'Wątpić'], correctAnswer: 'Uzasadnić' },
  { id: 61, language: 'English', word: 'Knowledge', options: ['Głupota', 'Wiedza', 'Ignorancja', 'Pustka'], correctAnswer: 'Wiedza' },
  { id: 62, language: 'English', word: 'Legitimate', options: ['Nielegalny', 'Prawowity', 'Fałszywy', 'Wątpliwy'], correctAnswer: 'Prawowity' },
  { id: 63, language: 'English', word: 'Maintain', options: ['Niszczyć', 'Utrzymać', 'Zaniedbywać', 'Zmieniać'], correctAnswer: 'Utrzymać' },
  { id: 64, language: 'English', word: 'Persevere', options: ['Poddawać się', 'Wytrwać', 'Rezygnować', 'Wątpić'], correctAnswer: 'Wytrwać' },
  { id: 65, language: 'English', word: 'Resilient', options: ['Wrażliwy', 'Odporny', 'Słaby', 'Podatny'], correctAnswer: 'Odporny' },
  { id: 66, language: 'English', word: 'Significant', options: ['Błahy', 'Znaczący', 'Mały', 'Nieważny'], correctAnswer: 'Znaczący' },
  { id: 67, language: 'English', word: 'Tolerate', options: ['Akceptować', 'Tolerować', 'Odrzucać', 'Potępiać'], correctAnswer: 'Tolerować' },
  { id: 68, language: 'English', word: 'Unique', options: ['Powszechny', 'Unikalny', 'Zwykły', 'Typowy'], correctAnswer: 'Unikalny' },
  { id: 69, language: 'English', word: 'Verify', options: ['Domyślać się', 'Weryfikować', 'Fałszować', 'Ignorować'], correctAnswer: 'Weryfikować' },
  { id: 70, language: 'English', word: 'Widespread', options: ['Lokalny', 'Rozpowszechniony', 'Ograniczony', 'Rzadki'], correctAnswer: 'Rozpowszechniony' },
  { id: 71, language: 'English', word: 'Yield', options: ['Walczyć', 'Ulegać', 'Opierać się', 'Zabierać'], correctAnswer: 'Ulegać' },
  { id: 72, language: 'English', word: 'Zealous', options: ['Apatyczny', 'Gorliwy', 'Obojętny', 'Leniwy'], correctAnswer: 'Gorliwy' },
  { id: 73, language: 'English', word: 'Abundant', options: ['Rzadki', 'Obfity', 'Brakujący', 'Minimalny'], correctAnswer: 'Obfity' },
  { id: 74, language: 'English', word: 'Bolster', options: ['Osłabiać', 'Wzmacniać', 'Podkopywać', 'Niszczyć'], correctAnswer: 'Wzmacniać' },
  { id: 75, language: 'English', word: 'Candid', options: ['Nieszczery', 'Szczery', 'Ukryty', 'Skomplikowany'], correctAnswer: 'Szczery' },
  { id: 76, language: 'English', word: 'Deviate', options: ['Trzymać się kursu', 'Zbaczać', 'Podążać', 'Naśladować'], correctAnswer: 'Zbaczać' },
  { id: 77, language: 'English', word: 'Eminent', options: ['Nieznany', 'Wybitny', 'Zwykły', 'Przeciętny'], correctAnswer: 'Wybitny' },
  { id: 78, language: 'English', word: 'Feasible', options: ['Niemożliwy', 'Wykonalny', 'Trudny', 'Niepraktyczny'], correctAnswer: 'Wykonalny' },
  { id: 79, language: 'English', word: 'Gregarious', options: ['Samotniczy', 'Towarzyski', 'Nieśmiały', 'Zamknięty w sobie'], correctAnswer: 'Towarzyski' },
  { id: 80, language: 'English', word: 'Hinder', options: ['Pomagać', 'Utrudniać', 'Wspierać', 'Ułatwiać'], correctAnswer: 'Utrudniać' },
  { id: 81, language: 'English', word: 'Inevitable', options: ['Możliwy do uniknięcia', 'Nieunikniony', 'Niepewny', 'Przypadkowy'], correctAnswer: 'Nieunikniony' },
  { id: 82, language: 'English', word: 'Juxtapose', options: ['Oddzielać', 'Zestawiać', 'Mieszać', 'Ukrywać'], correctAnswer: 'Zestawiać' },
  { id: 83, language: 'English', word: 'Keen', options: ['Tępy', 'Obojętny', 'Bystry', 'Niezainteresowany'], correctAnswer: 'Bystry' },
  { id: 84, language: 'English', word: 'Lucid', options: ['Mętny', 'Przejrzysty', 'Niejasny', 'Skomplikowany'], correctAnswer: 'Przejrzysty' },
  { id: 85, language: 'English', word: 'Myriad', options: ['Garstka', 'Niezliczony', 'Kilka', 'Ograniczona ilość'], correctAnswer: 'Niezliczony' },
  { id: 86, language: 'English', word: 'Novice', options: ['Ekspert', 'Nowicjusz', 'Weteran', 'Mistrz'], correctAnswer: 'Nowicjusz' },
  { id: 87, language: 'English', word: 'Omit', options: ['Dodawać', 'Pominąć', 'Uwzględniać', 'Podkreślać'], correctAnswer: 'Pominąć' },
  { id: 88, language: 'English', word: 'Ponder', options: ['Działać impulsywnie', 'Rozważać', 'Ignorować', 'Zapominać'], correctAnswer: 'Rozważać' },
  { id: 89, language: 'English', word: 'Quintessential', options: ['Nietypowy', 'Kwintesencjonalny', 'Odbiegający od normy', 'Rzadki'], correctAnswer: 'Kwintesencjonalny' },
  { id: 90, language: 'English', word: 'Refute', options: ['Potwierdzać', 'Obalić', 'Zgadzać się', 'Dowodzić'], correctAnswer: 'Obalić' },
  { id: 91, language: 'English', word: 'Scrutinize', options: ['Przeglądać pobieżnie', 'Badać szczegółowo', 'Ignorować', 'Akceptować bezkrytycznie'], correctAnswer: 'Badać szczegółowo' },
  { id: 92, language: 'English', word: 'Tentative', options: ['Ostateczny', 'Niepewny', 'Pewny', 'Zdecydowany'], correctAnswer: 'Niepewny' },
  { id: 93, language: 'English', word: 'Undermine', options: ['Wzmacniać', 'Podkopywać', 'Wspierać', 'Budować'], correctAnswer: 'Podkopywać' },
  { id: 94, language: 'English', word: 'Vivid', options: ['Blady', 'Wyrazisty', 'Nudny', 'Matowy'], correctAnswer: 'Wyrazisty' },
  { id: 95, language: 'English', word: 'Whimsical', options: ['Poważny', 'Kapryśny', 'Przewidywalny', 'Logiczny'], correctAnswer: 'Kapryśny' },
  { id: 96, language: 'English', word: 'Exemplary', options: ['Przeciętny', 'Wzorowy', 'Zły', 'Niedostateczny'], correctAnswer: 'Wzorowy' },
  { id: 97, language: 'English', word: 'Yearn', options: ['Być obojętnym', 'Tęsknić', 'Nienawidzić', 'Unikać'], correctAnswer: 'Tęsknić' },
  { id: 98, language: 'English', word: 'Zest', options: ['Apatia', 'Entuzjazm', 'Smutek', 'Nuda'], correctAnswer: 'Entuzjazm' },
  { id: 99, language: 'English', word: 'Pragmatic', options: ['Idealistyczny', 'Pragmatyczny', 'Teoretyczny', 'Nierealistyczny'], correctAnswer: 'Pragmatyczny' },
  { id: 100, language: 'English', word: 'Eloquent', options: ['Niewyraźny', 'Wymowny', 'Milczący', 'Prosty'], correctAnswer: 'Wymowny' },
];
