
export interface Question {
  id: number;
  language: 'English';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'English', word: 'Ask out', options: ['Zaprosić kogoś na randkę', 'Oddzwonić', 'Odwołać', 'Wychować'], correctAnswer: 'Zaprosić kogoś na randkę' },
  { id: 2, language: 'English', word: 'Back up', options: ['Zepsuć się', 'Kontynuować', 'Poprzeć', 'Zrobić kopię zapasową'], correctAnswer: 'Poprzeć' },
  { id: 3, language: 'English', word: 'Blow up', options: ['Wybuchnąć', 'Ściszyć', 'Uspokoić się', 'Poddać się'], correctAnswer: 'Wybuchnąć' },
  { id: 4, language: 'English', word: 'Break down', options: ['Zbudować', 'Naprawić', 'Zepsuć się', 'Załamać się'], correctAnswer: 'Zepsuć się' },
  { id: 5, language: 'English', word: 'Break up', options: ['Zejść się', 'Pogodzić się', 'Rozstać się', 'Oświadczyć się'], correctAnswer: 'Rozstać się' },
  { id: 6, language: 'English', word: 'Bring up', options: ['Ukryć temat', 'Pominąć', 'Poruszyć temat', 'Wychować'], correctAnswer: 'Poruszyć temat' },
  { id: 7, language: 'English', word: 'Call back', options: ['Zadzwonić pierwszy raz', 'Oddzwonić', 'Rozłączyć się', 'Odebrać telefon'], correctAnswer: 'Oddzwonić' },
  { id: 8, language: 'English', word: 'Call off', options: ['Odwołać', 'Potwierdzić', 'Zaplanować', 'Przełożyć'], correctAnswer: 'Odwołać' },
  { id: 9, language: 'English', word: 'Carry on', options: ['Zatrzymać się', 'Zrezygnować', 'Kontynuować', 'Poczekać'], correctAnswer: 'Kontynuować' },
  { id: 10, language: 'English', word: 'Catch up', options: ['Zostać w tyle', 'Przyspieszyć', 'Nadrobić zaległości', 'Zwolnić'], correctAnswer: 'Nadrobić zaległości' },
  { id: 11, language: 'English', word: 'Check in', options: ['Zameldować się', 'Wymeldować się', 'Wyjechać', 'Zarezerwować'], correctAnswer: 'Zameldować się' },
  { id: 12, language: 'English', word: 'Check out', options: ['Sprawdzić', 'Wymeldować się', 'Zignorować', 'Potwierdzić'], correctAnswer: 'Sprawdzić' },
  { id: 13, language: 'English', word: 'Come across', options: ['Szukać czegoś', 'Natknąć się', 'Ominąć', 'Zgubić'], correctAnswer: 'Natknąć się' },
  { id: 14, language: 'English', word: 'Come back', options: ['Odejść', 'Wyjechać', 'Wrócić', 'Zostać'], correctAnswer: 'Wrócić' },
  { id: 15, language: 'English', word: 'Come in', options: ['Wyjść', 'Wejść', 'Zaczekać na zewnątrz', 'Pukać'], correctAnswer: 'Wejść' },
  { id: 16, language: 'English', word: 'Come out', options: ['Schować się', 'Wejść do środka', 'Wyjść', 'Ukazać się'], correctAnswer: 'Wyjść' },
  { id: 17, language: 'English', word: 'Come over', options: ['Odwiedzić kogoś', 'Wpaść z wizytą', 'Wyjść z domu', 'Zostać w domu'], correctAnswer: 'Wpaść z wizytą' },
  { id: 18, language: 'English', word: 'Cut down', options: ['Zwiększyć', 'Ograniczyć', 'Dodać', 'Pomnożyć'], correctAnswer: 'Ograniczyć' },
  { id: 19, language: 'English', word: 'Cut off', options: ['Połączyć', 'Odciąć', 'Przerwać', 'Przedłużyć'], correctAnswer: 'Odciąć' },
  { id: 20, language: 'English', word: 'Deal with', options: ['Radzić sobie z czymś', 'Ignorować problem', 'Unikać', 'Tworzyć problem'], correctAnswer: 'Radzić sobie z czymś' },
  { id: 21, language: 'English', word: 'Drop by', options: ['Odwiedzić na długo', 'Wpaść na chwilę', 'Ominąć', 'Zadzwonić'], correctAnswer: 'Wpaść na chwilę' },
  { id: 22, language: 'English', word: 'Drop off', options: ['Odebrać', 'Podrzucić', 'Zasnąć', 'Obudzić się'], correctAnswer: 'Podrzucić' },
  { id: 23, language: 'English', word: 'Figure out', options: ['Zrozumieć', 'Rozgryźć', 'Zignorować', 'Zapomnieć'], correctAnswer: 'Zrozumieć' },
  { id: 24, language: 'English', word: 'Fill in', options: ['Wypełnić', 'Zastąpić', 'Opróżnić', 'Pominąć'], correctAnswer: 'Wypełnić' },
  { id: 25, language: 'English', word: 'Find out', options: ['Dowiedzieć się', 'Ukryć informację', 'Zgadnąć', 'Zapomnieć'], correctAnswer: 'Dowiedzieć się' },
  { id: 26, language: 'English', word: 'Get along', options: ['Kłócić się', 'Dogadywać się', 'Ignorować się', 'Walczyć'], correctAnswer: 'Dogadywać się' },
  { id: 27, language: 'English', word: 'Get back', options: ['Iść naprzód', 'Zostać', 'Wrócić', 'Odejść'], correctAnswer: 'Wrócić' },
  { id: 28, language: 'English', word: 'Get in', options: ['Wyjść', 'Wejść', 'Dostać się', 'Wyskoczyć'], correctAnswer: 'Wejść' },
  { id: 29, language: 'English', word: 'Get off', options: ['Wsiąść', 'Wysiąść', 'Zejść z pracy', 'Wejść'], correctAnswer: 'Wysiąść' },
  { id: 30, language: 'English', word: 'Get on', options: ['Wsiąść', 'Radzić sobie', 'Wysiąść', 'Zrezygnować'], correctAnswer: 'Wsiąść' },
  { id: 31, language: 'English', word: 'Get over', options: ['Zachorować', 'Dojść do siebie', 'Pamiętać', 'Cierpieć'], correctAnswer: 'Dojść do siebie' },
  { id: 32, language: 'English', word: 'Get through', options: ['Przebrnąć', 'Dodzwonić się', 'Poddawać się', 'Unikać'], correctAnswer: 'Przebrnąć' },
  { id: 33, language: 'English', word: 'Give back', options: ['Zabrać', 'Oddać', 'Pożyczyć', 'Ukraść'], correctAnswer: 'Oddać' },
  { id: 34, language: 'English', word: 'Give up', options: ['Poddać się', 'Rzucić coś', 'Kontynuować', 'Walczyć'], correctAnswer: 'Poddać się' },
  { id: 35, language: 'English', word: 'Go ahead', options: ['Zatrzymać się', 'Kontynuować', 'Zgodzić się', 'Cofnąć się'], correctAnswer: 'Kontynuować' },
  { id: 36, language: 'English', word: 'Go back', options: ['Iść naprzód', 'Wrócić', 'Zostać', 'Przyspieszyć'], correctAnswer: 'Wrócić' },
  { id: 37, language: 'English', word: 'Go on', options: ['Dziać się', 'Kontynuować', 'Zatrzymać', 'Cofnąć'], correctAnswer: 'Dziać się' },
  { id: 38, language: 'English', word: 'Go out', options: ['Wejść', 'Wyjść', 'Zostać w domu', 'Siedzieć'], correctAnswer: 'Wyjść' },
  { id: 39, language: 'English', word: 'Go through', options: ['Ominąć', 'Przejść przez coś', 'Uniknąć', 'Zatrzymać się'], correctAnswer: 'Przejść przez coś' },
  { id: 40, language: 'English', word: 'Hang out', options: ['Pracować', 'Uczyć się', 'Spędzać czas', 'Siedzieć samemu'], correctAnswer: 'Spędzać czas' },
  { id: 41, language: 'English', word: 'Hold on', options: ['Puścić', 'Zrezygnować', 'Poczekać', 'Przyspieszyć'], correctAnswer: 'Poczekać' },
  { id: 42, language: 'English', word: 'Keep on', options: ['Przestać', 'Zatrzymać', 'Kontynuować', 'Począć'], correctAnswer: 'Kontynuować' },
  { id: 43, language: 'English', word: 'Let down', options: ['Podnieść', 'Zawieść', 'Wspierać', 'Pomóc'], correctAnswer: 'Zawieść' },
  { id: 44, language: 'English', word: 'Look after', options: ['Ignorować', 'Szukać', 'Opiekować się', 'Zaniedbywać'], correctAnswer: 'Opiekować się' },
  { id: 45, language: 'English', word: 'Look for', options: ['Znaleźć', 'Gubić', 'Szukać', 'Patrzeć na'], correctAnswer: 'Szukać' },
  { id: 46, language: 'English', word: 'Look forward to', options: ['Obawiać się', 'Nie móc się doczekać', 'Żałować', 'Zapominać'], correctAnswer: 'Nie móc się doczekać' },
  { id: 47, language: 'English', word: 'Look into', options: ['Sprawdzić', 'Zbadać', 'Zignorować', 'Pominąć'], correctAnswer: 'Sprawdzić' },
  { id: 48, language: 'English', word: 'Look out', options: ['Ignorować', 'Uważać', 'Patrzeć do środka', 'Zamykać oczy'], correctAnswer: 'Uważać' },
  { id: 49, language: 'English', word: 'Make up', options: ['Kłócić się', 'Pogodzić się', 'Wymyślić', 'Zapomnieć'], correctAnswer: 'Pogodzić się' },
  { id: 50, language: 'English', word: 'Move on', options: ['Zostać', 'Iść dalej', 'Cofnąć się', 'Pamiętać'], correctAnswer: 'Iść dalej' },
  { id: 51, language: 'English', word: 'Open up', options: ['Zamknąć się', 'Otworzyć się', 'Milczeć', 'Ukrywać'], correctAnswer: 'Otworzyć się' },
  { id: 52, language: 'English', word: 'Pick up', options: ['Odebrać', 'Podnieść', 'Upuścić', 'Zostawić'], correctAnswer: 'Odebrać' },
  { id: 53, language: 'English', word: 'Put off', options: ['Przyspieszyć', 'Zrobić od razu', 'Odkładać', 'Anulować'], correctAnswer: 'Odkładać' },
  { id: 54, language: 'English', word: 'Run into', options: ['Ominąć', 'Wpaść na kogoś', 'Umówić się', 'Unikać'], correctAnswer: 'Wpaść na kogoś' },
  { id: 55, language: 'English', word: 'Settle down', options: ['Rozwijać się', 'Ustatkować się', 'Podróżować', 'Imprezować'], correctAnswer: 'Ustatkować się' },
  { id: 56, language: 'English', word: 'Show up', options: ['Ukryć się', 'Pojawić się', 'Zniknąć', 'Być nieobecnym'], correctAnswer: 'Pojawić się' },
  { id: 57, language: 'English', word: 'Shut up', options: ['Mówić głośno', 'Zamknąć się', 'Krzyczeć', 'Szeptać'], correctAnswer: 'Zamknąć się' },
  { id: 58, language: 'English', word: 'Sort out', options: '["Ogarnąć", "Rozwiązać", "Zrobić bałagan", "Zignorować"]', correctAnswer: 'Ogarnąć' },
  { id: 59, language: 'English', word: 'Take over', options: ['Oddać kontrolę', 'Przejąć', 'Poddać się', 'Współpracować'], correctAnswer: 'Przejąć' },
  { id: 60, language: 'English', word: 'Take up', options: ['Rzucić hobby', 'Zacząć (hobby)', 'Kontynuować', 'Oglądać'], correctAnswer: 'Zacząć (hobby)' },
  { id: 61, language: 'English', word: 'Think over', options: ['Działać impulsywnie', 'Przemyśleć', 'Zapomnieć', 'Zignorować'], correctAnswer: 'Przemyśleć' },
  { id: 62, language: 'English', word: 'Throw away', options: ['Zbierać', 'Naprawiać', 'Wyrzucić', 'Przechowywać'], correctAnswer: 'Wyrzucić' },
  { id: 63, language: 'English', word: 'Turn down', options: ['Odrzucić', 'Ściszyć', 'Zaakceptować', 'Podgłośnić'], correctAnswer: 'Odrzucić' },
  { id: 64, language: 'English', word: 'Turn up', options: ['Zniknąć', 'Pojawić się', 'Podgłośnić', 'Ściszyć'], correctAnswer: 'Pojawić się' },
  { id: 65, language: 'English', word: 'Work out', options: ['Poddać się', 'Rozwiązać', 'Ćwiczyć', 'Odpoczywać'], correctAnswer: 'Rozwiązać' },
  { id: 66, language: 'English', word: 'Write down', options: ['Zapamiętać', 'Zapisać', 'Powiedzieć', 'Przeczytać'], correctAnswer: 'Zapisać' },
  { id: 67, language: 'English', word: 'Set up', options: ['Zlikwidować', 'Założyć', 'Zorganizować', 'Zniszczyć'], correctAnswer: 'Założyć' },
  { id: 68, language: 'English', word: 'Slow down', options: ['Przyspieszyć', 'Zwolnić', 'Zatrzymać się', 'Pędzić'], correctAnswer: 'Zwolnić' },
  { id: 69, language: 'English', word: 'Speed up', options: ['Zwolnić', 'Przyspieszyć', 'Zatrzymać się', 'Czołgać się'], correctAnswer: 'Przyspieszyć' },
  { id: 70, language: 'English', word: 'Step down', options: ['Awansować', 'Ustąpić', 'Zacząć', 'Przejąć'], correctAnswer: 'Ustąpić' },
  { id: 71, language: 'English', word: 'Step up', options: ['Cofnąć się', 'Zrezygnować', 'Zwiększyć zaangażowanie', 'Zmniejszyć wysiłek'], correctAnswer: 'Zwiększyć zaangażowanie' },
  { id: 72, language: 'English', word: 'Break out', options: ['Wybuchnąć', 'Uciec', 'Wejść', 'Zatrzymać'], correctAnswer: 'Wybuchnąć' },
  { id: 73, language: 'English', word: 'Bring back', options: ['Zabrać', 'Wyrzucić', 'Przywrócić', 'Zapomnieć'], correctAnswer: 'Przywrócić' },
  { id: 74, language: 'English', word: 'Calm down', options: ['Zdenerwować się', 'Uspokoić się', 'Krzyczeć', 'Płakać'], correctAnswer: 'Uspokoić się' },
  { id: 75, language: 'English', word: 'Check over', options: ['Zignorować', 'Sprawdzić pobieżnie', 'Sprawdzić dokładnie', 'Zaufać'], correctAnswer: 'Sprawdzić dokładnie' },
  { id: 76, language: 'English', word: 'Clear up', options: ['Wyjaśnić', 'Posprzątać', 'Zrobić bałagan', 'Zaciemnić'], correctAnswer: 'Wyjaśnić' },
  { id: 77, language: 'English', word: 'Come along', options: ['Odejść', 'Przyjść', 'Robić postępy', 'Zostać w tyle'], correctAnswer: 'Przyjść' },
  { id: 78, language: 'English', word: 'Cut back', options: ['Zwiększyć wydatki', 'Ograniczyć wydatki', 'Wydawać więcej', 'Inwestować'], correctAnswer: 'Ograniczyć wydatki' },
  { id: 79, language: 'English', word: 'Fall apart', options: ['Trzymać się razem', 'Rozpaść się', 'Budować', 'Naprawiać'], correctAnswer: 'Rozpaść się' },
  { id: 80, language: 'English', word: 'Fall behind', options: ['Być na czele', 'Nadążać', 'Zostać w tyle', 'Przyspieszać'], correctAnswer: 'Zostać w tyle' },
  { id: 81, language: 'English', word: 'Fill out', options: ['Opróżnić', 'Wypełnić formularz', 'Pominąć', 'Zniszczyć'], correctAnswer: 'Wypełnić formularz' },
  { id: 82, language: 'English', word: 'Get away', options: ['Zostać', 'Wyjechać', 'Uciec', 'Wrócić'], correctAnswer: 'Wyjechać' },
  { id: 83, language: 'English', word: 'Get by', options: ['Ponieść porażkę', 'Radzić sobie', 'Być bogatym', 'Cierpieć'], correctAnswer: 'Radzić sobie' },
  { id: 84, language: 'English', word: 'Get together', options: ['Rozstać się', 'Spotkać się', 'Unikać się', 'Pracować samemu'], correctAnswer: 'Spotkać się' },
  { id: 85, language: 'English', word: 'Give in', options: ['Walczyć', 'Ulec', 'Oprzeć się', 'Wygrać'], correctAnswer: 'Ulec' },
  { id: 86, language: 'English', word: 'Go wrong', options: ['Udać się', 'Pójść nie tak', 'Być poprawnym', 'Naprawić'], correctAnswer: 'Pójść nie tak' },
  { id: 87, language: 'English', word: 'Hang on', options: ['Rozłączyć się', 'Poczekać', 'Odejść', 'Przyspieszyć'], correctAnswer: 'Poczekać' },
  { id: 88, language: 'English', word: 'Keep up', options: ['Zwalniać', 'Nadążać', 'Zostawać w tyle', 'Zatrzymywać się'], correctAnswer: 'Nadążać' },
  { id: 89, language: 'English', word: 'Log in', options: ['Wylogować się', 'Zarejestrować się', 'Zalogować się', 'Usunąć konto'], correctAnswer: 'Zalogować się' },
  { id: 90, language: 'English', word: 'Log out', options: ['Zalogować się', 'Wylogować się', 'Dołączyć', 'Zablokować'], correctAnswer: 'Wylogować się' },
  { id: 91, language: 'English', word: 'Sign in', options: ['Podpisać się', 'Zalogować', 'Wypisać się', 'Anulować'], correctAnswer: 'Zalogować' },
  { id: 92, language: 'English', word: 'Sign out', options: ['Zalogować się', 'Wylogować się', 'Zapisać się', 'Potwierdzić'], correctAnswer: 'Wylogować się' },
  { id: 93, language: 'English', word: 'Turn on', options: ['Wyłączyć', 'Włączyć', 'Zepsuć', 'Naprawić'], correctAnswer: 'Włączyć' },
  { id: 94, language: 'English', word: 'Turn off', options: ['Włączyć', 'Wyłączyć', 'Zwiększyć moc', 'Podłączyć'], correctAnswer: 'Wyłączyć' },
  { id: 95, language: 'English', word: 'Plug in', options: ['Odłączyć', 'Podłączyć', 'Wyłączyć', 'Zepsuć'], correctAnswer: 'Podłączyć' },
  { id: 96, language: 'English', word: 'Back out', options: ['Dołączyć', 'Wycofać się', 'Zaangażować się', 'Potwierdzić'], correctAnswer: 'Wycofać się' },
  { id: 97, language: 'English', word: 'Boot up', options: ['Zamknąć system', 'Uruchomić system', 'Zrestartować', 'Zainstalować'], correctAnswer: 'Uruchomić system' },
  { id: 98, language: 'English', word: 'Shut down', options: ['Uruchomić', 'Zamknąć', 'Wyłączyć', 'Włączyć'], correctAnswer: 'Zamknąć' },
  { id: 99, language: 'English', word: 'Freak out', options: ['Uspokoić się', 'Spanikować', 'Zrelaksować się', 'Być obojętnym'], correctAnswer: 'Spanikować' },
  { id: 100, language: 'English', word: 'Lash out', options: ['Pochwalić', 'Wybuchnąć gniewem', 'Przytulić', 'Przeprosić'], correctAnswer: 'Wybuchnąć gniewem' },
  { id: 101, language: 'English', word: 'Mess up', options: ['Naprawić', 'Schrzanić coś', 'Uporządkować', 'Zrobić dobrze'], correctAnswer: 'Schrzanić coś' },
  { id: 102, language: 'English', word: 'Pass out', options: ['Obudzić się', 'Zemdlać', 'Być przytomnym', 'Zasnąć'], correctAnswer: 'Zemdlać' },
  { id: 103, language: 'English', word: 'Snap out of', options: '["Pogrążyć się", "Otrząsnąć się", "Zmartwić się", "Zignorować"]', correctAnswer: 'Otrząsnąć się' },
  { id: 104, language: 'English', word: 'Wear out', options: ['Zmęczyć', 'Zużyć', 'Odpocząć', 'Naprawić'], correctAnswer: 'Zmęczyć' },
  { id: 105, language: 'English', word: 'Blow off', options: ['Potraktować poważnie', 'Zlekceważyć', 'Spotkać się', 'Zgodzić się'], correctAnswer: 'Zlekceważyć' },
  { id: 106, language: 'English', word: 'Bottle up', options: ['Wyrażać emocje', 'Tłumić emocje', 'Otworzyć butelkę', 'Dzielić się uczuciami'], correctAnswer: 'Tłumić emocje' },
  { id: 107, language: 'English', word: 'Bring along', options: ['Zostawić', 'Zapomnieć', 'Zabrać ze sobą', 'Ukryć'], correctAnswer: 'Zabrać ze sobą' },
  { id: 108, language: 'English', word: 'Call up', options: ['Rozłączyć się', 'Zadzwonić', 'Wysłać wiadomość', 'Ignorować'], correctAnswer: 'Zadzwonić' },
  { id: 109, language: 'English', word: 'Come around', options: ['Trzymać się zdania', 'Zmienić zdanie', 'Odejść', 'Unikać'], correctAnswer: 'Zmienić zdanie' },
  { id: 110, language: 'English', word: 'Cut out', options: ['Przestać', 'Wyciąć', 'Zacząć', 'Dodać'], correctAnswer: 'Przestać' },
  { id: 111, language: 'English', word: 'Get ahead', options: ['Zostać w tyle', 'Wysunąć się na prowadzenie', 'Zwolnić', 'Poddawać się'], correctAnswer: 'Wysunąć się na prowadzenie' },
  { id: 112, language: 'English', word: 'Give away', options: ['Zachować dla siebie', 'Zdradzić', 'Oddać', 'Sprzedać'], correctAnswer: 'Zdradzić' },
  { id: 113, language: 'English', word: 'Hold back', options: ['Uwolnić', 'Powstrzymać', 'Pchnąć do przodu', 'Zachęcać'], correctAnswer: 'Powstrzymać' },
  { id: 114, language: 'English', word: 'Keep away', options: ['Zbliżyć się', 'Trzymać z daleka', 'Przyciągać', 'Dotykać'], correctAnswer: 'Trzymać z daleka' },
  { id: 115, language: 'English', word: 'Lay off', options: ['Zatrudnić', 'Zwolnić z pracy', 'Awansować', 'Pomagać'], correctAnswer: 'Zwolnić z pracy' },
  { id: 116, language: 'English', word: 'Live up to', options: ['Rozczarować', 'Spełnić oczekiwania', 'Ignorować', 'Zaniżać standardy'], correctAnswer: 'Spełnić oczekiwania' },
  { id: 117, language: 'English', word: 'Pass away', options: ['Urodzić się', 'Umrzeć', 'Ozdrowieć', 'Żyć wiecznie'], correctAnswer: 'Umrzeć' },
  { id: 118, language: 'English', word: 'Pull over', options: ['Przyspieszyć', 'Zjechać na bok', 'Kontynuować jazdę', 'Zawrócić'], correctAnswer: 'Zjechać na bok' },
  { id: 119, language: 'English', word: 'Run out', options: ['Skończyć się', 'Zacząć się', 'Mieć w zapasie', 'Znaleźć'], correctAnswer: 'Skończyć się' },
  { id: 120, language: 'English', word: 'Stand by', options: ['Odejść', 'Czekać', 'Wspierać', 'Sprzeciwiać się'], correctAnswer: 'Czekać' },
  { id: 121, language: 'English', word: 'Stick to', options: ['Zmienić', 'Porzucić', 'Trzymać się', 'Eksperymentować'], correctAnswer: 'Trzymać się' },
  { id: 122, language: 'English', word: 'Take off', options: ['Wystartować', 'Zdjąć', 'Lądować', 'Ubrać'], correctAnswer: 'Wystartować' },
  { id: 123, language: 'English', word: 'Turn around', options: ['Iść prosto', 'Odwrócić sytuację', 'Pogorszyć', 'Zachować status quo'], correctAnswer: 'Odwrócić sytuację' },
  { id: 124, language: 'English', word: 'Warm up', options: ['Ochłodzić się', 'Rozgrzać się', 'Odpoczywać', 'Zakończyć'], correctAnswer: 'Rozgrzać się' },
  { id: 125, language: 'English', word: 'Wrap up', options: ['Rozpocząć', 'Kontynuować', 'Zakończyć', 'Rozpakować'], correctAnswer: 'Zakończyć' }
];
