
export interface Question {
  id: number;
  language: 'French';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'French', word: 'Avoir le cafard', options: ['Mieć karalucha', 'Czuć się przygnębionym', 'Być wesołym', 'Pić kawę'], correctAnswer: 'Czuć się przygnębionym' },
  { id: 2, language: 'French', word: 'Avoir la tête dans les nuages', options: ['Mieć głowę w chmurach', 'Myśleć o czymś innym', 'Patrzeć w niebo', 'Być realistą'], correctAnswer: 'Myśleć o czymś innym' },
  { id: 3, language: 'French', word: 'Avoir un coup de foudre', options: ['Dostać uderzenie pioruna', 'Zakochać się nagle', 'Być porażonym prądem', 'Zaskoczyć kogoś'], correctAnswer: 'Zakochać się nagle' },
  { id: 4, language: 'French', word: 'Avoir un poil dans la main', options: ['Mieć włos w dłoni', 'Być pracowitym', 'Być leniwym', 'Mieć brudne ręce'], correctAnswer: 'Być leniwym' },
  { id: 5, language: 'French', word: 'Avoir la main verte', options: ['Mieć zieloną rękę', 'Być dobrym w ogrodnictwie', 'Malować na zielono', 'Być niedoświadczonym'], correctAnswer: 'Być dobrym w ogrodnictwie' },
  { id: 6, language: 'French', word: 'Appeler un chat un chat', options: ['Nazywać kota kotem', 'Mówić wprost', 'Mówić niejasno', 'Bawić się z kotem'], correctAnswer: 'Mówić wprost' },
  { id: 7, language: 'French', word: 'Battre le fer tant qu’il est chaud', options: ['Kuć żelazo póki gorące', 'Działać od razu', 'Bić żelazo, kiedy jest gorące', 'Czekać na właściwy moment'], correctAnswer: 'Działać od razu' },
  { id: 8, language: 'French', word: 'Boire comme un trou', options: ['Pić przez dziurę', 'Pić bardzo dużo', 'Mało pić', 'Pić przez słomkę'], correctAnswer: 'Pić bardzo dużo' },
  { id: 9, language: 'French', word: 'Casser les pieds à quelqu’un', options: ['Łamać komuś stopy', 'Denerwować kogoś', 'Masować stopy', 'Pomagać komuś'], correctAnswer: 'Denerwować kogoś' },
  { id: 10, language: 'French', word: 'Ce n’est pas la mer à boire', options: ['To nie jest morze do wypicia', 'Nie jest to trudne', 'To niemożliwe', 'Pływać w morzu'], correctAnswer: 'Nie jest to trudne' },
  { id: 11, language: 'French', word: 'Chercher midi à quatorze heures', options: ['Szukać południa o czternastej', 'Szukać problemu', 'Być punktualnym', 'Spóźniać się'], correctAnswer: 'Szukać problemu' },
  { id: 12, language: 'French', word: 'Coûter les yeux de la tête', options: ['Kosztować oczy głowy', 'Być bardzo drogie', 'Mieć problemy ze wzrokiem', 'Być tanim'], correctAnswer: 'Być bardzo drogie' },
  { id: 13, language: 'French', word: 'Couper les cheveux en quatre', options: ['Ciąć włosy na czworo', 'Być pedantycznym', 'Dzielić włos na czworo', 'Iść do fryzjera'], correctAnswer: 'Być pedantycznym' },
  { id: 14, language: 'French', word: 'Devoir une fière chandelle à quelqu’un', options: ['Być komuś winnym dumną świecę', 'Być wdzięcznym', 'Pożyczyć świeczkę', 'Obrazić kogoś'], correctAnswer: 'Być wdzięcznym' },
  { id: 15, language: 'French', word: 'Donner sa langue au chat', options: ['Dać język kotu', 'Poddawać się w zgadywaniu', 'Rozmawiać z kotem', 'Milczeć'], correctAnswer: 'Poddawać się w zgadywaniu' },
  { id: 16, language: 'French', word: 'Donner un coup de main', options: ['Dać uderzenie ręką', 'Pomóc komuś', 'Uderzyć kogoś', 'Podać rękę na powitanie'], correctAnswer: 'Pomóc komuś' },
  { id: 17, language: 'French', word: 'Être dans la lune', options: ['Być na księżycu', 'Być rozkojarzonym', 'Marzyć o kosmosie', 'Być realistą'], correctAnswer: 'Być rozkojarzonym' },
  { id: 18, language: 'French', word: 'Être sur son trente-et-un', options: ['Być na swojej trzydziestce jedynce', 'Być elegancko ubranym', 'Być spóźnionym', 'Obchodzić urodziny'], correctAnswer: 'Być elegancko ubranym' },
  { id: 19, language: 'French', word: 'Faire d’une pierre deux coups', options: ['Zrobić z kamienia dwa uderzenia', 'Załatwić dwie sprawy', 'Rzucać kamieniami', 'Budować dom'], correctAnswer: 'Załatwić dwie sprawy' },
  { id: 20, language: 'French', word: 'Faire la tête', options: ['Robić głowę', 'Być obrażonym', 'Myśleć intensywnie', 'Uśmiechać się'], correctAnswer: 'Być obrażonym' },
  { id: 21, language: 'French', word: 'Faire le pont', options: ['Robić most', 'Robić długi weekend', 'Pracować w święta', 'Budować most'], correctAnswer: 'Robić długi weekend' },
  { id: 22, language: 'French', word: 'Faire la sourde oreille', options: ['Robić głuche ucho', 'Ignorować coś', 'Słuchać uważnie', 'Być głuchym'], correctAnswer: 'Ignorować coś' },
  { id: 23, language: 'French', word: 'Faire l’idiot', options: ['Robić idiotę', 'Udawać głupiego', 'Być mądrym', 'Zachowywać się poważnie'], correctAnswer: 'Udawać głupiego' },
  { id: 24, language: 'French', word: 'Faire un tabac', options: ['Robić tytoń', 'Odnieść sukces', 'Palić papierosy', 'Ponieść porażkę'], correctAnswer: 'Odnieść sukces' },
  { id: 25, language: 'French', word: 'Il pleut des cordes', options: ['Pada deszcz ze sznurków', 'Bardzo mocno pada', 'Lekko kropi', 'Jest słonecznie'], correctAnswer: 'Bardzo mocno pada' },
  { id: 26, language: 'French', word: 'Jeter l’éponge', options: ['Rzucić gąbkę', 'Poddawać się', 'Myć się', 'Kontynuować walkę'], correctAnswer: 'Poddawać się' },
  { id: 27, language: 'French', word: 'La goutte d’eau qui fait déborder le vase', options: ['Kropla wody, która przelewa wazę', 'Ostatnia kropla', 'Mały problem', 'Dużo wody'], correctAnswer: 'Ostatnia kropla' },
  { id: 28, language: 'French', word: 'Lâcher la grappe à quelqu’un', options: ['Puścić kiść winogron', 'Przestać komuś przeszkadzać', 'Przeszkadzać komuś', 'Jeść winogrona'], correctAnswer: 'Przestać komuś przeszkadzać' },
  { id: 29, language: 'French', word: 'Mettre les pieds dans le plat', options: ['Włożyć stopy do naczynia', 'Powiedzieć coś nietaktownie', 'Jeść obiad', 'Być ostrożnym'], correctAnswer: 'Powiedzieć coś nietaktownie' },
  { id: 30, language: 'French', word: 'Mettre la main à la pâte', options: ['Włożyć rękę do ciasta', 'Wziąć się do pracy', 'Gotować', 'Odpoczywać'], correctAnswer: 'Wziąć się do pracy' },
  { id: 31, language: 'French', word: 'Mettre son grain de sel', options: ['Dodać swoje ziarenko soli', 'Wtrącać się', 'Przyprawiać danie', 'Milczeć'], correctAnswer: 'Wtrącać się' },
  { id: 32, language: 'French', word: 'Ne pas être dans son assiette', options: ['Nie być na swoim talerzu', 'Czuć się źle', 'Być głodnym', 'Być w świetnej formie'], correctAnswer: 'Czuć się źle' },
  { id: 33, language: 'French', word: 'Ne pas avoir froid aux yeux', options: ['Nie mieć zimna w oczach', 'Być odważnym', 'Bać się', 'Mieć problemy ze wzrokiem'], correctAnswer: 'Być odważnym' },
  { id: 34, language: 'French', word: 'Ne pas être sorti de l’auberge', options: ['Nie wyjść z gospody', 'Nie mieć problemu zakończonego', 'Być na wakacjach', 'Dobrze się bawić'], correctAnswer: 'Nie mieć problemu zakończonego' },
  { id: 35, language: 'French', word: 'Ne pas avoir la langue dans sa poche', options: ['Nie mieć języka w kieszeni', 'Mówić otwarcie', 'Być nieśmiałym', 'Milczeć'], correctAnswer: 'Mówić otwarcie' },
  { id: 36, language: 'French', word: 'Ne pas avoir un rond', options: ['Nie mieć koła', 'Nie mieć pieniędzy', 'Być bogatym', 'Mieć dużo monet'], correctAnswer: 'Nie mieć pieniędzy' },
  { id: 37, language: 'French', word: 'Ne pas mâcher ses mots', options: ['Nie przeżuwać słów', 'Mówić bez ogródek', 'Mówić niewyraźnie', 'Milczeć'], correctAnswer: 'Mówić bez ogródek' },
  { id: 38, language: 'French', word: 'Ne pas savoir où donner de la tête', options: ['Nie wiedzieć, gdzie dać głowę', 'Być przytłoczonym', 'Odpoczywać', 'Być zrelaksowanym'], correctAnswer: 'Być przytłoczonym' },
  { id: 39, language: 'French', word: 'Ne pas tenir la route', options: ['Nie trzymać się drogi', 'Nie mieć sensu', 'Jechać ostrożnie', 'Być logicznym'], correctAnswer: 'Nie mieć sensu' },
  { id: 40, language: 'French', word: 'Passer du coq à l’âne', options: ['Przechodzić od koguta do osła', 'Przechodzić od tematu do tematu', 'Rozmawiać o zwierzętach', 'Mówić na jeden temat'], correctAnswer: 'Przechodzić od tematu do tematu' },
  { id: 41, language: 'French', word: 'Passer l’arme à gauche', options: ['Przekazać broń na lewo', 'Umrzeć', 'Poddawać się', 'Iść na wojnę'], correctAnswer: 'Umrzeć' },
  { id: 42, language: 'French', word: 'Passer sous silence', options: ['Przejść pod ciszą', 'Pominąć coś', 'Mówić głośno', 'Podkreślić coś'], correctAnswer: 'Pominąć coś' },
  { id: 43, language: 'French', word: 'Pleuvoir des cordes', options: ['Padać ze sznurków', 'Mocno padać', 'Kropić', 'Być słonecznie'], correctAnswer: 'Mocno padać' },
  { id: 44, language: 'French', word: 'Poser un lapin à quelqu’un', options: ['Położyć królika na kimś', 'Nie przyjść na spotkanie', 'Dać komuś prezent', 'Gotować królika'], correctAnswer: 'Nie przyjść na spotkanie' },
  { id: 45, language: 'French', word: 'Prendre le taureau par les cornes', options: ['Wziąć byka za rogi', 'Wziąć sprawy w swoje ręce', 'Iść na corridę', 'Unikać problemów'], correctAnswer: 'Wziąć sprawy w swoje ręce' },
  { id: 46, language: 'French', word: 'Prendre la poudre d’escampette', options: ['Wziąć proszek ucieczki', 'Uciec szybko', 'Brać lekarstwo', 'Zostać w miejscu'], correctAnswer: 'Uciec szybko' },
  { id: 47, language: 'French', word: 'Prendre son courage à deux mains', options: ['Wziąć odwagę w obie ręce', 'Zebrać odwagę', 'Być tchórzem', 'Unikać wyzwań'], correctAnswer: 'Zebrać odwagę' },
  { id: 48, language: 'French', word: 'Raconter des salades', options: ['Opowiadać o sałatkach', 'Opowiadać bzdury', 'Mówić prawdę', 'Gotować'], correctAnswer: 'Opowiadać bzdury' },
  { id: 49, language: 'French', word: 'Rentrer dans sa coquille', options: ['Wejść do swojej muszli', 'Zamknąć się w sobie', 'Być otwartym', 'Zbierać muszelki'], correctAnswer: 'Zamknąć się w sobie' },
  { id: 50, language: 'French', word: 'Se mettre sur son 31', options: ['Usiąść na swoim 31', 'Ubierać się elegancko', 'Obchodzić 31 urodziny', 'Spóźnić się'], correctAnswer: 'Ubierać się elegancko' },
  { id: 51, language: 'French', word: 'Se mettre dans de beaux draps', options: ['Położyć się w pięknej pościeli', 'Wpaść w kłopoty', 'Iść spać', 'Być w luksusie'], correctAnswer: 'Wpaść w kłopoty' },
  { id: 52, language: 'French', word: 'Se serrer la ceinture', options: ['Zaciskać pasek', 'Ograniczyć wydatki', 'Być na diecie', 'Kupować nowy pasek'], correctAnswer: 'Ograniczyć wydatki' },
  { id: 53, language: 'French', word: 'Se tirer une balle dans le pied', options: ['Strzelić sobie w stopę', 'Zaszkodzić sobie samemu', 'Iść do lekarza', 'Bawić się bronią'], correctAnswer: 'Zaszkodzić sobie samemu' },
  { id: 54, language: 'French', word: 'Tenir la chandelle', options: ['Trzymać świeczkę', 'Być niepotrzebnym świadkiem', 'Oświetlać drogę', 'Brać udział w zabawie'], correctAnswer: 'Być niepotrzebnym świadkiem' },
  { id: 55, language: 'French', word: 'Tomber dans les pommes', options: ['Wpaść w jabłka', 'Stracić przytomność', 'Zbierać jabłka', 'Jeść szarlotkę'], correctAnswer: 'Stracić przytomność' },
  { id: 56, language: 'French', word: 'Tourner autour du pot', options: ['Kręcić się wokół garnka', 'Owijać w bawełnę', 'Mówić prosto z mostu', 'Gotować zupę'], correctAnswer: 'Owijać w bawełnę' },
  { id: 57, language: 'French', word: 'Trouver chaussure à son pied', options: ['Znaleźć but na swoją stopę', 'Znaleźć coś idealnego', 'Kupować buty', 'Mieć problem ze znalezieniem butów'], correctAnswer: 'Znaleźć coś idealnego' },
  { id: 58, language: 'French', word: 'Avoir la pêche', options: ['Mieć brzoskwinię', 'Być pełnym energii', 'Jeść owoce', 'Być zmęczonym'], correctAnswer: 'Być pełnym energii' },
  { id: 59, language: 'French', word: 'Avoir du pain sur la planche', options: ['Mieć chleb na desce', 'Mieć dużo pracy', 'Kroić chleb', 'Być bezrobotnym'], correctAnswer: 'Mieć dużo pracy' },
  { id: 60, language: 'French', word: 'Avoir un chat dans la gorge', options: ['Mieć kota w gardle', 'Mieć chrypkę', 'Głaskać kota', 'Mówić głośno'], correctAnswer: 'Mieć chrypkę' },
  { id: 61, language: 'French', word: 'Avoir le coup de foudre', options: ['Dostać uderzenie pioruna', 'Zakochać się natychmiast', 'Mieć talent', 'Być szybkim'], correctAnswer: 'Zakochać się natychmiast' },
  { id: 62, language: 'French', word: 'Casser du sucre sur le dos de quelqu’un', options: ['Łamać cukier na czyichś plecach', 'Obgadywać kogoś', 'Robić masaż', 'Słodzić komuś'], correctAnswer: 'Obgadywać kogoś' },
  { id: 63, language: 'French', word: 'Chercher la petite bête', options: ['Szukać małego zwierzątka', 'Szukać problemów', 'Kochać zwierzęta', 'Być optymistą'], correctAnswer: 'Szukać problemów' },
  { id: 64, language: 'French', word: 'Coûter un bras', options: ['Kosztować ramię', 'Kosztować bardzo dużo', 'Mieć ból ręki', 'Być tanim'], correctAnswer: 'Kosztować bardzo dużo' },
  { id: 65, language: 'French', word: 'Donner du fil à retordre', options: ['Dać nić do skręcania', 'Sprawiać trudności', 'Szyć', 'Pomagać'], correctAnswer: 'Sprawiać trudności' },
  { id: 66, language: 'French', word: 'En faire tout un fromage', options: ['Zrobić z tego cały ser', 'Robić problem z niczego', 'Produkować ser', 'Jeść fondue'], correctAnswer: 'Robić problem z niczego' },
  { id: 67, language: 'French', word: 'Être au bout du rouleau', options: ['Być na końcu rolki', 'Być wykończonym', 'Zaczynać od nowa', 'Mieć dużo energii'], correctAnswer: 'Być wykończonym' },
  { id: 68, language: 'French', word: 'Être dans de beaux draps', options: ['Być w pięknej pościeli', 'Mieć poważne problemy', 'Iść spać', 'Luksusowo żyć'], correctAnswer: 'Mieć poważne problemy' },
  { id: 69, language: 'French', word: 'Être dans les nuages', options: ['Być w chmurach', 'Być roztargnionym', 'Latać', 'Patrzeć w niebo'], correctAnswer: 'Być roztargnionym' },
  { id: 70, language: 'French', word: 'Être sur les rotules', options: ['Być na rzepkach', 'Być bardzo zmęczonym', 'Klęczeć', 'Modlić się'], correctAnswer: 'Być bardzo zmęczonym' },
  { id: 71, language: 'French', word: 'Faire chou blanc', options: ['Zrobić białą kapustę', 'Nie odnieść sukcesu', 'Gotować kapustę', 'Odnieść sukces'], correctAnswer: 'Nie odnieść sukcesu' },
  { id: 72, language: 'French', word: 'Faire l’autruche', options: ['Robić strusia', 'Ignorować problem', 'Być odważnym', 'Patrzeć na ptaki'], correctAnswer: 'Ignorować problem' },
  { id: 73, language: 'French', word: 'Il n’y a pas de fumée sans feu', options: ['Nie ma dymu bez ognia', 'W każdej plotce jest ziarno prawdy', 'Palić ognisko', 'Gasić pożar'], correctAnswer: 'W każdej plotce jest ziarno prawdy' },
  { id: 74, language: 'French', word: 'Jeter l’argent par les fenêtres', options: ['Wyrzucać pieniądze przez okna', 'Marnować pieniądze', 'Oszczędzać', 'Inwestować'], correctAnswer: 'Marnować pieniądze' },
  { id: 75, language: 'French', word: 'La moutarde me monte au nez', options: ['Musztarda podchodzi mi do nosa', 'Wkurzyć się', 'Jeść hot-doga', 'Być spokojnym'], correctAnswer: 'Wkurzyć się' },
  { id: 76, language: 'French', word: 'Les carottes sont cuites', options: ['Marchewki są ugotowane', 'Sprawy są stracone', 'Gotować obiad', 'Wszystko jest gotowe'], correctAnswer: 'Sprawy są stracone' },
  { id: 77, language: 'French', word: 'Mettre la charrue avant les bœufs', options: ['Stawiać pług przed wołami', 'Działać w złej kolejności', 'Pracować na roli', 'Być dobrze zorganizowanym'], correctAnswer: 'Działać w złej kolejności' },
  { id: 78, language: 'French', word: 'Mettre les bouchées doubles', options: ['Kłaść podwójne kęsy', 'Przyspieszyć wysiłki', 'Jeść bardzo szybko', 'Odpoczywać'], correctAnswer: 'Przyspieszyć wysiłki' },
  { id: 79, language: 'French', word: 'Monter sur ses grands chevaux', options: ['Wsiadać na swoje wielkie konie', 'Obrazić się', 'Jeździć konno', 'Być spokojnym'], correctAnswer: 'Obrazić się' },
  { id: 80, language: 'French', word: 'Ne pas casser trois pattes à un canard', options: ['Nie złamać kaczce trzech nóg', 'Nic specjalnego', 'Być okrutnym dla zwierząt', 'Być wyjątkowym'], correctAnswer: 'Nic specjalnego' },
  { id: 81, language: 'French', word: 'Ne pas être né de la dernière pluie', options: ['Nie urodzić się z ostatniego deszczu', 'Być doświadczonym', 'Być młodym', 'Latać w deszczu'], correctAnswer: 'Być doświadczonym' },
  { id: 82, language: 'French', word: 'Ne pas avoir la tête sur les épaules', options: ['Nie mieć głowy na ramionach', 'Nie myśleć racjonalnie', 'Być rozsądnym', 'Mieć ból głowy'], correctAnswer: 'Nie myśleć racjonalnie' },
  { id: 83, language: 'French', word: 'Prendre quelqu’un la main dans le sac', options: ['Złapać kogoś z ręką w torbie', 'Przyłapać kogoś', 'Pomagać w zakupach', 'Okraść kogoś'], correctAnswer: 'Przyłapać kogoś' },
  { id: 84, language: 'French', word: 'Rentrer bredouille', options: ['Wrócić z pustymi rękami', 'Nie odnieść sukcesu', 'Wrócić z niczym', 'Wrócić z zakupami'], correctAnswer: 'Nie odnieść sukcesu' },
  { id: 85, language: 'French', word: 'Se creuser la tête', options: ['Drapać się po głowie', 'Intensywnie myśleć', 'Mieć ból głowy', 'Odpoczywać'], correctAnswer: 'Intensywnie myśleć' },
  { id: 86, language: 'French', word: 'Se mettre dans la peau de quelqu’un', options: ['Wejść w czyjąś skórę', 'Wczuć się w kogoś', 'Przebierać się', 'Krytykować kogoś'], correctAnswer: 'Wczuć się w kogoś' },
  { id: 87, language: 'French', word: 'Se mettre sur la sellette', options: ['Usiąść na stołku', 'Być w trudnej sytuacji', 'Być sądzonym', 'Odpoczywać'], correctAnswer: 'Być w trudnej sytuacji' },
  { id: 88, language: 'French', word: 'Tirer les vers du nez', options: ['Wyciągać robaki z nosa', 'Wyciągnąć informacje', 'Być chorym', 'Kłamać'], correctAnswer: 'Wyciągnąć informacje' },
  { id: 89, language: 'French', word: 'Tomber sur un os', options: ['Upaść na kość', 'Napotkać trudność', 'Jeść zupę', 'Złamać nogę'], correctAnswer: 'Napotkać trudność' },
  { id: 90, language: 'French', word: 'Tourner la page', options: ['Przewrócić stronę', 'Zapomnieć o przeszłości', 'Czytać książkę', 'Pisać list'], correctAnswer: 'Zapomnieć o przeszłości' },
  { id: 91, language: 'French', word: 'Tourner autour du pot', options: ['Kręcić się wokół garnka', 'Omijać temat', 'Mówić prosto z mostu', 'Gotować zupę'], correctAnswer: 'Omijać temat' },
  { id: 92, language: 'French', word: 'Tuer le temps', options: ['Zabić czas czymś', 'Zabić czas', 'Pracować', 'Spieszyć się'], correctAnswer: 'Zabić czas czymś' },
  { id: 93, language: 'French', word: 'Vendre la mèche', options: ['Sprzedać knot', 'Wyjawić sekret', 'Sprzedawać świeczki', 'Oszukiwać'], correctAnswer: 'Wyjawić sekret' },
  { id: 94, language: 'French', word: 'Voler dans les plumes', options: ['Latać w piórach', 'Ataki słowne', 'Latać jak ptak', 'Być miłym'], correctAnswer: 'Ataki słowne' },
  { id: 95, language: 'French', word: 'Vouloir le beurre et l’argent du beurre', options: ['Chcieć masła i pieniędzy za masło', 'Chcieć wszystkiego', 'Być chciwym', 'Robić zakupy'], correctAnswer: 'Chcieć wszystkiego' },
  { id: 96, language: 'French', word: 'Faire la pluie et le beau temps', options: ['Robić deszcz i ładną pogodę', 'Kontrolować sytuację', 'Prognozować pogodę', 'Być niezdecydowanym'], correctAnswer: 'Kontrolować sytuację' },
  { id: 97, language: 'French', word: 'En avoir ras le bol', options: ['Mieć czegoś dość', 'Mieć pełną miskę', 'Być najedzonym', 'Być szczęśliwym'], correctAnswer: 'Mieć czegoś dość' },
  { id: 98, language: 'French', word: 'Être comme un poisson dans l’eau', options: ['Być jak ryba w wodzie', 'Czuć się komfortowo', 'Pływać', 'Być mokrym'], correctAnswer: 'Czuć się komfortowo' },
  { id: 99, language: 'French', word: 'Avoir la tête sur les épaules', options: ['Mieć głowę na ramionach', 'Myśleć rozsądnie', 'Być wysokim', 'Mieć ból głowy'], correctAnswer: 'Myśleć rozsądnie' },
  { id: 100, language: 'French', word: 'Mettre de l’eau dans son vin', options: ['Dolać wody do wina', 'Iść na kompromis', 'Pić wino z wodą', 'Być nieugiętym'], correctAnswer: 'Iść na kompromis' },
  { id: 101, language: 'French', word: 'Sauter du coq à l’âne', options: ['Skakać z koguta na osła', 'Przechodzić od tematu do tematu', 'Rozmawiać o zwierzętach', 'Mówić na jeden temat'], correctAnswer: 'Przechodzić od tematu do tematu' },
  { id: 102, language: 'French', word: 'Avoir la gueule de bois', options: ['Mieć drewnianą twarz', 'Mieć kaca', 'Być smutnym', 'Mieć zły smak w ustach'], correctAnswer: 'Mieć kaca' },
  { id: 103, language: 'French', word: 'Faire les yeux doux', options: ['Robić słodkie oczy', 'Spojrzeć zalotnie', 'Mieć problemy ze wzrokiem', 'Być smutnym'], correctAnswer: 'Spojrzeć zalotnie' },
  { id: 104, language: 'French', word: 'Ne pas se laisser abattre', options: ['Nie dać się powalić', 'Nie poddawać się', 'Walczyć', 'Być smutnym'], correctAnswer: 'Nie poddawać się' },
  { id: 105, language: 'French', word: 'Avoir le cœur sur la main', options: ['Mieć serce na dłoni', 'Być bardzo hojny', 'Być zakochanym', 'Mieć problemy z sercem'], correctAnswer: 'Być bardzo hojny' },
  { id: 106, language: 'French', word: 'Tenir le coup', options: ['Trzymać uderzenie', 'Wytrzymać trudności', 'Poddawać się', 'Być silnym fizycznie'], correctAnswer: 'Wytrzymać trudności' },
  { id: 107, language: 'French', word: 'Mettre la main au portefeuille', options: ['Włożyć rękę do portfela', 'Zapłacić za coś', 'Kraść pieniądze', 'Oszczędzać'], correctAnswer: 'Zapłacić za coś' },
  { id: 108, language: 'French', word: 'Avoir la tête comme une pastèque', options: ['Mieć głowę jak arbuz', 'Mieć duży ból głowy', 'Jeść arbuza', 'Być głupim'], correctAnswer: 'Mieć duży ból głowy' },
  { id: 109, language: 'French', word: 'Se faire des cheveux blancs', options: ['Robić sobie białe włosy', 'Martwić się', 'Siwieć', 'Farbować włosy'], correctAnswer: 'Martwić się' },
  { id: 110, language: 'French', word: 'Être dans la panade', options: ['Być w panierce', 'Być w tarapatach', 'Gotować', 'Być brudnym'], correctAnswer: 'Być w tarapatach' },
  { id: 111, language: 'French', word: 'Rester bouche bée', options: ['Pozostać z otwartymi ustami', 'Być bardzo zaskoczonym', 'Milczeć', 'Ziewać'], correctAnswer: 'Być bardzo zaskoczonym' },
  { id: 112, language: 'French', word: 'Avoir les yeux plus gros que le ventre', options: ['Mieć oczy większe niż brzuch', 'Brać za dużo', 'Być głodnym', 'Mieć duże oczy'], correctAnswer: 'Brać za dużo' },
  { id: 113, language: 'French', word: 'Avoir plusieurs cordes à son arc', options: ['Mieć kilka strun w swoim łuku', 'Mieć różne możliwości', 'Być łucznikiem', 'Mieć wiele opcji'], correctAnswer: 'Mieć różne możliwości' },
  { id: 114, language: 'French', word: 'Faire chou gras', options: ['Robić tłustą kapustę', 'Odnieść sukces lub korzyść', 'Dobrze zjeść', 'Gotować bigos'], correctAnswer: 'Odnieść sukces lub korzyść' },
  { id: 115, language: 'French', word: 'Être aux anges', options: ['Być u aniołów', 'Być bardzo szczęśliwym', 'Być w niebie (po śmierci)', 'Modlić się'], correctAnswer: 'Być bardzo szczęśliwym' },
  { id: 116, language: 'French', word: 'Monter sur le podium', options: ['Wejść na podium', 'Zająć wysokie miejsce', 'Osiągnąć sukces', 'Wygrać zawody'], correctAnswer: 'Zająć wysokie miejsce' },
  { id: 117, language: 'French', word: 'Avoir une faim de loup', options: ['Mieć głód wilka', 'Być bardzo głodnym', 'Polować na wilki', 'Jeść mięso'], correctAnswer: 'Być bardzo głodnym' },
  { id: 118, language: 'French', word: 'Tomber dans le panneau', options: ['Wpaść w panel', 'Dać się oszukać', 'Uderzyć w znak', 'Zgubić drogę'], correctAnswer: 'Dać się oszukać' },
  { id: 119, language: 'French', word: 'Se mettre la rate au court-bouillon', options: ['Włożyć śledzionę do bulionu', 'Denerwować się', 'Gotować zupę', 'Być chorym'], correctAnswer: 'Denerwować się' },
  { id: 120, language: 'French', word: 'Prendre la clé des champs', options: ['Wziąć klucz do pól', 'Uciec, wyjechać', 'Iść na spacer', 'Otworzyć bramę'], correctAnswer: 'Uciec, wyjechać' },
  { id: 121, language: 'French', word: 'Tenir la route', options: ['Trzymać się drogi', 'Być solidnym, przekonywującym', 'Prowadzić samochód', 'Być silnym'], correctAnswer: 'Być solidnym, przekonywującym' },
  { id: 122, language: 'French', word: 'Avoir le bras long', options: ['Mieć długie ramię', 'Mieć wpływy', 'Być wysokim', 'Sięgać daleko'], correctAnswer: 'Mieć wpływy' },
  { id: 123, language: 'French', word: 'Avoir voix au chapitre', options: ['Mieć głos w kapitule', 'Mieć prawo do decyzji', 'Śpiewać w chórze', 'Być ważnym'], correctAnswer: 'Mieć prawo do decyzji' },
  { id: 124, language: 'French', word: 'Casser la baraque', options: ['Zniszczyć budę', 'Odnieść wielki sukces', 'Zrobić demolkę', 'Być głośno'], correctAnswer: 'Odnieść wielki sukces' },
  { id: 125, language: 'French', word: 'Mettre les voiles', options: ['Postawić żagle', 'Wyjechać, odejść', 'Żeglować', 'Szykować się do podróży'], correctAnswer: 'Wyjechać, odejść' },
  { id: 126, language: 'French', word: 'Faire feu de tout bois', options: ['Robić ogień z każdego drewna', 'Wykorzystać wszystkie możliwości', 'Palić w kominku', 'Być zdesperowanym'], correctAnswer: 'Wykorzystać wszystkie możliwości' }
];

