export interface Question {
  id: number;
  language: 'Polish';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'Polish', word: 'Cześć', options: ['Goodbye', 'Hello', 'Thank you', 'Sorry'], correctAnswer: 'Hello' },
  { id: 2, language: 'Polish', word: 'Do widzenia', options: ['Hello', 'Good morning', 'Good night', 'Goodbye'], correctAnswer: 'Goodbye' },
  { id: 3, language: 'Polish', word: 'Dziękuję', options: ['Please', 'You\'re welcome', 'Thank you', 'Sorry'], correctAnswer: 'Thank you' },
  { id: 4, language: 'Polish', word: 'Tak', options: ['Yes', 'No', 'Maybe', 'Always'], correctAnswer: 'Yes' },
  { id: 5, language: 'Polish', word: 'Nie', options: ['Good', 'Never', 'Why', 'No'], correctAnswer: 'No' },
  { id: 6, language: 'Polish', word: 'Mężczyzna', options: ['Woman', 'Man', 'Child', 'Person'], correctAnswer: 'Man' },
  { id: 7, language: 'Polish', word: 'Kobieta', options: ['Man', 'Girl', 'Woman', 'Boy'], correctAnswer: 'Woman' },
  { id: 8, language: 'Polish', word: 'Jeść', options: ['To drink', 'To sleep', 'To eat', 'To run'], correctAnswer: 'To eat' },
  { id: 9, language: 'Polish', word: 'Woda', options: ['Fire', 'Water', 'Earth', 'Air'], correctAnswer: 'Water' },
  { id: 10, language: 'Polish', word: 'Kot', options: ['Dog', 'Bird', 'Fish', 'Cat'], correctAnswer: 'Cat' },
  { id: 11, language: 'Polish', word: 'Pies', options: ['Cat', 'Dog', 'Lion', 'Tiger'], correctAnswer: 'Dog' },
  { id: 12, language: 'Polish', word: 'Dom', options: ['Car', 'School', 'House', 'Shop'], correctAnswer: 'House' },
  { id: 13, language: 'Polish', word: 'Samochód', options: ['Bicycle', 'Train', 'Bus', 'Car'], correctAnswer: 'Car' },
  { id: 14, language: 'Polish', word: 'Szkoła', options: ['Hospital', 'School', 'University', 'Library'], correctAnswer: 'School' },
  { id: 15, language: 'Polish', word: 'Książka', options: ['Movie', 'Song', 'Book', 'Painting'], correctAnswer: 'Book' },
  { id: 16, language: 'Polish', word: 'Słońce', options: ['Moon', 'Star', 'Sun', 'Cloud'], correctAnswer: 'Sun' },
  { id: 17, language: 'Polish', word: 'Księżyc', options: ['Sun', 'Planet', 'Moon', 'Comet'], correctAnswer: 'Moon' },
  { id: 18, language: 'Polish', word: 'Miłość', options: ['Hate', 'Joy', 'Sadness', 'Love'], correctAnswer: 'Love' },
  { id: 19, language: 'Polish', word: 'Przyjaciel', options: ['Enemy', 'Neighbor', 'Friend', 'Family'], correctAnswer: 'Friend' },
  { id: 20, language: 'Polish', word: 'Rodzina', options: ['Friends', 'Family', 'Relatives', 'Neighbors'], correctAnswer: 'Family' },
  { id: 21, language: 'Polish', word: 'Rano', options: ['Evening', 'Night', 'Afternoon', 'Morning'], correctAnswer: 'Morning' },
  { id: 22, language: 'Polish', word: 'Noc', options: ['Day', 'Night', 'Dusk', 'Dawn'], correctAnswer: 'Night' },
  { id: 23, language: 'Polish', word: 'Dzień', options: ['Week', 'Month', 'Year', 'Day'], correctAnswer: 'Day' },
  { id: 24, language: 'Polish', word: 'Tydzień', options: ['Day', 'Week', 'Weekend', 'Month'], correctAnswer: 'Week' },
  { id: 25, language: 'Polish', word: 'Miesiąc', options: ['Year', 'Century', 'Decade', 'Month'], correctAnswer: 'Month' },
  { id: 26, language: 'Polish', word: 'Rok', options: ['Month', 'Year', 'Day', 'Hour'], correctAnswer: 'Year' },
  { id: 27, language: 'Polish', word: 'Dzisiaj', options: ['Yesterday', 'Tomorrow', 'Today', 'The day after tomorrow'], correctAnswer: 'Today' },
  { id: 28, language: 'Polish', word: 'Jutro', options: ['Today', 'Yesterday', 'The day before yesterday', 'Tomorrow'], correctAnswer: 'Tomorrow' },
  { id: 29, language: 'Polish', word: 'Proszę', options: ['Thank you', 'Please', 'Sorry', 'You\'re welcome'], correctAnswer: 'Please' },
  { id: 30, language: 'Polish', word: 'Jabłko', options: ['Banana', 'Orange', 'Apple', 'Pear'], correctAnswer: 'Apple' },
  { id: 31, language: 'Polish', word: 'Osiągać', options: ['To lose', 'To achieve', 'To avoid', 'To give up'], correctAnswer: 'To achieve' },
  { id: 32, language: 'Polish', word: 'Środowisko', options: ['City', 'Nature', 'Building', 'Environment'], correctAnswer: 'Environment' },
  { id: 33, language: 'Polish', word: 'Poprawiać', options: ['To worsen', 'To improve', 'To destroy', 'To leave'], correctAnswer: 'To improve' },
  { id: 34, language: 'Polish', word: 'Okazja', options: ['Problem', 'Obstacle', 'Opportunity', 'Risk'], correctAnswer: 'Opportunity' },
  { id: 35, language: 'Polish', word: 'Ciekawy', options: ['Indifferent', 'Bored', 'Curious', 'Sad'], correctAnswer: 'Curious' },
  { id: 36, language: 'Polish', word: 'Wydajny', options: ['Slow', 'Efficient', 'Lazy', 'Ineffective'], correctAnswer: 'Efficient' },
  { id: 37, language: 'Polish', word: 'Wyczerpany', options: ['Rested', 'Energetic', 'Exhausted', 'Strong'], correctAnswer: 'Exhausted' },
  { id: 38, language: 'Polish', word: 'Negocjować', options: ['To argue', 'To negotiate', 'To discuss', 'To agree'], correctAnswer: 'To negotiate' },
  { id: 39, language: 'Polish', word: 'Niezawodny', options: ['Reliable', 'Uncertain', 'Risky', 'Variable'], correctAnswer: 'Reliable' },
  { id: 40, language: 'Polish', word: 'Wyrafinowany', options: ['Simple', 'Primitive', 'Sophisticated', 'Common'], correctAnswer: 'Sophisticated' },
  { id: 41, language: 'Polish', word: 'Dwuznaczny', options: ['Clear', 'Specific', 'Unambiguous', 'Ambiguous'], correctAnswer: 'Ambiguous' },
  { id: 42, language: 'Polish', word: 'Sumienny', options: ['Careless', 'Lazy', 'Conscientious', 'Superficial'], correctAnswer: 'Conscientious' },
  { id: 43, language: 'Polish', word: 'Przedsiębiorca', options: ['Employee', 'Entrepreneur', 'Artist', 'Scientist'], correctAnswer: 'Entrepreneur' },
  { id: 44, language: 'Polish', word: 'Odporny', options: ['Vulnerable', 'Weak', 'Resilient', 'Sensitive'], correctAnswer: 'Resilient' },
  { id: 45, language: 'Polish', word: 'Wszechobecny', options: ['Rare', 'Unique', 'Ubiquitous', 'Invisible'], correctAnswer: 'Ubiquitous' },
  { id: 46, language: 'Polish', word: 'Odpowiedzialność', options: ['Impunity', 'Accountability', 'Chaos', 'Fun'], correctAnswer: 'Accountability' },
  { id: 47, language: 'Polish', word: 'Skrupulatny', options: ['Inaccurate', 'Chaotic', 'Meticulous', 'Quick'], correctAnswer: 'Meticulous' },
  { id: 48, language: 'Polish', word: 'Odkładać na później', options: ['To act immediately', 'To plan', 'To procrastinate', 'To finish early'], correctAnswer: 'To procrastinate' },
  { id: 49, language: 'Polish', word: 'Zbędny', options: ['Essential', 'Necessary', 'Important', 'Superfluous'], correctAnswer: 'Superfluous' },
  { id: 50, language: 'Polish', word: 'Wszechstronny', options: ['Limited', 'One-sided', 'Versatile', 'Specialized'], correctAnswer: 'Versatile' },
  { id: 51, language: 'Polish', word: 'Osiągnąć', options: ['To fail', 'To accomplish', 'To quit', 'To try'], correctAnswer: 'To accomplish' },
  { id: 52, language: 'Polish', word: 'Korzyść', options: ['Damage', 'Disadvantage', 'Benefit', 'Loss'], correctAnswer: 'Benefit' },
  { id: 53, language: 'Polish', word: 'Kluczowy', options: ['Irrelevant', 'Crucial', 'Additional', 'Optional'], correctAnswer: 'Crucial' },
  { id: 54, language: 'Polish', word: 'Pilny', options: ['Lazy', 'Diligent', 'Careless', 'Indifferent'], correctAnswer: 'Diligent' },
  { id: 55, language: 'Polish', word: 'Ulepszyć', options: ['To worsen', 'To enhance', 'To destroy', 'To weaken'], correctAnswer: 'To enhance' },
  { id: 56, language: 'Polish', word: 'Elastyczny', options: ['Stiff', 'Flexible', 'Unchanging', 'Constant'], correctAnswer: 'Flexible' },
  { id: 57, language: 'Polish', word: 'Generować', options: ['To destroy', 'To generate', 'To consume', 'To stop'], correctAnswer: 'To generate' },
  { id: 58, language: 'Polish', word: 'Wahać się', options: ['To be sure', 'To hesitate', 'To decide', 'To act'], correctAnswer: 'To hesitate' },
  { id: 59, language: 'Polish', word: 'Wdrożyć', options: ['To ignore', 'To implement', 'To plan', 'To reject'], correctAnswer: 'To implement' },
  { id: 60, language: 'Polish', word: 'Uzasadnić', options: ['To accuse', 'To justify', 'To deny', 'To doubt'], correctAnswer: 'To justify' },
  { id: 61, language: 'Polish', word: 'Wiedza', options: ['Stupidity', 'Knowledge', 'Ignorance', 'Emptiness'], correctAnswer: 'Knowledge' },
  { id: 62, language: 'Polish', word: 'Prawowity', options: ['Illegal', 'Legitimate', 'False', 'Questionable'], correctAnswer: 'Legitimate' },
  { id: 63, language: 'Polish', word: 'Utrzymać', options: ['To destroy', 'To maintain', 'To neglect', 'To change'], correctAnswer: 'To maintain' },
  { id: 64, language: 'Polish', word: 'Wytrwać', options: ['To give up', 'To persevere', 'To quit', 'To doubt'], correctAnswer: 'To persevere' },
  { id: 65, language: 'Polish', word: 'Odporny', options: ['Sensitive', 'Resilient', 'Weak', 'Vulnerable'], correctAnswer: 'Resilient' },
  { id: 66, language: 'Polish', word: 'Znaczący', options: ['Trivial', 'Significant', 'Small', 'Irrelevant'], correctAnswer: 'Significant' },
  { id: 67, language: 'Polish', word: 'Tolerować', options: ['To accept', 'To tolerate', 'To reject', 'To condemn'], correctAnswer: 'To tolerate' },
  { id: 68, language: 'Polish', word: 'Unikalny', options: ['Common', 'Unique', 'Ordinary', 'Typical'], correctAnswer: 'Unique' },
  { id: 69, language: 'Polish', word: 'Weryfikować', options: ['To guess', 'To verify', 'To falsify', 'To ignore'], correctAnswer: 'To verify' },
  { id: 70, language: 'Polish', word: 'Rozpowszechniony', options: ['Local', 'Widespread', 'Limited', 'Rare'], correctAnswer: 'Widespread' },
  { id: 71, language: 'Polish', word: 'Ulegać', options: ['To fight', 'To yield', 'To resist', 'To take'], correctAnswer: 'To yield' },
  { id: 72, language: 'Polish', word: 'Gorliwy', options: ['Apathetic', 'Zealous', 'Indifferent', 'Lazy'], correctAnswer: 'Zealous' },
  { id: 73, language: 'Polish', word: 'Obfity', options: ['Scarce', 'Abundant', 'Lacking', 'Minimal'], correctAnswer: 'Abundant' },
  { id: 74, language: 'Polish', word: 'Wzmacniać', options: ['To weaken', 'To bolster', 'To undermine', 'To destroy'], correctAnswer: 'To bolster' },
  { id: 75, language: 'Polish', word: 'Szczery', options: ['Insincere', 'Candid', 'Hidden', 'Complicated'], correctAnswer: 'Candid' },
  { id: 76, language: 'Polish', word: 'Zbaczać', options: ['To stay on course', 'To deviate', 'To follow', 'To imitate'], correctAnswer: 'To deviate' },
  { id: 77, language: 'Polish', word: 'Wybitny', options: ['Unknown', 'Eminent', 'Ordinary', 'Average'], correctAnswer: 'Eminent' },
  { id: 78, language: 'Polish', word: 'Wykonalny', options: ['Impossible', 'Feasible', 'Difficult', 'Impractical'], correctAnswer: 'Feasible' },
  { id: 79, language: 'Polish', word: 'Towarzyski', options: ['Solitary', 'Gregarious', 'Shy', 'Introverted'], correctAnswer: 'Gregarious' },
  { id: 80, language: 'Polish', word: 'Utrudniać', options: ['To help', 'To hinder', 'To support', 'To facilitate'], correctAnswer: 'To hinder' },
  { id: 81, language: 'Polish', word: 'Nieunikniony', options: ['Avoidable', 'Inevitable', 'Uncertain', 'Accidental'], correctAnswer: 'Inevitable' },
  { id: 82, language: 'Polish', word: 'Zestawiać', options: ['To separate', 'To juxtapose', 'To mix', 'To hide'], correctAnswer: 'To juxtapose' },
  { id: 83, language: 'Polish', word: 'Bystry', options: ['Dull', 'Indifferent', 'Keen', 'Uninterested'], correctAnswer: 'Keen' },
  { id: 84, language: 'Polish', word: 'Przejrzysty', options: ['Cloudy', 'Lucid', 'Vague', 'Complicated'], correctAnswer: 'Lucid' },
  { id: 85, language: 'Polish', word: 'Niezliczony', options: ['A handful', 'Myriad', 'A few', 'Limited number'], correctAnswer: 'Myriad' },
  { id: 86, language: 'Polish', word: 'Nowicjusz', options: ['Expert', 'Novice', 'Veteran', 'Master'], correctAnswer: 'Novice' },
  { id: 87, language: 'Polish', word: 'Pominąć', options: ['To add', 'To omit', 'To include', 'To emphasize'], correctAnswer: 'To omit' },
  { id: 88, language: 'Polish', word: 'Rozważać', options: ['To act impulsively', 'To ponder', 'To ignore', 'To forget'], correctAnswer: 'To ponder' },
  { id: 89, language: 'Polish', word: 'Kwintesencjonalny', options: ['Atypical', 'Quintessential', 'Aberrant', 'Rare'], correctAnswer: 'Quintessential' },
  { id: 90, language: 'Polish', word: 'Obalić', options: ['To confirm', 'To refute', 'To agree', 'To prove'], correctAnswer: 'To refute' },
  { id: 91, language: 'Polish', word: 'Badać szczegółowo', options: ['To glance over', 'To scrutinize', 'To ignore', 'To accept uncritically'], correctAnswer: 'To scrutinize' },
  { id: 92, language: 'Polish', word: 'Niepewny', options: ['Final', 'Tentative', 'Certain', 'Decisive'], correctAnswer: 'Tentative' },
  { id: 93, language: 'Polish', word: 'Podkopywać', options: ['To strengthen', 'To undermine', 'To support', 'To build'], correctAnswer: 'To undermine' },
  { id: 94, language: 'Polish', word: 'Wyrazisty', options: ['Pale', 'Vivid', 'Dull', 'Matte'], correctAnswer: 'Vivid' },
  { id: 95, language: 'Polish', word: 'Kapryśny', options: ['Serious', 'Whimsical', 'Predictable', 'Logical'], correctAnswer: 'Whimsical' },
  { id: 96, language: 'Polish', word: 'Wzorowy', options: ['Average', 'Exemplary', 'Bad', 'Insufficient'], correctAnswer: 'Exemplary' },
  { id: 97, language: 'Polish', word: 'Tęsknić', options: ['To be indifferent', 'To yearn', 'To hate', 'To avoid'], correctAnswer: 'To yearn' },
  { id: 98, language: 'Polish', word: 'Entuzjazm', options: ['Apathy', 'Zest', 'Sadness', 'Boredom'], correctAnswer: 'Zest' },
  { id: 99, language: 'Polish', word: 'Pragmatyczny', options: ['Idealistic', 'Pragmatic', 'Theoretical', 'Unrealistic'], correctAnswer: 'Pragmatic' },
  { id: 100, language: 'Polish', word: 'Wymowny', options: ['Inarticulate', 'Eloquent', 'Silent', 'Simple'], correctAnswer: 'Eloquent' },
];
