
export interface Question {
  id: number;
  language: 'English';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'English', word: 'Ask out', options: ['Zapytać o drogę', 'Poprosić o wyjście', 'Zaprośić kogoś na randkę', 'Wypytać kogoś'], correctAnswer: 'Zaprośić kogoś na randkę' },
  { id: 2, language: 'English', word: 'Back up', options: ['Cofnąć się', 'Wrócić', 'Poprzeć / Zrobić kopię zapasową', 'Zrezygnować'], correctAnswer: 'Poprzeć / Zrobić kopię zapasową' },
  { id: 3, language: 'English', word: 'Blow up', options: ['Nadmuchać', 'Powiększyć', 'Zdmuchnąć', 'Wybuchnąć / Zdenerwować się'], correctAnswer: 'Wybuchnąć / Zdenerwować się' },
  { id: 4, language: 'English', word: 'Break down', options: ['Przełamać', 'Zniszczyć', 'Zepsuć się / Załamać się', 'Rozbić'], correctAnswer: 'Zepsuć się / Załamać się' },
  { id: 5, language: 'English', word: 'Break up', options: ['Zepsuć się', 'Przerwać', 'Złamać', 'Rozstać się'], correctAnswer: 'Rozstać się' },
  { id: 6, language: 'English', word: 'Bring up', options: ['Przynieść na górę', 'Podnieść', 'Poruszyć temat / Wychować', 'Zwrócić'], correctAnswer: 'Poruszyć temat / Wychować' },
  { id: 7, language: 'English', word: 'Call back', options: ['Odwołać', 'Zadzwonić później', 'Przedzwonić', 'Oddzwonić'], correctAnswer: 'Oddzwonić' },
  { id: 8, language: 'English', word: 'Call off', options: ['Zadzwonić', 'Odwołać', 'Wyłączyć', 'Przełożyć'], correctAnswer: 'Odwołać' },
  { id: 9, language: 'English', word: 'Carry on', options: ['Nieść dalej', 'Kontynuować', 'Przewozić', 'Zachowywać się'], correctAnswer: 'Kontynuować' },
  { id: 10, language: 'English', word: 'Catch up', options: ['Złapać', 'Dogonić', 'Nadrobić zaległości', 'Spotkać się'], correctAnswer: 'Nadrobić zaległości' },
  { id: 11, language: 'English', word: 'Check in', options: ['Sprawdzić', 'Zameldować się / Dać znać', 'Zapłacić', 'Wypisać się'], correctAnswer: 'Zameldować się / Dać znać' },
  { id: 12, language: 'English', word: 'Check out', options: ['Sprawdzić', 'Przejrzeć', 'Opłacić rachunek', 'Wymeldować się / Sprawdzić'], correctAnswer: 'Wymeldować się / Sprawdzić' },
  { id: 13, language: 'English', word: 'Come across', options: ['Przejść przez', 'Natknąć się', 'Spotkać', 'Znaleźć'], correctAnswer: 'Natknąć się' },
  { id: 14, language: 'English', word: 'Come back', options: ['Odejść', 'Wrócić', 'Przyjść', 'Odwiedzić'], correctAnswer: 'Wrócić' },
  { id: 15, language: 'English', word: 'Come in', options: ['Wyjść', 'Wejść', 'Wrócić', 'Odejść'], correctAnswer: 'Wejść' },
  { id: 16, language: 'English', word: 'Come out', options: ['Wejść', 'Wrócić', 'Wyjść / Ukazać się', 'Zostać'], correctAnswer: 'Wyjść / Ukazać się' },
  { id: 17, language: 'English', word: 'Come over', options: ['Przejść przez', 'Przejechać', 'Odwiedzić', 'Wpaść z wizytą'], correctAnswer: 'Wpaść z wizytą' },
  { id: 18, language: 'English', word: 'Cut down', options: ['Ściąć', 'Przeciąć', 'Ograniczyć', 'Zmniejszyć'], correctAnswer: 'Ograniczyć' },
  { id: 19, language: 'English', word: 'Cut off', options: ['Odciąć / Przerwać', 'Wyciąć', 'Obciąć', 'Skrócić'], correctAnswer: 'Odciąć / Przerwać' },
  { id: 20, language: 'English', word: 'Deal with', options: ['Handlować czymś', 'Radzić sobie z czymś', 'Unikać czegoś', 'Zajmować się'], correctAnswer: 'Radzić sobie z czymś' },
  { id: 21, language: 'English', word: 'Drop by', options: ['Upuścić coś', 'Wpaść na chwilę', 'Zrezygnować', 'Przejść obok'], correctAnswer: 'Wpaść na chwilę' },
  { id: 22, language: 'English', word: 'Drop off', options: ['Odpaść', 'Podrzucić / Zasnąć', 'Upuścić', 'Wysiąść'], correctAnswer: 'Podrzucić / Zasnąć' },
  { id: 23, language: 'English', word: 'Figure out', options: ['Rysować postać', 'Liczyć', 'Zrozumieć / Rozgryźć', 'Wyobrazić sobie'], correctAnswer: 'Zrozumieć / Rozgryźć' },
  { id: 24, language: 'English', word: 'Fill in', options: ['Wypełnić / Zastąpić', 'Napełnić', 'Uzupełnić', 'Wlać'], correctAnswer: 'Wypełnić / Zastąpić' },
  { id: 25, language: 'English', word: 'Find out', options: ['Znaleźć na zewnątrz', 'Dowiedzieć się', 'Szukać', 'Odkryć'], correctAnswer: 'Dowiedzieć się' },
  { id: 26, language: 'English', word: 'Get along', options: ['Iść wzdłuż', 'Dogadywać się', 'Radzić sobie', 'Oddalić się'], correctAnswer: 'Dogadywać się' },
  { id: 27, language: 'English', word: 'Get back', options: ['Dostać z powrotem', 'Cofnąć się', 'Zemścić się', 'Wrócić'], correctAnswer: 'Wrócić' },
  { id: 28, language: 'English', word: 'Get in', options: ['Wyjść', 'Dostać się do środka', 'Wejść / Dostać się', 'Wsiąść'], correctAnswer: 'Wejść / Dostać się' },
  { id: 29, language: 'English', word: 'Get off', options: ['Zejść', 'Wysiąść / Zejść z pracy', 'Wstać', 'Uciec'], correctAnswer: 'Wysiąść / Zejść z pracy' },
  { id: 30, language: 'English', word: 'Get on', options: ['Zejść', 'Wsiąść / Radzić sobie', 'Dogadywać się', 'Kontynuować'], correctAnswer: 'Wsiąść / Radzić sobie' },
  { id: 31, language: 'English', word: 'Get over', options: ['Przejść nad', 'Przeskoczyć', 'Dojść do siebie', 'Zapomnieć'], correctAnswer: 'Dojść do siebie' },
  { id: 32, language: 'English', word: 'Get through', options: ['Przejść przez', 'Przebrnąć / Dodzwonić się', 'Zdać egzamin', 'Zakończyć'], correctAnswer: 'Przebrnąć / Dodzwonić się' },
  { id: 33, language: 'English', word: 'Give back', options: ['Oddać', 'Podarować', 'Zwrócić', 'Cofnąć'], correctAnswer: 'Oddać' },
  { id: 34, language: 'English', word: 'Give up', options: ['Oddać', 'Poddawać się / Rzucić coś', 'Zrezygnować', 'Porzucić'], correctAnswer: 'Poddawać się / Rzucić coś' },
  { id: 35, language: 'English', word: 'Go ahead', options: ['Iść prosto', 'Zacząć', 'Kontynuować / Zgodzić się', 'Proszę bardzo'], correctAnswer: 'Kontynuować / Zgodzić się' },
  { id: 36, language: 'English', word: 'Go back', options: ['Cofać się', 'Wrócić', 'Pójść z tyłu', 'Zrezygnować'], correctAnswer: 'Wrócić' },
  { id: 37, language: 'English', word: 'Go on', options: ['Iść dalej', 'Kontynuować', 'Dziać się / Kontynuować', 'Włączać'], correctAnswer: 'Dziać się / Kontynuować' },
  { id: 38, language: 'English', word: 'Go out', options: ['Wyjść', 'Wychodzić z domu', 'Randkować', 'Zgasnąć'], correctAnswer: 'Wyjść' },
  { id: 39, language: 'English', word: 'Go through', options: ['Przejść przez coś', 'Przejrzeć', 'Doświadczyć', 'Przeanalizować'], correctAnswer: 'Przejść przez coś' },
  { id: 40, language: 'English', word: 'Hang out', options: ['Wieszać na zewnątrz', 'Spędzać czas', 'Czekać', 'Relaksować się'], correctAnswer: 'Spędzać czas' },
  { id: 41, language: 'English', word: 'Hold on', options: ['Trzymać się', 'Poczekać', 'Zawiesić', 'Czekać na linii'], correctAnswer: 'Poczekać' },
  { id: 42, language: 'English', word: 'Keep on', options: ['Trzymać na', 'Zachować', 'Kontynuować', 'Robić dalej'], correctAnswer: 'Kontynuować' },
  { id: 43, language: 'English', word: 'Let down', options: ['Opuścić', 'Rozczarować', 'Zawieść', 'Obniżyć'], correctAnswer: 'Zawieść' },
  { id: 44, language: 'English', word: 'Look after', options: ['Patrzeć za', 'Szukać', 'Opiekować się', 'Doglądać'], correctAnswer: 'Opiekować się' },
  { id: 45, language: 'English', word: 'Look for', options: ['Szukać', 'Patrzeć na', 'Znaleźć', 'Oczekiwać'], correctAnswer: 'Szukać' },
  { id: 46, language: 'English', word: 'Look forward to', options: ['Patrzeć w przód', 'Oczekiwać z niecierpliwością', 'Planować', 'Nie móc się doczekać'], correctAnswer: 'Nie móc się doczekać' },
  { id: 47, language: 'English', word: 'Look into', options: ['Patrzeć w', 'Zbadać', 'Sprawdzić / Zbadać', 'Przejrzeć'], correctAnswer: 'Sprawdzić / Zbadać' },
  { id: 48, language: 'English', word: 'Look out', options: ['Patrzeć na zewnątrz', 'Uważać', 'Wypatrywać', 'Strzec się'], correctAnswer: 'Uważać' },
  { id: 49, language: 'English', word: 'Make up', options: ['Robić makijaż', 'Pogodzić się / Wymyślić', 'Zmyślić historię', 'Nadrobić'], correctAnswer: 'Pogodzić się / Wymyślić' },
  { id: 50, language: 'English', word: 'Move on', options: ['Przesunąć się', 'Iść dalej', 'Zapomnieć o czymś', 'Zacząć od nowa'], correctAnswer: 'Iść dalej' },
  { id: 51, language: 'English', word: 'Open up', options: ['Otworzyć', 'Otworzyć się', 'Rozpocząć', 'Udostępnić'], correctAnswer: 'Otworzyć się' },
  { id: 52, language: 'English', word: 'Pick up', options: ['Podnieść', 'Odebrać / Podnieść / Nauczyć się', 'Zebrać', 'Podwieźć'], correctAnswer: 'Odebrać / Podnieść / Nauczyć się' },
  { id: 53, language: 'English', word: 'Put off', options: ['Odłożyć ubranie', 'Odkładać', 'Zniechęcać', 'Przesunąć'], correctAnswer: 'Odkładać' },
  { id: 54, language: 'English', word: 'Run into', options: ['Wbiec do', 'Spotkać przypadkiem', 'Zderzyć się z', 'Wpaść na kogoś'], correctAnswer: 'Wpaść na kogoś' },
  { id: 55, language: 'English', word: 'Settle down', options: ['Usiąść', 'Uspokoić się', 'Ustatkowac się', 'Zamieszkać'], correctAnswer: 'Ustatkowac się' },
  { id: 56, language: 'English', word: 'Show up', options: ['Pokazać', 'Zjawić się', 'Pojawić się', 'Zdemaskować'], correctAnswer: 'Pojawić się' },
  { id: 57, language: 'English', word: 'Shut up', options: ['Zamknąć', 'Uciszyć', 'Zamknąć się', 'Milczeć'], correctAnswer: 'Zamknąć się' },
  { id: 58, language: 'English', word: 'Sort out', options: ['Sortować', 'Uporządkować', 'Rozwiązać', 'Ogarnąć / Rozwiązać'], correctAnswer: 'Ogarnąć / Rozwiązać' },
  { id: 59, language: 'English', word: 'Take over', options: ['Przejąć', 'Przejąć kontrolę', 'Zastąpić', 'Zająć'], correctAnswer: 'Przejąć' },
  { id: 60, language: 'English', word: 'Take up', options: ['Podnieść', 'Zająć', 'Zacząć (hobby)', 'Skrócić'], correctAnswer: 'Zacząć (hobby)' },
  { id: 61, language: 'English', word: 'Think over', options: ['Przemyśleć', 'Rozważyć', 'Zastanowić się', 'Myśleć o'], correctAnswer: 'Przemyśleć' },
  { id: 62, language: 'English', word: 'Throw away', options: ['Odrzucić', 'Wyrzucić', 'Zmarnować', 'Pozbyć się'], correctAnswer: 'Wyrzucić' },
  { id: 63, language: 'English', word: 'Turn down', options: ['Odrzucić / Ściszyć', 'Skręcić w dół', 'Zmniejszyć', 'Odmówić'], correctAnswer: 'Odrzucić / Ściszyć' },
  { id: 64, language: 'English', word: 'Turn up', options: ['Pojawić się / Podgłośnić', 'Podkręcić', 'Znaleźć się', 'Zwiększyć'], correctAnswer: 'Pojawić się / Podgłośnić' },
  { id: 65, language: 'English', word: 'Work out', options: ['Rozwiązać / Ćwiczyć', 'Trenować', 'Obliczyć', 'Udać się'], correctAnswer: 'Rozwiązać / Ćwiczyć' },
  { id: 66, language: 'English', word: 'Write down', options: ['Zapisać', 'Notować', 'Spisać', 'Opisać'], correctAnswer: 'Zapisać' },
  { id: 67, language: 'English', word: 'Set up', options: ['Ustawić', 'Założyć / Zorganizować', 'Przygotować', 'Zainstalować'], correctAnswer: 'Założyć / Zorganizować' },
  { id: 68, language: 'English', word: 'Slow down', options: ['Zwolnić', 'Spowolnić', 'Hamować', 'Zmniejszyć tempo'], correctAnswer: 'Zwolnić' },
  { id: 69, language: 'English', word: 'Speed up', options: ['Przyspieszyć', 'Zwiększyć prędkość', 'Przyśpieszać', 'Przyśpieszyć'], correctAnswer: 'Przyspieszyć' },
  { id: 70, language: 'English', word: 'Step down', options: ['Zejść', 'Ustąpić', 'Zrezygnować', 'Zmniejszyć'], correctAnswer: 'Ustąpić' },
  { id: 71, language: 'English', word: 'Step up', options: ['Podejść', 'Zwiększyć zaangażowanie', 'Wzmocnić', 'Przyspieszyć'], correctAnswer: 'Zwiększyć zaangażowanie' },
  { id: 72, language: 'English', word: 'Break out', options: ['Wydostać się', 'Uciec', 'Wybuchnąć / Uciec', 'Wyłamać się'], correctAnswer: 'Wybuchnąć / Uciec' },
  { id: 73, language: 'English', word: 'Bring back', options: ['Przywrócić', 'Przynieść z powrotem', 'Oddać', 'Przypomnieć'], correctAnswer: 'Przywrócić' },
  { id: 74, language: 'English', word: 'Calm down', options: ['Uspokoić się', 'Ochłonąć', 'Zrelaksować się', 'Opanować się'], correctAnswer: 'Uspokoić się' },
  { id: 75, language: 'English', word: 'Check over', options: ['Sprawdzić pobieżnie', 'Przejrzeć', 'Skontrolować', 'Sprawdzić dokładnie'], correctAnswer: 'Sprawdzić dokładnie' },
  { id: 76, language: 'English', word: 'Clear up', options: ['Wyjaśnić / Posprzątać', 'Oczyścić', 'Rozjaśnić się (o pogodzie)', 'Uporządkować'], correctAnswer: 'Wyjaśnić / Posprzątać' },
  { id: 77, language: 'English', word: 'Come along', options: ['Iść wzdłuż', 'Dołączyć', 'Robić postępy', 'Przyjść / Robić postępy'], correctAnswer: 'Przyjść / Robić postępy' },
  { id: 78, language: 'English', word: 'Cut back', options: ['Przyciąć', 'Ograniczyć wydatki', 'Zredukować', 'Obciąć'], correctAnswer: 'Ograniczyć wydatki' },
  { id: 79, language: 'English', word: 'Fall apart', options: ['Rozpaść się', 'Rozlecieć się', 'Załamać się', 'Zniszczyć'], correctAnswer: 'Rozpaść się' },
  { id: 80, language: 'English', word: 'Fall behind', options: ['Odpaść', 'Zostać w tyle', 'Mieć zaległości', 'Spóźniać się'], correctAnswer: 'Zostać w tyle' },
  { id: 81, language: 'English', word: 'Fill out', options: ['Wypełnić formularz', 'Napełnić', 'Uzupełnić', 'Wypełnić'], correctAnswer: 'Wypełnić formularz' },
  { id: 82, language: 'English', word: 'Get away', options: ['Uciec', 'Wyjechać / Uciec', 'Wydostać się', 'Oddalić się'], correctAnswer: 'Wyjechać / Uciec' },
  { id: 83, language: 'English', word: 'Get by', options: ['Przejść obok', 'Radzić sobie', 'Przetrwać', 'Utrzymać się'], correctAnswer: 'Radzić sobie' },
  { id: 84, language: 'English', word: 'Get together', options: ['Zebrać razem', 'Spotkać się', 'Zgromadzić się', 'Umówić się'], correctAnswer: 'Spotkać się' },
  { id: 85, language: 'English', word: 'Give in', options: ['Oddać', 'Ulec', 'Poddawać się', 'Ustąpić'], correctAnswer: 'Ulec' },
  { id: 86, language: 'English', word: 'Go wrong', options: ['Pójść źle', 'Pójść nie tak', 'Pomylić się', 'Zepsuć się'], correctAnswer: 'Pójść nie tak' },
  { id: 87, language: 'English', word: 'Hang on', options: ['Zawiesić na', 'Poczekać', 'Trzymać się', 'Czekać'], correctAnswer: 'Poczekać' },
  { id: 88, language: 'English', word: 'Keep up', options: ['Trzymać w górze', 'Nadążać', 'Utrzymywać', 'Kontynuować'], correctAnswer: 'Nadążać' },
  { id: 89, language: 'English', word: 'Log in', options: ['Zapisać się', 'Wejść', 'Zalogować się', 'Zarejestrować'], correctAnswer: 'Zalogować się' },
  { id: 90, language: 'English', word: 'Log out', options: ['Wyjść', 'Wylogować się', 'Opuścić', 'Zakończyć'], correctAnswer: 'Wylogować się' },
  { id: 91, language: 'English', word: 'Sign in', options: ['Podpisać się / Zalogować', 'Wpisać się', 'Zameldować się', 'Zarejestrować'], correctAnswer: 'Podpisać się / Zalogować' },
  { id: 92, language: 'English', word: 'Sign out', options: ['Wypisać się', 'Wymeldować się', 'Zrezygnować', 'Wylogować się'], correctAnswer: 'Wylogować się' },
  { id: 93, language: 'English', word: 'Turn on', options: ['Włączyć', 'Uruchomić', 'Odpalić', 'Nakręcić'], correctAnswer: 'Włączyć' },
  { id: 94, language: 'English', word: 'Turn off', options: ['Skręcić', 'Wyłączyć', 'Zgasić', 'Zniechęcić'], correctAnswer: 'Wyłączyć' },
  { id: 95, language: 'English', word: 'Plug in', options: ['Podłączyć', 'Włączyć do prądu', 'Zatkać', 'Wepchnąć'], correctAnswer: 'Podłączyć' },
  { id: 96, language: 'English', word: 'Back out', options: ['Cofnąć się', 'Wycofać się', 'Zrezygnować', 'Odstąpić'], correctAnswer: 'Wycofać się' },
  { id: 97, language: 'English', word: 'Boot up', options: ['Założyć buty', 'Uruchomić system', 'Włączyć komputer', 'Wystartować'], correctAnswer: 'Uruchomić system' },
  { id: 98, language: 'English', word: 'Shut down', options: ['Zamknąć', 'Wyłączyć', 'Zakończyć działanie', 'Zamknąć / Wyłączyć'], correctAnswer: 'Zamknąć / Wyłączyć' },
  { id: 99, language: 'English', word: 'Freak out', options: ['Spanikować', 'Oszaleć', 'Zdenerwować się', 'Wystraszyć się'], correctAnswer: 'Spanikować' },
  { id: 100, language: 'English', word: 'Lash out', options: ['Uderzyć', 'Skrytykować', 'Wybuchnąć gniewem', 'Zaatakować'], correctAnswer: 'Wybuchnąć gniewem' },
  { id: 101, language: 'English', word: 'Mess up', options: ['Zrobić bałagan', 'Schrzanić coś', 'Pomylić się', 'Zepsuć'], correctAnswer: 'Schrzanić coś' },
  { id: 102, language: 'English', word: 'Pass out', options: ['Rozdawać', 'Zemdlać', 'Stracić przytomność', 'Zasnąć'], correctAnswer: 'Zemdlać' },
  { id: 103, language: 'English', word: 'Snap out of', options: ['Wyjść z czegoś', 'Otrząsnąć się', 'Obudzić się', 'Przestać'], correctAnswer: 'Otrząsnąć się' },
  { id: 104, language: 'English', word: 'Wear out', options: ['Nosić na zewnątrz', 'Zmęczyć / Zużyć', 'Znosić', 'Wyczerpać'], correctAnswer: 'Zmęczyć / Zużyć' },
  { id: 105, language: 'English', word: 'Blow off', options: ['Zdmuchnąć', 'Zlekceważyć', 'Olać', 'Zignorować'], correctAnswer: 'Zlekceważyć' },
  { id: 106, language: 'English', word: 'Bottle up', options: ['Butelkować', 'Tłumić emocje', 'Ukrywać uczucia', 'Zamykać w sobie'], correctAnswer: 'Tłumić emocje' },
  { id: 107, language: 'English', word: 'Bring along', options: ['Przynieść', 'Przyprowadzić', 'Wziąć ze sobą', 'Zabrać ze sobą'], correctAnswer: 'Zabrać ze sobą' },
  { id: 108, language: 'English', word: 'Call up', options: ['Zadzwonić', 'Wezwać', 'Skontaktować się', 'Powołać do wojska'], correctAnswer: 'Zadzwonić' },
  { id: 109, language: 'English', word: 'Come around', options: ['Wpaść z wizytą', 'Dojść do siebie', 'Zmienić zdanie', 'Odwiedzić'], correctAnswer: 'Zmienić zdanie' },
  { id: 110, language: 'English', word: 'Cut out', options: ['Wyciąć', 'Przestać / Wyciąć', 'Wyeliminować', 'Wyłączyć'], correctAnswer: 'Przestać / Wyciąć' },
  { id: 111, language: 'English', word: 'Get ahead', options: ['Iść naprzód', 'Wyprzedzić', 'Wysunąć się na prowadzenie', 'Osiągnąć sukces'], correctAnswer: 'Wysunąć się na prowadzenie' },
  { id: 112, language: 'English', word: 'Give away', options: ['Oddać', 'Rozdać', 'Zdradzić / Oddać', 'Wyjawić'], correctAnswer: 'Zdradzić / Oddać' },
  { id: 113, language: 'English', word: 'Hold back', options: ['Powstrzymać', 'Zatrzymać', 'Ukrywać', 'Wahać się'], correctAnswer: 'Powstrzymać' },
  { id: 114, language: 'English', word: 'Keep away', options: ['Trzymać z daleka', 'Unikać', 'Nie zbliżać się', 'Trzymać się z dala'], correctAnswer: 'Trzymać się z dala' },
  { id: 115, language: 'English', word: 'Lay off', options: ['Odłożyć', 'Przestać', 'Zwolnić z pracy', 'Dać spokój'], correctAnswer: 'Zwolnić z pracy' },
  { id: 116, language: 'English', word: 'Live up to', options: ['Żyć do', 'Sprostać', 'Spełnić oczekiwania', 'Żyć zgodnie z'], correctAnswer: 'Spełnić oczekiwania' },
  { id: 117, language: 'English', word: 'Pass away', options: ['Przejść obok', 'Minąć', 'Umrzeć', 'Odejść'], correctAnswer: 'Umrzeć' },
  { id: 118, language: 'English', word: 'Pull over', options: ['Pociągnąć', 'Zatrzymać się na poboczu', 'Zjechać na bok', 'Zatrzymać pojazd'], correctAnswer: 'Zjechać na bok' },
  { id: 119, language: 'English', word: 'Run out', options: ['Wybiec', 'Skończyć się', 'Wyczerpać się', 'Uciekać'], correctAnswer: 'Skończyć się' },
  { id: 120, language: 'English', word: 'Stand by', options: ['Stać obok', 'Wspierać', 'Czekać / Wspierać', 'Być w gotowości'], correctAnswer: 'Czekać / Wspierać' },
  { id: 121, language: 'English', word: 'Stick to', options: ['Przykleić się do', 'Trzymać się', 'Przestrzegać', 'Obstawać przy'], correctAnswer: 'Trzymać się' },
  { id: 122, language: 'English', word: 'Take off', options: ['Zdjąć', 'Wystartować / Zdjąć', 'Odlecieć', 'Odnieść sukces'], correctAnswer: 'Wystartować / Zdjąć' },
  { id: 123, language: 'English', word: 'Turn around', options: ['Odwrócić się', 'Zawracać', 'Odwrócić sytuację', 'Poprawić'], correctAnswer: 'Odwrócić sytuację' },
  { id: 124, language: 'English', word: 'Warm up', options: ['Podgrzać', 'Rozgrzać się', 'Rozgrzewka', 'Ocieplić'], correctAnswer: 'Rozgrzać się' },
  { id: 125, language: 'English', word: 'Wrap up', options: ['Zawinąć', 'Zakończyć', 'Podsumować', 'Ubrać się ciepło'], correctAnswer: 'Zakończyć' },
];


