import type { Language } from './storage';

export interface Tradition {
  name: { pl: string; native: string; };
  description: { pl: string; native: string; };
}

export interface TraditionsPageData {
  lang: Language;
  traditions: Tradition[];
  ui: {
    title: { pl: string; native: string; };
    backButton: { pl: string; native: string; };
  }
}

export const allTraditionsData: Record<Language, TraditionsPageData> = {
  en: {
    lang: 'en',
    traditions: [
        { name: { pl: 'Popołudniowa herbata', native: 'Afternoon Tea' }, description: { pl: 'Lekki posiłek spożywany około godziny 16:00, składający się z małych kanapek, ciasteczek (scones) z dżemem i śmietaną oraz ciast, serwowany z herbatą. To kwintesencja brytyjskiej tradycji i elegancji.', native: 'A light meal eaten around 4 PM, consisting of small sandwiches, scones with jam and cream, and cakes, served with tea. It is the quintessence of British tradition and elegance.' } },
        { name: { pl: 'Noc Guya Fawkesa', native: 'Guy Fawkes Night' }, description: { pl: 'Obchodzona 5 listopada, upamiętnia nieudany spisek prochowy z 1605 roku. Świętuje się ją pokazami fajerwerków, paleniem ognisk i kukieł Guya Fawkesa.', native: 'Celebrated on November 5th, it commemorates the failed Gunpowder Plot of 1605. It is celebrated with firework displays, bonfires, and the burning of Guy Fawkes effigies.' } },
        { name: { pl: 'Boxing Day', native: 'Boxing Day' }, description: { pl: 'Drugi dzień świąt Bożego Narodzenia (26 grudnia), tradycyjnie dzień dawania prezentów służbie. Dziś to dzień wolny, znany z wyprzedaży i wydarzeń sportowych, zwłaszcza meczów piłki nożnej.', native: 'The day after Christmas Day (December 26th), traditionally a day for giving gifts to servants. Today, it is a public holiday known for sales and sporting events, especially football matches.' } },
        { name: { pl: 'Dzień Naleśnika (Shrove Tuesday)', native: 'Pancake Day' }, description: { pl: 'Ostatni dzień przed rozpoczęciem Wielkiego Postu, tradycyjnie spożywa się naleśniki, aby zużyć bogate składniki przed postem. W wielu miastach odbywają się też wyścigi z patelniami.', native: 'The last day before the start of Lent, traditionally pancakes are eaten to use up rich ingredients before the fast. Many towns also hold pancake races.' } },
        { name: { pl: 'Tańce Morris', native: 'Morris Dancing' }, description: { pl: 'Tradycyjny angielski taniec ludowy, zwykle wykonywany przez grupy tancerzy w dzwonkach na nogach, z kijami, mieczami lub chusteczkami. Często można go zobaczyć na letnich festynach.', native: 'A traditional English folk dance, usually performed by groups of dancers wearing bells on their legs, and using sticks, swords, or handkerchiefs. It is often seen at summer fetes.' } },
        { name: { pl: 'Taniec wokół Słupa Majowego', native: 'Maypole Dancing' }, description: { pl: 'Starożytny zwyczaj obchodzony 1 maja (May Day), polegający na tańczeniu wokół wysokiego słupa ozdobionego wstążkami, które tancerze splatają w skomplikowane wzory.', native: 'An ancient custom celebrated on May 1st (May Day), involving dancing around a tall pole decorated with ribbons, which the dancers weave into intricate patterns.' } },
        { name: { pl: 'Toczenie Sera', native: 'Cheese-Rolling' }, description: { pl: 'Ekscentryczne, coroczne wydarzenie w Cooper\'s Hill w Gloucestershire, gdzie uczestnicy gonią toczący się w dół stromego wzgórza krąg sera Double Gloucester. Wygrywa pierwsza osoba, która przekroczy linię mety.', native: 'An eccentric annual event at Cooper\'s Hill in Gloucestershire, where participants chase a rolling wheel of Double Gloucester cheese down a steep hill. The first person to cross the finish line wins.' } },
        { name: { pl: 'Zmiana warty', native: 'Changing of the Guard' }, description: { pl: 'Uroczysta ceremonia, podczas której żołnierze pełniący wartę przed Pałacem Buckingham i innymi rezydencjami królewskimi są zmieniani przez nową grupę. To barwny spektakl pełen precyzji i tradycji.', native: 'A formal ceremony in which the soldiers guarding Buckingham Palace and other royal residences are replaced by a new group. It is a colorful spectacle full of precision and tradition.' } },
        { name: { pl: 'Wyścigi konne w Ascot', native: 'Royal Ascot' }, description: { pl: 'Jedno z najsłynniejszych wydarzeń w świecie wyścigów konnych, znane z rygorystycznego dress code\'u, zwłaszcza wymyślnych kapeluszy noszonych przez panie w Dniu Dam.', native: 'One of the most famous events in the world of horse racing, known for its strict dress code, especially the elaborate hats worn by ladies on Ladies\' Day.' } },
        { name: { pl: 'Niedzielna Pieczeń', native: 'Sunday Roast' }, description: { pl: 'Tradycyjny brytyjski posiłek serwowany w niedzielę. Zazwyczaj składa się z pieczonego mięsa (wołowiny, kurczaka, jagnięciny), pieczonych ziemniaków, warzyw, Yorkshire pudding i sosu pieczeniowego (gravy).', native: 'A traditional British meal served on Sundays. It typically consists of roasted meat (beef, chicken, lamb), roast potatoes, vegetables, Yorkshire pudding, and gravy.' } },
        { name: { pl: 'Dożynki', native: 'Harvest Festival' }, description: { pl: 'Święto dziękczynienia za zbiory, obchodzone w kościołach i szkołach jesienią. Ludzie przynoszą jedzenie, które jest następnie rozdawane potrzebującym.', native: 'A celebration of the food grown on the land, celebrated in churches and schools in autumn. People bring food which is then donated to those in need.' } },
        { name: { pl: 'Kultura pubowa', native: 'Pub Culture' }, description: { pl: 'Pub (public house) jest centralnym punktem brytyjskiego życia społecznego. To miejsce spotkań, rozmów, picia piwa i często spożywania tradycyjnych posiłków, jak "fish and chips".', native: 'The pub (public house) is a central part of British social life. It\'s a place for meeting, talking, drinking beer, and often eating traditional meals like "fish and chips".' } },
        { name: { pl: 'Kolejka', native: 'Queuing' }, description: { pl: 'Sztuka cierpliwego stania w kolejce jest uważana za narodową cechę Brytyjczyków. Jest to niepisana zasada społeczna, której przestrzega się w sklepach, na przystankach autobusowych i w wielu innych miejscach.', native: 'The art of patiently standing in line is considered a national characteristic of the British. It is an unwritten social rule observed in shops, at bus stops, and in many other places.' } },
        { name: { pl: 'Pantomima świąteczna', native: 'Christmas Pantomime' }, description: { pl: 'Rodzaj muzycznej komedii teatralnej, wystawianej w okresie świątecznym. Charakteryzuje się udziałem publiczności, slapstickiem i rolami, w których mężczyźni grają kobiety (dame) i na odwrót.', native: 'A type of musical comedy stage production, performed during the Christmas season. It is characterized by audience participation, slapstick humour, and roles where men play women (dame) and vice versa.' } },
        { name: { pl: 'Noc Walpurgi', native: 'Walpurgis Night' }, description: { pl: 'Obchodzona w wigilię 1 maja, tradycja ta jest szczególnie żywa w niektórych wiejskich rejonach Anglii. Wiąże się z pogańskimi obrzędami powitania wiosny, często z ogniskami i tańcami.', native: 'Celebrated on the eve of May 1st, this tradition is particularly strong in some rural areas of England. It is associated with pagan rituals to welcome spring, often involving bonfires and dancing.' } },
    ],
    ui: { title: { pl: 'Tradycje', native: 'Traditions' }, backButton: { pl: 'Powrót do Kultury', native: 'Back to Culture' } }
  },
  de: {
    lang: 'de',
    traditions: [
        { name: { pl: 'Oktoberfest', native: 'Oktoberfest' }, description: { pl: 'Największy na świecie festiwal ludowy, odbywający się co roku w Monachium. Słynie z ogromnych namiotów piwnych, tradycyjnej bawarskiej muzyki, strojów (Dirndl i Lederhosen) i jedzenia.', native: 'Das größte Volksfest der Welt, das jährlich in München stattfindet. Berühmt für seine riesigen Bierzelte, traditionelle bayerische Musik, Trachten (Dirndl und Lederhosen) und Speisen.' } },
        { name: { pl: 'Jarmarki bożonarodzeniowe', native: 'Weihnachtsmärkte' }, description: { pl: 'Tradycyjne jarmarki odbywające się w okresie adwentu w centrach miast. Oferują grzane wino (Glühwein), pierniki (Lebkuchen), rękodzieło i tworzą świąteczną atmosferę.', native: 'Traditionelle Märkte, die während der Adventszeit in den Stadtzentren stattfinden. Sie bieten Glühwein, Lebkuchen, Handwerkskunst und schaffen eine festliche Atmosphäre.' } },
        { name: { pl: 'Schultüte', native: 'Schultüte' }, description: { pl: 'Tradycja wręczania dzieciom w pierwszym dniu szkoły dużej, stożkowatej torby wypełnionej słodyczami i przyborami szkolnymi. Ma na celu osłodzenie rozpoczęcia nauki.', native: 'Eine Tradition, bei der Kinder am ersten Schultag eine große, kegelförmige Tüte voller Süßigkeiten und Schulmaterialien erhalten. Sie soll den Schulbeginn versüßen.' } },
        { name: { pl: 'Taniec w Maj', native: 'Tanz in den Mai' }, description: { pl: 'Świętowanie nadejścia maja w noc z 30 kwietnia na 1 maja. Organizowane są imprezy i festyny, często z ogniskami i ustawianiem ozdobionego drzewka majowego (Maibaum).', native: 'Eine Feier zur Begrüßung des Mais in der Nacht vom 30. April auf den 1. Mai. Es werden Partys und Feste veranstaltet, oft mit Lagerfeuern und dem Aufstellen eines geschmückten Maibaums.' } },
        { name: { pl: 'Karnawał (Karneval/Fasching)', native: 'Karneval/Fasching' }, description: { pl: 'Okres zabaw przed Wielkim Postem, szczególnie hucznie obchodzony w Nadrenii (Kolonia, Düsseldorf). Charakteryzuje się paradami, przebraniami i zabawnymi obrzędami, jak "Weiberfastnacht".', native: 'Die Zeit der Feierlichkeiten vor der Fastenzeit, die besonders im Rheinland (Köln, Düsseldorf) ausgelassen gefeiert wird. Gekennzeichnet durch Paraden, Kostüme und lustige Rituale wie die "Weiberfastnacht".' } },
        { name: { pl: 'Kawa i ciasto', native: 'Kaffee und Kuchen' }, description: { pl: 'Popołudniowe spotkanie towarzyskie przy kawie i domowym ciastku, podobne do brytyjskiej herbatki. Jest to ważny element niemieckiej gościnności i życia rodzinnego.', native: 'Ein geselliges Beisammensein am Nachmittag bei Kaffee und hausgemachtem Kuchen, ähnlich dem britischen Nachmittagstee. Es ist ein wichtiger Teil der deutschen Gastfreundschaft und des Familienlebens.' } },
        { name: { pl: 'Polterabend', native: 'Polterabend' }, description: { pl: 'Wieczór przedślubny, podczas którego goście tłuką porcelanę przed domem przyszłej pary młodej. Ma to przynieść szczęście i odstraszyć złe duchy, a wspólne sprzątanie symbolizuje współpracę.', native: 'Ein Vorabend der Hochzeit, an dem die Gäste vor dem Haus des Brautpaares Porzellan zerschlagen. Dies soll Glück bringen und böse Geister vertreiben, und das gemeinsame Aufräumen symbolisiert die Zusammenarbeit.' } },
        { name: { pl: 'Wieniec adwentowy', native: 'Adventskranz' }, description: { pl: 'Wieniec z gałązek jodły z czterema świecami. W każdą niedzielę adwentu zapala się kolejną świecę, odliczając czas do Bożego Narodzenia.', native: 'Ein Kranz aus Tannenzweigen mit vier Kerzen. An jedem Adventssonntag wird eine weitere Kerze angezündet, um die Zeit bis Weihnachten herunterzuzählen.' } },
        { name: { pl: 'Ogniska wielkanocne', native: 'Osterfeuer' }, description: { pl: 'W wielu regionach w noc przed Niedzielą Wielkanocną pali się duże ogniska. Zwyczaj ten ma pogańskie korzenie i symbolizuje pożegnanie zimy i powitanie wiosny.', native: 'In vielen Regionen werden in der Nacht vor dem Ostersonntag große Feuer entzündet. Dieser Brauch hat heidnische Wurzeln und symbolisiert den Abschied vom Winter und die Begrüßung des Frühlings.' } },
        { name: { pl: 'Pochody z lampionami', native: 'Laternelaufen' }, description: { pl: 'Wieczorne pochody dzieci z własnoręcznie wykonanymi lampionami, organizowane w okolicach Dnia Świętego Marcina (11 listopada). Dzieci śpiewają piosenki o lampionach i otrzymują słodycze.', native: 'Abendliche Umzüge von Kindern mit selbstgebastelten Laternen, die um den Martinstag (11. November) herum veranstaltet werden. Die Kinder singen Lieder über Laternen und erhalten Süßigkeiten.' } },
        { name: { pl: 'Dożynki', native: 'Erntedankfest' }, description: { pl: 'Święto dziękczynienia za plony, obchodzone na początku października. W kościołach przygotowuje się ołtarze z owoców, warzyw i zbóż, a w wielu miejscowościach odbywają się festyny i parady.', native: 'Ein Fest zum Dank für die Ernte, das Anfang Oktober gefeiert wird. In den Kirchen werden Altäre mit Obst, Gemüse und Getreide geschmückt, und in vielen Orten finden Feste und Umzüge statt.' } },
        { name: { pl: 'Richtfest', native: 'Richtfest' }, description: { pl: 'Ceremonia po zakończeniu budowy więźby dachowej nowego domu. Na dachu umieszcza się ozdobioną wiechę, a cieśla wygłasza tradycyjną mowę. To podziękowanie dla wszystkich budowniczych.', native: 'Eine Zeremonie nach Fertigstellung des Dachstuhls eines neuen Hauses. Auf dem Dach wird ein geschmückter Richtkranz angebracht, und der Zimmermann hält eine traditionelle Rede. Es ist ein Dank an alle Bauleute.' } },
        { name: { pl: 'Noc Walpurgi', native: 'Walpurgisnacht' }, description: { pl: 'W noc z 30 kwietnia na 1 maja, zwłaszcza w górach Harz, odbywają się festyny nawiązujące do legend o zlotach czarownic. Ludzie przebierają się za czarownice i diabły, tańcząc wokół ognisk.', native: 'In der Nacht vom 30. April auf den 1. Mai, besonders im Harz, finden Feste statt, die sich auf Legenden von Hexentreffen beziehen. Die Menschen verkleiden sich als Hexen und Teufel und tanzen um Lagerfeuer.' } },
        { name: { pl: 'Stammtisch', native: 'Stammtisch' }, description: { pl: 'Regularne, nieformalne spotkanie grupy osób (zwykle mężczyzn) w pubie lub restauracji przy stałym, zarezerwowanym stole. To ważny element lokalnego życia społecznego.', native: 'Ein regelmäßiges, informelles Treffen einer Gruppe von Personen (meist Männer) in einer Kneipe oder einem Restaurant an einem fest reservierten Tisch. Es ist ein wichtiger Bestandteil des lokalen gesellschaftlichen Lebens.' } },
        { name: { pl: 'Sylwester', native: 'Silvester' }, description: { pl: 'Noc sylwestrowa obchodzona jest hucznie, z pokazami fajerwerków o północy. Popularne tradycje to m.in. wróżenie z ołowiu (Bleigießen) i jedzenie soczewicy, co ma przynieść pieniądze w nowym roku.', native: 'Die Silvesternacht wird ausgelassen gefeiert, mit Feuerwerk um Mitternacht. Beliebte Traditionen sind das Bleigießen und das Essen von Linsen, was im neuen Jahr Geld bringen soll.' } },
    ],
    ui: { title: { pl: 'Tradycje', native: 'Traditionen' }, backButton: { pl: 'Powrót do Kultury', native: 'Zurück zur Kultur' } }
  },
  fr: {
    lang: 'fr',
    traditions: [
        { name: { pl: 'Święto Narodowe (14 lipca)', native: 'Fête Nationale (14 Juillet)' }, description: { pl: 'Upamiętnia zdobycie Bastylii w 1789 roku i początek Rewolucji Francuskiej. Obchody obejmują poranną paradę wojskową na Polach Elizejskich i wieczorne pokazy sztucznych ogni w całej Francji.', native: 'Commemorates the storming of the Bastille in 1789 and the beginning of the French Revolution. Celebrations include a morning military parade on the Champs-Élysées and evening firework displays throughout France.' } },
        { name: { pl: 'Festiwal Muzyki', native: 'Fête de la Musique' }, description: { pl: 'Odbywa się 21 czerwca, w najdłuższy dzień w roku. Profesjonalni i amatorscy muzycy wychodzą na ulice, aby grać darmowe koncerty, a całe miasta zamieniają się w wielką scenę muzyczną.', native: 'Held on June 21st, the longest day of the year. Professional and amateur musicians take to the streets to play free concerts, and entire cities turn into a giant music stage.' } },
        { name: { pl: 'Beaujolais Nouveau', native: 'Beaujolais Nouveau' }, description: { pl: 'Święto młodego wina z regionu Beaujolais, które trafia do sprzedaży co roku w trzeci czwartek listopada. Wydarzenie to jest obchodzone w bistrach i restauracjach w całej Francji pod hasłem "Le Beaujolais nouveau est arrivé!".', native: 'A celebration of the young wine from the Beaujolais region, which goes on sale every year on the third Thursday of November. The event is celebrated in bistros and restaurants throughout France with the slogan "Le Beaujolais nouveau est arrivé!".' } },
        { name: { pl: 'Apéro (Aperitif)', native: 'L\'Apéro' }, description: { pl: 'To więcej niż drink przed kolacją; to ważny rytuał społeczny. Spotkanie z przyjaciółmi lub rodziną na lekkie napoje (np. pastis, wino) i przekąski (oliwki, orzeszki) przed głównym posiłkiem.', native: 'It\'s more than a pre-dinner drink; it\'s an important social ritual. A get-together with friends or family for light drinks (e.g., pastis, wine) and snacks (olives, nuts) before the main meal.' } },
        { name: { pl: 'Objawienie Pańskie (Ciasto Trzech Króli)', native: 'Épiphanie (Galette des Rois)' }, description: { pl: '6 stycznia spożywa się specjalne ciasto "galette des rois", w którym ukryta jest mała figurka (la fève). Osoba, która ją znajdzie, zostaje "królem" lub "królową" na jeden dzień.', native: 'On January 6th, a special cake called "galette des rois" is eaten, inside which a small figurine (la fève) is hidden. The person who finds it becomes "king" or "queen" for the day.' } },
        { name: { pl: 'Prima Aprilis', native: 'Poisson d\'Avril' }, description: { pl: '1 kwietnia dzieci i dorośli robią sobie żarty, a tradycją jest przyklejanie papierowej ryby na plecach niczego niepodejrzewającej osoby i krzyczenie "Poisson d\'Avril!".', native: 'On April 1st, children and adults play pranks on each other, and the tradition is to stick a paper fish on the back of an unsuspecting person and shout "Poisson d\'Avril!".' } },
        { name: { pl: 'Dzień Naleśnika (La Chandeleur)', native: 'La Chandeleur' }, description: { pl: 'Święto obchodzone 2 lutego, podczas którego tradycyjnie je się naleśniki (crêpes). Przesąd mówi, że trzymanie monety w jednej ręce podczas obracania pierwszego naleśnika przyniesie szczęście.', native: 'A holiday celebrated on February 2nd, during which crêpes are traditionally eaten. Superstition holds that holding a coin in one hand while flipping the first crêpe will bring good fortune.' } },
        { name: { pl: 'Tour de France', native: 'Tour de France' }, description: { pl: 'Najsłynniejszy wyścig kolarski na świecie, który co roku w lipcu przyciąga miliony widzów na trasy w całej Francji. To narodowe święto sportu i kultury.', native: 'The world\'s most famous cycling race, which attracts millions of spectators to routes across France every July. It is a national celebration of sport and culture.' } },
        { name: { pl: 'Konwalia 1 maja', native: 'Le muguet du 1er mai' }, description: { pl: 'W Święto Pracy (1 maja) tradycją jest wręczanie bliskim gałązek konwalii, które mają przynieść szczęście na nadchodzący rok.', native: 'On Labour Day (May 1st), it is a tradition to give sprigs of lily of the valley to loved ones, which are believed to bring good luck for the coming year.' } },
        { name: { pl: 'Wigilia Bożego Narodzenia (Le Réveillon)', native: 'Le Réveillon de Noël' }, description: { pl: 'Długa i uroczysta kolacja w wieczór 24 grudnia, często składająca się z wielu dań, w tym owoców morza, foie gras, indyka i tradycyjnego ciasta "bûche de Noël".', native: 'A long and festive dinner on the evening of December 24th, often consisting of many courses, including seafood, foie gras, turkey, and the traditional "bûche de Noël" cake.' } },
        { name: { pl: 'Wszystkich Świętych', native: 'Toussaint' }, description: { pl: '1 listopada to dzień wolny od pracy, w którym Francuzi odwiedzają groby bliskich, składając na nich kwiaty, najczęściej chryzantemy.', native: 'November 1st is a public holiday when the French visit the graves of their loved ones, laying flowers, most commonly chrysanthemums.' } },
        { name: { pl: 'Święto Sąsiadów', native: 'Fête des Voisins' }, description: { pl: 'Coroczne wydarzenie, zwykle pod koniec maja, zachęcające mieszkańców jednego budynku lub ulicy do zorganizowania wspólnego spotkania, aby lepiej się poznać.', native: 'An annual event, usually at the end of May, encouraging residents of a building or street to organize a get-together to get to know each other better.' } },
        { name: { pl: 'Winobranie', native: 'Les Vendanges' }, description: { pl: 'Zbiory winogron, szczególnie w regionach winiarskich jak Bordeaux czy Burgundia, to ważny czas w roku, często zwieńczony lokalnymi festynami i świętowaniem.', native: 'The grape harvest, especially in wine regions like Bordeaux or Burgundy, is an important time of the year, often culminating in local festivals and celebrations.' } },
        { name: { pl: 'Targi staroci', native: 'Brocantes et Vide-greniers' }, description: { pl: 'Popularne w całej Francji, zwłaszcza w weekendy. Są to pchle targi lub wyprzedaże garażowe, gdzie można znaleźć wszystko, od antyków po używane ubrania i książki.', native: 'Popular throughout France, especially on weekends. These are flea markets or garage sales where you can find everything from antiques to used clothes and books.' } },
        { name: { pl: 'Festiwal w Cannes', native: 'Festival de Cannes' }, description: { pl: 'Jeden z najbardziej prestiżowych festiwali filmowych na świecie, odbywający się co roku w maju na Lazurowym Wybrzeżu. Przyciąga największe gwiazdy kina i dyktuje trendy w światowej kinematografii.', native: 'One of the most prestigious film festivals in the world, held annually in May on the French Riviera. It attracts the biggest movie stars and sets trends in world cinema.' } },
    ],
    ui: { title: { pl: 'Tradycje', native: 'Traditions' }, backButton: { pl: 'Powrót do Kultury', native: 'Retour à la Culture' } }
  },
  it: {
    lang: 'it',
    traditions: [
        { name: { pl: 'Aperitivo', native: 'Aperitivo' }, description: { pl: 'Wieczorny rytuał przed kolacją. Zamawiając drinka (np. Aperol Spritz), otrzymuje się dostęp do bufetu z przekąskami. To forma spotkania towarzyskiego i sposób na zaostrzenie apetytu.', native: 'An evening ritual before dinner. When you order a drink (e.g., Aperol Spritz), you get access to a buffet of snacks. It is a form of social gathering and a way to whet the appetite.' } },
        { name: { pl: 'Karnawał w Wenecji', native: 'Carnevale di Venezia' }, description: { pl: 'Słynny na całym świecie karnawał, znany z wyszukanych masek i kostiumów. Ulice i place Wenecji wypełniają się paradami, balami i przedstawieniami, tworząc magiczną atmosferę.', native: 'A world-famous carnival known for its elaborate masks and costumes. The streets and squares of Venice fill with parades, balls, and performances, creating a magical atmosphere.' } },
        { name: { pl: 'Ferragosto', native: 'Ferragosto' }, description: { pl: 'Święto 15 sierpnia, Wniebowzięcie Najświętszej Maryi Panny, które jest kulminacyjnym punktem włoskich wakacji. Większość Włochów spędza ten dzień na plaży, w górach lub na festynach.', native: 'A holiday on August 15th, the Assumption of Mary, which is the high point of the Italian summer holidays. Most Italians spend this day at the beach, in the mountains, or at festivals.' } },
        { name: { pl: 'Palio di Siena', native: 'Palio di Siena' }, description: { pl: 'Historyczny wyścig konny, który odbywa się dwa razy w roku na głównym placu Sieny, Piazza del Campo. Reprezentanci różnych dzielnic (contrade) rywalizują w pełnym pasji i tradycji widowisku.', native: 'A historic horse race held twice a year in Siena\'s main square, Piazza del Campo. Representatives of different districts (contrade) compete in a spectacle full of passion and tradition.' } },
        { name: { pl: 'La Befana', native: 'La Befana' }, description: { pl: 'W noc z 5 na 6 stycznia, czarownica Befana przynosi dzieciom prezenty. Grzeczne dzieci dostają słodycze do skarpet, a niegrzeczne – węgiel (z cukru).', native: 'On the night of January 5th to 6th, the witch Befana brings gifts to children. Good children receive sweets in their stockings, while naughty ones get coal (made of sugar).' } },
        { name: { pl: 'Poniedziałek Wielkanocny', native: 'Pasquetta' }, description: { pl: 'Dzień po Wielkanocy, tradycyjnie spędzany na piknikach i wycieczkach za miasto z rodziną i przyjaciółmi.', native: 'The day after Easter, traditionally spent on picnics and trips out of town with family and friends.' } },
        { name: { pl: 'Sagra', native: 'Sagra' }, description: { pl: 'Lokalne festyny poświęcone określonemu produktowi spożywczemu (np. truflom, winu, kasztanom). To okazja do świętowania, jedzenia i poznawania lokalnej kultury.', native: 'Local festivals dedicated to a specific food product (e.g., truffles, wine, chestnuts). It is an opportunity to celebrate, eat, and get to know the local culture.' } },
        { name: { pl: 'Szopka bożonarodzeniowa', native: 'Il Presepe' }, description: { pl: 'Tradycja budowania szopek jest we Włoszech bardzo silna, zwłaszcza w Neapolu, gdzie rzemieślnicy tworzą skomplikowane sceny z życia codziennego wokół Świętej Rodziny.', native: 'The tradition of building nativity scenes is very strong in Italy, especially in Naples, where artisans create intricate scenes of daily life around the Holy Family.' } },
        { name: { pl: 'Kolacja wigilijna', native: 'La Vigilia' }, description: { pl: 'Wigilia Bożego Narodzenia, tradycyjnie postna, znana jako "Uczta Siedmiu Ryb". Składa się z wielu dań rybnych i owoców morza, bez mięsa.', native: 'Christmas Eve, traditionally a fast day, known as the "Feast of the Seven Fishes." It consists of many fish and seafood dishes, without meat.' } },
        { name: { pl: 'Passeggiata', native: 'La Passeggiata' }, description: { pl: 'Wieczorny, niespieszny spacer po głównych ulicach lub placach miasta. To ważny rytuał społeczny, okazja do spotkań, rozmów i pokazania się.', native: 'An evening, leisurely stroll through the main streets or squares of a town. It is an important social ritual, an opportunity to meet, talk, and be seen.' } },
        { name: { pl: 'Rzucanie ryżem na ślubie', native: 'Il lancio del riso' }, description: { pl: 'Po ceremonii ślubnej goście obsypują parę młodą ryżem, co ma symbolizować płodność, bogactwo i szczęście.', native: 'After the wedding ceremony, guests shower the newlyweds with rice, which is meant to symbolize fertility, wealth, and happiness.' } },
        { name: { pl: 'Gra w bocce', native: 'Il gioco delle bocce' }, description: { pl: 'Tradycyjna gra w kule, popularna zwłaszcza wśród starszych mężczyzn. Gracze rzucają metalowe kule jak najbliżej małej kulki zwanej "pallino".', native: 'A traditional ball game, especially popular among older men. Players throw metal balls as close as possible to a small ball called the "pallino".' } },
        { name: { pl: 'Drzemka poobiednia', native: 'La siesta / pennichella' }, description: { pl: 'Krótka drzemka po obiedzie, szczególnie popularna w cieplejszych, południowych regionach, kiedy wiele sklepów jest zamykanych na kilka godzin.', native: 'A short nap after lunch, particularly popular in the warmer, southern regions, when many shops close for a few hours.' } },
        { name: { pl: 'Układanie kwiatów (Infiorata)', native: 'Infiorata' }, description: { pl: 'W okresie Bożego Ciała ulice wielu miast pokrywane są misternymi, kolorowymi dywanami ułożonymi z płatków kwiatów, tworzącymi religijne i artystyczne obrazy.', native: 'During the Corpus Christi period, the streets of many towns are covered with intricate, colorful carpets made of flower petals, creating religious and artistic images.' } },
        { name: { pl: 'Noc Świętego Wawrzyńca', native: 'Notte di San Lorenzo' }, description: { pl: 'W noc 10 sierpnia, znaną jako noc spadających gwiazd (Perseidów), Włosi gromadzą się, aby oglądać niebo i wypowiadać życzenia.', native: 'On the night of August 10th, known as the night of the shooting stars (Perseids), Italians gather to watch the sky and make wishes.' } },
    ],
    ui: { title: { pl: 'Tradycje', native: 'Tradizioni' }, backButton: { pl: 'Powrót do Kultury', native: 'Torna a Cultura' } }
  },
  es: {
    lang: 'es',
    traditions: [
        { name: { pl: 'La Tomatina', native: 'La Tomatina' }, description: { pl: 'Coroczna bitwa na pomidory odbywająca się w ostatnią środę sierpnia w Buñol. Tysiące ludzi z całego świata bierze udział w tej godzinnej, radosnej walce.', native: 'An annual tomato fight held on the last Wednesday of August in Buñol. Thousands of people from all over the world participate in this hour-long, joyous battle.' } },
        { name: { pl: 'Biegi byków w Pampelunie', native: 'San Fermín' }, description: { pl: 'Słynny festiwal w Pampelunie, którego główną atrakcją są "encierros" – biegi, w których śmiałkowie uciekają przed bykami po ulicach miasta.', native: 'A famous festival in Pamplona, whose main attraction is the "encierros" – runs in which brave participants flee from bulls through the city streets.' } },
        { name: { pl: 'Flamenco', native: 'Flamenco' }, description: { pl: 'Tradycyjna sztuka z Andaluzji, łącząca śpiew (cante), taniec (baile) i grę na gitarze (toque). To pełen pasji i emocji wyraz kultury południowej Hiszpanii.', native: 'A traditional art form from Andalusia, combining singing (cante), dancing (baile), and guitar playing (toque). It is an expression of passion and emotion from southern Spanish culture.' } },
        { name: { pl: 'Sjesta', native: 'Siesta' }, description: { pl: 'Tradycyjna popołudniowa drzemka, szczególnie powszechna w cieplejszych regionach. Wiele sklepów i firm zamyka się na kilka godzin po południu.', native: 'A traditional afternoon nap, especially common in warmer regions. Many shops and businesses close for a few hours in the afternoon.' } },
        { name: { pl: 'Kultura Tapas', native: 'La cultura de las tapas' }, description: { pl: 'Społeczny zwyczaj chodzenia od baru do baru, jedząc małe porcje jedzenia (tapas) i pijąc drinki. To sposób na spędzanie czasu z przyjaciółmi, a nie tylko posiłek.', native: 'The social custom of going from bar to bar, eating small portions of food (tapas) and having drinks. It is a way of spending time with friends, not just a meal.' } },
        { name: { pl: 'Las Fallas', native: 'Las Fallas' }, description: { pl: 'Festiwal ognia w Walencji, podczas którego przez kilka dni na ulicach stoją ogromne, satyryczne rzeźby (fallas), które na koniec są palone w spektakularny sposób.', native: 'A festival of fire in Valencia, during which huge, satirical sculptures (fallas) stand on the streets for several days, only to be spectacularly burned at the end.' } },
        { name: { pl: 'Semana Santa', native: 'Semana Santa' }, description: { pl: 'Wielki Tydzień, obchodzony w całej Hiszpanii z uroczystymi procesjami, podczas których bractwa (cofradías) niosą figury religijne ulicami miast.', native: 'Holy Week, celebrated throughout Spain with solemn processions, during which brotherhoods (cofradías) carry religious figures through the city streets.' } },
        { name: { pl: 'Dwanaście winogron w Sylwestra', native: 'Doce uvas de la suerte' }, description: { pl: 'O północy 31 grudnia Hiszpanie jedzą dwanaście winogron, po jednym na każde uderzenie zegara. Ma to przynieść szczęście w nadchodzącym roku.', native: 'At midnight on December 31st, Spaniards eat twelve grapes, one for each chime of the clock. This is supposed to bring good luck for the coming year.' } },
        { name: { pl: 'El Gordo', native: 'El Gordo' }, description: { pl: 'Hiszpańska loteria bożonarodzeniowa, jedna z największych na świecie. Losowanie 22 grudnia jest ważnym wydarzeniem społecznym, a wygrane często dzielone są w obrębie rodzin i lokalnych społeczności.', native: 'The Spanish Christmas Lottery, one of the largest in the world. The draw on December 22nd is an important social event, and winnings are often shared among families and local communities.' } },
        { name: { pl: 'Ludzkie wieże', native: 'Castells' }, description: { pl: 'Tradycja z Katalonii, polegająca na budowaniu wielopoziomowych wież z ludzi. To spektakularny pokaz siły, równowagi i współpracy.', native: 'A tradition from Catalonia, involving the building of multi-level human towers. It is a spectacular display of strength, balance, and teamwork.' } },
        { name: { pl: 'Feria de Abril', native: 'Feria de Abril' }, description: { pl: 'Tygodniowy festiwal w Sewilli, który odbywa się dwa tygodnie po Wielkanocy. Tereny targowe wypełniają się kolorowymi namiotami (casetas), muzyką, tańcem sevillanas i jedzeniem.', native: 'A week-long festival in Seville, held two weeks after Easter. The fairgrounds fill with colorful tents (casetas), music, sevillanas dancing, and food.' } },
        { name: { pl: 'Ogniska Świętego Jana', native: 'Hogueras de San Juan' }, description: { pl: 'W noc z 23 na 24 czerwca, szczególnie na wybrzeżu, pali się ogniska na plażach, aby powitać lato. Tradycją jest przeskakiwanie przez ogień i kąpiel w morzu o północy.', native: 'On the night of June 23rd to 24th, especially on the coast, bonfires are lit on the beaches to welcome summer. It is traditional to jump over the fire and swim in the sea at midnight.' } },
        { name: { pl: 'Dzień Trzech Króli', native: 'Día de Reyes' }, description: { pl: 'To 6 stycznia dzieci w Hiszpanii otrzymują prezenty, przyniesione przez Trzech Króli. Wieczorem 5 stycznia w miastach odbywają się uroczyste parady (Cabalgata de Reyes Magos).', native: 'It is on January 6th that children in Spain receive their presents, brought by the Three Kings. On the evening of January 5th, grand parades (Cabalgata de Reyes Magos) are held in cities.' } },
        { name: { pl: 'Karnawał w Kadyksie i na Teneryfie', native: 'Carnaval de Cádiz y Tenerife' }, description: { pl: 'Dwa z najsłynniejszych karnawałów w Hiszpanii. W Kadyksie króluje satyra i humorystyczne piosenki (chirigotas), a na Teneryfie widowiskowe parady i wybory królowej karnawału.', native: 'Two of the most famous carnivals in Spain. Cádiz is dominated by satire and humorous songs (chirigotas), while Tenerife features spectacular parades and the election of a carnival queen.' } },
        { name: { pl: 'Pielgrzymka (Romería)', native: 'La Romería' }, description: { pl: 'Religijna pielgrzymka do sanktuarium, która często przeradza się w ludowy festyn z jedzeniem, muzyką i tańcem. Najsłynniejsza to Romería de El Rocío w Andaluzji.', native: 'A religious pilgrimage to a shrine, which often turns into a folk festival with food, music, and dancing. The most famous is the Romería de El Rocío in Andalusia.' } },
    ],
    ui: { title: { pl: 'Tradycje', native: 'Tradiciones' }, backButton: { pl: 'Powrót do Kultury', native: 'Volver a Cultura' } }
  },
};
