import type { OddOneOutSet } from '../odd-one-out';

export const oddOneOutQuestionsEn: OddOneOutSet[] = [
    { words: ['Apple', 'Banana', 'Carrot', 'Orange', 'Grape', 'Strawberry'], correct: 'Carrot', category: { en: 'Fruits', de: 'Obst', fr: 'Fruits', es: 'Frutas', it: 'Frutta' } },
    { words: ['Dog', 'Lion', 'Cat', 'Table', 'Elephant', 'Tiger'], correct: 'Table', category: { en: 'Animals', de: 'Tiere', fr: 'Animaux', es: 'Animales', it: 'Animali' } },
    { words: ['Red', 'Blue', 'Green', 'Heavy', 'Yellow', 'Purple'], correct: 'Heavy', category: { en: 'Colors', de: 'Farben', fr: 'Couleurs', es: 'Colores', it: 'Colori' } },
    { words: ['Car', 'Bicycle', 'Airplane', 'Book', 'Train', 'Bus'], correct: 'Book', category: { en: 'Vehicles', de: 'Fahrzeuge', fr: 'Véhicules', es: 'Vehículos', it: 'Veicoli' } },
    { words: ['Shirt', 'Trousers', 'Spoon', 'Hat', 'Jacket', 'Socks'], correct: 'Spoon', category: { en: 'Clothes', de: 'Kleidung', fr: 'Vêtements', es: 'Ropa', it: 'Abbigliamento' } },
    { words: ['Happy', 'Sad', 'Tall', 'Angry', 'Excited', 'Scared'], correct: 'Tall', category: { en: 'Emotions', de: 'Emotionen', fr: 'Émotions', es: 'Emociones', it: 'Emozioni' } },
    { words: ['January', 'Monday', 'July', 'December', 'April', 'August'], correct: 'Monday', category: { en: 'Months', de: 'Monate', fr: 'Mois', es: 'Meses', it: 'Mesi' } },
    { words: ['Run', 'Swim', 'Sing', 'Chair', 'Jump', 'Read'], correct: 'Chair', category: { en: 'Verbs', de: 'Verben', fr: 'Verbes', es: 'Verbos', it: 'Verbi' } },
    { words: ['Paris', 'London', 'Berlin', 'Europe', 'Tokyo', 'Rome'], correct: 'Europe', category: { en: 'Cities', de: 'Städte', fr: 'Villes', es: 'Ciudades', it: 'Città' } },
    { words: ['Sofa', 'Armchair', 'Bed', 'Oven', 'Wardrobe', 'Desk'], correct: 'Oven', category: { en: 'Furniture', de: 'Möbel', fr: 'Meubles', es: 'Muebles', it: 'Mobili' } },
    { words: ['Math', 'History', 'Lunch', 'Science', 'English', 'Art'], correct: 'Lunch', category: { en: 'School Subjects', de: 'Schulfächer', fr: 'Matières scolaires', es: 'Asignaturas', it: 'Materie scolastiche' } },
    { words: ['Football', 'Basketball', 'Swimming', 'Cooking', 'Tennis', 'Baseball'], correct: 'Cooking', category: { en: 'Sports', de: 'Sportarten', fr: 'Sports', es: 'Deportes', it: 'Sport' } },
    { words: ['Guitar', 'Piano', 'Drums', 'Microphone', 'Violin', 'Trumpet'], correct: 'Microphone', category: { en: 'Musical Instruments', de: 'Musikinstrumente', fr: 'Instruments de musique', es: 'Instrumentos musicales', it: 'Strumenti musicali' } },
    { words: ['Sunny', 'Rainy', 'Cloudy', 'Windy', 'Snowy', 'Night'], correct: 'Night', category: { en: 'Weather', de: 'Wetter', fr: 'Météo', es: 'Tiempo', it: 'Meteo' } },
    { words: ['Hammer', 'Screwdriver', 'Wrench', 'Fork', 'Saw', 'Pliers'], correct: 'Fork', category: { en: 'Tools', de: 'Werkzeuge', fr: 'Outils', es: 'Herramientas', it: 'Attrezzi' } },
    { words: ['Potato', 'Onion', 'Broccoli', 'Apple', 'Spinach', 'Cabbage'], correct: 'Apple', category: { en: 'Vegetables', de: 'Gemüse', fr: 'Légumes', es: 'Verduras', it: 'Verdure' } },
    { words: ['Doctor', 'Teacher', 'Student', 'Engineer', 'Artist', 'Chef'], correct: 'Student', category: { en: 'Occupations', de: 'Berufe', fr: 'Métiers', es: 'Profesiones', it: 'Professioni' } },
    { words: ['Water', 'Juice', 'Milk', 'Bread', 'Tea', 'Coffee'], correct: 'Bread', category: { en: 'Drinks', de: 'Getränke', fr: 'Boissons', es: 'Bebidas', it: 'Bevande' } },
    { words: ['Head', 'Arm', 'Leg', 'Window', 'Foot', 'Hand'], correct: 'Window', category: { en: 'Body Parts', de: 'Körperteile', fr: 'Parties du corps', es: 'Partes del cuerpo', it: 'Parti del corpo' } },
    { words: ['Poland', 'Germany', 'France', 'Africa', 'Spain', 'Italy'], correct: 'Africa', category: { en: 'Countries', de: 'Länder', fr: 'Pays', es: 'Países', it: 'Paesi' } },
    { words: ['Circle', 'Square', 'Triangle', 'Loud', 'Rectangle', 'Star'], correct: 'Loud', category: { en: 'Shapes', de: 'Formen', fr: 'Formes', es: 'Formas', it: 'Forme' } },
    { words: ['Oven', 'Microwave', 'Blender', 'Sofa', 'Toaster', 'Kettle'], correct: 'Sofa', category: { en: 'Kitchen Appliances', de: 'Küchengeräte', fr: 'Appareils de cuisine', es: 'Electrodomésticos de cocina', it: 'Elettrodomestici da cucina' } },
    { words: ['Mother', 'Father', 'Brother', 'Friend', 'Sister', 'Uncle'], correct: 'Friend', category: { en: 'Family Members', de: 'Familienmitglieder', fr: 'Membres de la famille', es: 'Miembros de la familia', it: 'Membri della famiglia' } },
    { words: ['House', 'School', 'Hospital', 'River', 'Library', 'Station'], correct: 'River', category: { en: 'Buildings', de: 'Gebäude', fr: 'Bâtiments', es: 'Edificios', it: 'Edifici' } },
    { words: ['Mars', 'Jupiter', 'Saturn', 'Sun', 'Venus', 'Earth'], correct: 'Sun', category: { en: 'Planets', de: 'Planeten', fr: 'Planètes', es: 'Planetas', it: 'Pianeti' } },
    { words: ['English', 'Spanish', 'French', 'Math', 'German', 'Italian'], correct: 'Math', category: { en: 'Languages', de: 'Sprachen', fr: 'Langues', es: 'Idiomas', it: 'Lingue' } },
    { words: ['Fish', 'Whale', 'Dolphin', 'Shark', 'Octopus', 'Lion'], correct: 'Lion', category: { en: 'Sea Animals', de: 'Meerestiere', fr: 'Animaux marins', es: 'Animales marinos', it: 'Animali marini' } },
    { words: ['Cow', 'Pig', 'Sheep', 'Chicken', 'Horse', 'Tiger'], correct: 'Tiger', category: { en: 'Farm Animals', de: 'Bauernhoftiere', fr: 'Animaux de la ferme', es: 'Animales de granja', it: 'Animali da fattoria' } },
    { words: ['Asia', 'Europe', 'Africa', 'Australia', 'Brazil', 'America'], correct: 'Brazil', category: { en: 'Continents', de: 'Kontinente', fr: 'Continents', es: 'Continentes', it: 'Continenti' } },
    { words: ['Big', 'Small', 'Fast', 'Slow', 'Quickly', 'Tall'], correct: 'Quickly', category: { en: 'Adjectives', de: 'Adjektive', fr: 'Adjectifs', es: 'Adjetivos', it: 'Aggettivi' } }
];
