import type { OddOneOutSet } from '../odd-one-out';

export const oddOneOutQuestionsFr: OddOneOutSet[] = [
    { words: ['Pomme', 'Banane', 'Carotte', 'Orange', 'Raisin', 'Fraise'], correct: 'Carotte', category: { en: 'Fruits', de: 'Obst', fr: 'Fruits', es: 'Frutas', it: 'Frutta' } },
    { words: ['Chien', 'Lion', 'Chat', 'Table', 'Éléphant', 'Tigre'], correct: 'Table', category: { en: 'Animals', de: 'Tiere', fr: 'Animaux', es: 'Animales', it: 'Animali' } },
    { words: ['Rouge', 'Bleu', 'Vert', 'Lourd', 'Jaune', 'Violet'], correct: 'Lourd', category: { en: 'Colors', de: 'Farben', fr: 'Couleurs', es: 'Colores', it: 'Colori' } },
    { words: ['Voiture', 'Vélo', 'Avion', 'Livre', 'Train', 'Bus'], correct: 'Livre', category: { en: 'Vehicles', de: 'Fahrzeuge', fr: 'Véhicules', es: 'Vehículos', it: 'Veicoli' } },
    { words: ['Chemise', 'Pantalon', 'Cuillère', 'Chapeau', 'Veste', 'Chaussettes'], correct: 'Cuillère', category: { en: 'Clothes', de: 'Kleidung', fr: 'Vêtements', es: 'Ropa', it: 'Abbigliamento' } },
    { words: ['Heureux', 'Triste', 'Grand', 'En colère', 'Excité', 'Effrayé'], correct: 'Grand', category: { en: 'Emotions', de: 'Emotionen', fr: 'Émotions', es: 'Emociones', it: 'Emozioni' } },
    { words: ['Janvier', 'Lundi', 'Juillet', 'Décembre', 'Avril', 'Août'], correct: 'Lundi', category: { en: 'Months', de: 'Monate', fr: 'Mois', es: 'Meses', it: 'Mesi' } },
    { words: ['Courir', 'Nager', 'Chanter', 'Chaise', 'Sauter', 'Lire'], correct: 'Chaise', category: { en: 'Verbs', de: 'Verben', fr: 'Verbes', es: 'Verbos', it: 'Verbi' } },
    { words: ['Paris', 'Londres', 'Berlin', 'Europe', 'Tokyo', 'Rome'], correct: 'Europe', category: { en: 'Cities', de: 'Städte', fr: 'Villes', es: 'Ciudades', it: 'Città' } },
    { words: ['Canapé', 'Fauteuil', 'Lit', 'Four', 'Armoire', 'Bureau'], correct: 'Four', category: { en: 'Furniture', de: 'Möbel', fr: 'Meubles', es: 'Muebles', it: 'Mobili' } },
    { words: ['Maths', 'Histoire', 'Déjeuner', 'Science', 'Français', 'Art'], correct: 'Déjeuner', category: { en: 'School Subjects', de: 'Schulfächer', fr: 'Matières scolaires', es: 'Asignaturas', it: 'Materie scolastiche' } },
    { words: ['Football', 'Basketball', 'Natation', 'Cuisine', 'Tennis', 'Baseball'], correct: 'Cuisine', category: { en: 'Sports', de: 'Sportarten', fr: 'Sports', es: 'Deportes', it: 'Sport' } },
    { words: ['Guitare', 'Piano', 'Batterie', 'Microphone', 'Violon', 'Trompette'], correct: 'Microphone', category: { en: 'Musical Instruments', de: 'Musikinstrumente', fr: 'Instruments de musique', es: 'Instrumentos musicales', it: 'Strumenti musicali' } },
    { words: ['Ensoleillé', 'Pluvieux', 'Nuageux', 'Venteux', 'Neigeux', 'Nuit'], correct: 'Nuit', category: { en: 'Weather', de: 'Wetter', fr: 'Météo', es: 'Tiempo', it: 'Meteo' } },
    { words: ['Marteau', 'Tournevis', 'Clé', 'Fourchette', 'Scie', 'Pince'], correct: 'Fourchette', category: { en: 'Tools', de: 'Werkzeuge', fr: 'Outils', es: 'Herramientas', it: 'Attrezzi' } },
    { words: ['Pomme de terre', 'Oignon', 'Brocoli', 'Pomme', 'Épinards', 'Chou'], correct: 'Pomme', category: { en: 'Vegetables', de: 'Gemüse', fr: 'Légumes', es: 'Verduras', it: 'Verdure' } },
    { words: ['Médecin', 'Professeur', 'Étudiant', 'Ingénieur', 'Artiste', 'Chef'], correct: 'Étudiant', category: { en: 'Occupations', de: 'Berufe', fr: 'Métiers', es: 'Profesiones', it: 'Professioni' } },
    { words: ['Eau', 'Jus', 'Lait', 'Pain', 'Thé', 'Café'], correct: 'Pain', category: { en: 'Drinks', de: 'Getränke', fr: 'Boissons', es: 'Bebidas', it: 'Bevande' } },
    { words: ['Tête', 'Bras', 'Jambe', 'Fenêtre', 'Pied', 'Main'], correct: 'Fenêtre', category: { en: 'Body Parts', de: 'Körperteile', fr: 'Parties du corps', es: 'Partes del cuerpo', it: 'Parti del corpo' } },
    { words: ['Pologne', 'Allemagne', 'France', 'Afrique', 'Espagne', 'Italie'], correct: 'Afrique', category: { en: 'Countries', de: 'Länder', fr: 'Pays', es: 'Países', it: 'Paesi' } },
    { words: ['Cercle', 'Carré', 'Triangle', 'Fort', 'Rectangle', 'Étoile'], correct: 'Fort', category: { en: 'Shapes', de: 'Formen', fr: 'Formes', es: 'Formas', it: 'Forme' } },
    { words: ['Four', 'Micro-ondes', 'Mixeur', 'Canapé', 'Grille-pain', 'Bouilloire'], correct: 'Canapé', category: { en: 'Kitchen Appliances', de: 'Küchengeräte', fr: 'Appareils de cuisine', es: 'Electrodomésticos de cocina', it: 'Elettrodomestici da cucina' } },
    { words: ['Mère', 'Père', 'Frère', 'Ami', 'Sœur', 'Oncle'], correct: 'Ami', category: { en: 'Family Members', de: 'Familienmitglieder', fr: 'Membres de la famille', es: 'Miembros de la familia', it: 'Membri della famiglia' } },
    { words: ['Maison', 'École', 'Hôpital', 'Rivière', 'Bibliothèque', 'Gare'], correct: 'Rivière', category: { en: 'Buildings', de: 'Gebäude', fr: 'Bâtiments', es: 'Edificios', it: 'Edifici' } },
    { words: ['Mars', 'Jupiter', 'Saturne', 'Soleil', 'Vénus', 'Terre'], correct: 'Soleil', category: { en: 'Planets', de: 'Planeten', fr: 'Planètes', es: 'Planetas', it: 'Pianeti' } },
    { words: ['Français', 'Espagnol', 'Anglais', 'Maths', 'Allemand', 'Italien'], correct: 'Maths', category: { en: 'Languages', de: 'Sprachen', fr: 'Langues', es: 'Idiomas', it: 'Lingue' } },
    { words: ['Poisson', 'Baleine', 'Dauphin', 'Requin', 'Poulpe', 'Lion'], correct: 'Lion', category: { en: 'Sea Animals', de: 'Meerestiere', fr: 'Animaux marins', es: 'Animales marinos', it: 'Animali marini' } },
    { words: ['Vache', 'Cochon', 'Mouton', 'Poulet', 'Cheval', 'Tigre'], correct: 'Tigre', category: { en: 'Farm Animals', de: 'Bauernhoftiere', fr: 'Animaux de la ferme', es: 'Animales de granja', it: 'Animali da fattoria' } },
    { words: ['Asie', 'Europe', 'Afrique', 'Australie', 'Brésil', 'Amérique'], correct: 'Brésil', category: { en: 'Continents', de: 'Kontinente', fr: 'Continents', es: 'Continentes', it: 'Continenti' } },
    { words: ['Grand', 'Petit', 'Rapide', 'Lent', 'Vite', 'Haut'], correct: 'Vite', category: { en: 'Adjectives', de: 'Adjektive', fr: 'Adjectifs', es: 'Adjetivos', it: 'Aggettivi' } }
];
