import type { OddOneOutSet } from '../odd-one-out';

export const oddOneOutQuestionsEs: OddOneOutSet[] = [
    { words: ['Manzana', 'Plátano', 'Zanahoria', 'Naranja', 'Uva', 'Fresa'], correct: 'Zanahoria', category: { en: 'Fruits', de: 'Obst', fr: 'Fruits', es: 'Frutas', it: 'Frutta' } },
    { words: ['Perro', 'León', 'Gato', 'Mesa', 'Elefante', 'Tigre'], correct: 'Mesa', category: { en: 'Animals', de: 'Tiere', fr: 'Animaux', es: 'Animales', it: 'Animali' } },
    { words: ['Rojo', 'Azul', 'Verde', 'Pesado', 'Amarillo', 'Morado'], correct: 'Pesado', category: { en: 'Colors', de: 'Farben', fr: 'Couleurs', es: 'Colores', it: 'Colori' } },
    { words: ['Coche', 'Bicicleta', 'Avión', 'Libro', 'Tren', 'Autobús'], correct: 'Libro', category: { en: 'Vehicles', de: 'Fahrzeuge', fr: 'Véhicules', es: 'Vehículos', it: 'Veicoli' } },
    { words: ['Camisa', 'Pantalones', 'Cuchara', 'Sombrero', 'Chaqueta', 'Calcetines'], correct: 'Cuchara', category: { en: 'Clothes', de: 'Kleidung', fr: 'Vêtements', es: 'Ropa', it: 'Abbigliamento' } },
    { words: ['Feliz', 'Triste', 'Alto', 'Enojado', 'Emocionado', 'Asustado'], correct: 'Alto', category: { en: 'Emotions', de: 'Emotionen', fr: 'Émotions', es: 'Emociones', it: 'Emozioni' } },
    { words: ['Enero', 'Lunes', 'Julio', 'Diciembre', 'Abril', 'Agosto'], correct: 'Lunes', category: { en: 'Months', de: 'Monate', fr: 'Mois', es: 'Meses', it: 'Mesi' } },
    { words: ['Correr', 'Nadar', 'Cantar', 'Silla', 'Saltar', 'Leer'], correct: 'Silla', category: { en: 'Verbs', de: 'Verben', fr: 'Verbes', es: 'Verbos', it: 'Verbi' } },
    { words: ['París', 'Londres', 'Berlín', 'Europa', 'Tokio', 'Roma'], correct: 'Europa', category: { en: 'Cities', de: 'Städte', fr: 'Villes', es: 'Ciudades', it: 'Città' } },
    { words: ['Sofá', 'Sillón', 'Cama', 'Horno', 'Armario', 'Escritorio'], correct: 'Horno', category: { en: 'Furniture', de: 'Möbel', fr: 'Meubles', es: 'Muebles', it: 'Mobili' } },
    { words: ['Matemáticas', 'Historia', 'Almuerzo', 'Ciencia', 'Español', 'Arte'], correct: 'Almuerzo', category: { en: 'School Subjects', de: 'Schulfächer', fr: 'Matières scolaires', es: 'Asignaturas', it: 'Materie scolastiche' } },
    { words: ['Fútbol', 'Baloncesto', 'Natación', 'Cocina', 'Tenis', 'Béisbol'], correct: 'Cocina', category: { en: 'Sports', de: 'Sportarten', fr: 'Sports', es: 'Deportes', it: 'Sport' } },
    { words: ['Guitarra', 'Piano', 'Batería', 'Micrófono', 'Violín', 'Trompeta'], correct: 'Micrófono', category: { en: 'Musical Instruments', de: 'Musikinstrumente', fr: 'Instruments de musique', es: 'Instrumentos musicales', it: 'Strumenti musicali' } },
    { words: ['Soleado', 'Lluvioso', 'Nublado', 'Ventoso', 'Nevado', 'Noche'], correct: 'Noche', category: { en: 'Weather', de: 'Wetter', fr: 'Météo', es: 'Tiempo', it: 'Meteo' } },
    { words: ['Martillo', 'Destornillador', 'Llave inglesa', 'Tenedor', 'Sierra', 'Alicates'], correct: 'Tenedor', category: { en: 'Tools', de: 'Werkzeuge', fr: 'Outils', es: 'Herramientas', it: 'Attrezzi' } },
    { words: ['Patata', 'Cebolla', 'Brócoli', 'Manzana', 'Espinacas', 'Repollo'], correct: 'Manzana', category: { en: 'Vegetables', de: 'Gemüse', fr: 'Légumes', es: 'Verduras', it: 'Verdure' } },
    { words: ['Médico', 'Profesor', 'Estudiante', 'Ingeniero', 'Artista', 'Chef'], correct: 'Estudiante', category: { en: 'Occupations', de: 'Berufe', fr: 'Métiers', es: 'Profesiones', it: 'Professioni' } },
    { words: ['Agua', 'Jugo', 'Leche', 'Pan', 'Té', 'Café'], correct: 'Pan', category: { en: 'Drinks', de: 'Getränke', fr: 'Boissons', es: 'Bebidas', it: 'Bevande' } },
    { words: ['Cabeza', 'Brazo', 'Pierna', 'Ventana', 'Pie', 'Mano'], correct: 'Ventana', category: { en: 'Body Parts', de: 'Körperteile', fr: 'Parties du corps', es: 'Partes del cuerpo', it: 'Parti del corpo' } },
    { words: ['Polonia', 'Alemania', 'Francia', 'África', 'España', 'Italia'], correct: 'África', category: { en: 'Countries', de: 'Länder', fr: 'Pays', es: 'Países', it: 'Paesi' } },
    { words: ['Círculo', 'Cuadrado', 'Triángulo', 'Fuerte', 'Rectángulo', 'Estrella'], correct: 'Fuerte', category: { en: 'Shapes', de: 'Formen', fr: 'Formes', es: 'Formas', it: 'Forme' } },
    { words: ['Horno', 'Microondas', 'Licuadora', 'Sofá', 'Tostadora', 'Hervidor'], correct: 'Sofá', category: { en: 'Kitchen Appliances', de: 'Küchengeräte', fr: 'Appareils de cuisine', es: 'Electrodomésticos de cocina', it: 'Elettrodomestici da cucina' } },
    { words: ['Madre', 'Padre', 'Hermano', 'Amigo', 'Hermana', 'Tío'], correct: 'Amigo', category: { en: 'Family Members', de: 'Familienmitglieder', fr: 'Membres de la famille', es: 'Miembros de la familia', it: 'Membri della famiglia' } },
    { words: ['Casa', 'Escuela', 'Hospital', 'Río', 'Biblioteca', 'Estación'], correct: 'Río', category: { en: 'Buildings', de: 'Gebäude', fr: 'Bâtiments', es: 'Edificios', it: 'Edifici' } },
    { words: ['Marte', 'Júpiter', 'Saturno', 'Sol', 'Venus', 'Tierra'], correct: 'Sol', category: { en: 'Planets', de: 'Planeten', fr: 'Planètes', es: 'Planetas', it: 'Pianeti' } },
    { words: ['Español', 'Inglés', 'Francés', 'Matemáticas', 'Alemán', 'Italiano'], correct: 'Matemáticas', category: { en: 'Languages', de: 'Sprachen', fr: 'Langues', es: 'Idiomas', it: 'Lingue' } },
    { words: ['Pez', 'Ballena', 'Delfín', 'Tiburón', 'Pulpo', 'León'], correct: 'León', category: { en: 'Sea Animals', de: 'Meerestiere', fr: 'Animaux marins', es: 'Animales marinos', it: 'Animali marini' } },
    { words: ['Vaca', 'Cerdo', 'Oveja', 'Pollo', 'Caballo', 'Tigre'], correct: 'Tigre', category: { en: 'Farm Animals', de: 'Bauernhoftiere', fr: 'Animaux de la ferme', es: 'Animales de granja', it: 'Animali da fattoria' } },
    { words: ['Asia', 'Europa', 'África', 'Australia', 'Brasil', 'América'], correct: 'Brasil', category: { en: 'Continents', de: 'Kontinente', fr: 'Continents', es: 'Continentes', it: 'Continenti' } },
    { words: ['Grande', 'Pequeño', 'Rápido', 'Lento', 'Rápidamente', 'Alto'], correct: 'Rápidamente', category: { en: 'Adjectives', de: 'Adjektive', fr: 'Adjectifs', es: 'Adjetivos', it: 'Aggettivi' } }
];
