import type { OddOneOutSet } from '../odd-one-out';

export const oddOneOutQuestionsIt: OddOneOutSet[] = [
    { words: ['Mela', 'Banana', 'Carota', 'Arancia', 'Uva', 'Fragola'], correct: 'Carota', category: { en: 'Fruits', de: 'Obst', fr: 'Fruits', es: 'Frutas', it: 'Frutta' } },
    { words: ['Cane', 'Leone', 'Gatto', 'Tavolo', 'Elefante', 'Tigre'], correct: 'Tavolo', category: { en: 'Animals', de: 'Tiere', fr: 'Animaux', es: 'Animales', it: 'Animali' } },
    { words: ['Rosso', 'Blu', 'Verde', 'Pesante', 'Giallo', 'Viola'], correct: 'Pesante', category: { en: 'Colors', de: 'Farben', fr: 'Couleurs', es: 'Colores', it: 'Colori' } },
    { words: ['Auto', 'Bicicletta', 'Aereo', 'Libro', 'Treno', 'Autobus'], correct: 'Libro', category: { en: 'Vehicles', de: 'Fahrzeuge', fr: 'Véhicules', es: 'Vehículos', it: 'Veicoli' } },
    { words: ['Camicia', 'Pantaloni', 'Cucchiaio', 'Cappello', 'Giacca', 'Calzini'], correct: 'Cucchiaio', category: { en: 'Clothes', de: 'Kleidung', fr: 'Vêtements', es: 'Ropa', it: 'Abbigliamento' } },
    { words: ['Felice', 'Triste', 'Alto', 'Arrabbiato', 'Emozionato', 'Spaventato'], correct: 'Alto', category: { en: 'Emotions', de: 'Emotionen', fr: 'Émotions', es: 'Emociones', it: 'Emozioni' } },
    { words: ['Gennaio', 'Lunedì', 'Luglio', 'Dicembre', 'Aprile', 'Agosto'], correct: 'Lunedì', category: { en: 'Months', de: 'Monate', fr: 'Mois', es: 'Meses', it: 'Mesi' } },
    { words: ['Correre', 'Nuotare', 'Cantare', 'Sedia', 'Saltare', 'Leggere'], correct: 'Sedia', category: { en: 'Verbs', de: 'Verben', fr: 'Verbes', es: 'Verbos', it: 'Verbi' } },
    { words: ['Parigi', 'Londra', 'Berlino', 'Europa', 'Tokyo', 'Roma'], correct: 'Europa', category: { en: 'Cities', de: 'Städte', fr: 'Villes', es: 'Ciudades', it: 'Città' } },
    { words: ['Divano', 'Poltrona', 'Letto', 'Forno', 'Armadio', 'Scrivania'], correct: 'Forno', category: { en: 'Furniture', de: 'Möbel', fr: 'Meubles', es: 'Muebles', it: 'Mobili' } },
    { words: ['Matematica', 'Storia', 'Pranzo', 'Scienza', 'Italiano', 'Arte'], correct: 'Pranzo', category: { en: 'School Subjects', de: 'Schulfächer', fr: 'Matières scolaires', es: 'Asignaturas', it: 'Materie scolastiche' } },
    { words: ['Calcio', 'Basket', 'Nuoto', 'Cucina', 'Tennis', 'Baseball'], correct: 'Cucina', category: { en: 'Sports', de: 'Sportarten', fr: 'Sports', es: 'Deportes', it: 'Sport' } },
    { words: ['Chitarra', 'Pianoforte', 'Batteria', 'Microfono', 'Violino', 'Tromba'], correct: 'Microfono', category: { en: 'Musical Instruments', de: 'Musikinstrumente', fr: 'Instruments de musique', es: 'Instrumentos musicales', it: 'Strumenti musicali' } },
    { words: ['Soleggiato', 'Piovoso', 'Nuvoloso', 'Ventoso', 'Nevoso', 'Notte'], correct: 'Notte', category: { en: 'Weather', de: 'Wetter', fr: 'Météo', es: 'Tiempo', it: 'Meteo' } },
    { words: ['Martello', 'Cacciavite', 'Chiave inglese', 'Forchetta', 'Sega', 'Pinza'], correct: 'Forchetta', category: { en: 'Tools', de: 'Werkzeuge', fr: 'Outils', es: 'Herramientas', it: 'Attrezzi' } },
    { words: ['Patata', 'Cipolla', 'Broccoli', 'Mela', 'Spinaci', 'Cavolo'], correct: 'Mela', category: { en: 'Vegetables', de: 'Gemüse', fr: 'Légumes', es: 'Verduras', it: 'Verdure' } },
    { words: ['Medico', 'Insegnante', 'Studente', 'Ingegnere', 'Artista', 'Cuoco'], correct: 'Studente', category: { en: 'Occupations', de: 'Berufe', fr: 'Métiers', es: 'Profesiones', it: 'Professioni' } },
    { words: ['Acqua', 'Succo', 'Latte', 'Pane', 'Tè', 'Caffè'], correct: 'Pane', category: { en: 'Drinks', de: 'Getränke', fr: 'Boissons', es: 'Bebidas', it: 'Bevande' } },
    { words: ['Testa', 'Braccio', 'Gamba', 'Finestra', 'Piede', 'Mano'], correct: 'Finestra', category: { en: 'Body Parts', de: 'Körperteile', fr: 'Parties du corps', es: 'Partes del cuerpo', it: 'Parti del corpo' } },
    { words: ['Polonia', 'Germania', 'Francia', 'Africa', 'Spagna', 'Italia'], correct: 'Africa', category: { en: 'Countries', de: 'Länder', fr: 'Pays', es: 'Países', it: 'Paesi' } },
    { words: ['Cerchio', 'Quadrato', 'Triangolo', 'Forte', 'Rettangolo', 'Stella'], correct: 'Forte', category: { en: 'Shapes', de: 'Formen', fr: 'Formes', es: 'Formas', it: 'Forme' } },
    { words: ['Forno', 'Microonde', 'Frullatore', 'Divano', 'Tostapane', 'Bollitore'], correct: 'Divano', category: { en: 'Kitchen Appliances', de: 'Küchengeräte', fr: 'Appareils de cuisine', es: 'Electrodomésticos de cocina', it: 'Elettrodomestici da cucina' } },
    { words: ['Madre', 'Padre', 'Fratello', 'Amico', 'Sorella', 'Zio'], correct: 'Amico', category: { en: 'Family Members', de: 'Familienmitglieder', fr: 'Membres de la famille', es: 'Miembros de la familia', it: 'Membri della famiglia' } },
    { words: ['Casa', 'Scuola', 'Ospedale', 'Fiume', 'Biblioteca', 'Stazione'], correct: 'Fiume', category: { en: 'Buildings', de: 'Gebäude', fr: 'Bâtiments', es: 'Edificios', it: 'Edifici' } },
    { words: ['Marte', 'Giove', 'Saturno', 'Sole', 'Venere', 'Terra'], correct: 'Sole', category: { en: 'Planets', de: 'Planeten', fr: 'Planètes', es: 'Planetas', it: 'Pianeti' } },
    { words: ['Italiano', 'Spagnolo', 'Francese', 'Matematica', 'Tedesco', 'Inglese'], correct: 'Matematica', category: { en: 'Languages', de: 'Sprachen', fr: 'Langues', es: 'Idiomas', it: 'Lingue' } },
    { words: ['Pesce', 'Balena', 'Delfino', 'Squalo', 'Polpo', 'Leone'], correct: 'Leone', category: { en: 'Sea Animals', de: 'Meerestiere', fr: 'Animaux marins', es: 'Animales marinos', it: 'Animali marini' } },
    { words: ['Mucca', 'Maiale', 'Pecora', 'Pollo', 'Cavallo', 'Tigre'], correct: 'Tigre', category: { en: 'Farm Animals', de: 'Bauernhoftiere', fr: 'Animaux de la ferme', es: 'Animales de granja', it: 'Animali da fattoria' } },
    { words: ['Asia', 'Europa', 'Africa', 'Australia', 'Brasile', 'America'], correct: 'Brasile', category: { en: 'Continents', de: 'Kontinente', fr: 'Continents', es: 'Continentes', it: 'Continenti' } },
    { words: ['Grande', 'Piccolo', 'Veloce', 'Lento', 'Velocemente', 'Alto'], correct: 'Velocemente', category: { en: 'Adjectives', de: 'Adjektive', fr: 'Adjectifs', es: 'Adjetivos', it: 'Aggettivi' } }
];
