import type { OddOneOutSet } from '../odd-one-out';

export const oddOneOutQuestionsDe: OddOneOutSet[] = [
    { words: ['Apfel', 'Banane', 'Karotte', 'Orange', 'Traube', 'Erdbeere'], correct: 'Karotte', category: { en: 'Fruits', de: 'Obst', fr: 'Fruits', es: 'Frutas', it: 'Frutta' } },
    { words: ['Hund', 'Löwe', 'Katze', 'Tisch', 'Elefant', 'Tiger'], correct: 'Tisch', category: { en: 'Animals', de: 'Tiere', fr: 'Animaux', es: 'Animales', it: 'Animali' } },
    { words: ['Rot', 'Blau', 'Grün', 'Schwer', 'Gelb', 'Lila'], correct: 'Schwer', category: { en: 'Colors', de: 'Farben', fr: 'Couleurs', es: 'Colores', it: 'Colori' } },
    { words: ['Auto', 'Fahrrad', 'Flugzeug', 'Buch', 'Zug', 'Bus'], correct: 'Buch', category: { en: 'Vehicles', de: 'Fahrzeuge', fr: 'Véhicules', es: 'Vehículos', it: 'Veicoli' } },
    { words: ['Hemd', 'Hose', 'Löffel', 'Hut', 'Jacke', 'Socken'], correct: 'Löffel', category: { en: 'Clothes', de: 'Kleidung', fr: 'Vêtements', es: 'Ropa', it: 'Abbigliamento' } },
    { words: ['Glücklich', 'Traurig', 'Groß', 'Wütend', 'Aufgeregt', 'Ängstlich'], correct: 'Groß', category: { en: 'Emotions', de: 'Emotionen', fr: 'Émotions', es: 'Emociones', it: 'Emozioni' } },
    { words: ['Januar', 'Montag', 'Juli', 'Dezember', 'April', 'August'], correct: 'Montag', category: { en: 'Months', de: 'Monate', fr: 'Mois', es: 'Meses', it: 'Mesi' } },
    { words: ['Laufen', 'Schwimmen', 'Singen', 'Stuhl', 'Springen', 'Lesen'], correct: 'Stuhl', category: { en: 'Verbs', de: 'Verben', fr: 'Verbes', es: 'Verbos', it: 'Verbi' } },
    { words: ['Paris', 'London', 'Berlin', 'Europa', 'Tokio', 'Rom'], correct: 'Europa', category: { en: 'Cities', de: 'Städte', fr: 'Villes', es: 'Ciudades', it: 'Città' } },
    { words: ['Sofa', 'Sessel', 'Bett', 'Ofen', 'Kleiderschrank', 'Schreibtisch'], correct: 'Ofen', category: { en: 'Furniture', de: 'Möbel', fr: 'Meubles', es: 'Muebles', it: 'Mobili' } },
    { words: ['Mathe', 'Geschichte', 'Mittagessen', 'Wissenschaft', 'Deutsch', 'Kunst'], correct: 'Mittagessen', category: { en: 'School Subjects', de: 'Schulfächer', fr: 'Matières scolaires', es: 'Asignaturas', it: 'Materie scolastiche' } },
    { words: ['Fußball', 'Basketball', 'Schwimmen', 'Kochen', 'Tennis', 'Baseball'], correct: 'Kochen', category: { en: 'Sports', de: 'Sportarten', fr: 'Sports', es: 'Deportes', it: 'Sport' } },
    { words: ['Gitarre', 'Klavier', 'Schlagzeug', 'Mikrofon', 'Geige', 'Trompete'], correct: 'Mikrofon', category: { en: 'Musical Instruments', de: 'Musikinstrumente', fr: 'Instruments de musique', es: 'Instrumentos musicales', it: 'Strumenti musicali' } },
    { words: ['Sonnig', 'Regnerisch', 'Wolkig', 'Windig', 'Schneebedeckt', 'Nacht'], correct: 'Nacht', category: { en: 'Weather', de: 'Wetter', fr: 'Météo', es: 'Tiempo', it: 'Meteo' } },
    { words: ['Hammer', 'Schraubendreher', 'Schraubenschlüssel', 'Gabel', 'Säge', 'Zange'], correct: 'Gabel', category: { en: 'Tools', de: 'Werkzeuge', fr: 'Outils', es: 'Herramientas', it: 'Attrezzi' } },
    { words: ['Kartoffel', 'Zwiebel', 'Brokkoli', 'Apfel', 'Spinat', 'Kohl'], correct: 'Apfel', category: { en: 'Vegetables', de: 'Gemüse', fr: 'Légumes', es: 'Verduras', it: 'Verdure' } },
    { words: ['Arzt', 'Lehrer', 'Student', 'Ingenieur', 'Künstler', 'Koch'], correct: 'Student', category: { en: 'Occupations', de: 'Berufe', fr: 'Métiers', es: 'Profesiones', it: 'Professioni' } },
    { words: ['Wasser', 'Saft', 'Milch', 'Brot', 'Tee', 'Kaffee'], correct: 'Brot', category: { en: 'Drinks', de: 'Getränke', fr: 'Boissons', es: 'Bebidas', it: 'Bevande' } },
    { words: ['Kopf', 'Arm', 'Bein', 'Fenster', 'Fuß', 'Hand'], correct: 'Fenster', category: { en: 'Body Parts', de: 'Körperteile', fr: 'Parties du corps', es: 'Partes del cuerpo', it: 'Parti del corpo' } },
    { words: ['Polen', 'Deutschland', 'Frankreich', 'Afrika', 'Spanien', 'Italien'], correct: 'Afrika', category: { en: 'Countries', de: 'Länder', fr: 'Pays', es: 'Países', it: 'Paesi' } },
    { words: ['Kreis', 'Quadrat', 'Dreieck', 'Laut', 'Rechteck', 'Stern'], correct: 'Laut', category: { en: 'Shapes', de: 'Formen', fr: 'Formes', es: 'Formas', it: 'Forme' } },
    { words: ['Ofen', 'Mikrowelle', 'Mixer', 'Sofa', 'Toaster', 'Wasserkocher'], correct: 'Sofa', category: { en: 'Kitchen Appliances', de: 'Küchengeräte', fr: 'Appareils de cuisine', es: 'Electrodomésticos de cocina', it: 'Elettrodomestici da cucina' } },
    { words: ['Mutter', 'Vater', 'Bruder', 'Freund', 'Schwester', 'Onkel'], correct: 'Freund', category: { en: 'Family Members', de: 'Familienmitglieder', fr: 'Membres de la famille', es: 'Miembros de la familia', it: 'Membri della famiglia' } },
    { words: ['Haus', 'Schule', 'Krankenhaus', 'Fluss', 'Bibliothek', 'Bahnhof'], correct: 'Fluss', category: { en: 'Buildings', de: 'Gebäude', fr: 'Bâtiments', es: 'Edificios', it: 'Edifici' } },
    { words: ['Mars', 'Jupiter', 'Saturn', 'Sonne', 'Venus', 'Erde'], correct: 'Sonne', category: { en: 'Planets', de: 'Planeten', fr: 'Planètes', es: 'Planetas', it: 'Pianeti' } },
    { words: ['Deutsch', 'Spanisch', 'Französisch', 'Mathe', 'Englisch', 'Italienisch'], correct: 'Mathe', category: { en: 'Languages', de: 'Sprachen', fr: 'Langues', es: 'Idiomas', it: 'Lingue' } },
    { words: ['Fisch', 'Wal', 'Delfin', 'Hai', 'Oktopus', 'Löwe'], correct: 'Löwe', category: { en: 'Sea Animals', de: 'Meerestiere', fr: 'Animaux marins', es: 'Animales marinos', it: 'Animali marini' } },
    { words: ['Kuh', 'Schwein', 'Schaf', 'Huhn', 'Pferd', 'Tiger'], correct: 'Tiger', category: { en: 'Farm Animals', de: 'Bauernhoftiere', fr: 'Animaux de la ferme', es: 'Animales de granja', it: 'Animali da fattoria' } },
    { words: ['Asien', 'Europa', 'Afrika', 'Australien', 'Brasilien', 'Amerika'], correct: 'Brasilien', category: { en: 'Continents', de: 'Kontinente', fr: 'Continents', es: 'Continentes', it: 'Continenti' } },
    { words: ['Groß', 'Klein', 'Schnell', 'Langsam', 'Schnell (Adverb)', 'Hoch'], correct: 'Schnell (Adverb)', category: { en: 'Adjectives', de: 'Adjektive', fr: 'Adjectifs', es: 'Adjetivos', it: 'Aggettivi' } }
];
