
export interface Question {
  id: number;
  language: 'German';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'German', word: 'Alles in Butter', options: ['Wszystko w porządku', 'Jeść śniadanie', 'Coś jest nie tak', 'Wszystko w maśle'], correctAnswer: 'Wszystko w porządku' },
  { id: 2, language: 'German', word: 'Alle Viere von sich strecken', options: ['Rozciągać wszystkie kończyny', 'Być bardzo zmęczonym', 'Rozluźnić się całkowicie', 'Wstać energicznie'], correctAnswer: 'Rozluźnić się całkowicie' },
  { id: 3, language: 'German', word: 'Auf Wolke sieben sein', options: ['Być na siódmej chmurze', 'Być w siódmym niebie', 'Być bardzo smutnym', 'Latać samolotem'], correctAnswer: 'Być w siódmym niebie' },
  { id: 4, language: 'German', word: 'Auf dem Holzweg sein', options: ['Spacerować po lesie', 'Być w błędzie', 'Iść drewnianą ścieżką', 'Mieć rację'], correctAnswer: 'Być w błędzie' },
  { id: 5, language: 'German', word: 'Auf die Palme bringen', options: ['Wspinać się na palmę', 'Uspokajać kogoś', 'Doprowadzić do wściekłości', 'Jechać na wakacje'], correctAnswer: 'Doprowadzić do wściekłości' },
  { id: 6, language: 'German', word: 'Auf die Tube drücken', options: ['Naciskać na tubkę', 'Przyspieszyć coś', 'Zwolnić tempo', 'Malować obraz'], correctAnswer: 'Przyspieszyć coś' },
  { id: 7, language: 'German', word: 'Auf Herz und Nieren prüfen', options: ['Badać serce i nerki', 'Dokładnie sprawdzić', 'Zrobić badania lekarskie', 'Sprawdzać powierzchownie'], correctAnswer: 'Dokładnie sprawdzić' },
  { id: 8, language: 'German', word: 'Aus allen Wolken fallen', options: ['Spadać ze wszystkich chmur', 'Być bardzo zaskoczonym', 'Spodziewać się czegoś', 'Skakać ze spadochronem'], correctAnswer: 'Być bardzo zaskoczonym' },
  { id: 9, language: 'German', word: 'Aus dem Nähkästchen plaudern', options: ['Plotkować o szyciu', 'Wyjawić sekret', 'Rozmawiać o modzie', 'Szyć ubrania'], correctAnswer: 'Wyjawić sekret' },
  { id: 10, language: 'German', word: 'Aus dem Häuschen sein', options: ['Wyjść z domku', 'Być bardzo podekscytowanym', 'Być smutnym', 'Remontować dom'], correctAnswer: 'Być bardzo podekscytowanym' },
  { id: 11, language: 'German', word: 'Bärenhunger haben', options: ['Mieć głód niedźwiedzia', 'Być bardzo głodnym', 'Być najedzonym', 'Polować na niedźwiedzie'], correctAnswer: 'Być bardzo głodnym' },
  { id: 12, language: 'German', word: 'Das A und O sein', options: ['Być alfabetem', 'Być początkiem i końcem', 'Być najważniejszym', 'Być nieistotnym'], correctAnswer: 'Być najważniejszym' },
  { id: 13, language: 'German', word: 'Das Kind beim Schopfe packen', options: ['Łapać dziecko za włosy', 'Skorzystać z okazji', 'Wychowywać dziecko', 'Czekać na odpowiedni moment'], correctAnswer: 'Skorzystać z okazji' },
  { id: 14, language: 'German', word: 'Das ist Jacke wie Hose', options: ['To kurtka jak spodnie', 'To obojętne', 'Pasować idealnie', 'Ubierać się modnie'], correctAnswer: 'To obojętne' },
  { id: 15, language: 'German', word: 'Den Nagel auf den Kopf treffen', options: ['Uderzyć w gwóźdź', 'Trafić w sedno', 'Popełnić błąd', 'Budować coś'], correctAnswer: 'Trafić w sedno' },
  { id: 16, language: 'German', word: 'Den Teufel an die Wand malen', options: ['Malować diabła na ścianie', 'Wywoływać wilka z lasu', 'Wyolbrzymiać problem', 'Być optymistą'], correctAnswer: 'Wyolbrzymiać problem' },
  { id: 17, language: 'German', word: 'Den Wald vor lauter Bäumen nicht sehen', options: ['Nie widzieć lasu z powodu drzew', 'Nie dostrzegać oczywistości', 'Gubić się w lesie', 'Być spostrzegawczym'], correctAnswer: 'Nie dostrzegać oczywistości' },
  { id: 18, language: 'German', word: 'Die Daumen drücken', options: ['Ściskać kciuki', 'Trzymać kciuki', 'Mieć bolące palce', 'Grozić komuś'], correctAnswer: 'Trzymać kciuki' },
  { id: 19, language: 'German', word: 'Die Kirche im Dorf lassen', options: ['Zostawić kościół we wsi', 'Nie przesadzać', 'Iść na mszę', 'Budować kościół'], correctAnswer: 'Nie przesadzać' },
  { id: 20, language: 'German', word: 'Die Katze aus dem Sack lassen', options: ['Wypuścić kota z worka', 'Wyjawić sekret', 'Bawić się z kotem', 'Trzymać coś w tajemnicy'], correctAnswer: 'Wyjawić sekret' },
  { id: 21, language: 'German', word: 'Die Nase voll haben', options: ['Mieć pełny nos', 'Mieć katar', 'Mieć czegoś dość', 'Węszyć'], correctAnswer: 'Mieć czegoś dość' },
  { id: 22, language: 'German', word: 'Die Spreu vom Weizen trennen', options: ['Oddzielić plewy od pszenicy', 'Odróżnić ważne od nieistotnego', 'Pracować na roli', 'Robić mąkę'], correctAnswer: 'Odróżnić ważne od nieistotnego' },
  { id: 23, language: 'German', word: 'Ein Auge zudrücken', options: ['Zamknąć jedno oko', 'Przymknąć na coś oko', 'Mieć problemy ze wzrokiem', 'Obserwować uważnie'], correctAnswer: 'Przymknąć na coś oko' },
  { id: 24, language: 'German', word: 'Ein Brett vor dem Kopf haben', options: ['Mieć deskę przed głową', 'Być twardogłowym', 'Nie rozumieć czegoś oczywistego', 'Być mądrym'], correctAnswer: 'Nie rozumieć czegoś oczywistego' },
  { id: 25, language: 'German', word: 'Ein Herz und eine Seele sein', options: ['Być sercem i duszą', 'Być bardzo blisko z kimś', 'Być zakochanym', 'Mieć dobre serce'], correctAnswer: 'Być bardzo blisko z kimś' },
  { id: 26, language: 'German', word: 'Ein Schlag in die Magengrube', options: ['Uderzenie w żołądek', 'Szokujące doświadczenie', 'Ból brzucha', 'Przyjemna niespodzianka'], correctAnswer: 'Szokujące doświadczenie' },
  { id: 27, language: 'German', word: 'Ein Tropfen auf den heißen Stein', options: ['Kropla na gorącym kamieniu', 'Mały, nieznaczący efekt', 'Kropla w morzu potrzeb', 'Coś bardzo cennego'], correctAnswer: 'Kropla w morzu potrzeb' },
  { id: 28, language: 'German', word: 'Eine Extrawurst bekommen', options: ['Dostać dodatkową kiełbasę', 'Otrzymać specjalne traktowanie', 'Być głodnym', 'Lubić kiełbasę'], correctAnswer: 'Otrzymać specjalne traktowanie' },
  { id: 29, language: 'German', word: 'Eine Schraube locker haben', options: ['Mieć luźną śrubę', 'Być trochę szalonym', 'Naprawiać coś', 'Być poważnym'], correctAnswer: 'Być trochę szalonym' },
  { id: 30, language: 'German', word: 'Etwas auf die lange Bank schieben', options: ['Przesuwać coś na długą ławkę', 'Odkładać coś na później', 'Załatwić coś od razu', 'Siedzieć na ławce'], correctAnswer: 'Odkładać coś na później' },
  { id: 31, language: 'German', word: 'Etwas durch die Blume sagen', options: ['Powiedzieć coś przez kwiaty', 'Powiedzieć coś delikatnie', 'Mówić wprost', 'Dawać komuś kwiaty'], correctAnswer: 'Powiedzieć coś delikatnie' },
  { id: 32, language: 'German', word: 'Etwas unter den Tisch fallen lassen', options: ['Upuścić coś pod stół', 'Zignorować coś celowo', 'Ukrywać coś', 'Robić bałagan'], correctAnswer: 'Zignorować coś celowo' },
  { id: 33, language: 'German', word: 'Feuer und Flamme sein', options: ['Być ogniem i płomieniem', 'Być bardzo podekscytowanym', 'Gasić pożar', 'Być złym'], correctAnswer: 'Być bardzo podekscytowanym' },
  { id: 34, language: 'German', word: 'Fünf gerade sein lassen', options: ['Pozwolić piątce być prostą', 'Przymknąć na coś oko', 'Być dokładnym', 'Liczyć do pięciu'], correctAnswer: 'Przymknąć na coś oko' },
  { id: 35, language: 'German', word: 'Für jemanden die Hand ins Feuer legen', options: ['Włożyć za kogoś rękę do ognia', 'Dać za kogoś gwarancję', 'Narazić kogoś na niebezpieczeństwo', 'Rozpalać ognisko'], correctAnswer: 'Dać za kogoś gwarancję' },
  { id: 36, language: 'German', word: 'Für etwas gerade stehen', options: ['Stać prosto za coś', 'Pnosić odpowiedzialność', 'Bronić czegoś', 'Unikać konsekwencji'], correctAnswer: 'Pnosić odpowiedzialność' },
  { id: 37, language: 'German', word: 'Hals- und Beinbruch', options: ['Złamania szyi i nogi', 'Powodzenia!', 'Życzyć komuś źle', 'Iść do szpitala'], correctAnswer: 'Powodzenia!' },
  { id: 38, language: 'German', word: 'Hand in Hand gehen', options: ['Iść ręka w rękę', 'Iść ramię w ramię', 'Współpracować', 'Spacerować'], correctAnswer: 'Iść ramię w ramię' },
  { id: 39, language: 'German', word: 'Ins Gras beißen', options: ['Gryźć trawę', 'Umrzeć', 'Jeść sałatkę', 'Leżeć na trawie'], correctAnswer: 'Umrzeć' },
  { id: 40, language: 'German', word: 'Ins kalte Wasser springen', options: ['Skakać do zimnej wody', 'Zrobić coś odważnie', 'Pływać w jeziorze', 'Unikać wyzwań'], correctAnswer: 'Zrobić coś odważnie' },
  { id: 41, language: 'German', word: 'Jemandem den Rücken stärken', options: ['Wzmacniać komuś plecy', 'Masować plecy', 'Wspierać kogoś', 'Atakować od tyłu'], correctAnswer: 'Wspierać kogoś' },
  { id: 42, language: 'German', word: 'Jemandem Honig ums Maul schmieren', options: ['Smarować komuś usta miodem', 'Pochlebiać komuś', 'Karmić miodem', 'Mówić prawdę'], correctAnswer: 'Pochlebiać komuś' },
  { id: 43, language: 'German', word: 'Jemandem auf den Keks gehen', options: ['Iść komuś na ciastko', 'Denerwować kogoś', 'Częstować ciastkami', 'Lubić kogoś'], correctAnswer: 'Denerwować kogoś' },
  { id: 44, language: 'German', word: 'Jemandem einen Bären aufbinden', options: ['Przywiązać komuś niedźwiedzia', 'Oszukać kogoś', 'Opowiadać bajki', 'Iść do zoo'], correctAnswer: 'Oszukać kogoś' },
  { id: 45, language: 'German', word: 'Jemandem die Daumen drücken', options: ['Wyciskać komuś kciuki', 'Trzymać za kogoś kciuki', 'Grozić komuś', 'Bić kogoś'], correctAnswer: 'Trzymać za kogoś kciuki' },
  { id: 46, language: 'German', word: 'Jemandem die Suppe versalzen', options: ['Przesolić komuś zupę', 'Psuć komuś przyjemność', 'Gotować zupę', 'Dzielić się jedzeniem'], correctAnswer: 'Psuć komuś przyjemność' },
  { id: 47, language: 'German', word: 'Jemandem unter die Arme greifen', options: ['Chwycić kogoś pod ramię', 'Pomóc komuś', 'Prowadzić kogoś', 'Atakować kogoś'], correctAnswer: 'Pomóc komuś' },
  { id: 48, language: 'German', word: 'Jemanden auf die Palme bringen', options: ['Wprowadzić kogoś na palmę', 'Doprowadzić kogoś do wściekłości', 'Pomóc się wspinać', 'Wysłać na wakacje'], correctAnswer: 'Doprowadzić kogoś do wściekłości' },
  { id: 49, language: 'German', word: 'Jemanden durch den Kakao ziehen', options: ['Przeciągnąć kogoś przez kakao', 'Wyśmiewać kogoś', 'Robić gorącą czekoladę', 'Brudzić kogoś'], correctAnswer: 'Wyśmiewać kogoś' },
  { id: 50, language: 'German', word: 'Jemanden ins kalte Wasser werfen', options: ['Wrzucić kogoś do zimnej wody', 'Wystawić kogoś na próbę', 'Uczyć pływać', 'Żartować z kogoś'], correctAnswer: 'Wystawić kogoś na próbę' },
  { id: 51, language: 'German', word: 'Jemanden mit offenen Armen empfangen', options: ['Przyjąć kogoś z otwartymi ramionami', 'Przyjąć kogoś serdecznie', 'Przytulić kogoś', 'Odrzucić kogoś'], correctAnswer: 'Przyjąć kogoś serdecznie' },
  { id: 52, language: 'German', word: 'Jemanden auf die Schippe nehmen', options: ['Wziąć kogoś na łopatę', 'Nabierać kogoś', 'Pracować z kimś', 'Przenosić kogoś'], correctAnswer: 'Nabierać kogoś' },
  { id: 53, language: 'German', word: 'Jemanden auf die Finger schauen', options: ['Patrzeć komuś na palce', 'Pilnować kogoś', 'Podziwiać czyjeś dłonie', 'Grać na pianinie'], correctAnswer: 'Pilnować kogoś' },
  { id: 54, language: 'German', word: 'Jemanden ins Herz schließen', options: ['Zamknąć kogoś w sercu', 'Polubić kogoś bardzo', 'Zakochać się', 'Mieć problemy z sercem'], correctAnswer: 'Polubić kogoś bardzo' },
  { id: 55, language: 'German', word: 'Jemanden über den Tisch ziehen', options: ['Przeciągnąć kogoś przez stół', 'Oszukać kogoś', 'Pokonać w siłowaniu na rękę', 'Przesunąć stół'], correctAnswer: 'Oszukać kogoś' },
  { id: 56, language: 'German', word: 'Jemanden vom Hocker reißen', options: ['Zerwać kogoś ze stołka', 'Zadziwić kogoś', 'Przewrócić kogoś', 'Pomóc wstać'], correctAnswer: 'Zadziwić kogoś' },
  { id: 57, language: 'German', word: 'Jemanden vor den Kopf stoßen', options: ['Uderzyć kogoś w głowę', 'Urazić kogoś', 'Zaskoczyć kogoś', 'Zgodzić się z kimś'], correctAnswer: 'Urazić kogoś' },
  { id: 58, language: 'German', word: 'Jemanden zur Schnecke machen', options: ['Zrobić z kogoś ślimaka', 'Zbesztać kogoś', 'Spowolnić kogoś', 'Bawić się ze ślimakami'], correctAnswer: 'Zbesztać kogoś' },
  { id: 59, language: 'German', word: 'Jemandem einen Strich durch die Rechnung machen', options: ['Zrobić komuś kreskę w rachunku', 'Pokrzyżować komuś plany', 'Pomóc w liczeniu', 'Popełnić błąd w obliczeniach'], correctAnswer: 'Pokrzyżować komuś plany' },
  { id: 60, language: 'German', word: 'Jemandem den Wind aus den Segeln nehmen', options: ['Zabrać komuś wiatr z żagli', 'Odebrać komuś inicjatywę', 'Pomóc żeglować', 'Uszkodzić żagiel'], correctAnswer: 'Odebrać komuś inicjatywę' },
  { id: 61, language: 'German', word: 'Kein Blatt vor den Mund nehmen', options: ['Nie brać liścia przed usta', 'Mówić wprost', 'Jeść sałatę', 'Być nieśmiałym'], correctAnswer: 'Mówić wprost' },
  { id: 62, language: 'German', word: 'Geld wie Heu haben', options: ['Mieć pieniądze jak siano', 'Mieć dużo pieniędzy', 'Być biednym', 'Pracować na farmie'], correctAnswer: 'Mieć dużo pieniędzy' },
  { id: 63, language: 'German', word: 'Kein Licht am Ende des Tunnels sehen', options: ['Nie widzieć światła na końcu tunelu', 'Nie widzieć rozwiązania', 'Być w ciemnym tunelu', 'Być optymistą'], correctAnswer: 'Nie widzieć rozwiązania' },
  { id: 64, language: 'German', word: 'Kein Ohr für etwas haben', options: ['Nie mieć ucha do czegoś', 'Nie chcieć czegoś słuchać', 'Być głuchym', 'Słuchać uważnie'], correctAnswer: 'Nie chcieć czegoś słuchać' },
  { id: 65, language: 'German', word: 'Klar wie Kloßbrühe', options: ['Jasne jak bulion kluskowy', 'Bardzo jasne', 'Coś niezrozumiałego', 'Gotować zupę'], correctAnswer: 'Bardzo jasne' },
  { id: 66, language: 'German', word: 'Krokodilstränen weinen', options: ['Płakać krokodylimi łzami', 'Fałszywie płakać', 'Bać się krokodyli', 'Płakać ze szczęścia'], correctAnswer: 'Fałszywie płakać' },
  { id: 67, language: 'German', word: 'Kurz und bündig', options: ['Krótko i zwięźle', 'Długo i rozwlekle', 'Pisać list', 'Mówić szybko'], correctAnswer: 'Krótko i zwięźle' },
  { id: 68, language: 'German', word: 'Mit dem Kopf durch die Wand', options: ['Iść z głową przez ścianę', 'Być upartym', 'Rozbijać ścianę', 'Podejmować ryzyko'], correctAnswer: 'Być upartym' },
  { id: 69, language: 'German', word: 'Mit allen Wassern gewaschen sein', options: ['Być umytym wszystkimi wodami', 'Być doświadczonym', 'Być mokrym', 'Pływać w morzu'], correctAnswer: 'Być doświadczonym' },
  { id: 70, language: 'German', word: 'Mit jemandem durch dick und dünn gehen', options: ['Iść z kimś przez grube i cienkie', 'Być razem w trudnych chwilach', 'Chodzić na spacery', 'Tylko w dobrych chwilach'], correctAnswer: 'Być razem w trudnych chwilach' },
  { id: 71, language: 'German', word: 'Mit Kanonen auf Spatzen schießen', options: ['Strzelać z armat do wróbli', 'Przesadzać', 'Używać zbyt silnych środków', 'Polować na ptaki'], correctAnswer: 'Przesadzać' },
  { id: 72, language: 'German', word: 'Mit einem blauen Auge davonkommen', options: ['Uciec z podbitym okiem', 'Wyjść z czegoś lekko', 'Mieć siniaka', 'Uniknąć kary'], correctAnswer: 'Wyjść z czegoś lekko' },
  { id: 73, language: 'German', word: 'Nach dem Rechten sehen', options: ['Patrzeć na prawo', 'Sprawdzić sytuację', 'Szukać czegoś', 'Być sędzią'], correctAnswer: 'Sprawdzić sytuację' },
  { id: 74, language: 'German', word: 'Nach dem Mund reden', options: ['Mówić według ust', 'Pochlebiać komuś', 'Mówić niewyraźnie', 'Powtarzać po kimś'], correctAnswer: 'Pochlebiać komuś' },
  { id: 75, language: 'German', word: 'Nicht alle Tassen im Schrank haben', options: ['Nie mieć wszystkich filiżanek w szafie', 'Być trochę szalonym', 'Robić porządki', 'Pić herbatę'], correctAnswer: 'Być trochę szalonym' },
  { id: 76, language: 'German', word: 'Nicht das Gelbe vom Ei sein', options: ['Nie być żółtkiem z jajka', 'Nie być idealnym', 'Być zepsutym', 'Gotować jajka'], correctAnswer: 'Nie być idealnym' },
  { id: 77, language: 'German', word: 'Nicht auf den Kopf gefallen sein', options: ['Nie upaść na głowę', 'Być bystrym', 'Być niezdarnym', 'Mieć zawroty głowy'], correctAnswer: 'Być bystrym' },
  { id: 78, language: 'German', word: 'Nicht den Kopf in den Sand stecken', options: ['Nie wkładać głowy w piasek', 'Nie poddawać się', 'Chować się przed problemem', 'Iść na plażę'], correctAnswer: 'Nie poddawać się' },
  { id: 79, language: 'German', word: 'Nicht über alle Berge sein', options: ['Nie być za wszystkimi górami', 'Nie zniknąć całkowicie', 'Być bezpiecznym', 'Wspinać się po górach'], correctAnswer: 'Nie zniknąć całkowicie' },
  { id: 80, language: 'German', word: 'Nur Bahnhof verstehen', options: ['Rozumieć tylko dworzec', 'Nie rozumieć nic', 'Czekać na pociąg', 'Podróżować koleją'], correctAnswer: 'Nie rozumieć nic' },
  { id: 81, language: 'German', word: 'Perlen vor die Säue werfen', options: ['Rzucać perły przed świnie', 'Marnować coś wartościowego', 'Karmić świnie', 'Być hojnym'], correctAnswer: 'Marnować coś wartościowego' },
  { id: 82, language: 'German', word: 'Quark mit Soße', options: ['Twaróg z sosem', 'Coś bez sensu', 'Jeść deser', 'Przepis kulinarny'], correctAnswer: 'Coś bez sensu' },
  { id: 83, language: 'German', word: 'Schwein haben', options: ['Mieć świnię', 'Mieć szczęście', 'Być brudnym', 'Hodować zwierzęta'], correctAnswer: 'Mieć szczęście' },
  { id: 84, language: 'German', word: 'Sich die Haare raufen', options: ['Wyrywać sobie włosy', 'Frustrować się', 'Czesać się', 'Iść do fryzjera'], correctAnswer: 'Frustrować się' },
  { id: 85, language: 'German', word: 'Sich ins Zeug legen', options: ['Położyć się w rzeczach', 'Bardzo się starać', 'Odpoczywać', 'Robić bałagan'], correctAnswer: 'Bardzo się starać' },
  { id: 86, language: 'German', word: 'Sich nicht in die Karten schauen lassen', options: ['Nie pozwalać patrzeć w swoje karty', 'Nie pokazywać planów', 'Grać w karty', 'Być szczerym'], correctAnswer: 'Nie pokazywać planów' },
  { id: 87, language: 'German', word: 'Sich zum Affen machen', options: ['Robić z siebie małpę', 'Ośmieszyć się', 'Iść do zoo', 'Bawić się'], correctAnswer: 'Ośmieszyć się' },
  { id: 88, language: 'German', word: 'Sich wie ein Fisch im Wasser fühlen', options: ['Czuć się jak ryba w wodzie', 'Czuć się komfortowo', 'Pływać', 'Być mokrym'], correctAnswer: 'Czuć się komfortowo' },
  { id: 89, language: 'German', word: 'Sich auf die faule Haut legen', options: ['Kłaść się na leniwą skórę', 'Leniuchować', 'Opalać się', 'Ciężko pracować'], correctAnswer: 'Leniuchować' },
  { id: 90, language: 'German', word: 'Sich etwas hinter die Ohren schreiben', options: ['Zapisać coś sobie za uszami', 'Zapamiętać coś', 'Robić notatki', 'Słuchać uważnie'], correctAnswer: 'Zapamiętać coś' },
  { id: 91, language: 'German', word: 'Sich etwas nicht nehmen lassen', options: ['Nie dać sobie czegoś zabrać', 'Nie pozwolić sobie odebrać', 'Być upartym', 'Bronić swoich rzeczy'], correctAnswer: 'Nie pozwolić sobie odebrać' },
  { id: 92, language: 'German', word: 'Sich etwas durch den Kopf gehen lassen', options: ['Pozwolić czemuś przejść przez głowę', 'Przemyśleć coś', 'Mieć ból głowy', 'Zapomnieć o czymś'], correctAnswer: 'Przemyśleć coś' },
  { id: 93, language: 'German', word: 'Sich etwas vom Munde absparen', options: ['Oszczędzać coś z ust', 'Oszczędzać', 'Być na diecie', 'Mówić mało'], correctAnswer: 'Oszczędzać' },
  { id: 94, language: 'German', word: 'Sich die Zähne ausbeißen', options: ['Wybić sobie zęby', 'Męczyć się z czymś', 'Jeść twarde rzeczy', 'Iść do dentysty'], correctAnswer: 'Męczyć się z czymś' },
  { id: 95, language: 'German', word: 'Sich keinen Kopf machen', options: ['Nie robić sobie głowy', 'Nie martwić się', 'Być beztroskim', 'Myśleć intensywnie'], correctAnswer: 'Nie martwić się' },
  { id: 96, language: 'German', word: 'Sich nicht lumpen lassen', options: ['Nie dać się oszukać', 'Nie oszczędzać wysiłku', 'Być hojnym', 'Być skąpym'], correctAnswer: 'Nie oszczędzać wysiłku' },
  { id: 97, language: 'German', word: 'Sich um Kopf und Kragen reden', options: ['Mówić o głowie i kołnierzu', 'Narazić się słowami', 'Plotkować', 'Dużo mówić'], correctAnswer: 'Narazić się słowami' },
  { id: 98, language: 'German', word: 'Sich von der Leber wegreden', options: ['Mówić od wątroby', 'Mówić szczerze', 'Mówić co ślina na język przyniesie', 'Być chorym na wątrobę'], correctAnswer: 'Mówić szczerze' },
  { id: 99, language: 'German', word: 'Sich etwas auf die Fahne schreiben', options: ['Zapisać coś sobie na fladze', 'Być z czegoś dumnym', 'Rysować flagę', 'Postawić sobie za cel'], correctAnswer: 'Być z czegoś dumnym' },
  { id: 100, language: 'German', word: 'Stehaufmännchen sein', options: ['Być wańką-wstańką', 'Być odpornym na porażki', 'Zawsze wstawać', 'Bawić się zabawką'], correctAnswer: 'Być odpornym na porażki' },
  { id: 101, language: 'German', word: 'Sturm im Wasserglas', options: ['Burza w szklance wody', 'Problem wyolbrzymiony', 'Pić wodę', 'Robić eksperyment'], correctAnswer: 'Problem wyolbrzymiony' },
  { id: 102, language: 'German', word: 'Tausend Meilen entfernt sein', options: ['Być oddalonym o tysiąc mil', 'Być bardzo daleko', 'Myśleć o czymś innym', 'Podróżować'], correctAnswer: 'Być bardzo daleko' },
  { id: 103, language: 'German', word: 'Tomaten auf den Augen haben', options: ['Mieć pomidory na oczach', 'Nie zauważać czegoś', 'Mieć czerwone oczy', 'Robić sałatkę'], correctAnswer: 'Nie zauważać czegoś' },
  { id: 104, language: 'German', word: 'Über den eigenen Schatten springen', options: ['Przeskoczyć własny cień', 'Przełamać własne ograniczenia', 'Skakać w dal', 'Bawić się cieniem'], correctAnswer: 'Przełamać własne ograniczenia' },
  { id: 105, language: 'German', word: 'Über die Stränge schlagen', options: ['Uderzyć w pasy', 'Przesadzić', 'Karać konia', 'Przekroczyć granice'], correctAnswer: 'Przesadzić' },
  { id: 106, language: 'German', word: 'Unter vier Augen sprechen', options: ['Rozmawiać pod czterema oczami', 'Rozmawiać prywatnie', 'Nosić okulary', 'Rozmawiać w cztery oczy'], correctAnswer: 'Rozmawiać prywatnie' },
  { id: 107, language: 'German', word: 'Unter die Haube kommen', options: ['Wejść pod czepek', 'Wyjść za mąż/żenić się', 'Nosić nakrycie głowy', 'Ukrywać się'], correctAnswer: 'Wyjść za mąż/żenić się' },
  { id: 108, language: 'German', word: 'Unter den Tisch fallen lassen', options: ['Upuścić pod stół', 'Zignorować coś', 'Schować pod stołem', 'Uniknąć tematu'], correctAnswer: 'Zignorować coś' },
  { id: 109, language: 'German', word: 'Von der Hand in den Mund leben', options: ['Żyć z ręki do ust', 'Żyć z dnia na dzień', 'Jeść rękami', 'Być biednym'], correctAnswer: 'Żyć z dnia na dzień' },
  { id: 110, language: 'German', word: 'Von allen guten Geistern verlassen sein', options: ['Być opuszczonym przez wszystkie dobre duchy', 'Być kompletnie zagubionym', 'Bać się duchów', 'Być samotnym'], correctAnswer: 'Być kompletnie zagubionym' },
  { id: 111, language: 'German', word: 'Vor der eigenen Tür kehren', options: ['Zamiatać przed własnymi drzwiami', 'Zająć się swoimi sprawami', 'Robić porządki', 'Krytykować innych'], correctAnswer: 'Zająć się swoimi sprawami' },
  { id: 112, language: 'German', word: 'Vor die Hunde gehen', options: ['Iść przed psy', 'Upadać, degenerować się', 'Iść na spacer z psem', 'Być w złej sytuacji'], correctAnswer: 'Upadać, degenerować się' },
  { id: 113, language: 'German', word: 'Vor die Wand fahren', options: ['Wjechać w ścianę', 'Zawalić coś całkowicie', 'Mieć wypadek', 'Ponieść porażkę'], correctAnswer: 'Zawalić coś całkowicie' },
  { id: 114, language: 'German', word: 'Vor Freude strahlen', options: ['Promienieć z radości', 'Być bardzo szczęśliwym', 'Uśmiechać się szeroko', 'Opalać się'], correctAnswer: 'Być bardzo szczęśliwym' },
  { id: 115, language: 'German', word: 'Vor sich hin dämmern', options: ['Drzemać przed sobą', 'Być w lekkim letargu', 'Śnić na jawie', 'Odpoczywać'], correctAnswer: 'Być w lekkim letargu' },
  { id: 116, language: 'German', word: 'Vor etwas die Augen verschließen', options: ['Zamykać oczy przed czymś', 'Ignorować coś', 'Nie chcieć czegoś widzieć', 'Udawać ślepego'], correctAnswer: 'Ignorować coś' },
  { id: 117, language: 'German', word: 'Wasser auf die Mühlen gießen', options: ['Lać wodę na młyny', 'Wzmacniać argumenty przeciwnika', 'Pomagać komuś nieświadomie', 'Pracować w młynie'], correctAnswer: 'Wzmacniać argumenty przeciwnika' },
  { id: 118, language: 'German', word: 'Wie aus dem Ei gepellt sein', options: ['Być jak z jajka obrany', 'Być perfekcyjnie ubranym', 'Wyglądać świeżo', 'Jeść jajka'], correctAnswer: 'Być perfekcyjnie ubranym' },
  { id: 119, language: 'German', word: 'Wie ein Stein im Brett haben', options: ['Mieć kamień w desce', 'Mieć przewagę u kogoś', 'Mieć u kogoś fory', 'Grać w planszówki'], correctAnswer: 'Mieć u kogoś fory' },
  { id: 120, language: 'German', word: 'Wie ein Lauffeuer verbreiten', options: ['Rozprzestrzeniać się jak ogień', 'Rozprzestrzeniać się szybko', 'Palić las', 'Gasić pożar'], correctAnswer: 'Rozprzestrzeniać się szybko' },
  { id: 121, language: 'German', word: 'Wie man in den Wald hineinruft, so schallt es heraus', options: ['Jak się w lesie woła, tak się odbija', 'Reakcje odpowiadają zachowaniom', 'Jak Kuba Bogu, tak Bóg Kubie', 'Krzyczeć w lesie'], correctAnswer: 'Jak Kuba Bogu, tak Bóg Kubie' },
  { id: 122, language: 'German', word: 'Wie ein Elefant im Porzellanladen', options: ['Jak słoń w składzie porcelany', 'Być niezręcznym', 'Niszczyć wszystko', 'Odwiedzać sklep'], correctAnswer: 'Być niezręcznym' },
  { id: 123, language: 'German', word: 'Wie die Katze um den heißen Brei schleichen', options: ['Chodzić jak kot koło gorącej kaszy', 'Owijać w bawełnę', 'Unikać tematu', 'Być ostrożnym'], correctAnswer: 'Owijać w bawełnę' },
  { id: 124, language: 'German', word: 'Wie auf heißen Kohlen sitzen', options: ['Siedzieć jak na gorących węglach', 'Być bardzo niespokojnym', 'Grillować', 'Opalać się'], correctAnswer: 'Być bardzo niespokojnym' },
  { id: 125, language: 'German', word: 'Wie ein rotes Tuch wirken', options: ['Działać jak czerwona płachta', 'Prowokować kogoś', 'Być zły jak byk', 'Oglądać corridę'], correctAnswer: 'Prowokować kogoś' },
  { id: 126, language: 'German', word: 'Willst du mit mir gehen?', options: ['Chcesz ze mną iść?', 'Zaproszenie na randkę', 'Propozycja chodzenia ze sobą', 'Iść na spacer'], correctAnswer: 'Propozycja chodzenia ze sobą' },
  { id: 127, language: 'German', word: 'Wo sich Fuchs und Hase gute Nacht sagen', options: ['Gdzie lis i zając mówią sobie dobranoc', 'Bardzo odległe miejsce', 'Na odludziu', 'W głębokim lesie'], correctAnswer: 'Na odludziu' },
  { id: 128, language: 'German', word: 'Wo gehobelt wird, da fallen Späne', options: ['Gdzie się struga, tam lecą wióry', 'Przy pracy są straty', 'Gdzie drwa rąbią, tam wióry lecą', 'Pracować w stolarni'], correctAnswer: 'Gdzie drwa rąbią, tam wióry lecą' },
  { id: 129, language: 'German', word: 'Wo Rauch ist, da ist auch Feuer', options: ['Gdzie dym, tam ogień', 'Nie ma dymu bez ognia', 'Palić ognisko', 'Widzieć dym'], correctAnswer: 'Nie ma dymu bez ognia' },
  { id: 130, language: 'German', word: 'Zu Befehl sein', options: ['Być na rozkaz', 'Do dyspozycji', 'Słuchać rozkazów', 'Być w wojsku'], correctAnswer: 'Do dyspozycji' },
  { id: 131, language: 'German', word: 'Zu tief ins Glas schauen', options: ['Patrzeć zbyt głęboko w szklankę', 'Za dużo pić', 'Być pijanym', 'Lbić alkohol'], correctAnswer: 'Za dużo pić' },
  { id: 132, language: 'German', word: 'Zwei Fliegen mit einer Klappe schlagen', options: ['Uderzyć dwie muchy jedną packą', 'Załatwić dwie rzeczy naraz', 'Upiec dwie pieczenie na jednym ogniu', 'Być skutecznym'], correctAnswer: 'Załatwić dwie rzeczy naraz' },
  { id: 133, language: 'German', word: 'Zwischen Baum und Borke stehen', options: ['Stać między drzewem a korą', 'Być w trudnej sytuacji', 'Być między młotem a kowadłem', 'Być w lesie'], correctAnswer: 'Być między młotem a kowadłem' },
  { id: 134, language: 'German', word: 'Auf eigenen Füßen stehen', options: ['Stać na własnych nogach', 'Być samodzielnym', 'Mieć silne nogi', 'Być dorosłym'], correctAnswer: 'Być samodzielnym' },
  { id: 135, language: 'German', word: 'Alles auf eine Karte setzen', options: ['Położyć wszystko na jedną kartę', 'Zaryzykować wszystko', 'Grać w karty', 'Mieć tylko jedną opcję'], correctAnswer: 'Zaryzykować wszystko' },
  { id: 136, language: 'German', word: 'Den Kopf in den Sand stecken', options: ['Wkładać głowę w piasek', 'Unikać problemów', 'Chować się', 'Być na plaży'], correctAnswer: 'Unikać problemów' },
  { id: 137, language: 'German', word: 'Die Zähne zusammenbeißen', options: ['Zaciskać zęby', 'Wytrzymać trudności', 'Być złym', 'Iść do dentysty'], correctAnswer: 'Wytrzymać trudności' },
  { id: 138, language: 'German', word: 'Ein Haar in der Suppe finden', options: ['Znaleźć włos w zupie', 'Szukać problemu', 'Narzekać na drobnostki', 'Być wybrednym'], correctAnswer: 'Szukać problemu' },
  { id: 139, language: 'German', word: 'Etwas aus dem Effeff beherrschen', options: ['Opanować coś z FF', 'Znać coś perfekcyjnie', 'Uczyć się czegoś', 'Być ekspertem'], correctAnswer: 'Znać coś perfekcyjnie' },
  { id: 140, language: 'German', word: 'Jemandem auf den Zahn fühlen', options: ['Czuć komuś na zębie', 'Dokładnie przepytać', 'Badać zęby', 'Iść do dentysty'], correctAnswer: 'Dokładnie przepytać' },
  { id: 141, language: 'German', word: 'Kein Wort über etwas verlieren', options: ['Nie stracić słowa o czymś', 'Nie wspominać o czymś', 'Milczeć', 'Trzymać w tajemnicy'], correctAnswer: 'Nie wspominać o czymś' },
  { id: 142, language: 'German', word: 'Mit der Tür ins Haus fallen', options: ['Wpaść z drzwiami do domu', 'Mówić bez ogródek', 'Być bezpośrednim', 'Być niegrzecznym'], correctAnswer: 'Mówić bez ogródek' },
];

