import type { GapWordQuestion } from '.';

export const gapWordsQuestionsEn: GapWordQuestion[] = [
  { wordWithGap: 'consci__tious', missingLetters: 'en', fullWord: 'conscientious' },
  { wordWithGap: 'phenom__on', missingLetters: 'en', fullWord: 'phenomenon' },
  { wordWithGap: 'rhy__m', missingLetters: 'th', fullWord: 'rhythm' },
  { wordWithGap: 'que__', missingLetters: 'ue', fullWord: 'queue' },
  { wordWithGap: 'lia__on', missingLetters: 'is', fullWord: 'liaison' },
  { wordWithGap: 'fl__rescent', missingLetters: 'uo', fullWord: 'fluorescent' },
  { wordWithGap: 'parapherna__a', missingLetters: 'li', fullWord: 'paraphernalia' },
  { wordWithGap: 'misch__vous', missingLetters: 'ie', fullWord: 'mischievous' },
  { wordWithGap: 'entrep__neur', missingLetters: 're', fullWord: 'entrepreneur' },
  { wordWithGap: 'bou__eois', missingLetters: 'rg', fullWord: 'bourgeois' },
  { wordWithGap: 'ya__t', missingLetters: 'ch', fullWord: 'yacht' },
  { wordWithGap: 'fu__sia', missingLetters: 'ch', fullWord: 'fuchsia' },
  { wordWithGap: 'co__oisseur', missingLetters: 'nn', fullWord: 'connoisseur' },
  { wordWithGap: 'ac__iesce', missingLetters: 'qu', fullWord: 'acquiesce' },
  { wordWithGap: 'idiosyncra__', missingLetters: 'sy', fullWord: 'idiosyncrasy' },
  { wordWithGap: 'onoma__poeia', missingLetters: 'to', fullWord: 'onomatopoeia' },
  { wordWithGap: 'mi__ennium', missingLetters: 'll', fullWord: 'millennium' },
  { wordWithGap: 'chrysan__emum', missingLetters: 'th', fullWord: 'chrysanthemum' },
  { wordWithGap: 'zu__hini', missingLetters: 'cc', fullWord: 'zucchini' },
  { wordWithGap: 'bureaucra__', missingLetters: 'cy', fullWord: 'bureaucracy' },
  { wordWithGap: 'da__shund', missingLetters: 'ch', fullWord: 'dachshund' },
  { wordWithGap: 'psy__iatrist', missingLetters: 'ch', fullWord: 'psychiatrist' },
  { wordWithGap: 'pseu__nym', missingLetters: 'do', fullWord: 'pseudonym' },
  { wordWithGap: 'hemor__age', missingLetters: 'rh', fullWord: 'hemorrhage' },
  { wordWithGap: 'Wor__stershire', missingLetters: 'ce', fullWord: 'Worcestershire' },
  { wordWithGap: 'aes__etic', missingLetters: 'th', fullWord: 'aesthetic' },
  { wordWithGap: 'man__ver', missingLetters: 'eu', fullWord: 'maneuver' },
  { wordWithGap: 'naus__us', missingLetters: 'eo', fullWord: 'nauseous' },
  { wordWithGap: 'susce__ible', missingLetters: 'pt', fullWord: 'susceptible' },
  { wordWithGap: 'a__ommodate', missingLetters: 'cc', fullWord: 'accommodate' }
];
