import type { GapWordQuestion } from '.';

export const gapWordsQuestionsIt: GapWordQuestion[] = [
  { wordWithGap: 'psi__logo', missingLetters: 'co', fullWord: 'psicologo' },
  { wordWithGap: 'gno__hi', missingLetters: 'cc', fullWord: 'gnocchi' },
  { wordWithGap: 'co__ienza', missingLetters: 'sc', fullWord: 'coscienza' },
  { wordWithGap: 'ghia__io', missingLetters: 'cc', fullWord: 'ghiaccio' },
  { wordWithGap: 'sc__nza', missingLetters: 'ie', fullWord: 'scienza' },
  { wordWithGap: 'a__uario', missingLetters: 'cq', fullWord: 'acquario' },
  { wordWithGap: 'chia__hierare', missingLetters: 'cc', fullWord: 'chiacchierare' },
  { wordWithGap: 'a__io', missingLetters: 'gl', fullWord: 'aglio' },
  { wordWithGap: 'fi__i', missingLetters: 'gl', fullWord: 'figli' },
  { wordWithGap: 'sba__iare', missingLetters: 'gl', fullWord: 'sbagliare' },
  { wordWithGap: 'circonfere__a', missingLetters: 'nz', fullWord: 'circonferenza' },
  { wordWithGap: 'scio__iere', missingLetters: 'gl', fullWord: 'sciogliere' },
  { wordWithGap: 'a__ensore', missingLetters: 'sc', fullWord: 'ascensore' },
  { wordWithGap: 'inge__ere', missingLetters: 'gn', fullWord: 'ingegnere' },
  { wordWithGap: 'ragio__ere', missingLetters: 'ni', fullWord: 'ragioniere' },
  { wordWithGap: 'auto__rada', missingLetters: 'st', fullWord: 'autostrada' },
  { wordWithGap: 'aero__rto', missingLetters: 'po', fullWord: 'aeroporto' },
  { wordWithGap: 'zan__ra', missingLetters: 'za', fullWord: 'zanzara' },
  { wordWithGap: 'z__no', missingLetters: 'ai', fullWord: 'zaino' },
  { wordWithGap: 'zu__hero', missingLetters: 'cc', fullWord: 'zucchero' },
  { wordWithGap: 'pi__a', missingLetters: 'zz', fullWord: 'pizza' },
  { wordWithGap: 'pa__o', missingLetters: 'zz', fullWord: 'pazzo' },
  { wordWithGap: 'a__iacciare', missingLetters: 'ggh', fullWord: 'agghiacciare' },
  { wordWithGap: 'chiun__e', missingLetters: 'qu', fullWord: 'chiunque' },
  { wordWithGap: 's__alo', missingLetters: 'qu', fullWord: 'squalo' },
  { wordWithGap: 'a__ila', missingLetters: 'qu', fullWord: 'aquila' },
  { wordWithGap: 's__erzo', missingLetters: 'ch', fullWord: 'scherzo' },
  { wordWithGap: 'ghia__', missingLetters: 'ia', fullWord: 'ghiaia' },
  { wordWithGap: 'scio__ro', missingLetters: 'pe', fullWord: 'sciopero' },
  { wordWithGap: 'ghi__', missingLetters: 'ro', fullWord: 'ghiro' }
];
