import type { GapWordQuestion } from '.';

export const gapWordsQuestionsFr: GapWordQuestion[] = [
  { wordWithGap: 'accu__llir', missingLetters: 'ei', fullWord: 'accueillir' },
  { wordWithGap: 'chi__rgien', missingLetters: 'ru', fullWord: 'chirurgien' },
  { wordWithGap: 'œ__l', missingLetters: 'i', fullWord: 'œil' },
  { wordWithGap: 'aujo__d\'hui', missingLetters: 'ur', fullWord: 'aujourd\'hui' },
  { wordWithGap: 'oi__au', missingLetters: 'se', fullWord: 'oiseau' },
  { wordWithGap: 'écu__uil', missingLetters: 're', fullWord: 'écureuil' },
  { wordWithGap: 'y__ourt', missingLetters: 'ao', fullWord: 'yaourt' },
  { wordWithGap: 'caout__ouc', missingLetters: 'ch', fullWord: 'caoutchouc' },
  { wordWithGap: 'quincai__erie', missingLetters: 'll', fullWord: 'quincaillerie' },
  { wordWithGap: 'f__ille', missingLetters: 'eu', fullWord: 'feuille' },
  { wordWithGap: 'gre__uille', missingLetters: 'no', fullWord: 'grenouille' },
  { wordWithGap: 'fau__uil', missingLetters: 'te', fullWord: 'fauteuil' },
  { wordWithGap: 'enthou__asme', missingLetters: 'si', fullWord: 'enthousiasme' },
  { wordWithGap: 'psy__logie', missingLetters: 'cho', fullWord: 'psychologie' },
  { wordWithGap: 'rhi__céros', missingLetters: 'no', fullWord: 'rhinocéros' },
  { wordWithGap: 'hélico__ère', missingLetters: 'pt', fullWord: 'hélicoptère' },
  { wordWithGap: 'extra__dinaire', missingLetters: 'or', fullWord: 'extraordinaire' },
  { wordWithGap: 'hir__delle', missingLetters: 'on', fullWord: 'hirondelle' },
  { wordWithGap: 'co__inelle', missingLetters: 'cc', fullWord: 'coccinelle' },
  { wordWithGap: 'pa__llon', missingLetters: 'pi', fullWord: 'papillon' },
  { wordWithGap: 'broui__ard', missingLetters: 'll', fullWord: 'brouillard' },
  { wordWithGap: 'cuei__ir', missingLetters: 'll', fullWord: 'cueillir' },
  { wordWithGap: 'f__illeton', missingLetters: 'eu', fullWord: 'feuilleton' },
  { wordWithGap: 'mervei__eux', missingLetters: 'll', fullWord: 'merveilleux' },
  { wordWithGap: 'tra__il', missingLetters: 'va', fullWord: 'travail' },
  { wordWithGap: 'con__il', missingLetters: 'se', fullWord: 'conseil' },
  { wordWithGap: 'so__eil', missingLetters: 'mm', fullWord: 'sommeil' },
  { wordWithGap: 'rév__l', missingLetters: 'ei', fullWord: 'réveil' },
  { wordWithGap: 'ab__lle', missingLetters: 'ei', fullWord: 'abeille' },
  { wordWithGap: 'so__il', missingLetters: 'le', fullWord: 'soleil' }
];
