import type { GapWordQuestion } from '.';

export const gapWordsQuestionsEs: GapWordQuestion[] = [
  { wordWithGap: 'desa__ollar', missingLetters: 'rr', fullWord: 'desarrollar' },
  { wordWithGap: 'otorrinolaringó__go', missingLetters: 'lo', fullWord: 'otorrinolaringólogo' },
  { wordWithGap: 'para__as', missingLetters: 'gu', fullWord: 'paraguas' },
  { wordWithGap: 'g__rra', missingLetters: 'ue', fullWord: 'guerra' },
  { wordWithGap: 'verg__nza', missingLetters: 'üe', fullWord: 'vergüenza' },
  { wordWithGap: 'pin__ino', missingLetters: 'gü', fullWord: 'pingüino' },
  { wordWithGap: 'ci__eña', missingLetters: 'gü', fullWord: 'cigüeña' },
  { wordWithGap: 'anti__edad', missingLetters: 'gü', fullWord: 'antigüedad' },
  { wordWithGap: 'nicarag__nse', missingLetters: 'üe', fullWord: 'nicaragüense' },
  { wordWithGap: 'psi__iatra', missingLetters: 'qu', fullWord: 'psiquiatra' },
  { wordWithGap: 'psicó__go', missingLetters: 'lo', fullWord: 'psicólogo' },
  { wordWithGap: 'exce__ional', missingLetters: 'pc', fullWord: 'excepcional' },
  { wordWithGap: 'e__austo', missingLetters: 'xh', fullWord: 'exhausto' },
  { wordWithGap: 'exhi__ción', missingLetters: 'bi', fullWord: 'exhibición' },
  { wordWithGap: 'zana__ria', missingLetters: 'ho', fullWord: 'zanahoria' },
  { wordWithGap: 'almo__da', missingLetters: 'ha', fullWord: 'almohada' },
  { wordWithGap: 'a__gar', missingLetters: 'ho', fullWord: 'ahogar' },
  { wordWithGap: 'aho__ar', missingLetters: 'rr', fullWord: 'ahorrar' },
  { wordWithGap: 'alre__dor', missingLetters: 'de', fullWord: 'alrededor' },
  { wordWithGap: 'ferroca__il', missingLetters: 'rr', fullWord: 'ferrocarril' },
  { wordWithGap: 'desoxirribo__leico', missingLetters: 'nuc', fullWord: 'desoxirribonucleico' },
  { wordWithGap: 'electrocardio__ama', missingLetters: 'gr', fullWord: 'electrocardiograma' },
  { wordWithGap: 'esternocleido__stoideo', missingLetters: 'ma', fullWord: 'esternocleidomastoideo' },
  { wordWithGap: 'Guada__ara', missingLetters: 'laj', fullWord: 'Guadalajara' },
  { wordWithGap: 'Que__taro', missingLetters: 'ré', fullWord: 'Querétaro' },
  { wordWithGap: 'chicha__ón', missingLetters: 'rr', fullWord: 'chicharrón' },
  { wordWithGap: 'Chihua__a', missingLetters: 'hu', fullWord: 'Chihuahua' },
  { wordWithGap: 'xi__fono', missingLetters: 'ló', fullWord: 'xilófono' },
  { wordWithGap: 'a__untamiento', missingLetters: 'y', fullWord: 'ayuntamiento' },
  { wordWithGap: 'pro__ibir', missingLetters: 'h', fullWord: 'prohibir' }
];
