import type { GapWordQuestion } from '.';

export const gapWordsQuestionsDe: GapWordQuestion[] = [
  { wordWithGap: 'Eichhö__chen', missingLetters: 'rn', fullWord: 'Eichhörnchen' },
  { wordWithGap: 'Streichholzschä__telchen', missingLetters: 'ch', fullWord: 'Streichholzschächtelchen' },
  { wordWithGap: 'Recht__reibung', missingLetters: 'sch', fullWord: 'Rechtsschreibung' },
  { wordWithGap: 'Fünfhundertfünfundfü__ig', missingLetters: 'nfz', fullWord: 'Fünfhundertfünfundfünfzig' },
  { wordWithGap: 'Geschwindigkeitsbe__enzung', missingLetters: 'gr', fullWord: 'Geschwindigkeitsbegrenzung' },
  { wordWithGap: 'Unabhängigkeitser__ärung', missingLetters: 'kl', fullWord: 'Unabhängigkeitserklärung' },
  { wordWithGap: 'au__erordentlich', missingLetters: 'ß', fullWord: 'außerordentlich' },
  { wordWithGap: 'qui__schend', missingLetters: 'et', fullWord: 'quietschend' },
  { wordWithGap: 'zwi__schern', missingLetters: 't', fullWord: 'zwitschern' },
  { wordWithGap: 'tsche__isch', missingLetters: 'ch', fullWord: 'tschechisch' },
  { wordWithGap: 'Rhy__mus', missingLetters: 'th', fullWord: 'Rhythmus' },
  { wordWithGap: '__lophon', missingLetters: 'Xy', fullWord: 'Xylophon' },
  { wordWithGap: 'gemü__lich', missingLetters: 't', fullWord: 'gemütlich' },
  { wordWithGap: 'wahr__einlich', missingLetters: 'sch', fullWord: 'wahrscheinlich' },
  { wordWithGap: 'außergewö__lich', missingLetters: 'hn', fullWord: 'außergewöhnlich' },
  { wordWithGap: 'Sehenswür__gkeit', missingLetters: 'di', fullWord: 'Sehenswürdigkeit' },
  { wordWithGap: 'Eifer__cht', missingLetters: 'su', fullWord: 'Eifersucht' },
  { wordWithGap: 'schre__lich', missingLetters: 'ck', fullWord: 'schrecklich' },
  { wordWithGap: 'Früh__ück', missingLetters: 'st', fullWord: 'Frühstück' },
  { wordWithGap: 'selbstver__ändlich', missingLetters: 'st', fullWord: 'selbstverständlich' },
  { wordWithGap: 'Ent__uldigung', missingLetters: 'sch', fullWord: 'Entschuldigung' },
  { wordWithGap: 'Freund__aft', missingLetters: 'sch', fullWord: 'Freundschaft' },
  { wordWithGap: 'wi__en__aftlich', missingLetters: 'ss', fullWord: 'wissenschaftlich' },
  { wordWithGap: 'durch__nittlich', missingLetters: 'sch', fullWord: 'durchschnittlich' },
  { wordWithGap: 'charakteris__isch', missingLetters: 't', fullWord: 'charakteristisch' },
  { wordWithGap: 'Brö__en', missingLetters: 'tch', fullWord: 'Brötchen' },
  { wordWithGap: 'Mä__en', missingLetters: 'dch', fullWord: 'Mädchen' },
  { wordWithGap: 'tat__chlich', missingLetters: 'sä', fullWord: 'tatsächlich' },
  { wordWithGap: 'plö__lich', missingLetters: 'tz', fullWord: 'plötzlich' },
  { wordWithGap: 'frö__ich', missingLetters: 'hl', fullWord: 'fröhlich' }
];
